### ISSUE TITLE
F-Zero GX fails to boot after revision 296

### ISSUE THREAD

**Issue by SwervinGirvin** [emukidid/swiss-gc#145]
Hello! 

Longtime lurker SwervinGirvin here! Someone in the community has brought this to my attention and I didn't see any other active threads on the matter so I decided to throw one up! 

1. swiss_r366_compressed.dol
2. NTSC GC DOL-001
3. SD Gecko, Non-modded system
4. SDML
5. Load F-Zero GX ISO

Ok, so basically is the issue I and others are experiencing is failure to load F-Zero GX from SD Gecko on the latest nightly build r366. It simply won't boot, it hangs on the green screen prior to game boot. Strangely enough, if I go back to swiss_r296 however it loads and plays just fine, but every other revision I've got from then on seems to hang up. Notable revisions include: r334, r342, and r364. All of these revisions were tested on the same set up described above. Thanks so much for this wonderful software and all your hard work on it, hope you can provide some feed back or squash this problem in a future revision!

**Comment by emukidid** [comment]
Hello,

Can you please try with the latest revision - I believe I've fixed this one.
