### ISSUE TITLE
Pokemon XD black screen on boot from SD Gecko and Smash Bros freez

### ISSUE THREAD

**Issue by santiis2010** [emukidid/swiss-gc#146]
Hello, new here :)

My system:
- SD Gecko Toshiba 8GB SDHC class 10
- GC Dol 001 with Xeno chip
- Swiss v0.4 r371

When i boot pokemon XD all i can see is a black screen and nothing more
In Smash Bros when i go to 1 Player mode, selected the character and push start button, it freez the game, only music and i have to reset the console

**Comment by emukidid** [comment]
Pokemon XD/Colosseum have been fixed in 0.4r431
