### ISSUE TITLE
Auto-load Cheats

### ISSUE THREAD

**Issue by teconmoon** [emukidid/swiss-gc#147]
With Swiss' current implementation, is it possible to have a game automatically load any available cheats without having to manually select them all each time? I have a lot of games that rely on AR/Gecko codes for proper widescreen, and it would be nice if they auto-loaded instead of having to manually turn the codes on each time.

Thanks for supporting Swiss all these years!

**Comment by emukidid** [comment]
Added this in r373, grab the latest and see how you go :)

**Comment by teconmoon** [comment]
Thanks so much I will be testing tonight for sure!

**Comment by teconmoon** [comment]
Works great! Thanks for the addition!
