### ISSUE TITLE
Mario Party 4 - Party Mode sets a random person to 999 coins at mini game results screen

### ISSUE THREAD

**Issue by ghost** [emukidid/swiss-gc#149]
Wrote about this issue on gc-forever but adding it here since it's still an issue with the latest build.

**Game**
Mario Party 4
**Region**
USA
**Medium**
SD Gecko
**Swiss version**
Swiss r377
**Detailed report of the issue**
The game doesn't crash, but during party mode after a minigame, a (seemingly) random player will jump to 999 coins. Issue is not present when using WASP or using Swiss to boot disk directly.

[YouTube Video showing bug](https://www.youtube.com/watch?v=Z83Qh9rXypc)

**Comment by thecybermind** [comment]
Swiss r382:

After playing this (Mario Party 4 (USA, v1.00), SD Gecko) last night with my roommates, we casually noticed the 999 coins seemed to go to the first loser (in elimination-style games) or last place player (in scored games) in a free-for-all mini game (didn't happen in 2v2 or 3v1 games). I originally thought it was a Wiird cheat that was automatically turned on, but I checked after the game and I had no cheats at all for GMPE01.

On a side note, everyone eventually had 999 coins so it ended up being a game of "who can magic lamp/boo's crystal ball the most stars" so it was still fun, but definitely had a different feel to it.

**Comment by AlexS2412** [comment]
Sounds like you have cheats enabled.

**Comment by doylie1984** [comment]
So I know it's been a while but I just got into this gamecube/ swiss thing & find the same problem this is the only post I found about it. Just wonder if you fixed it. Swiss R371.

**Comment by emukidid** [comment]
Needs this fixed: https://gbatemp.net/entry/nintendont-bugs-mario-party-4-freezing.15078/

**Comment by emukidid** [comment]
Cannot reproduce after e489d01d7c25ae03d0540d1263b43e09fed0b8e5

**Comment by shahidullan9-maker** [comment]
2659935

**Comment by realbaylen** [comment]
This happened to me
