### ISSUE TITLE
new versions won't load games from SD or IDE-EXI, properly or at all.

### ISSUE THREAD

**Issue by radorn** [emukidid/swiss-gc#151]
I have 2 PAL GCs, one with XenoGC and another with a qoob.
Both seem to work correctly and load games and homebrew from DVD correctly.

Now, I have this old version of Swiss v0.3 dated 2012-07-24 (doesn't seem to report revision number anywhere) on DVD which seems to load games from SDgecko correctly (but with stuttering, which, I believe, is unavoidable?)

Recently I found, though, that no v0.4 compile from this repository has worked for me. I tried r382 first and didn't work, so I tried again with the earliest version avaiable here, r371, and didn't work either.

Most games just wont load or will get stuck sooner or later, and I'm not talking just about shrinked images, but also untouched dumps.

One telling example is Sonic Riders. It loads up to the SEGA logo. After which a video sequence is supposed to come. In the old 0.3 version it works, albeit with a lot of stuttering. In v0.4 it gets stuck at the SEGA logo screen and just won't load any further. Other games will suffer similar problems or just won't display anything at all.

For further reference, I also have an IDE-EXI, and tested it with the most recent version with the same results as with SDgecko. I only tested it with v0.4r382 before removing it and giving up, though. Then I found that old v0.3 disc that I had and tried again just with SD, finding that it indeed works where v0.4 doesn't (for me at least).

**Comment by emukidid** [comment]
You say "won't load games properly or at all" but only specifically mention 1 game, it's possible that just that one game has broken in compatibility, can you list any others? Also IDE-EXI vs SD doesn't make a difference, it's the same code in-game apart from the actual reading from the device.

**Comment by radorn** [comment]
zelda four swords
battallion wars
extreme g 3
auto modellista
ikaruga
mario kart double dash
pn03
super monkey ball
gadget racers
spartan total warrior
viewtiful joe
bomberman generation
sonic heroes
beyond good and evil
XIII

I can't be sure about all of them or if I didn't try any other, but all these were in the HDD when I tested v04r382, also including the aforementioned sonic riders, and failed. then I gave up... then I found that games that failed in 0.4 worked in 0.3. including sonic riders and zelda four swords, where I could even finish the first area and save.
I also tried some of the multi-game demo discs, but don't remember specific ones, and the starfox adventures prototype, which loaded the "starship bridge room" main menu, but suffered from horrible sound corruption and then crashed when I tried to do start a game, haven't tried that one on v0.3 again though.

If you want I can test more thoroughly with all that I have and compare results for all if that will help pinpoint the problem, but to me it's pretty clear that there's something that v0.4 doesn't like about either my disc images or my gamecubes that old v0.3 doesn't seem to mind at all.

**Comment by emukidid** [comment]
None of those games are on my SD card that I test with so I'll have to back some up and try them. PAL or NTSC?

**Comment by radorn** [comment]
mostly pal, some ntsc. guess I'll have to make a proper list with full info and results.
I'm a bit unfamiliar with the current state of the GC scene. Is there any indication for shrinked images? like should I use any particular fix/tool/sumthin on them?

**Comment by radorn** [comment]
OK this is getting weirder by the minute.
I just tried a few things more and again results keep changing.
I have a wiikey branded SD adapter and an old 2GB card. For the IDE-EXI I have a 160GB 2.5 inch drive.
Originally I tried the HDD with a FAT32 partition taking the whole disk. v0.4 listed the contents but most games failed, while v0.3 not only didn't list the contents, but actually corrupted the FS and I had to copy everything over again.
Now I tried making a <32GB partititon on that 160GB disk and 0.4 now loads things that didn't work before.
For example, I have a shrinked Zelda Four Swords (PAL) image, It doesn't work in v0.4 from SD or 160GB partition IDE-EXI, but it works from 32GB partition IDE-EXI.
The reason that it didn't work from the 160GB partition might be because it was formatted with a thirdparty tool? (though I passed a chkdsk on it, just to be sure), but then again, why does it fail from SD formatted with the windows tool.

This is getting out of hand...

Is there any guide about this whole thing? because I'm starting to feel really lost.

**Comment by Guspaz** [comment]
I just wanted to pop in and say that I've experienced the same issue in a similar setup. Booting Swiss 0.4 off a DVD on a PAL GCN with a XenoGC installed. Swiss 0.4 r382 won't load games (they either stop at a black screen, or show some logos and freeze) off an SDML, neither will Swiss 0.4 r414, but I grabbed an old copy of Swiss 0.3 (which I'm loading from inside of Swiss 0.4) and that appears to be able to load the games successfully.

Both versions (0.3 and 0.4) of Swiss are set to "Fast" mode for the SD card.  Setting 0.4 to "Compatible" didn't change anything.

**Comment by typorian** [comment]
I've got a PAL Gamecube, old one with digital out. With the two latest nightlies, I had problems running some games (jedi outcast and 1080 avalanche would just randomly completely freeze up on me) but with r371 the problem seems to be gone. If I can be of any assistance with debugging i'm glad to help.

**Comment by emukidid** [comment]
Try the latest release: https://github.com/emukidid/swiss-gc/releases/latest

**Comment by radorn** [comment]
Oh, hey, I don't have my GC at hand anymore and was thinking of maybe selling it, but I may get arround trying this at some point.
