### ISSUE TITLE
Swiss Hangs on Boot From Bad SDCard Read Failure.

### ISSUE THREAD

**Issue by NonaSuomy** [emukidid/swiss-gc#154]
@emukidid 
#153 
[#issuecomment-283269087](https://github.com/emukidid/swiss-gc/issues/153#issuecomment-283269087)
```
emukidid commented a day ago
Swiss/no software can detect if something is in the SD Gecko device because it's always shorting the sense lines making any software just know "hey, something is in the memory card slot". So the only way to do it is to try and initialise the card. If there's no card or it fails to read, it's setup to try again because some crappy cards take a while, that's why it hangs.
```

Add ability after SDCard read failure X times or taking too long, ask if you want to retry or to escape out of reading attempt cycle and fall back to the swiss menu, to prevent having to hard restart the hang on GC preventing wear and tear on the unit.

If it has yet to load anything within seconds you pretty much know it's not going to work and it should pull the ejection seat back to menu.

[Abort, Retry, Fail?](https://upload.wikimedia.org/wikipedia/commons/4/44/Abort_Retry_Fail.PNG)

**Comment by NonaSuomy** [comment]
Did you fix this?

**Comment by Extrems** [comment]
This was forcibly fixed by the SD2SP2 support.

**Comment by NonaSuomy** [comment]
Great I’ll test it out, thank you.
