### ISSUE TITLE
It would be nice if dot files on an SD card were ignored

### ISSUE THREAD

**Issue by ddribin** [emukidid/swiss-gc#156]
I've got an SD card with a bunch of dot files (file and directory names that begin with a '.'). These dot files are normally hidden under Unix by default. It would be nice if there were an option to hide these files in the Swiss file list, too. This card is used on a Mac which creates a bunch of dot files and directories, e.g. `/.fseventsd/`.

**Comment by emukidid** [comment]
Fixed, wait for the new build.
