### ISSUE TITLE
Super mario sunshine sound problem

### ISSUE THREAD

**Issue by thechosenone98** [emukidid/swiss-gc#157]
Hi,
I have the latest version of swiss and the only game i have trouble with os super mario sunshine.
My issue is that the only sound i can hear are in the cutscene that tend to lag. After that, when I can finally play, there is absolutely no sound (no music, no character voices, NOTHING). I'd like to know if this is fixable because nobody seems to have that problem.

Thx and I hope someone can help me.

**Comment by jtvjan** [comment]
From where are you loading Super Mario Sunshine, what device?

**Comment by RapAce** [comment]
Im having the same issue.I am loading Super Mario Sunshine from a sdgecko

**Comment by emukidid** [comment]
Closing old issues. Please re-open if you're still experiencing issues in the latest builds. (Specifically with alternate read patches enabled)
