### ISSUE TITLE
Eternal Darkness: Sanity's Requiem (USA-NTSC)- Freezes at the end of Chapter 9

### ISSUE THREAD

**Issue by zwolfy12** [emukidid/swiss-gc#160]
As the title suggests, at the end of the Chapter 9: The War to End All Wars, the game systematically freezes.

As the player approaches the door to reach the boss of that chapter, the image and sound stutter for a moment.

After he enters the room and the cutscene  ends, the game randomly freezes within moments.

I load the game without cheats, patches or any config changes.

I tried with 3 different SDHC cards: Emtec 32gb; Kingston 8gb; Sandisk 16gb. All with the same result.

Anyone who has ever played this game knows how addictive it is, so pretty please? ;)

Thanks in advance!

(PS): there is also some very light stutter during chapter transition cutscenes. Nothing that ruins the experience, though.

**Comment by emukidid** [comment]
Hi there,

Which device are you playing this from, SD card in memory card port? Have you tried muting audio streaming via the settings? I can take a look at it if you can provide your save file (use GCMM) and instructions on how to get to the point where it freezes.

**Comment by zwolfy12** [comment]
I'm getting an error on GCMM (FAT something, maybe I need to format the SD card again?). Until I can figure it out, here's what happened:

Turning off audio streaming fixes the freezing issue in Chapter 9 and for the rest of the game. 

What seems to be glitched (almost) permanently is spellcasting, more specifically the «SUMMON HORROR» spell. Casting it will immediately kill the game, UNTIL the very end on Chapter 12 when you need to use it to progress.   Then, and only then, it will work.

So technically it is quite possible to finish the game even with this spellcasting glitch, as the spell in question will work in that one time when it's needed. In any other time, the game will freeze.

The media I'm using is a knockoff(?) of the SD Gecko, called WiiSD. I also tried with the adapter that came with my SD Media Launcher, but it's very fussy with the cards.

Maybe you could add a note in the compatibility list, under this games's entry, mentioning these two problems, so folks will know what to do?

At any rate, I think this is it.

**Comment by emukidid** [comment]
Note added to the wiki compatibility list, thanks.
