### ISSUE TITLE
pokemon xd gale of darkness from dvd random exit area crash

### ISSUE THREAD

**Issue by jpf100** [emukidid/swiss-gc#161]
sometime when you exit a building or area when playing from dvd the game crashes with an audio loop of the last tone played, seem to be random because i can load up a save and exit the same building 5 times and have it only happen once or all five times

edit: upon further inspection it seems that it is not activating the disk drive when attempting to load large areas

**Comment by emukidid** [comment]
Try again with the latest version please and re-open if this is still an issue.
