### ISSUE TITLE
Fails on WODE running firmware 2.9B

### ISSUE THREAD

**Issue by dbenoy** [emukidid/swiss-gc#164]
I decided to dust off my old Wii and use some homebrew. I upgraded the WODE to the latest firmware (Found here: https://wode.obeygravity.de/Downloads)

With stealth mode on, which caused Swiss to boot to a black screen.

Turning stealth mode off, it boots to 'Detecting devices,' and hangs there forever. It says I can skip it by holding B when booting into Gamecube but holding B has no effect. Same hang, same message.

I tested it with both SD card and USB drive, same results.

**Comment by Streetwalrus** [comment]
Can you try with r387 or older?

**Comment by dbenoy** [comment]
Yep. That worked.

Since the device supports downgrading I tried a few different firmware versions. (all over 2.0) and they all failed, but I went and tried recent firmware with r387 and it seemed to work fine.

**Comment by Streetwalrus** [comment]
Alright, that's most likely related to the device handler changes, @emukidid will have to look at it, I don't have a wode.

**Comment by emukidid** [comment]
Should be fine in the latest builds.
