### ISSUE TITLE
Zelda Collectors Edition Crash when playing any song in majoras mask.

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#166]
When playing the game, any song will trigger a crash half-way through the audio file or sometimes before it will even play it. ive attached an image of the crash for example and included my save file. this seems to be because of the audio streaming in the game when loaded from sd. its fine when launched from dvd-r in swiss. @emukidid  if you would be able to work on this in the future it would be much appreciated. 

EDIT: actually upon further checking it seems with swiss r422 that the game itself freezes on the nintendo logo now when launched from dvd-r.

![image](https://user-images.githubusercontent.com/14182708/29344685-934715de-8207-11e7-882f-dd316bb56132.png)

[Majoras Mask Save.zip](https://github.com/emukidid/swiss-gc/files/1226893/Majoras.Mask.Save.zip)

**Comment by emukidid** [comment]
OK, I've only tried it on PAL and it was fine. I'll try NTSC.

**Comment by AlexS2412** [comment]
I havent tried PAL Yet. But i am Shocked that a simple Region Differencd can cause so many issues X-x

**Comment by emukidid** [comment]
I tried a few other titles with audio streaming and something weird is up, they crash hard after a minute or two, I need to see when it broke because it was fine when first introduced.

**Comment by AlexS2412** [comment]
Alright. Im just glad that it wasnt something on my end and a geniune error :p also do you have discord? If so my discord tag is Alex S#8291 and i could help with testing to see if the issue is fixed. That and it would be a helpful way to get in contact with you :3

**Comment by emukidid** [comment]
Try the latest build and let me know.

**Comment by AlexS2412** [comment]
okay it seems to work now but a new issue resulted from this. there is a small clicking noise that happens three times at the end of a audio file. i can submit a recording of this if it helps. but the main issue seems to be fixed now ^u^
