### ISSUE TITLE
Metroid Prime 2 In-Game BGM and SFX Fail To Play.

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#167]
It seems whatever the game accesses back and forth from the actual disc will flat-out cause the music to fail to load ( and looking at the actual disc the laser jumps up a little and down a little on the same spots) and it also seems certain sfx will be cut short as well or not play at all. Maybe the music not being played properly is the reason for the stutters as the prime games switch out music tracks constantly ingame on the fly.

For reference im playing from sd gecko in slot b that is 16gb and im using swiss r424. Also the disc version seems to have no issues.

**Comment by emukidid** [comment]
Are you saying you're using sd gecko in slot b but it's trying to access the disc?

**Comment by AlexS2412** [comment]
No i was saying that the disc always seems to access the same two places repeatedly and i assume this data must be the the ingame bgm. The audio issues only occur from sd. Sorry for the confusion @emukidid

**Comment by emukidid** [comment]
Can you provide a save for this too so I don't have to sit through the intro?

**Comment by AlexS2412** [comment]
Yeah i have a save far into the game. Ill post it shortly

**Comment by AlexS2412** [comment]
ive been bug testing swiss this week and im making sure to bring any issues i find to light so they can be taken care of. i just wish i had a more direct way of contacting you about them @emukidid

**Comment by emukidid** [comment]
This is a good way (the best way?) of contacting me about them without being too annoying :P - Plus it's a great way to document them and provide files

**Comment by AlexS2412** [comment]
so any luck with the issue?

**Comment by emukidid** [comment]
Remember the "without being too annoying" part? I have a day job, working on Swiss is just a hobby for spare time.

**Comment by AlexS2412** [comment]
It seems the game has become even less stable in the current swiss. It often crashes when loading a few rooms. Im not sure if this related to the changes in the r426 or not though.

**Comment by AlexS2412** [comment]
Okay so after a lot of researching ive discovered the bugs in the audio emulation on sd loading itself extends far past this game. All the affected titles are : 

Wario World 
(to the point of unstable Crashing on the first boss and 100% crash on beating the game)
Spider-Man 2 (audio slows to a crawl and voices are unrecognizable)
Super Mario Sunshine (Audio Just dies altogether after so long or crashes the game on a black screen)
Super Smash Bros. Melee (Severe audio Crackles on any track that is played, also can randomly crash.)

And that is all ive discovered for now. The majority of titles will have their music die outright or all sound as a whole. The worst of them crash altogether for some reason after thensound has failed. Im bringing this to your attention under the same issue because the bugs are very similar and all seem to be related to the audio itself @emukidid.

**Comment by emukidid** [comment]
They're related to the way SD read replacements work as a whole from this device, they take away time from the CPU to do blocking I/O because DMA can't be utilised from the EXI bus due to a hardware bug. I can only massage the problem so much before we run into these kinds of issues, I have an alternative read mode I'm going to implement which may help but I can't guarantee anything for SD Gecko.

**Comment by AlexS2412** [comment]
Alright. Thanks for trying either way. Your software really is an amazing piece of work ^-^

**Comment by AlexS2412** [comment]
So when can we expect this new read mode to be implemented? @emukidid i will patiently wait for it no matter how long it takes ^-^

**Comment by emukidid** [comment]
Closing old issues. Please re-open if you're still experiencing issues in the latest builds. (Specifically with alternate read patches enabled)
