### ISSUE TITLE
Swiss Will fail to get proper video mode on boot from SD Gecko in Slot B

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#169]
Swiss will repeatedly display in a lower resolution on startup but when i have the config on the memory card it seems to respect the video mode.

**Comment by emukidid** [comment]
What's your config device set to, and what is inserted into each slot at the time of booting Swiss?

**Comment by AlexS2412** [comment]
Well it seems at the time of posting this that it was in fact NOT swiss and as a result of my monitor freaking out. I reset the monitor aettings and it is once again normal.
