### ISSUE TITLE
Swiss Crashes when Moving/Copying Files for the second time on Lastest Version.

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#170]
If you attempt to move or copy files now it will crash when doing it a second time always.

**Comment by emukidid** [comment]
Can you add some steps on how to replicate this? I tried it by copying files from DVD->SD Gecko and it was fine.

**Comment by keks24** [comment]
I tried to move two different gci files from SD Gecko to Memory Slot A twice and it crashed. But sometimes it just works and sometimes it just crashes after the second time.

**Comment by emukidid** [comment]
Cannot replicate. Can re-open/link in the future if this comes up again.
