### ISSUE TITLE
Disc Drive Not Recognizing Game Disc (Bug)

### ISSUE THREAD

**Issue by wicksand420** [emukidid/swiss-gc#176]
I booted the latest build of swiss (R430) with windwaker and sdgecko and attempted to dump my gameboy player disc, and it stated that it was a possible backup and stated it was loading some patches, then failed to read the disc, upon reboot the disc drive no longer works, By the way, it was a retail disc i purchased with my gameboy player, not a backup.

**Comment by AlexS2412** [comment]
are you sure your disc drive just isnt bad? it works completely fine for me.

**Comment by wicksand420** [comment]
No, my disc drive was fine before it loaded patches, I have been the only owner of my gamecube, and have taken very good care of it, and have only played it for like 100 hours in the life of the console, it was fine before it stated it was loading patches, i think it fucked up the firmware of my drive.

**Comment by wicksand420** [comment]
I unplugged my gamecube for like six hours, turned it on and it said there was no disc, opened the disc drive, took out the disc, closed it, it stated there was no disc, no duh, opened it and put the disc in, and it recognized it as windwaker, rebooted swiss, and tried to dump the gameboy player disc again to see if i could replicate the bug, and it did it again.

**Comment by wicksand420** [comment]
I have just duplicated this bug, it seems when it loads the patches, it wont recognize a true gamecube disc until you take out the disc and let it scan no disc, then put the disc back in, this is strange.

**Comment by emukidid** [comment]
Patches for the drive are uploaded via Swiss into drive RAM. The drive RAM is volatile and is wiped every time the drive is reset so there's no way that the patches are remaining on your drive after a reboot, even if they were still somewhat resident in memory, a reset (which the original IPL & Swiss both do on startup) would clear it.

I think it's that your drive is getting itself into a state where it has struggled hard to read the disc and is then failing afterwards until some time has passed. Try another GameCube/laser and see how you go.

**Comment by wicksand420** [comment]
That's cool man, I know its not my drive and I have repeated this about six times, but what ever.

**Comment by emukidid** [comment]
Yeah, I've only been using the same patching methods for almost 10 years now across a bunch of different GameCubes, it's definitely not your drive, what would I know.

I genuinely want to help you identify the problem but I don't think it lies in the software patching of the drive, that's probably only a trigger for a problem on another (hardware) level. 

I've had completely working drives die all of a sudden and act strange like you describe until a hard power off for several hours, but I wasn't even reading backups at the time nor patching the drive (original IPL standard usage). The fix on those drive boards was to replace the capacitors.

**Comment by emukidid** [comment]
One genuine question though, you say "rebooted swiss", can you elaborate more? It could be that if you're not fully powering off the GameCube Swiss is getting confused about if the drive is already initalised or not and that might be something to look at.

**Comment by wicksand420** [comment]
Ok, check it out, I'll give you the rundown on what i do, step for step, I boot my gamecube with windwaker in the game slot and i have my real memory card in slot a and my sd gecko in slot b, i have the windwaker save and the dolphin file in slot a memory card, and the latest version of swiss named as per your github page. I boot the system and it boots the disc no problem, after the title screen it loads swiss, no problem, I take out my windwaker disc and insert my retail gameboy player disc I bought with my gameboy player, NTSC-U of corse, and press b and select the dvd, and it starts to scan the dvd in the drive, it takes about 30 seconds and states that it is a possible backup disc and states it is loading patches, when it is done loading the patches, it states that the dvd failed to load, while still in swiss, I attempt to insert another disc but it wont even show the dvd slot when pressing b and selecting the devices bar, so I power down the console and reboot it, and it goes to bios 1.0, and says there is no disc in the drive, if I power down again and turn it on it does the same thing, only after I remove the disc and close the top, and it reads that there is in fact no disc, will it read a gamecube disc, right after it reads no disc in the drive everything is fine and my console has no problem reading the disc. if i repete these steps it happens again and again. This console is my baby and i take good care of it, the disc drive has literally only had about a hundred hours of max play on it, i only use it for homebrews and the gameboy player, since the wii was totally hacked, i use that for playing gamecube games, so i really don't think it is the disc drive.

**Comment by AlexS2412** [comment]
I think its the gameboy player disc specifically that cant be loaded. I tried to run it from the sd card with no luck as it said it couldnt find what was needed to patch it. Try using GBI made by Extrems or just try and boot your Legitimate gameboy player disc.

**Comment by wicksand420** [comment]
I was attempting to make a backup in case of emergency, but had that happen and thought it might be a bug worth mentioning. I used my wii to back it up, so no problems there, I was wondering how the gamecube hardware handles backing up a disc, so I tried windwaker, it is slow as hell. everything is fine on my end, and swiss works like a charm, as long as i don't try to load my gameboy player disc while in swiss. I'll try GBI and see if can run the backup I made with wii, I tried it in swiss last night and it stated in couldn't find the correct patches for it on mine either, and loaded to a green screen with vertical stripes.

**Comment by AlexS2412** [comment]
GBI just directly starts the gameboy player.... and also the disc has dumps on isozone for you that are 8mb

**Comment by kureelrahul916-dot** [comment]
> I booted the latest build of swiss (R430) with windwaker and sdgecko and attempted to dump my gameboy player disc, and it stated that it was a possible backup and stated it was loading some patches, then failed to read the disc, upon reboot the disc drive no longer works, By the way, it was a retail disc i purchased with my gameboy player, not a backup.

I booted the latest build of swiss (R430) with windwaker and sdgecko and attempted to dump my gameboy player disc, and it stated that it was a possible backup and stated it was loading some patches, then failed to read the disc, upon reboot the disc drive no longer works, By the way, it was a retail disc i purchased with my gameboy player, not a backup.
