### ISSUE TITLE
Problemas al cargar algunos juegos

### ISSUE THREAD

**Issue by rojo1098** [emukidid/swiss-gc#177]
en la version mas actual de swiss 0.4 r431 e tenido muchos problemas al cargar los siguientes juegos: pokemon colloseum NTSC (se traba en el menu de start), animal crossing PAL (resetea la consola al momento de cargar la iso), nfs carbon NTSC (se traba en el menu de start),naruto gnt 4 ntsc-j (se traba en el menu de start),nfs undergound NTSC (se traba en el menu de opciones cuando vas a elegir una carrera) y Luigis mansion NTSC (el algunos videos se va el sonido o se escucha un pitido muy fuerte y molesto)

Sabes como podria solucionar estos problemas? poseo una gc dol-001 (las que tienen entrada de componente) + chip xeno 2.2 + sd gecko 32gb adata sdhc con lectura de 10.

**Comment by AlexS2412** [comment]
Quick translation from google translate : in the most current version of swiss 0.4 r431 has had many problems when loading the following games: pokemon colloseum NTSC (locked in the start menu), animal crossing PAL (reset the console when loading the iso), nfs carbon NTSC (locked in the start menu), naruto gnt 4 ntsc-j (locked in the start menu), nfs undergound NTSC (locked in the options menu when you are going to choose a race) and Luigis mansion NTSC some videos are going off the sound or you hear a loud and annoying beep)

Do you know how to solve these problems? I have a gc dol-001 (those that have component input) + xeno chip 2.2 + sd gecko 32gb adata sdhc with reading 10.

**Comment by rojo1098** [comment]
thank you by the translation

**Comment by emukidid** [comment]
Closing old issues. Please re-open if you're still experiencing issues in the latest builds.
