### ISSUE TITLE
pokemon colosseum/xd swiss r.431

### ISSUE THREAD

**Issue by ShadowMag1c1an** [emukidid/swiss-gc#178]
pokemon colosseum black screen on boot, pokemon xd loads to hz select then black screen both eur iso's loading via sd card

**Comment by emukidid** [comment]
I've only tried NTSC and they worked, I'll check the PAL versions soon.

**Comment by vinnycl** [comment]
Not working on NTSC and NTSC-J
https://www.youtube.com/watch?v=wd0dRmPp7as
Do I have to make any different setting ?

**Comment by TiKevin83** [comment]
I was able to play NTSC Colosseum from disk just fine yesterday on r.599 with and without video mode forcing.  Let me know if any testing is needed from SD card.
