### ISSUE TITLE
Swiss doesnt load Animal Crossing (Pal)

### ISSUE THREAD

**Issue by Kyss007** [emukidid/swiss-gc#184]
Hello,
so i got this problem:
when i try to boot the pal version of animal crossing (on the gamecube) it patches then its green for a wile then the gamecube reboots. (as shown in the video)

Gamecube: the one with the digitalout
Modchip: xenogc
swiss: r431
sd  card: adata 16gb / sandisk ultra 32 gb (tried both)

the  video: https://streamable.com/xofrq

hope you can help me!
Sorry for the bad english im german and not verry god at writing in english

**Comment by emukidid** [comment]
Use a recent build and when prompted, select the internal variant that you'd like to start.

![image](https://user-images.githubusercontent.com/4575117/50053574-75cb9600-0187-11e9-8312-a1a612bf4c2b.png)
