### ISSUE TITLE
Various Games Stop playing bgm entirely after so long From SD

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#186]
This happens with the Current Version of Swiss and can be reproduced by playing any of the following games after so long the bgm will stop playing and all other sound effects will remain: 

Paper Mario TTYD
Luigi's Mansion
Super Mario Sunshine

With Super Mario Sunshine in Particular a different issue also arises as to where all sound will stop playing as well at times.

**Comment by emukidid** [comment]
Try this again in the latest version but enable Alternate Read Patches
