### ISSUE TITLE
Swiss r440 doesnt boot from sd gecko root.

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#188]

**Comment by emukidid** [comment]
More info please

**Comment by AlexS2412** [comment]
@emukidid upon loading it in any form it wont be able to browse the sd card even when it loaded the swiss boot.dol from the sd gecko moments earlier to boot the newest revision. Pressing A on the sd card icon just takes you back to the menu. All other swiss revisions immediately open to the sd card menu unlike this one. I assume this problem was created by the new file system changes.

**Comment by emukidid** [comment]
What's your card formatted as?

**Comment by AlexS2412** [comment]
FAT32.

**Comment by emukidid** [comment]
Thanks, and what size is the card?

I'll add in some more error reporting to see what error you're getting exactly. I've tried FAT32, FAT16, exFAT in sizes: 4GB, 32GB, 128GB, 200GB and the only one that didn't work was a 1GB formatted as FAT12.

**Comment by AlexS2412** [comment]
32GB

**Comment by DERPSQUID9** [comment]
The same thing is happening to me. I use Datel's SD Media Launcher to boot Swiss from a 1 GB SD card and Swiss cannot read it nor a 64 GB SD card formatted to FAT32.

**Comment by Evan-Almighty** [comment]
I'm having the same problem with a 2 GB SD with FAT format (I'm not sure if that means FAT32, FAT16 or FAT12. It literally says FAT on under format on windows). Works fine with swiss r431.

**Comment by emukidid** [comment]
Try r442, Slot B support was completely broken!

**Comment by AlexS2412** [comment]
I KNEW IT!
