### ISSUE TITLE
20XX Training Pack and SD Remix ISOs don't work properly.

### ISSUE THREAD

**Issue by DERPSQUID9** [emukidid/swiss-gc#189]
I boot Swiss using a 1 GB SD card with Datel's SD Media Launcher and I tried using a 64 GB SDXC card to boot 20XX Training Pack 4.07++ and SD Remix 3.2.1 (both modified Melee 1.02 ISOs), but both lag like crazy when selecting a character or going through menus. I've tried updating Swiss to the newest version (0.4r442) and reformatting the card from FAT32 to exFAT, but the result remains the same. The ISOs only boot at all if the speed setting is set to "Compatible." I have not tried any other ISOs.

**Comment by DERPSQUID9** [comment]
I recently tried updating Swiss to 0.4r446 and booting a vanilla Melee ISO and it lagged as well, so I think that it is a problem with Swiss instead of the ISOs.

**Comment by emukidid** [comment]
It's a limitation of the SD card being connected to the memory card slot. Either find a card that works in Fast mode or burn it to DVD-R. I'm going to add an option to not read slowly (it'll cause audio buzzing), that might help you

**Comment by DERPSQUID9** [comment]
Thanks a ton! Can you recommend a good card, please? I currently use a Class 4 Sandisk 64gb SDXC. Should I get one with a higher speed class?

**Comment by emukidid** [comment]
I use at least Class 10/UHS-I cards as they don't mind being driven in 27MHz "fast" mode.

**Comment by DERPSQUID9** [comment]
I just bought a Class 10 UHS-1 64 GB Sandisk SDXC card and I copied the files from the old card onto it. I only get a green flash right before a black screen on fast mode. I haven't formatted it since I got it. Am I missing something?

**Comment by DERPSQUID9** [comment]
Also, isn't Fast mode 32 Mhz?

**Comment by emukidid** [comment]
Internally it's really like 27MHz cause that's the speed of the EXI bus. Check [issue 192](https://github.com/emukidid/swiss-gc/issues/192) where there's another guy having the exact same issues as you. I need to buy some crappier cards because I've never had this issue and maybe if I did I could add some better read/retry support into the in-game SD reading code.

**Comment by DERPSQUID9** [comment]
Also I don't know if this matters, but I have a DOL-101 Gamecube.

**Comment by DERPSQUID9** [comment]
I tried the 0.4r447 and it didn't help. I am aware that the option to have it not read slowly wasn't mentioned in the changelog, but I didn't want to assume. Would looking up the hardware revision for my Gamecube help you?
