### ISSUE TITLE
Issues w/ loading Pokemon Colosseum Bonus Disc

### ISSUE THREAD

**Issue by omarm12** [emukidid/swiss-gc#190]
I have been having problems loading the Pokemon Colosseum Bonus Disc. Whenever I select it from the Swiss menu, it loads the game then, after a green flash on-screen,it goes black with no responsiveness. I am using a 2gb SanDisk Sd card (FAT) to load Swiss onto my GCN, then swap it with a SanDisk Ultra Plus 32gb SDHC card (FAT). I am using this adapter (https://www.ebay.com/itm/Key-SD-Memory-Card-Stick-Converter-Adapter-for-Nintendo-Wii-Console-Video-HOT/142542188276?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m2749.l2649). I am using an Action Replay disk as well. If you need any more info, I will do my best to provide it. I have tried different adapters, sd cards, formatting, nothing seems to work. Thank you.

**Comment by emukidid** [comment]
Use the latest version and select the pokedownload.tgc when prompted. The thpPlayer.dol and Main DOL aren't compatible.

![image](https://user-images.githubusercontent.com/4575117/50221159-36e64c00-03e4-11e9-869e-cf95d01739dc.png)
