### ISSUE TITLE
Swiss r442 doesnt recognize inserted disc. 

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#191]
It will always fail to load no matter what disc i insert if it is a backup or not. It claims no disc is inserted but other softwares like gcos and r431 of swiss will still see it.

**Comment by emukidid** [comment]
I need more info, boot method of Swiss, when do you insert the disc, all the steps you can think of. What format is the disc, etc. I've been using an original disc just fine.

**Comment by AlexS2412** [comment]
Booted from sd gecko as usual. It jist does not see burnt discs when every other build up to this one did.

**Comment by AlexS2412** [comment]
No idea why this isnt closed but is fixed by r446
