### ISSUE TITLE
Sonic Riders not working in recent version 0.4 R446

### ISSUE THREAD

**Issue by sebastorron** [emukidid/swiss-gc#193]
This game works on v0.3 but lags and then it gets stuck on the SEGA logo in newer versions like 0.4. Now that I saw a new revision, I think that you guys should check it out. I am on a NTSC Gamecube running the SD Media Launcher on a 32 GB PNY 10 Class memory card.

This issue has been out for a while and I love that game!!

**Comment by emukidid** [comment]
Sonic riders does some low level memory stuff that needs to be patched specifically.

**Comment by souturus** [comment]
hey i am using rev 533 and still problems with sonic riders man, what files are needed to be patched?

**Comment by emukidid** [comment]
It hasn't been fixed is what I'm saying.  I need to see what nintendont has done to fix it because there's specific patches in there for that game.

**Comment by regulardude400** [comment]
Might possibly be relevant if this is still an issue? https://github.com/FIX94/Nintendont/blob/master/kernel/Patch.c
