### ISSUE TITLE
SWISS + XENO Issue 

### ISSUE THREAD

**Issue by CryCic4da** [emukidid/swiss-gc#194]
I installed a xeno chip and it works fine. I losd the GBI using swiss and it works fine. I try to launch a PAL game in swiss, it is resetting the drive, then thinks it is a backup, throws the error "disk not initialized" and then "Failed to mount DVD. Press A". When I turn it off and run the game like I normally would, it still works. What is the problem here? Why is swiss unable to read the discs? Is the modchip blocking swiss from reading its region? Strangely enough, it throws the exact same error as when a disc is not inserted. How come? It would seem that swiss cannot patch the drive when xeno is installed.

**Comment by emukidid** [comment]
Try the latest build.

**Comment by CryCic4da** [comment]
Yes it works now! Thank you for attending this issue so quickly!
