### ISSUE TITLE
Zelda Twilight Princess no longer boots from sd gecko in swiss r446

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#196]
Sorry for leaving so many issues but it appears this is broken in the newest swiss now.

**Comment by ChristinMilloy** [comment]
Can confirm. Now getting error dump screen, same iso booted previously. Made sure there was no fragmentation on card.

**Comment by AlexS2412** [comment]
It worked again after replacing with a fresh iso lol

**Comment by ChristinMilloy** [comment]
Confirmed Twilight crashes (issue affects all *single disc* titles)  in r449. Due to bug in multi-disc support feature in folders where 'disc2.iso' is not present. Duplicate issue #198
