### ISSUE TITLE
PSO Episode I & II Plus Black Screen

### ISSUE THREAD

**Issue by RevoltsRevolution** [emukidid/swiss-gc#200]
I tested several other games - all seem to work without any problems. PSO I & II Plus NTSC however doesn't. In the Swiss compatibility list is the Plus version in green, working. However I don't get how this should be accomplished since nothing worked so far.

I tried Google for hours now - the only thread I found was on reddit, with some deleted comments so I don't even know if THAT could've helped or not.

The ISO I try to load has several DOLs before I start. I tried every one, and also the B button for normal start. Is this an issue with the latest version of swiss or is this common? And yes, I really want to use the Plus version. ;)

**Comment by emukidid** [comment]
Try this https://github.com/emukidid/swiss-gc/releases/tag/0.4r451

**Comment by pmasterBR** [comment]
Thank you very much for the update, but even using this version of swiss, I do not understand why pso does not open. I tried all the boots including PSOv3, my version does not have any changes, but something that I always found strange, and that there were already in the previous versions, is that when I open the PSO, a message appears saying: Patching file 1/7, error, can never patch: '' Filed to find necessary functions for patch ''. What could it be? Thank you.

**Comment by emukidid** [comment]
@pmasterBR, if you're seeing that then the ISO you're using isn't valid, perform a SHA-1 checksum calculation on it and check the result against redump.org known SHA-1's.

**Comment by pmasterBR** [comment]
Thanks for your tip, it helped a lot, I managed to open the game, including the version plus, I noticed that if you open an older version of the swiss, in case I use the 174, it will try to patch the iso, and if you try to open by review 541 after this, the game will give that error. But I managed to open it, thank you brother.

**Comment by emukidid** [comment]
I'd recommend keeping a separate sd card if you're using such an old version.

Glad it worked out.
