### ISSUE TITLE
SMB ISO loading with the BBA

### ISSUE THREAD

**Issue by Jademalo** [emukidid/swiss-gc#201]
I'm having issues with this, and so far haven't managed to successfully play a game with it.

I've got Samba set up properly on my Debian server, and everything is wired. After loading swiss, everything is configured correctly and I get the list of ISOs. It takes a while to scroll through them, but I'm assuming it's just the time it takes Swiss to actually get the icons etc.
When loading a game, it tends to hang on Loading DOL for a good minute, but after that will seemingly start to load.

So far, every game I've tried has hung in some way instantly. Super Mario Sunshine hangs on a green screen, and F-Zero GX hangs on the Nintendo/SEGA screen. They load fine through an SD Card, though with audio issues.

Should I be able to load games with this feature in it's current state, or is it extremely early on and not usable for ISO loading quite yet?
Considering the speed of SD loading, I would've thought that loading with the BBA would be by far the best method since the disc drive is ~3MB/s and 100mbit through the BBA is about 12MB/s theoretically.

Any advice or clarification would be appreciated, thanks!

**Comment by emukidid** [comment]
Regarding the speed - the BBA is actually limited by the same EXI bus that memory cards/SD cards run off of which is capped at ~27MHz (slower than the DVD drive).

Samba browsing works, but you need to set up some primitive file serving too that only Extrems has managed to make work.

**Comment by Jademalo** [comment]
That's a shame :(
It would still be more convenient though. 

What file serving is needed exactly? I'm willing to give it a shot if there's a bit of info. Do you just mean the FTP option rather than samba?

**Comment by ChristinMilloy** [comment]
I am very interested in this as well. I am technically inclined and would love to get my Linux NAS to serve games to the GameCube, even if it involves setting up a new sharing protocol or advanced configuration.

Any information on how Extrems managed to achieve it?

**Comment by emukidid** [comment]
You'll need to set this up http://fsp.sourceforge.net/

And apparently you need to limit the GC to 10mbit half duplex, good luck, let me know how you go (I've not managed to test it properly).

**Comment by Jademalo** [comment]
Ouch, limiting it to 10mbit half duplex is quite the challenge. My Linux server also doesn't seem to want to install any fsp servers either, getting a whack ton of errors. I'll give it a better go when I've got a bit more time, but it's not looking likely right now.

Is there a reason why Samba doesn't work? Is it a limitation of the protocol, or is it just that the feature hasn't been developed enough yet?

**Comment by ChristinMilloy** [comment]
Do we know what Extrems used as his gamecube loader once he got the FSP working on the linux end?

Has he/she/they documented the process anywhere online? I did a forum search for "FSP" on gc-forever and nothing came up.

**Comment by ChristinMilloy** [comment]
I've sent Extrems a polite PM on gc-forever to see what information might be available or forthcoming.

**Comment by emukidid** [comment]
There are now settings (page 2 of the settings menu - most just read only for now) in Swiss that will allow FSP to be customised a bit more. There's also a FSP device in the Swiss device list rather than needing Samba + FSP. I've used fspd.exe without a problem on windows, and run it through a TP-Link TL-SG108E managed switch.
