### ISSUE TITLE
Paper Mario: The Thousand Year Door crash at levels 10, 20, or 30

### ISSUE THREAD

**Issue by blagdorfinguy** [emukidid/swiss-gc#205]
Most of the game is stuttered but completely playable, with some audio issues, but since at least 4-r334, the game crashes upon selecting reward for reaching levels 10, 20, or 30. Verified on 4-r451, running off of a Sandisck 16 GB SDHC card.

**Comment by emukidid** [comment]
@blagdorfinguy, can you try in one of the very latest builds please? Send me a .gci backup of your save if it's still a problem after that.

**Comment by wolfpacleader1986** [comment]
I’m having the same issue. The game freezes when I reach level 10 right after I select which I want to increase. I DO have a save backup I can send you. You’d have to beat a boss first and when you do, it levels you up to 10. Let me know how to send it to you.

**Comment by blagdorfinguy** [comment]
Fixed in 4-r650! Almost a full year later, and I JUST NOW figured out how to update Swiss, and even so it's a bandaid fix (however that's only because my disk burner isn't working)

Thank you so much! I'm gonna play the s**t out of this now!
