### ISSUE TITLE
Serial Port 2?

### ISSUE THREAD

**Issue by freeacount1** [emukidid/swiss-gc#207]
Any chance of serial port 2 can be used for SD or USBGecko in a future release?

**Comment by emukidid** [comment]
I spent a bit of time on this to no avail. citrus3000psi provided me with an adapter prototype to try out micro SD from Serial Port 2 but I couldn't get it to work in libOGC no matter what changes I did to exi.c.

I'll try again at some point with barebones EXI code bypassing libOGC completely in that regard to see if it's something wrong with the adapter.
