### ISSUE TITLE
Audio Streaming Issue

### ISSUE THREAD

**Issue by Ohaa2** [emukidid/swiss-gc#211]
Honestly,

When trying to play GameCube titles, that have Audio Stream, using SD or USB on GameCube modded by Swiss, issues with Audio Streaming occurs. As an example of this, when playing "Eternal Darkness: Sanity's Requiem", there were no Intro Poem audio nor in-game music.

**Comment by emukidid** [comment]
Just tried this with SDXC in Slot A on a GameCube via SD to memory card adaptor (SDGecko) and it played fine. Try the following:
1. Use the latest build
2. Try a freshly formatted SD card (with no swiss.ini in case if you've disabled audio streaming etc)
3. Make sure the ISO is a verified dump
