### ISSUE TITLE
Melee freezes at NOW LOADING when you choose a stage.

### ISSUE THREAD

**Issue by OldGnashburg** [emukidid/swiss-gc#212]
So whenever you choose a stage in Melee, the game will get permanently stuck saying NOW LOADING, but the audio still works, but I can't exit out of it or anything. Not sure if this is an issue with my SDGecko setup.

**Comment by nutsky** [comment]
This also happen to.

Swiss: r599
Game: Smash Melee (US) using SD gecko

**Comment by hfc2x** [comment]
It doesn't freeze for me, but it takes _extremely_ long to load everything. I'm using r401 and it works much better with Melee.

**Comment by emukidid** [comment]
Please try again with more recent releases and in-particular with the "Alternate Read Method" enabled.
