### ISSUE TITLE
Graphical Artifacting on Game Logos in SWISS Menu when loading folder contents

### ISSUE THREAD

**Issue by boktai1000** [emukidid/swiss-gc#217]
I've tested and reproduced this issue with the latest-at-this time SWISS release of r599.

My configuration consists of a 4GB non-SDHC card and Component Cables if it matters. On my SD Card I have a folder in the root of the SD Card named "games" that contains a variety of ISOs - I believe some game ISOs/GCMs are needed as well as some other files and folders in the root directory in order to reproduce this due to the manner of the bug.

The bug occurs in SWISS when you go to browse the contents of your folder holding your game files, and when the folder is loading - you will see graphical artifacting (usually green artifacting rectangles) over what would typically be either a folder or files "icon" such as the game art or the default logos for Dir or Dol.

I don't have a capture device, so I'm unable to provide a screenshot - but as I mentioned reproducing it should be pretty simple. Have a couple of folder/files in your root folder, and then a folder that has some games in it that will require SWISS to process the folder contents for games and their artwork. While SWISS is loading, the current screen you're at will corrupt/artifact the respective logos for most or all games, folders, and any files (such as dol files).

As far as I can tell, this is purely a cosmetic issue at least as far as I can tell, but I don't know if there any additional repercussions or implications behind the scenes with it as that's beyond what I'm aware of.

I also posted this issue to the forums, but felt like I should probably do a formal GitHib issue for it as well- https://www.gc-forever.com/forums/viewtopic.php?f=25&t=1375&p=42934#p42934

I was also reading some of the commit changes / changelogs for recent releases and it sounds like there was some GUI rework in the back-end. I'm unsure when this change actually came through though so I don't know if it's related, I just know right now that it's happening in the r599 build.

**Comment by emukidid** [comment]
This should be addressed in the next release with commit 7ba99580e577c5248ae30538fd60d837256f34a5
