### ISSUE TITLE
dont load pal games

### ISSUE THREAD

**Issue by rojo1098** [emukidid/swiss-gc#219]
i have zelda tp,re0,zelda 4 sword and others in pal versioin but my swiss r599 don load it but in version r431 i can load it.

**Comment by rojo1098** [comment]
i have the config text of r431, video mode:auto, titles zelda MQ,TP,WW,etc. Resident Evil 0,2 and 4. my GC is USA region. when i load the game only show me a black screen, but if i run the games in r431 works very well

**Comment by tengzl33t** [comment]
Same problem with Resident Evil 4 PAL (don't load, only black screen), but NTSC version works well. 
I have PAL console with Swiss 0.4 r646.
