### ISSUE TITLE
PSO I & II Plus Freezes When Going Online

### ISSUE THREAD

**Issue by krow1994** [emukidid/swiss-gc#225]
PSO I & II Plus works fine offline, but when trying to go online it freezes on the loading screen. I'm playing from SD, on a Gamecube, connecting using a broadband adapter.

**Comment by adolfnixon** [comment]
I can try and help with testing if needed.

**Comment by krow1994** [comment]
I can help with testing if needed.

**Comment by witcheslive** [comment]
I would like to add that, while I know this is a pain, I would extremely love to see this working

**Comment by witcheslive** [comment]
Update: it works as of https://github.com/emukidid/swiss-gc/commits/v0.4r743
