### ISSUE TITLE
Multi Disc Games Do Not Work

### ISSUE THREAD

**Issue by jeromedontdev** [emukidid/swiss-gc#226]
On the latest release, I am unable to get multi disc games to function properly. I have tried Baten Kaitos and Tales of Symphonia. For each of these I have tried two different SD cards and two different verions. I have found issues regardless. With Tales, font is garbled, with Baten, it freezes at a green screen.

What I have found is that if I do not adhere to the multi disc naming convention, they load without issue. 

i.e.
"Tales - 1.iso" (nonworking) > "Tales - 1disc.iso" (working)

**Comment by emukidid** [comment]
Check [this](https://www.gc-forever.com/forums/viewtopic.php?f=25&t=4318) thread, it's fixed in r650.
