### ISSUE TITLE
Crashing on latest release

### ISSUE THREAD

**Issue by dark-nova** [emukidid/swiss-gc#228]
Hi,

I have never soft-modded my GameCube before and decided to give Swiss a shot, using the latest release (`swiss_r649`). I have tried both the compressed and regular .dol. To load the file, I use psul and it appears to send the file correctly.

However, I have experienced Swiss crashes in the following ways:
- Immediately after it launches up until an unspecified time, Swiss can crash if I move the analog stick. I get to a black screen with what appears to be a crash dump and an exception. Pressing A here causes `reset` to be printed at the bottom but does not appear to reset anything.
- After it seems to fully load, Swiss will also lock up (confirmed by observing time freezing). No exception screen as above

I have tried using separate controllers (first a Wavebird, and a regular wired one), but I don't seem to make any progress.

I have also tried the previous version (`swiss_r646`) but I still experience the same issues.

Any advice?

**Comment by emukidid** [comment]
What devices do you have plugged in when this happens? Any more info you can add?

**Comment by dark-nova** [comment]
I have a Broadband Adapter attached to the console. Aside from that, I
tested just with one controller in use (Wavebird and wired, all official).

If it helps, I've noticed my GameCube has had clock issues since I first
started using it again, after years of inactivity. Wondering if that
indicates other issues.

Thanks for looking into this.

**Comment by emukidid** [comment]
I used PSOLoad (similar enough to PSUL) and couldn't replicate this, perhaps it has been addressed since this ticket was raised. Let me know if it's still broken for you.
