### ISSUE TITLE
"Exception (DSI) ocurred!" when trying to open original game disc with swiss.ini saved on official memory card

### ISSUE THREAD

**Issue by zesamot** [emukidid/swiss-gc#232]
First of all, thank you for all the hard work spent in this great project!

About the problem, it's a minor issue but I would like to report it to you guys non the less. I'm always getting an "Exception (DSI) occurred!" error when trying to open an original Gamecube dvd from the device selection. It shows the initializing progress bar and then crashes. I noticed that this only happens if I have a swiss.ini configuration file saved on my official NGC memory card (no matter the slot that it is chosen as the configuration device). If I delete the swiss.ini file everything works great, although this means configuring the game settings every time I boot (not a big deal if there is no way around it).

Currently I'm only using Swiss to force 480p/576p mode and remove alpha dithering.

- Using a Wii PAL
- Latest Swiss release (v0.4r650)
- Booting original GC game discs
- Using an official Nintendo memory card with game save files and also as configuration device to save swiss.ini
- Exception (DSI) occurred!:
          DAR 0129DBC4 DSISR 06000000       
          STACK DUMP:
          8009ff78-->8009fa54-->80022248-->800229a0-->
          80009cbc-->800065bc-->80062ef4-->80062e58

Let me know if you need any more informationd and thank you once again.

**Comment by emukidid** [comment]
I fixed a memory card crash in b2d694c9f1554a04efe70975d77922dbf80dbd1b but I don't think it will have fixed this. Worth a try anyway after the next build is available.

**Comment by zesamot** [comment]
Thank you, I'll give it a try when the next build is released and will report it back to you.
