### ISSUE TITLE
Metroid Prime 1 & 2 FMV are slowed

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#235]
using the alternate read patches the gameplay stutters and music issues have been fixed. the only issue left is the FMVs that play on the title screen and in some areas of the game are slower than normal and end prematurely.

**Comment by emukidid** [comment]
Try with the latest release and see if has improved at all. If you're lucky enough to have access to a BBA that will yield slightly better results too.

**Comment by AndehX** [comment]
Just posting to add that I have noticed this too.  I also notice slowdown/stutter in certain areas of the game.  This is with alternate read patches enabled.  I am using a Sandisk Extreme 64GB SD card.
