### ISSUE TITLE
Releases in Zip / tar.gz?

### ISSUE THREAD

**Issue by solderjs** [emukidid/swiss-gc#238]
Could you upload the releases in `zip` instead of `7z`?

* All Windows machines have Zip pre-installed
* All Macs have Zip _and_ `tar` and `gz` installed
* All Linux machines have `tar` and `gz` pre-installed, and most have `unzip` as well.

Also... why do 1337 h4x0r2 always upload things in 7z and rar? In the broader open source community we all use standard formats (`zip` and `tar.gz`), but it seems that lots of hardcore hackers / crackers / reverse engineerers prefer obscure formats.

They don't really compress _that_ much better in the general case (though it did seem to do a better job in this particular case) and they're super difficult to deal with... what's the draw?

**Comment by solderjs** [comment]
P.S. Thanks for doing this. I'm glad it exists, just frustrating to have to install and figure out how to use 7z and, worse, trying to explain it to others.

**Comment by emukidid** [comment]
Sure - I'll add more variants. 

7z does compress better from what I've found which is why I used it.

**Comment by solderjs** [comment]
👏 Thank you!

That would be so awesome and so much easier for doing tutorials, screencasts, and scripts.

**Comment by emukidid** [comment]
.tar.gz and .zip both end up near 15MB each, how about a .tar.xz or is that too obscure/1337 h4x0r2esque for you?

**Comment by keilmillerjr** [comment]
7z is awesome. Being blunt, if you cant google and find http://www.7-zip.org for a precompiled windows binary, then figuring out what to do with swiss probably isn't for you. Mac: brew install p7zip Arch: pacman install p7zip Ubuntu: apt-get install p7zip-full p7zip-rar

**Comment by emukidid** [comment]
Not going to add alternatives, it's one sentence to direct someone to 7-zip or similar tools. Sorry.

**Comment by solderjs** [comment]
Nooooooooooooo!

Who cares if it takes 15mb? Why add a mental load of figuring something out that doesn't need to be?

`.tar.gz` and `.zip` are easy and convenient and doesn't require additional tools or steps.

Also, repeating the instruction for easier reading and copy/pasting:

**Mac**

```bash
brew install p7zip
```

**Arch**

```bash
pacman install p7zip
```

**Ubuntu**

```bash
apt-get install p7zip-full p7zip-rar
```

**Windows**

<http://www.7-zip.org>

**Comment by Steel-J** [comment]
Wow, aren't you an entitled loser.... not everything has to change to accommodate your deficiencies. It's free software being regularly updated and provided to you at no cost and yet you still complain.

**Comment by solderjs** [comment]
@Steel-J No need for name calling and mud-slinging.

I represent the majority of people: people who don't have 7z installed and find it cumbersome to use.

**Comment by solderjs** [comment]
My goal is to help this project reach more people, and for them to be more likely to experience success with less education.

**Comment by coolaj86** [comment]
Re: https://github.com/emukidid/swiss-gc/releases/tag/v0.5r927 tar.xz: Thank you! I really appreciate it!
