### ISSUE TITLE
Corrupted Memory Cards with Swiss-GC

### ISSUE THREAD

**Issue by Xibalba66** [emukidid/swiss-gc#239]
Hello,

Since I have been using WISD (SD Gecko) it is impossible for me to keep my GameCube saves.
I tested with 4 different (official) memory cards but as soon as I restart the console and launch a game, the console asks me to format my memory card to be able to use it...
I don't have this problem when I play with 8cm DVDs.... Only with Swiss. 

I use:
- GameCube with XenoGC
- 4 Nintendo official Memory Cards
- WISD (SD Gecko)
- SanDisk Ultra Micro SDHC 32 GB and Samsung 32 GB EVO plus Micro SDHC
- Swiss 0.4 r656 (new build) and 0.4 r646

Can you help me?

**Comment by Tommy1995gc** [comment]
Hi there,
I have just read your issue and I can confirm you that I have the same problem when I launch Battle Stadium D.O.N or any other Japanese title using 0.4 rxxx Swiss versions
I recommend you to use one of 0.3 versions of Swiss for these games, just like I do. I know that the compatibility is so bad with them but you can avoid the corruption of your Memory cards doing that.
You can find the same problem with Battle Stadium D.O.N in the swiss-compatibility list here: https://www.gc-forever.com/wiki/index.php…
Unfortunately I don't know how to patch the games to ntsc-u...

I hope I was helpful.

Yours truly,
Thomas

(P.S. I know that it is difficult to find the oldest Swiss versions on Google, therefore I attached you the same Swiss version I use :D ) 
[Swiss v0.3.zip](https://github.com/emukidid/swiss-gc/files/3800566/Swiss.v0.3.zip)

**Comment by Extrems** [comment]
You may use the force text encoding option.
