### ISSUE TITLE
r656 compatibility issues

### ISSUE THREAD

**Issue by Mazz1983ita** [emukidid/swiss-gc#241]
DOL-001, XenoGC clone, swiss r656 on DVD-R, .iso from SD via memory card adapter.

Most games run as expected but some, even if listed in the compatibility list as working, give me the infamous "An error has occurred. Turn the Power Off and check the Nintendo GameCube Instruction Booklet for further instructions.".

Blank DVDs are hard to come by in my area, and I wanted to know if there's something I can do in the settings or I have to burn the fresh new release.

Thanks in advance.

**Comment by emukidid** [comment]
You can load the Swiss DOL automatically from SD card if you place it on there as boot.dol. That means any time a new Swiss release is made you just drop it onto the SD card as boot.dol and your old version from disc will boot it for you.
