### ISSUE TITLE
Loading files from SD Gecko requires remounting SD card

### ISSUE THREAD

**Issue by MikeIronFist** [emukidid/swiss-gc#242]
When I load Swiss via (Slot B) SD Gecko + SD Media Launcher, it appears to load the top level directory of my SD card into the file list but doesn't seem to "fully" mount it. Directories appear empty and any DOL files on the root of the SD card will fail to load.

Going to the mount menu and remounting the SD card fixes this and allows the DOL files and folders to be read correctly. DOL files load as normal after remount.

This bug seems to have emerged with this release, as reverting to r656 removes the issue.
So on r656, DOL files and directories will read correctly at boot time.

**Comment by Extrems** [comment]
Fixed in ba6dba8 (r773).
