### ISSUE TITLE
Wiikey fusion no longer reads SD card

### ISSUE THREAD

**Issue by afromanDAN** [emukidid/swiss-gc#243]
When it boots up there's an option to mount but it doesn't mount. I also can't mount from the sd card slot.

**Comment by afromanDAN** [comment]
I had to downgrade via the recovery iso.

**Comment by emukidid** [comment]
Grab [9c7d8020ddb2e936df0340d1ba3e82098e6e9a15](https://github.com/emukidid/swiss-gc/releases/tag/v0.4r683) from the releases page and close this issue if it's working now.
