### ISSUE TITLE
r683 - 'An error has occurred' during gameplay

### ISSUE THREAD

**Issue by atlaso** [emukidid/swiss-gc#244]
Using an SDGecko booted from SD Media Launcher. After updating to r683, games are suddenly crashing during gameplay at seemingly random times. So far Kirby Air Ride and Super Monkey Ball have crashed with this error. I deleted the patches and the swiss.ini file after upgrading. This issue wasn't present in the previous version I used (r650). I assume the updated alternate read patches are the issue.

**Comment by AndehX** [comment]
I have the same issue in Metroid Prime.  I'll get "An error has occured" at random times when attempting to open a door.  Also worth noting is that the music will continuously loop the last couple seconds just before the error occurs.

**Comment by ThadHouse** [comment]
I think I'm seeing the same thing in Simpsons Hit and Run as well. It randomly crashes without warning, all in different areas. Usually only lasts about a minute or 2.

**Comment by Extrems** [comment]
Fixed in d594b6b.
