### ISSUE TITLE
Patches on Swiss through WASP

### ISSUE THREAD

**Issue by RenoFriends** [emukidid/swiss-gc#247]
I have WASP installed internally on my GC and the latest version of Swiss but I can't find information about how to run properly the games with audio streaming.
There are patches that can be applied? Do I need to put in on the SD? I want to avoid using SD Gecko if possible, thanks!

**Comment by emukidid** [comment]
WASP doesn't support audio streaming and Swiss doesn't support it as a read device directly, we basically set it up with enough and then let it do its thing. At some point I will try the alternate read patch code with it to see how it performs, but there's no point until it has audio streaming too.

**Comment by Extrems** [comment]
Fixed in 48d80be (r861).
