### ISSUE TITLE
Instructions for building with latest (3.0.3) version of devkitPro

### ISSUE THREAD

**Issue by ThadHouse** [emukidid/swiss-gc#248]
I'm attempting to build from source in order to get a build with the read patches fixed, and am running into an issue. I am using a fresh copy of devkitPro on Windows 10, using the msys2 shell. The same build works to build cleanRip, but fails in a weird way for swiss. I get the following output from make.

```
Building on Windows_NT
make[1]: Entering directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/cube/swiss'
clean ...
make[1]: Leaving directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/cube/swiss'
make[1]: Entering directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/pc/usbgecko'
make[1]: Leaving directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/pc/usbgecko'
make[1]: Entering directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/cube/patches'
Building execD replacement ...
make[1]: *** [Makefile:33: build-execD] Error 1
make[1]: Leaving directory '/home/thadh/Documents/GitHub/thadhouse/swiss-gc/cube/patches'
make: *** [Makefile:48: compile-patches] Error 2
```
Its seems like its getting an error calling gcc, but it works just fine from the cleanrip build, and also works if I manually compile the compiler.

**Comment by emukidid** [comment]
Are you typing "make all" from the root dir? That works fine for me.
