### ISSUE TITLE
Background music audio in some games r685

### ISSUE THREAD

**Issue by linkse08** [emukidid/swiss-gc#252]
I have some problems with the latest version of Swiss r685. I use wind waker exploid to boot Swiss and I have Swiss r472 on my Memory card. I boot Swiss r685 from my SD and try to play some games like Luigi's Mansion the game after 5 minutes lose the background music, this happens again with Paper Mario, I try to boot smash melee and happens again. I use the config with the DVD motor stops when Swiss boot, with the version r472  boots well with some issues but the background music works. 
Gamecube model: DOL-001
sd card: 8gb class 4 sandisk
boot: memory card in B port with sd adapter
I use the digital output with original Gamecube component cable
Thanks emukidid and the team for all!

**Comment by AlexS2412** [comment]
use alternate read patches from the config menu. this fixes audio issues and speed issues for almost every game, fmv however will still be a little slow for some reason

**Comment by linkse08** [comment]
I used the alternate patches and make this problem in Luigi's Mansion, in the other games I only boot once and happened that problem. When I tried to boot for second time, the problem was solve but I must reload the sd card again when I boot the last version of Swiss for the music works.

**Comment by FabS0nic** [comment]
Hello, i have the issue with r688 and Luigi's Mansion, no background music. Have tried alternate read patches but same issue. I also tried others SD cards but the issue still the same. Any ideas ? Thanks

**Comment by mitchoshea** [comment]
Having the same issue as well, no background music in Luigis Mansion, THPS 4 and a bunch of other games. Used alternative read patches and made no difference.

Setup:
DOL-001 GameCube
SD Media Launcher in Slot B
SanDisk 128GB Micro SD XC
GCHD Mk-ii

**Comment by mitchoshea** [comment]
I’ve since tried using SDSP2 and r714 to load games from and the issue persists. I recall using a previous release (r565 or something like that) where the music would play initially and then stop after some time, however with recent releases the bgm just doesn’t play at all right from the get go with almost every single game I’ve tried.

**Comment by Extrems** [comment]
Fixed in 87554d3 (r749).
