### ISSUE TITLE
Black screen when loading backups with Fast/32Mhz option

### ISSUE THREAD

**Issue by atlaso** [emukidid/swiss-gc#253]
I'm only able to use my microSD with the 'compatible' option despite the card being suitable for 32mhz, according to the compatibility list. Attempting to load a backup with the 'fast' speed enabled results in a frozen black screen.

For reference, my microSD card is a Sandisk Ultra 32GB, Class 10. I'm using the SDGecko that came with the SD Media Launcher. Do I need a different adapter to use the 32mhz option? This issue persists across all versions.

**Comment by emukidid** [comment]
Try r688, this may have resolved it.
