### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by vidplace7** [emukidid/swiss-gc#257]
The swiss-gc project currently does not appear to have a license for it's codebase.

[Not having a license leaves the codebase in a weird place as far as what can and can't be done with it](https://choosealicense.com/no-permission/). On paper, this only allows for the code to be used by the owner.
In practice, no license means that anyone can do whatever they want. Including making a closed source fork and selling it for a profit.

Contributors to this project should pick a license that reflects their intentions for the use of this code.
I would suggest the GPL license, which allows for commercial use, but mandates that any changes to the code should be published.
https://choosealicense.com/licenses/gpl-3.0/

**Comment by emukidid** [comment]
I have purposely left the repo without a LICENSE file to allow default copyright laws to apply. I'm curious as to why this has been brought up now?

**Comment by emukidid** [comment]
Added GPL v2.0.
