### ISSUE TITLE
Possibility to autoboot an iso-gamefile?

### ISSUE THREAD

**Issue by Mon3000** [emukidid/swiss-gc#259]
Hi emukidid, 

I was wondering, if you would like to implement a function in Swiss, with which it is possible to autoboot an iso-file directly from Swiss at startup, like it is possible with dol-files. 
For me this would be a great feature for the swiss experience, starting your gamecube and directly boot into your game with the chosen default game settings. 
What do you think about such an option?
Best regards

**Comment by emukidid** [comment]
Added in 9cb7ef38cae6af07a1828c01ac6e8a6ac3255ced

**Comment by TheInfernolab** [comment]
Thank you for implementing this!

I downloaded the new "swiss_r906-compressed.dol" & put it on my GameCube.

Can you please explain how to assign the .iso file that shall be auto-booted?
And how to prevent the autoboot if desired?
I do not see documentation or on-screen help to explain the process.

Thank you very much!
-Jason

**Comment by Extrems** [comment]
Select a game, press Z as written on-screen.

**Comment by TheInfernolab** [comment]
Thank you for your quick reply. I do not see a Z option.
After selecting a game, only buttons X, Y, B, & A are shown with their action. Pushing Z does nothing.

My setup:
GameCube DOL-001
Hyperboot installed
"swiss_r906-compressed.dol" on an SD card in a memory card-to-SD card adapter in slot B; file is in the "HYPERBOOT" directory
One .ISO game is in the root directory, on the same level as the "HYPERBOOT" directory

Thank you very much!
-Jason
![01](https://user-images.githubusercontent.com/64886717/92985337-69609400-f466-11ea-9dfe-86916989481b.JPG)
![02](https://user-images.githubusercontent.com/64886717/92985349-74b3bf80-f466-11ea-998b-0befa4eddcb3.JPG)

**Comment by Extrems** [comment]
Do you have a valid configuration device set?

**Comment by TheInfernolab** [comment]
Thank you very much for the advice. I have now set a valid configuration device & am able to save settings & am getting closer!

Now, when I select the ISO, I do see the option for "Load at startup (Z) [Current: Yes]" & it saves this setting successfully.

When I boot the Gamecube, I am presented with the image below, indicating that this ISO has been selected & its selection has been saved successfully, but it does not boot the ISO. Is the new functionality intended to boot (launch) the ISO, or select it within the Swiss menu without running the ISO?

Thank you very much,
-Jason

![IMG_20200912_145605](https://user-images.githubusercontent.com/64886717/93005914-f78e5600-f50a-11ea-98c0-228d543df71d.jpg)

**Comment by emukidid** [comment]
It's intended to send you to this screen so that you can then just press A or review your settings. I might refine the functionality further with a timeout on this screen if sent to it via the "Load at startup" option.

**Comment by TheInfernolab** [comment]
Thank you for explaining. I will cross my fingers that you incorporate a timeout launch or even an instant launch (which could be overridden by holding a certain button when Swiss is launched).

The desire is for something like a party kiosk/demo setup where it can be left unattended w/ non-savvy folks so that, when the game crashes, they can just cycle the power to get back up & running again; or so that it's literally "just plug it in & turn it on" to play.

Thank you very much!
-Jason
