### ISSUE TITLE
Reset console after load a game 

### ISSUE THREAD

**Issue by rojo1098** [emukidid/swiss-gc#260]
In the last version (r685) when i try to load a game like zelda collectors or zelda ocarina with 2 or more games in the same disc, the console restart automatically.

In another versions like r634 i can play the games perfectly.

Im using a GC first generations with chip xeno and sd card ( 32gb read:4 ) in the b slot.

(im pressing the B button to start automatic)

**Comment by emukidid** [comment]
In settings, can you try enabling Alternate Read Patches if they aren't already enabled.

**Comment by rojo1098** [comment]
they are already enabled, i try erasing the config ini and let the new version create one new but the problem continue.

**Comment by Papy-G** [comment]
Same problem here with 688 and OoT, first I thought it was SD2SP2 related.
SWISS seems to hurt itself in confusion if persisting in trying, unable to save config, then, no isos vignettes, and can't launch any of them anymore!
Erased patches and ini file to no avail…
Do we have to check what was the last release that worked?

**Comment by Papy-G** [comment]
Hi, issue can be closed, it works when disabling alternate read patches (r688/Pal GC/Pal Zelda OoT MQ).
