### ISSUE TITLE
TLoZ: Twilight Princess is broken

### ISSUE THREAD

**Issue by hfc2x** [emukidid/swiss-gc#261]
On the latest build (as of writing, r688), The Legend of Zelda Twilight Princess manages to boot, but immediately after loading, throws the default error of "An error has occurred, please turn off the Nintendo Gamecube". I don't know when this broke, but the last build I used in which the ISO I'm using, worked fine, was from before the rework (r401).

I'm booting from an SD Gecko on memory card slot B. The Wind Waker doesn't have this issue.

EDIT: Pokémon XD is also broken now, but it only shows black screen upon booting. Pokémon Colosseum doesn't have this issue.

**Comment by Extrems** [comment]
Works for me. Pokémon XD was fixed in cc56956.

Make sure your disc images match Redump. Only use NKit when shrinking.

**Comment by hfc2x** [comment]
Okay, my bad. Twilight Princess was a mistake on my end. _However_, I'm using a non-shrunk, clean (and Redump-checked) image of Pokémon XD, and it boots into black screen. It boots okay with older builds, but doesn't with latest.

**Comment by Extrems** [comment]
Again, it was fixed in cc56956, which corresponds to r691.
