### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by ZweiBR** [emukidid/swiss-gc#262]
Metal Gear Solid: The Twin Snakes

Freezing when starting the game in the name of KONAMI.

**Comment by Extrems** [comment]
Known issue since 223a426. Still haven't figured it out.

**Comment by ZweiBR** [comment]
This version of swiss 451 works, after 20 seconds it goes by the name KONAMI.

**Comment by ZweiBR** [comment]
https://www.youtube.com/watch?v=gV5By4HSvQA

**Comment by Extrems** [comment]
It works in r688 if you disable the alternate read patches.

**Comment by ZweiBR** [comment]
https://www.youtube.com/watch?v=Jid4oBdTXow

The screen flashes green as you can see in the video.

**Comment by Extrems** [comment]
Fixed in 4279534 (r712).
