### ISSUE TITLE
Having to burn new disc upon each update

### ISSUE THREAD

**Issue by RobertDaleSmith** [emukidid/swiss-gc#263]
My stack of burned Swiss discs is starting to become larger than the number of blank ones I have left. I was curious if it's possible to make a one time boot disc that reads the actual Swiss files off of an inserted SD card instead? Either from SD in a memory card slot or SD2SP2? This way upon each update I just update my SD card files and keep using the same disc. Maybe this is already possible and I just didn't dig deep enough? It would be awesome if future Swiss releases included a one time boot disc for SD loading.

**Comment by keilmillerjr** [comment]
I just got my SD2SP2. Need some discs and a cd rom drive. Was thinking the same thing. Perhaps a boot disc that checked for swiss file on various locations.

**Comment by emukidid** [comment]
You don't need to burn new discs, Swiss will look for boot.dol from SD cards and certain other devices, just place new releases as boot.dol on the root of your SD card.

**Comment by RobertDaleSmith** [comment]
@emukidid I figured I didn't dig deep enough lol. Thanks for the quick response.
