### ISSUE TITLE
Can't reach Animal Crossing's title screen on Swiss v0.4 r688

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#265]
**Bug Description**
Animal Crossing (USA) fails to reach in the title screen. With Alternate Reading, the Nintendo logo lingers for a bit longer and then the error message pops up, as shown in the video.
Without Alternate Reading, the game simply freezes at the logo screen.

**Video**
https://www.youtube.com/watch?v=ab-84rIbRug

**SD Card Information**
Port used: SD2SP2
Brand: Kingston
Format: microSD
Type: Class 10 + UHS-I
Size: 32GB

**Game File Information**
ISO's CRC32: 7BE72542
Compression format: gcm

**Swiss version**
v0.4 r688

**Swiss commit**
f413d75

**Comment by Extrems** [comment]
This game works fine. Your issue is unrelated to it.

**Comment by JCnatorU** [comment]
So, I'm doing it wrong then. How could I get that one running up?

**Comment by Extrems** [comment]
I have no idea. It should just work.

**Comment by Extrems** [comment]
Please only use NKit to shrink disc images. Other tools are broken.
https://wiki.gbatemp.net/wiki/NKit

**Comment by JCnatorU** [comment]
Got around compressing the original disc image into a .nkit.iso with NKit v1.4, and managed to get the game working with the same parameters. Turns out GCM Utility v0.5 was responsible for this issue.

Might want to write in the README.md file about favoring NKit over other compression tools when it comes to converting disc images.

**Comment by Extrems** [comment]
I've done something more aggressive. See ec87a4e.
