### ISSUE TITLE
Problem with Viewtiful Joe (Europe) and Alternate Read Patch

### ISSUE THREAD

**Issue by gkralicek** [emukidid/swiss-gc#266]
Performances in this game (especially during intro cinematics and attract mode) are really poor using Alternate Read Patch which is weird as far as all the other games i've tried always showed improved performances when using this reading method.

**Comment by Extrems** [comment]
It is showing an improvement over the old method, but it's performing as expected.

**Comment by gkralicek** [comment]
No, the old method is much better with cinematics than the alternate patch method on this game this is why i was surprised cause on all the other games i've tried the alternate read method always showed an improvement. Try it ! :=)

**Comment by Extrems** [comment]
I have. Do you need a video?

**Comment by gkralicek** [comment]
No, don't bother making a video, i trust you :=). So maybe something is wrong with my conf cause for me it's the other way round, the alternate patch brings awful breakups in the video and audio in the first intro animation while turning back to old method, gives me acceptable speed with a lot less hiccups.

**Comment by Extrems** [comment]
My best guess is your SD card is somehow struggling with stretched-out multiple block read commands.

**Comment by gkralicek** [comment]
I made some further tests today and couldn't spot what the problem is with my conf.
I'm using SD Media launcher to boot the Gamecube and swiss (latest r714) is launched from SD Gecko in memory slot B. All my games are placed on a Sandisk 32Gb SD card plugged in SP2.
I tried different brands of cards (Kingston, Samsung,...) but i get the same poor result with Viewtiful Joe (European Pal version) when using alternate read method.
I made 2 videos i posted on youtube so that you can see what i get

https://www.youtube.com/watch?v=A46MQQC-H04 (this one show the choppy result with Alternate Read )
https://www.youtube.com/watch?v=qSN4fACIVcM (this one show the much better result achieved with old method)

Any idea ??

**Comment by Extrems** [comment]
This seem specific to the European version. I only checked it using the Broadband Adapter/File Service Protocol.

**Comment by gkralicek** [comment]
I can confirm the problem only happens when using the european version of the game as i just tried with an ISO image of the US version of Viewtiful Joe and it works perfectly with Alternate Read method (much smoother than the old method and very close to being perfect with only a few audio/video hiccups)
So i guess the european version needs a specific patch of its own.

**Comment by Extrems** [comment]
Most of the game-specific patches are for games using custom/buggy virtual memory managers. A game-specific patch is inappropriate in this case.

**Comment by Extrems** [comment]
Fixed in a5ca3ea (r723). Turns out it was appropriate.

**Comment by Extrems** [comment]
Fixed in 87554d3 (r749).
