### ISSUE TITLE
r714 won't allow browsing SD card in memory port B once files on SP2 are displayed

### ISSUE THREAD

**Issue by gkralicek** [emukidid/swiss-gc#267]
r714 looks for SD card in SP2 by default and when found files are displayed right after swiss has loaded from my SD-Gecko plugged in memory port B. But when pressing the "B" (red) button to access the drive browser and selecting the SD card in memory port B, nothing is diplayed and i'm taken back endlessly to the drives list to select from. 
Seems once the content of SD in SP2 is displayed, the port hosting the SD-Gecko used for booting swiss is discarded by the system and cannot be accessed anymore. The same happens if i want to save the parameters on the SD in slot B, i get a "config save error" message because the system can't access the drive.
When reverting back to the previous version of swiss (r688) there is no such a problem anymore.

**Comment by Extrems** [comment]
I tested this with the configuration device set to either Serial Port 2 or Memory Slot B and both worked.

**Comment by Extrems** [comment]
Can you try setting the EXI Speed to Compatible/16 MHz? That setting didn't actually work before.

**Comment by gkralicek** [comment]
Yes it works ! If i set EXI Speed to Compatible/16Mhz, i can again access the content of the SD card i got in memory slot B. But by doing this all the other slots connected to EXI bus run at 16Mhz which slows down games execution from SP2 (especially obvious with the ones using audio streaming)
The strangest thing is that i can browse my SD card in slot B with r688 even with the bus speed set at 32Mhz by default while i can't do it anymore with r714 unless i slow down the bus speed to 16Mhz.
Weird...

**Comment by Extrems** [comment]
That's because it was effectively stuck to 16 MHz in Swiss. It only took effect in-game.

**Comment by gkralicek** [comment]
Ok i see so it means the bus speed settings now works as intended with r714 which wasn't the case with the previous r688.
Wouldn't it be possible to set the bus speed handling for each device individually instead of making it a global parameter affecting all devices on the EXI bus ?

**Comment by Extrems** [comment]
Fixed in ba6dba8 (r773).
