### ISSUE TITLE
v0.4 r714 - Harry Potter and the Chamber of Secret (USA) - Hard Reset button combo not resetting

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#268]
**Bug Description**
Performing the Hard Reset button combo (R + Z + B + D-Pad Down) leads to disc ejection error screen instead of rebooting. Pressing the Reset button on the console reboots to GameCube BIOS.

**Image**
![0002](https://user-images.githubusercontent.com/53985633/70545677-f2474980-1b3b-11ea-8233-8f78aff6174e.png)

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: 115F3228
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by Extrems** [comment]
As of 57678c5, IGR no longer respond at all. This game and Dark Summit use a reset callback, which we're unable to deal with at the moment.

**Comment by Extrems** [comment]
Fixed in cb2e544 (r764).
