### ISSUE TITLE
v0.4 r714 - Kirby Air Ride (USA) - Game won't boot without USB Gecko debug output

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#269]
**Bug Description**
The game won't boot at all regardless of the disc reading mode without USB Gecko debug output, as it displays black screen forever.

**Video**
https://www.youtube.com/watch?v=xx05K2crxhw

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: F1A3E7A2
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by Extrems** [comment]
Works for me.

**Comment by Extrems** [comment]
I seem to have confused myself with this. I had hit a bad block on my SD card while testing different configurations.

**Comment by Extrems** [comment]
Cannot reproduce with SanDisk Ultra 64GB or Kingston Canvas Select 32GB, using either Memory Slot A/B or Serial Port 2, with default or any settings, with or without any accessories.
