### ISSUE TITLE
v0.4 r714 - Billy Hatcher and the Giant Egg (USA) - Hard Reset button combo won't trigger reboot behavior

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#270]
**Bug Description**
Performing the Hard Reset button combo (R + Z + B + D-Pad Down) won't trigger reboot behavior. Hitting the actual reset button will reboot straight to the game.

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: 894DDFF0
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by Extrems** [comment]
Fixed in 57678c5 (r729).
