### ISSUE TITLE
v0.4 r714 - 1080° Avalanche (USA) - Music won't play outside of FMVs

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#271]
**Bug Description**
Using Swiss's Alternate Reading, music won't play outside of FMVs regardless of the music volume set in Sound Options.

**Video**
https://www.youtube.com/watch?v=HkawrhAotLE

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: 2C37CF08
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by Extrems** [comment]
Fixed in e3c4023 (r848), but DMA audio is currently missing instead, while streaming audio is playing.
