### ISSUE TITLE
v0.4 r714 - Wave Race Blue Storm (USA) - No wave sounds and music won't play outside of Sound Test

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#272]
**Bug Description**
Using Swiss's Alternate Reading, music won't play outside of Sound Test and there's no wave sound at the title and loading screen.

**Video**
https://www.youtube.com/watch?v=HqCFUecwvWw

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: D2EE9CCD
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by BrianVerHur** [comment]
Same with the EUR iso, 

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 32GB

**Swiss version**
v0.4 r785

**Comment by Extrems** [comment]
Enable audio streaming emulation to hear streaming audio.

**Comment by JCnatorU** [comment]
With audio streaming enabled as of v0.4 r798, the music plays correctly outside of the inherent SD2SP2 bus speed limitation.

**Comment by Extrems** [comment]
It's not inherent to the bus speed limitation, it's inherent to the old patches.

**Comment by Extrems** [comment]
Fixed in e3c4023 (r848), but DMA audio is currently missing instead, while streaming audio is playing.
