### ISSUE TITLE
v0.4 r714 - Luigi's Mansion (USA) - Inconsistent audio playback

### ISSUE THREAD

**Issue by JCnatorU** [emukidid/swiss-gc#273]
**Bug Description**
After starting a new game, music and certain audio files (i.e. Luigi obtained a key) won't play while having Swiss's Alternate Reading enabled. After a reboot and selecting an existing file slot (at 9:40 in the video), the missing audio is back with the exception of music cutoff occurring while talking to the second Toad for the first time.

**Video**
https://www.youtube.com/watch?v=tPYxHKaVK9s

**SD Card Information**
Adapter used: SD2SP2
Brand: Sandisk
Format: microSD
Type: Class 10 + UHS-I
Size: 128GB

**Game File Information**
Original ISO's CRC32: 0B0C339D
Compression format: NKIT ISO

**Swiss version**
v0.4 r714

**Swiss commit**
ec87a4e

**Comment by Extrems** [comment]
There's a race condition in the game that's proving difficult to debug.

**Comment by JamesComo44** [comment]
I also encountered this bug. Audio and BGM seems to work fine if played without Alternate Read Patches. However doing so causes serious lag and stuttering in certain areas, like the 1F Main Hallway and some cutscenes.

**Comment by Extrems** [comment]
"Fixed" in 28042e8 (r734).

**Comment by Extrems** [comment]
Fixed in 87554d3 (r749).
