### ISSUE TITLE
Does not work with Datel Action Replay (EUR disc)

### ISSUE THREAD

**Issue by buggii** [emukidid/swiss-gc#274]
If loaded (r714 but also r688)  directly from Datel AR it loads to a black screen (or better "blue screen" = no signal) and hangs.

Works fine if loaded from Swiss r431.

**Comment by Extrems** [comment]
Reformat your SD card.

**Comment by DBrusson** [comment]
Hi,
Exact same issue here, with 2 different SD cards, both formatted several time in FAT with 32kb Alloc unit size
