### ISSUE TITLE
Remove Nkit Nag

### ISSUE THREAD

**Issue by AlexS2412** [emukidid/swiss-gc#276]
i have never been able to get this software to work, even after running the prequisites to attempt to get it to run, and my images shrunk with gcm tool have always been fine. the specific isos that have bugs like warioware i do not shrink, and for people like me who have been properly using the shrinking tools that have been around since the beginning of the scene and are now expected to use tools that are so unstable i cant even get them to run is an insult. swiss was built originally for freedom on the gamecube and to see what is essentially an ad for Nkit is shameful and should be removed.

**Comment by Extrems** [comment]
No.

**Comment by Extrems** [comment]
If you want it to be removed, devise an algorithm to detect broken images.

**Comment by AlexS2412** [comment]
> If you want it to be removed, devise an algorithm to detect broken images.

use a hash check with redump.dat or any type of hash checker. it should be very easy as both unshrunk and shrunk hashes are publicly available right now even on multiple databases.

**Comment by Extrems** [comment]
Where is this database of verified correct shrunk disc images? I only know that it exists for NKit.

**Comment by Extrems** [comment]
Also, the hashing process would add approximately 14 minutes to each game load.

**Comment by AlexS2412** [comment]
> Also, the hashing process would add approximately 14 minutes to each game load.

it sounds like you just want to make everyone suffer with pointless nag because you want them to use nkit dumps, ironically when i finally did get it to work it claimed nkit shrunk my iso improperly. this really be a one time message if an improperly shrunk one is detected. hell you could even add a config option so the nag can be turned off if the user knows that their dumps are working and nkit was not used,instead of adding delay to the boot process for each game by adding this useless nag as people can still boot the improperly shrunk or corrupted games anyway. punishing users who know what they are doing because its easier to debug is saddening really. if someone reports an issue and they arent using nkit isos then you could tell them to switch. but this approach is bad.

**Comment by AlexS2412** [comment]
wanted to note as well that @emukidid himself said to use gcutil as the recommended shrinker here :
https://www.gc-forever.com/forums/viewtopic.php?t=4093

which is why i used it in the first place.

**Comment by Extrems** [comment]
If you saw "Invalid or Corrupt File!", that's an unrelated bug related to SD card mounting. If you saw "Disc shrunk using an unsupported tool." with an NKit disc image, that's impossible unless the file corrupted somewhere along the way.

The change was made with @emukidid's approval, and you quoted a post from before NKit existed.

All I'm asking of you is an algorithm to detect broken disc images, which should add no time to the boot process.

**Comment by emukidid** [comment]
@AlexS2412 sadly hash detection would take too long, we could potentially come up with a hash database for every FST in every game but this too would take time to create and then again to implement and check. In this day and age of cheap SD storage, I'd also have to recommend to use either use full images or become familiar with NKit, it's just easier to avoid the risk of badly shrunk images. Also, GCMUtil is "OK" for most things as I said in that forum post, but that's just the thing, I'm not aware of what it's not doing correctly so it's best to avoid it now.
