### ISSUE TITLE
Phantasy Star Online Episode I & II Plus freezes upon loading

### ISSUE THREAD

**Issue by witcheslive** [emukidid/swiss-gc#279]
When trying to load PSO Plus from a memory card SD adapter, it freezes on the NOW LOADING screen and does not load, preventing me from even getting to issue #225 which I would also love to see fixed as I have invested quite a bit in getting this game to play online, but cannot play a patched version because of these issues. I am getting an sd2sp2 but it is not here yet, so I am not sure if the issue persists.

If there's anything I can help with testing, please let me know, I do not have a modded gamecube, only softmods, but my day job is programmer so I know my way around debugging output ;)

**Comment by Extrems** [comment]
I don't know, all issues have been fixed and the game is fully working.

**Comment by witcheslive** [comment]
It doesn't work online (see #225 ) and I am not the only one who cannot get Plus in particular to load

**Comment by Extrems** [comment]
Are you not using r743?

**Comment by witcheslive** [comment]
It appears I am using an earlier revision, I will update and report back

**Comment by witcheslive** [comment]
Wow it works and with online too! Sorry for not checking if there's a new version first, and thanks for all the hard work :)
