### ISSUE TITLE
v0.4 r748 Pokemon XD Gale of Darkness Freeze after the first FMV

### ISSUE THREAD

**Issue by Jacky412** [emukidid/swiss-gc#281]
Hi, I just downloaded r748 today and tried loading Pokemon XD Gale of Darkness via SD Gecko. However the game freeze immediately after the very first FMV when a new game is started.

Please kindly look into it. I appreciate your time and effort.

**Comment by Extrems** [comment]
Fixed in 87554d3 (r749).
