### ISSUE TITLE
r748 displays Exception (DSI) occurred error when launched

### ISSUE THREAD

**Issue by senseico** [emukidid/swiss-gc#284]
Launching r748 using an Action Replay disc and memory card SD reader results in "Exception (DSI) occurred!" error. Screenshot with stack dump attached.

r447 launches fine with no errors. I have tried r747 and r743 and have the same issue.
![IMG_2544](https://user-images.githubusercontent.com/6375422/71674627-b4f46700-2d49-11ea-9138-5c043772c9ee.jpeg)

**Comment by senseico** [comment]
I just connected an SD2SP2, and after doing so, Swiss boots up version r748 with no issues. Seems that without the SD2SP2 connected, it displays the error mentioned.

**Comment by Extrems** [comment]
Fixed in 3b2a059 (r754). However, the underlying issue is #267.
