### ISSUE TITLE
v0.4 r756 Not Loading Resident Evil 0 Disc 1 on GC Loader (maybe others only tested GC Loader)

### ISSUE THREAD

**Issue by LVNeptune** [emukidid/swiss-gc#285]
Using Swiss with GC Loader Disc 1 hangs at the initial screen warning of gore. Disc 2 loads fine though. If the game is autobooted by renaming it to boot.iso it loads perfectly fine. Seems like there may be a patch or something Swiss is doing that's breaking it from loading correctly.

**Comment by Extrems** [comment]
Check the fragmentation status of that file using Defraggler. If it has more than 1 fragment, that's a known firmware bug.

**Comment by LVNeptune** [comment]
> Check the fragmentation status of that file using Defraggler. If it has more than 1 fragment, that's a known firmware bug.

Known firmware bug in GC Loader or something else? Like I said direct boot in GC Loader works fine. Will check regardless. Wouldn’t think it’s fragmented being a brand new card and it was the first thing written to it.

**Comment by LVNeptune** [comment]
Defragmenting that one file seemed to resolve it, in Swiss. As I stated, it worked fine when direct booting from GC Loader though leading me to believe it's a software problem within Swiss.

**Comment by Extrems** [comment]
Sorry, it is a firmware bug in the GC Loader, confirmed by its creator.

**Comment by Extrems** [comment]
Fixed in [firmware 1.0.0](https://github.com/danielkraak/GC-Loader/releases/tag/1.0.0), please update.
