### ISSUE TITLE
action replay + sd gecko problem ?!

### ISSUE THREAD

**Issue by pourq** [emukidid/swiss-gc#286]
Hello,
I boot on my ACTION REPLAY CD and it does not see my SD card (2go) which is in my SD GECKO ?!
I renamed "swiss_r756-compressed.dol" to "autoexec.dol" then copied to the root and also copied to the root SDLOADER.BIN
Did I do something wrong or forget something? I'm lost...
thank you

**Comment by ScottSchods** [comment]
I have been having the same issue for 2 weeks, thinking it was hardware-related, but after swapping out every piece of hardware involved in the process I have found no solution. Hopefully a fix can be found, because at the moment I am confused.

**Comment by Extrems** [comment]
Make sure your SD card is formatted as FAT(16).
