### ISSUE TITLE
No reloading dol option request (SD Gecko)

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#287]
I would like to request an option to disable the reloading dol option.

As in, direct boot into the game instead of patching the dol to the SD card ever time. Like the older versions of swiss.

Thanks.

**Comment by Extrems** [comment]
I'd like to limit it to games that have their default DOL call OSResetSystem(OS_RESET_RESTART, ...), but no. No option.

**Comment by 60fpshacksrock** [comment]
Okay. Thanks.
