### ISSUE TITLE
Viper Extreme flashable firmware file?

### ISSUE THREAD

**Issue by mrgw454** [emukidid/swiss-gc#288]
Can you please tell me if there is a Viper (Extreme) flashable firmware file as part of the release package?  I see one called 'swiss_r756-lz-viper.dol', however, the size of this file seems too large and it doesn't appear to have the same header information as the Cobra or GCOS flashable firmware files.  

I would like to use Swiss as a replacement for the GCOS 1.5 firmware I'm using now.  

Thanks for any help/information you can provide.

**Comment by Extrems** [comment]
Use https://github.com/redolution/iplboot.

**Comment by mrgw454** [comment]
I really appreciate the quick response.  Thank you!
