### ISSUE TITLE
Phantasy Star Online Plus v2 GCLoader and Swiss r756 freeze offline new game

### ISSUE THREAD

**Issue by kimbapslice** [emukidid/swiss-gc#289]
Phantasy Star Oline 1 and 2 Plus (v2) freezes when starting a new game using GC Loader (firmware 1.0.0 beta and 1.0.0 official) and Swiss 576 when pressing B to start normally when asked to select dol. After starting normally, I would start an offline game and select a new character. The game would freeze as it tries to play the FMV. Gamecube memory card in Slot A, SD to gamecube adapter in Slot B.

I am not sure if the auto 8 patches are causing issues with GC Loader. If I do the same procedure but only have a gamecube memory card in slot A, patches cannot apply because there's no slot B, starting an offline game with a new character works fine.

Loading a saved game instead of a new character works. Using Swiss to run the game and create a new character if ISO is from SD Slot B works (instead of running ISO from GC Loader).

**Comment by Extrems** [comment]
This is an issue with the old read patches. DVD/GCLoader haven't been moved to the new read patches yet. This should be happening soon.

**Comment by kimbapslice** [comment]
Thank you for the update Extrems! Also, is there/(will there be) an option to disable all patching (when used with GCLoader) or is this not necessary? My apologies as I am not extremely familiar with the read patches. I assume they are for SD adapters and sd2spi. And I love your work on Swiss - so many features and functionality! Thank you again.

**Comment by Extrems** [comment]
They are necessary for any of our other patches to stay resident (all video options, in-game reset, cheats, etc).

**Comment by Extrems** [comment]
I'm not sure what's going on anymore, and it's not looking easy to debug.

**Comment by Extrems** [comment]
Fixed in f5a42b2 (r788).
