### ISSUE TITLE
r756 Skies of Arcadia forced 480p not loading

### ISSUE THREAD

**Issue by LVNeptune** [emukidid/swiss-gc#290]
At some point between r544 and now Skies of Arcadia NTSC stopped loading in forced 480p. According to the compatibility list it was working at one point https://www.gc-forever.com/wiki/index.php?title=Swiss/Forced_Progressive_Compatibility_List currently using Carby Component cables but doubt that makes a difference here. Forcing it to 576p does get it to load but I believe the frequency is slightly different.

**Comment by Extrems** [comment]
Still working here.
