### ISSUE TITLE
Default Game Settings broken

### ISSUE THREAD

**Issue by mario-64** [emukidid/swiss-gc#291]
I'm using build 756 on a NTSC GameCube with GCdual and GC Loader. Swiss settings are saved to the SD2SP2 card. Per-game settings save and work correctly. Default game settings do not

I started by deleting swiss.ini to ensure a clean slate. I then set Swiss default game settings to force 480p. When I launch a non-progressive game such as Blood Omen 2 Swiss flashes "video mode 480i" and the game does not open in 480p. Clearly the default game settings are being ignored. 

Please fix this. Manually setting hundreds of games to force 480p isn't practical. This is exactly what default game settings should provide. Thank you

**Comment by emukidid** [comment]
bcc18acdc7de6e6a553325ce6ac4c067bb2a26e2 fixes this for games that don't have a config entry. "Default game settings" will apply to a game until a single setting in a game is changed & saved. I'll change it in the future so that individual settings can save per game.

**Comment by mario-64** [comment]
@emukidid Thank you! Can't wait to try it out :)

**Comment by mario-64** [comment]
Works great @emukidid . Thanks again!
