### ISSUE TITLE
Is there going to be SD support for SP1? Where is Code for SD2SP?

### ISSUE THREAD

**Issue by AddioElectronics** [emukidid/swiss-gc#294]
So is there going to be support for serial port 1?

And where is the code which handles SD2SP for serial port 2?
I looked pretty hard but couldn't see anything related to SP2, I want to give it a go.

**Comment by Extrems** [comment]
No reason to support something that doesn't exist and would have added complexity over every other ports.

**Comment by AddioElectronics** [comment]
What do you mean it doesn't exist? Or do you mean its not spi?

**Comment by Extrems** [comment]
There's no existing SD Card Adapter for Serial Port 1, and supporting it would be a big headache.

Here's a hint why.

Memory Slot A: EXI channel 0, device 0.
Memory Slot B: EXI channel 1, device 0.
Serial Port 2: EXI channel 2, device 0.

Serial Port 1: EXI channel **0**, device **2**.

**Comment by Extrems** [comment]
Some SD cards are also known to ignore device select and will barf in this setup.

**Comment by AddioElectronics** [comment]
Oh, my plan was to make a an adapter for SP1, would take me 5 minutes.
Why would having it on same channel as memory card 1 be a head ache?  Especially it having a different device id should make it easy, I admit I don't know the architecture at all, but it sounds to me like a lot of the code could be copy pasted. 
If I could find the actual code that handles it I might be able to do it. I've worked with FATFS before, I'm currently using it for a project/product at the moment.

**Comment by Extrems** [comment]
All code assume there would only ever be one SD card per channel and they would be the first device.

You need to start here: https://github.com/emukidid/libogc/blob/master/libogc/sdgecko_io.c

**Comment by AddioElectronics** [comment]
I just noticed this, if(EXI_SelectSD(drv_no,EXI_DEVICE_0,_ioCardFreq)==0).
Almost seems like its all setup to use any channel/device, but would just need a way of selecting it in the UI.
I've never even used the UI so I'm not sure how things are setup, maybe I should start there haha
