### ISSUE TITLE
once i run a game swiss turns green for a split second then is just black

### ISSUE THREAD

**Issue by vegaking72** [emukidid/swiss-gc#295]
Plz help devs

**Comment by Extrems** [comment]
Are you using Memory Slot A or Memory Slot B?

**Comment by vegaking72** [comment]
It's in slot b

**Comment by Extrems** [comment]
Do you have any other information to go on? Brand of SD card? Brand of SD card adapter? Does your disc images match Redump? Are you using any non-default settings? Which Swiss revision?

**Comment by Extrems** [comment]
Can you give me the output of this DOL?
[template.zip](https://github.com/emukidid/swiss-gc/files/4113177/template.zip)

**Comment by vegaking72** [comment]
I'm currently not at my house right now but once I will tell you what is this template

**Comment by vegaking72** [comment]
its says Hello world

**Comment by Extrems** [comment]
I need to know the stuff below that.

**Comment by vegaking72** [comment]
oh ok in a sec

**Comment by vegaking72** [comment]
it says 
_io_gcsda 0 _ioWPFlag 0
_io_gcsdb 1 _ioWPFlag 0
_io_gcsd2 0 _ioWPFlag 1

**Comment by Extrems** [comment]
Well, that's boring. I can't help with your issue.

**Comment by vegaking72** [comment]
so can someone else can
