### ISSUE TITLE
Swiss config failed to save

### ISSUE THREAD

**Issue by germanojrr** [emukidid/swiss-gc#297]
I can't change and save any configuration on Swiss. Everytime i change a configuration and go to save option, appears this message "Config failed to save".

I don't know what to do. Someone can help me???

**Comment by Extrems** [comment]
Set a valid configuration device.

**Comment by germanojrr** [comment]
> Set a valid configuration device.

How do i do that?

**Comment by emukidid** [comment]
In the first page of the settings screen
