### ISSUE TITLE
r714-r766: Official SD Card Reader DOL-019 Not detected after booting Swiss

### ISSUE THREAD

**Issue by stompkatz** [emukidid/swiss-gc#300]
Swiss won't recognize anything inside a DOL-019 SD Reader starting in r714 and newer versions. I'm booting Swiss with IPLBoot or Action Replay with a 2GB SD Card inside the DOL-019 and it works but then, once it loaded, it doesn't recognize the device. The device is working OK with older versions. I guess there are hardware differences between SD Gecko and DOL-019 because a clone SD Gecko works without problems in any versions

**Comment by Extrems** [comment]
1. Press Z to show all devices.
2. Navigate to device.
3. Press X for EXI options.
4. Set speed to compatible.
5. Select device.

**Comment by stompkatz** [comment]
Yeah! That worked.

**Comment by Extrems** [comment]
Fixed in ba6dba8 (r773).
