### ISSUE TITLE
766 - Option to hide known file types results in incorrect GBI launching

### ISSUE THREAD

**Issue by amerika13** [emukidid/swiss-gc#301]
Last night I updated to Swiss 766 and I noticed the feature to hide known file types within the options.  I enabled it. I then launched GBI.dol and noticed that I did not get the configuration screen as I normally would when launching GBI.dol.  GBI was launched with, I presume, only default options. When i turned the hide file types feature off, GBI would launch with the configuration screen as expected again.

**Comment by missionfloyd** [comment]
It seems this keeps DCP and CLI files from being detected.

**Comment by emukidid** [comment]
Fixed in 452282fb93a0829f2f7f6e615b40918bc2c020ad (r774)
