### ISSUE TITLE
Starfox Adventures no voices and no effects. 

### ISSUE THREAD

**Issue by HiNu7** [emukidid/swiss-gc#304]
Using Xen8GC and the SD2SP2 with an .Iso format.  Using Swiss 775.

**Comment by vxbinaca** [comment]
My copy ran fine, are you sure you're using a REDUMP verified image?

**Comment by emukidid** [comment]
Alternate Read Patches from SD won't be able to play audio until this is fixed, if you're running the ISO from disc then it'll be fine.

**Comment by Extrems** [comment]
Fixed in e3c4023 (r848), but DMA audio is currently missing instead, while streaming audio is playing.
