### ISSUE TITLE
Choppy playback of video for Intellivision Lives!

### ISSUE THREAD

**Issue by kynrek** [emukidid/swiss-gc#308]
When watching the history of intellivision video on the intellivision lives game the video and audio seem choppy and slightly distorted after watching it for a few minutes. I am loading from an SD card using sd2sp and forcing 480p video mode. Running the latest stable build v0.4r775-1

**Comment by Extrems** [comment]
The clipping is part of the video. The occasional slowdowns are likely a wontfix.

**Comment by kynrek** [comment]
No worries. I figured it would be a low priority issue figured I would post it just in case it was caused by another more interesting reason :). Keep up the great work!
