### ISSUE TITLE
Cannot reinitialize SD card after in-game reset with certain brands

### ISSUE THREAD

**Issue by kynrek** [emukidid/swiss-gc#309]
Can not access sd2sp after In game reset. I put a copy of swiss.dol as Igr.dol both using the igr.dol and reset options both cause the sd2sp to be removed from the available drives list.

**Comment by kynrek** [comment]
This was with version v0.4r775

**Comment by Extrems** [comment]
This was fixed in r775-1 and I cannot reproduce this issue.

**Comment by kynrek** [comment]
This is the file I used to boot r775-1 742da9b22130bb41812c8683ac82fbe3  ./swiss_r775/DOL/swiss_r775-compressed.dol. I will try emukid's pre release version

**Comment by kynrek** [comment]
I thrived the prerelease that emu kid published and got the same results. I noticed that the sd2sp stops working even if I relaunch Swiss from the file browser rather than through an I game reset the only thing that fixes it is a power off and back on.

**Comment by Extrems** [comment]
Which SD card brand and model?

**Comment by kynrek** [comment]
In the sd2sp2 I am using a transcend 64GB premium400x. In the SD card adapter I am using a transcend 2gb.

**Comment by kynrek** [comment]
I switched to a samsung evo 256gb in the sd2sp2 and it resolved the issue! Thanks for the support!

**Comment by Extrems** [comment]
No, that doesn't solve anything.

**Comment by kynrek** [comment]
Oh, sorry I assumed a brand incompatibility issue would be a wont’t fix.  Let me know if there is anything else I can test to help.

**Comment by Extrems** [comment]
Fixed in emukidid/libogc@7fe9cb8.
