### ISSUE TITLE
Ftp Server connection refused

### ISSUE THREAD

**Issue by Sirethief2525** [emukidid/swiss-gc#316]
I can't seem to get the ftp server on swiss to connect to anything. I have an IP address from my router that I can see in the swiss settings; and the only two things I'm running on my network are the Gamecube and the computer that I'm using to connect to the Gamecube, but for some reason the connection is getting refused by the server which I assume is the gamecube. I'm pretty sure I've tried everything I can think of and my dad who has a network engineering degree seems to pretty stumped on this as well so maybe there is a setting that I'm missing somewhere that isn't allowing the connection? I've also tried Filezilla, Adminhands(Android), and FlashFXP if that's any help. Thanks in advance and I appreciate all the work you put into making swiss as great and compatible as it has gotten in the past 5 1/2 years I've been using it.

**Comment by Extrems** [comment]
It's a client, not a server.

**Comment by Sirethief2525** [comment]
Well.. That probably explains why nothing I've tried is working hahaha so it's a little different than the ftp software on the switch and wii u then?
