### ISSUE TITLE
Baten Kaitos music problems

### ISSUE THREAD

**Issue by Sandstral** [emukidid/swiss-gc#317]
So I was testing some games and I notice that the first Baten Kaitos (not Origins) has some problems with the music in the last version. I'm using a SD card reader on port A with a Sandisk A1 card.
The problem is that the music either stops suddenly, or goes to almost the end of the song, or even plays a different song, even overlapping. You can see all this in the main menu and in the first screen after starting a new game.
If I enable the Audio Streaming patch, the audio seems to work almost OK (there's some stuttering here and there) but the FMVs lag like hell. This doesn't happen with Audio Streaming disabled.
Then I checked old versions and I discovered the game worked perfectly (minor stuttering in FMVs but that's normal due to the port speed) in version 656 with the Alternate Read enabled (it's enabled by default), and in the next version, 682, is broken in the same way as in the last one.
I also notice that also in version 656 when I launch the game there's no patching or anything but there is in 682.
I tried with both the Redump NTSC iso and the undubbed one, same results.
I don't know if I messed up somewhere along the way or this is indeed a bug.

**Comment by Extrems** [comment]
Fixed in 6ea074d (r806).
