### ISSUE TITLE
GoldenEye RogueAgent , Latest swiss, Will not work at all

### ISSUE THREAD

**Issue by narlaawolfy** [emukidid/swiss-gc#318]
Swiss v0.4 Rev 798 (and all other v.0.4 revs)

GoldenEye Rogue Agent, Both NTSC and Eur ( default images not shrunk in anyway)

After booting the game proceeds to ask for correct display mode, then black screen with : ''An error has occurred. Turn  the power off and refer to the Nintendo Gamecube Instruction Booklet for further instructions''

According to compatibility guides on the internet this game was last working on Swiss 0.3-r174 . 

Any chance of a fix ?

**Comment by Extrems** [comment]
Same issue as Medal of Honor: European Assault.

**Comment by Extrems** [comment]
Fixed in b4ca6c2 (r805).
