### ISSUE TITLE
Unable to copy .iso file from Slot B to SP2

### ISSUE THREAD

**Issue by CharlieBeatnik** [emukidid/swiss-gc#321]
I am unable to copy an .iso file, or perhaps any large file, between SD cards in Slot B to SP2 and vice versa. Copying does start a megabyte or so is transferred, however it then stops with the message:

> Failed to Read! (262144 -1)

I have tried a variety of SD cards and also with the SD/IDE speed at 32 and 16Mhz. I'm using Swiss 798 (6b40ae9).

**Comment by Colourclash** [comment]
I also get this when trying to copy from SDA to my SP2 card. SP2 card is working fine for .iso files when I copy them directly to the SD card. Tried a couple of different cards. One formatted with FAT and another with exFat. Both get the same error after copying has progressed for some time: "Failed to Read! (262144 -1)". I am on Swiss r845. Commit a14827b.

![IMG_2194](https://user-images.githubusercontent.com/883891/86452417-2e2e4000-bd14-11ea-9113-d9dfd83e6904.jpeg)
