### ISSUE TITLE
Mario Party 6 Crash (Swiss r785)

### ISSUE THREAD

**Issue by lvlhead** [emukidid/swiss-gc#322]
The following message is displayed during gameplay accompanied by a hard crash.

```
OSPanic encounterd:

dvdfs.c:756
DVDReadAsync(): specified area is out of the file
```

**Comment by emukidid** [comment]
what device are you playing this from?

**Comment by lvlhead** [comment]
> what device are you playing this from?

Hardware: DOL-001
IPL: 1.1
Boot chain: Action Replay -> SDGecko -> Swiss -> Load ISO/DOL from SD2SP2

Please let me know if you'd like more information or if there's a standard of information you'd like.

**Comment by Extrems** [comment]
Cannot reproduce. Please verify you have a valid dump.

**Comment by lvlhead** [comment]
@Extrems This is confirmed to be a bad dump, please disregard and close the ticket.  Thanks for all your hard work!
