### ISSUE TITLE
In-game reset DOL not working

### ISSUE THREAD

**Issue by mario-64** [emukidid/swiss-gc#324]
I am using Swiss 0.5 (806) with GCloader on a Gamecube with GCdual 3.0d. 

I have In-game reset configured to use igr.dol which is the Swiss DOL file. When you press the button combo to reset it just resets the game same as Reboot does. It doesn't launch the Swiss dol as it should. I've tested the compressed and regular dol but neither works. This is quite annoying as the whole point is to be able to reset back to the Swiss menu without hard booting the Gamecube.

**Comment by Extrems** [comment]
igr.dol has to be on the patch device (SD Card Adapter in Serial Port 2, Memory Slot B, or Memory Slot A).

**Comment by mario-64** [comment]
> igr.dol has to be on the patch device (SD Card Adapter in Serial Port 2, Memory Slot B, or Memory Slot A).

Oh ok. I didn't realize that. Let me move it to my SD2SP2 then retest. I'll report back soon. Thanks Extrems
