### ISSUE TITLE
Crash while scrolling list using joystick

### ISSUE THREAD

**Issue by cristofercruz** [emukidid/swiss-gc#329]
I've run into a crash a couple times while browsing a list and recently found a way to consistently replicate the crash using the joystick to scroll. If you push the joystick slightly just enough to see the loading window but not enough to skip to the next item and leave it held like this for a few seconds Swiss will crash to an exception screen. I've linked a video demonstrating the crash.

[![video](https://user-images.githubusercontent.com/9136454/77912748-f2cd3280-7247-11ea-9f2c-eb16554bb4f4.png)](https://www.youtube.com/watch?v=NtKyvvSUSP0)

**Comment by emukidid** [comment]
Fixed in 6f53d767
