### ISSUE TITLE
Action Replay SDLOADER.BIN help

### ISSUE THREAD

**Issue by i0brendan0** [emukidid/swiss-gc#330]
I can't get the action replay to automatically go to swiss. I had the SDLOADER.BIN and the swiss_r813.dol file as is on the SD card. Then I renamed it to swiss.dol and neither auto loaded swiss. I'm using a recent version of the action replay software (I bought it like a couple months ago) and the original SD reader from it (it reads MAX and has this translucent thing in one of the corners that I haven't figured out its purpose.)

**Comment by Extrems** [comment]
SDLOADER.BIN is for use as replacement for http://www.gc-linux.org/wiki/SDload
You're looking for autoexec.dol

**Comment by i0brendan0** [comment]
There is no autoexec.dol. Or do you mean rename Swiss.dol to autoexec.dol?

**Comment by Extrems** [comment]
Yes, or whatever you want.

**Comment by i0brendan0** [comment]
Ok. It might be worth mentioning that somewhere so others can find out easily. I imagine others like me don't know that something like this can be done with the Action Replay.
