### ISSUE TITLE
Memory Card Slot A not working on Wii

### ISSUE THREAD

**Issue by Cannonball2001** [emukidid/swiss-gc#333]
In the games that I tried (all games were loaded via the original disc), they say there's no memory card in slot A when there actually was (and these were games that don't support slot B). And this seems to be an issue on Wii because I didn't encounter this problem on Gamecube.

**Comment by Extrems** [comment]
Fixed in 7d612e8 (r826).

**Comment by Cannonball2001** [comment]
So what do I do? Do I replace something with those codes?
