### ISSUE TITLE
Issue with all .5 versions with SD2SP2

### ISSUE THREAD

**Issue by godashram** [emukidid/swiss-gc#334]
So, I have my US gamecube using an action replay to boot swiss.
was on v0.4r795 and v0.4r798 with no issues with my SD2SP2. Used cleanrip to backup a ton of games over the last week. Tried updating to v0.5r827 and on boot it'll see my sd2sp2 on the Device Selection, but when attempting to load it jumps back to the device selection screen and no longer sees the sd2sp2.

Tried all 3 v0.5 versions with the same issue. Jumped back to v0.4r798 and the sd2sp2 is detected fine. Not sure if I missed something or not.

**Comment by Extrems** [comment]
There were no relevant changes in v0.5r806, so I have no idea.

**Comment by Filyx20** [comment]
i also am having this issue, however one thing i have noticed is that when on a 5. version, and by having the config file on slot b, only then will the sd2sp2 be detected.
https://youtu.be/iN1A7Zm4Lww

**Comment by emukidid** [comment]
Can't reproduce, try with latest.
