### ISSUE TITLE
Error compiling v0.5r827 on MSYS2/MinGW-w64 - undefined reference to `sdgecko_getSpeed'

### ISSUE THREAD

**Issue by Baers** [emukidid/swiss-gc#336]
OS: Windows 10 x64 Version 1909
Build environment: MSYS2/MinGW-w64 (from https://www.msys2.org/)
devkitPro: devkitPPC r36-1, libogc 1.8.24-1 

First of all, thank you for providing such a great tool.

I tried compiling the latest version from source using both `make dev` and `make all`, but compilation fails at the linker stage with the following error (repeated for multiple source files):

```
c:/msys64/opt/devkitpro/devkitppc/bin/../lib/gcc/powerpc-eabi/8.4.0/../../../../powerpc-eabi/bin/ld.exe: deviceHandler-DVD.o: in function `deviceHandler_DVD_setupFile':
C:/msys64/home/Baers/swiss/cube/swiss/source/devices/dvd/deviceHandler-DVD.c:474: undefined reference to `sdgecko_getSpeed'
```

Full console output: [console.log](https://github.com/emukidid/swiss-gc/files/4586027/console.log)

I also tried searching the latest libogc source, the devkitPro forums, Google, and GitHub, but I didn't find any references to sdgecko_getSpeed. I think that it is a local change to libogc on the developer side, but please let me know if there are any additional dependencies that I may have missed. For what it's worth, devkitPro was freshly installed.

Thanks for your consideration.

**Comment by Extrems** [comment]
https://github.com/emukidid/libogc

**Comment by Baers** [comment]
Doh!

Thanks for the link.
