### ISSUE TITLE
Incorrect Free Space showing in swiss_r827

### ISSUE THREAD

**Issue by SlowCatalyst** [emukidid/swiss-gc#338]
I am running swiss_r827 with the SD2SP2, and Swiss reports the incorrect amount of free space remaining on the SD, but just reports the same exact amount of GB as the total amount of the SD's capacity.

However, when I switch to carousel, the Free Space value is then correct.

**Comment by Diegorella** [comment]
this detail is only aesthetic ... or can it cause a bug ...?

**Comment by cristofercruz** [comment]
Oops.

@Diegorella It's just a display issue. I submitted a PR to fix it.
