### ISSUE TITLE
unable to connect via ftp

### ISSUE THREAD

**Issue by alberto-bortolato** [emukidid/swiss-gc#339]
when i try to select "File Transfer Protocol" from the "Device Selection" i'm redirect to the sd card

[video](https://drive.google.com/open?id=1cN-Bme9SpD57pMRfc_bkH0Qi7Gcx8fcO)

**Comment by Extrems** [comment]
You're asking about the File Transfer Protocol, but the video show the File Service Protocol.

Those are two totally different things.

**Comment by alberto-bortolato** [comment]
> 
> 
> You're asking about the File Transfer Protocol, but the video show the File Service Protocol.
> 
> Those are two totally different things.

sorry, this is the new video [video](https://drive.google.com/open?id=1cP727XEbnuUQ81ww50sCGfIrzwg6-DMS)

**Comment by alberto-bortolato** [comment]
so?

**Comment by Extrems** [comment]
I have no idea. There should be a pause and some kind of error message.
