### ISSUE TITLE
Remember cheats when launching a title

### ISSUE THREAD

**Issue by SBRK** [emukidid/swiss-gc#345]
Would it be possible to keep the enabled cheats for a game, so that you don't have to enable it everytime when launching the game? This would be mostly useful for Widescreen codes, since most of the time, enabling widescreen from the Swiss options results in culling problems, while the widescreen via cheat code works great.

**Comment by capz** [comment]
oh man that would be an awesome feature. enable all cheats automatically doesnt quite work for me so i always manually enable what i need, storing these selections would be awesome

**Comment by deneraraujo** [comment]
This would be very useful!

**Comment by eleriaqueen** [comment]
Oh wow yeah this would be a really good feature !

**Comment by emukidid** [comment]
The ability for Swiss to remember the last used cheats has been added in fe5301ddb902dacf67202090cb569475a78e2e06. If your cheat file changes, Swiss will disregard previous selections. If any issues are found please create a new issue on the tracker, thanks!

**Comment by SBRK** [comment]
tHANKS <3
