### ISSUE TITLE
Swiss+GCLoader 007 Nightfire Doesn't Boot With SD Gecko Inserted

### ISSUE THREAD

**Issue by GoobyCorp** [emukidid/swiss-gc#346]
I have to remove my SD Gecko to get 007 Nightfire to boot, it appears the reason for this is because it doesn't have anywhere to save the patches so they don't load. A way to disable game patching would be nice to have, disable video patches does pretty much nothing.

**Comment by Extrems** [comment]
An option to disable game patching is basically an option to disable all of Swiss.

Disable video patches does have its purpose as there are known issues that can't be immediately addressed.

**Comment by GoobyCorp** [comment]
but if removing an SD card is a fix for it then why isn't it easily fixable in code?

**Comment by Extrems** [comment]
When you do that, only the main DOL is patched. This game has multiple executables and so patches are lost when a new executable is loaded, or the main DOL itself is reloaded.

**Comment by GoobyCorp** [comment]
Well when I boot it using only the GCLoader without Swiss at all it works fine, so is there a way to completely disable patching? This game appears to work without any.

**Comment by Extrems** [comment]
Any game will work without any. But then you don't have any Swiss features whatsoever.

**Comment by GoobyCorp** [comment]
Would it be possible to add a way to select which patches get applied or maybe an experimental feature to remove them altogether?

**Comment by Extrems** [comment]
You already get to select what get applied.

**Comment by GoobyCorp** [comment]
I've disabled all the patches I could find on Swiss and the game refuses to boot without removing the SD card or setting it as the boot ISO on the GCLoader.

**Comment by Extrems** [comment]
Does that SD card work in that adapter for loading games?

**Comment by GoobyCorp** [comment]
For some games it works fine, but it's super slow as is anything over the EXI bus.

**Comment by Extrems** [comment]
If it's only some games then there's a problem.

**Comment by GoobyCorp** [comment]
Every game I've tested works.

**Comment by Extrems** [comment]
Trying it here and... it works for me. I don't know what to say.

**Comment by GoobyCorp** [comment]
Sorry just tested it on the SD Gecko, it works fine but it runs slow and it would be nice to one day only need the GCLoader.

**Comment by Extrems** [comment]
I've tested it from both the GCLoader and the File Service Protocol.

**Comment by GoobyCorp** [comment]
So this is what I've come up with:

GCLoader -> Works
Swiss -> SD Gecko -> Works
Swiss -> GCLoader -> Doesn't work

**Comment by Extrems** [comment]
I'm not sure what you mean by running slow, the attract movie is playing close to perfect.

**Comment by GoobyCorp** [comment]
The game boots on everything but after the game says press start on the main menu the screen goes black then it displays a disc read error.

**Comment by Extrems** [comment]
Well, I got past that.

https://files.extremscorner.org/gamecube/screenshots/nightfire.png

**Comment by GoobyCorp** [comment]
Loading on the GCLoader through Swiss you were able to? Is yours NTSC-U?

**Comment by Extrems** [comment]
Fixed in 6ed93b1 (r837).
