### ISSUE TITLE
Radirgy Generic: fails to boot through IPL

### ISSUE THREAD

**Issue by tjanas** [emukidid/swiss-gc#347]
Swiss: v0.5r836
Device: SD2SP2
GameCube model: DOL-001
IPL Version: NTSC Revision 1.0
Video Mode: NTSC 480i

**Comment by tjanas** [comment]
I also tried this on another DOL-001 GameCube with IPL Version: NTSC Revision 1.1 and it has the same issue.

**Comment by Extrems** [comment]
Something seem to be disrupting a multiple block read command. No issue with single block reads.

**Comment by Extrems** [comment]
Fixed in b7a8f59 (r843).
