### ISSUE TITLE
Gamecube boot sequence gets skipped

### ISSUE THREAD

**Issue by tedmahsun** [emukidid/swiss-gc#349]
Just curious if this is normal behavior?
https://www.youtube.com/watch?v=cRNHyb3PexM

The Gamecube boot sequence immediately gets skipped before Swiss is loaded. It's so fast my OSSC barely has time to sync. If this is normal behavior, I'm wondering if this can be disabled? I'm aware of the "Boot through IPL" option but I'd rather have the boot sequence before Swiss loads.

EDIT: Ohhhhh I see it was a feature added in v0.5r806! Ah nvm then!

**Comment by Damn-Deal-Done** [comment]
When booting Swiss from disc or SD card the boot sequence is fine. It only skips with GameCube loader. Can this be fixed so the whole boot sequence plays before going into GameCube loader?

**Comment by BeardMonster** [comment]
I would also like the option to not be skipped on Swiss boot up. Doesn't feel right. :) Thanks

**Comment by Extrems** [comment]
Partially fixed in 77db14e (r971). You can now hold the A Button to access the GameCube Main Menu.

**Comment by Extrems** [comment]
Fixed in 08cf185 (r976). Use ISO/swiss.iso as boot.iso when you don't wish this behavior.
