### ISSUE TITLE
Regression - memory card corrupt error

### ISSUE THREAD

**Issue by patters-syno** [emukidid/swiss-gc#350]
Just got back into the cube after finally getting a Carby. Playing the .gcm file Super Mario 64 that circulated some years ago (itself a rip of the emulator from the Zelda bonus disc), I notice that it loads my save fine with old faithful Swiss r366 but if I boot it with r836 the game says that the memory card is corrupt on booting the game. Switch back to r366 and it works again. I've tried disabling as much behaviour that would be patched in the dol as I can (IGR, audio streaming, etc.) but I cannot get it working on r836. I have also cleared the swiss-patches folder.

Any idea what would might cause this error? I need to boot this title via Swiss to force 480p now that I'm playing it on a 4K screen and I'd like to switch to an SD2SP2 which will need the newer Swiss build. I also tried converting it to NKit, but that didn't help.

EDIT - I have the same issue with the ripped .gcms of Legend of Zelda Ocarina of Time and OoT Master Quest, except that to get these two working I have to go all the way back to sd-boot 0.4RC3. But that version can't force 480p properly. These games need to be played as rips to be able to force 480p. This is because the disc version loads the game after a separate menu .dol binary, so the 480p patch only affects that menu and not the game.

I'm using a PAL DOL-001 with a Qoob Pro 1.3c (booting Swiss from its flash storage), WiiKey branded SD card adaptor in Slot B, BBA, and Gameboy Player. I have disabled all the Qoob's patches too in case they interfere with Swiss patches.
`MD5 (mario64.gcm) = c72ea396c23fee1d26db26e387aecd47`
`MD5 (Zelda OOT.gcm) = 47cdfe98e540b8ece2eab7c40302af46`
`MD5 (Zelda OOT Master Quest.gcm) = 0dd5a890c772d28d2a083c7cae26e6b5`
I think these files were all hosted at a site called "The Purple Cube" back in 2010 or so. They are 43MB, 44MB, and 44MB respectively.

**Comment by patters-syno** [comment]
I've done some more testing and I see that Swiss r836 is able to correctly 480p patch both the physical disc version and the NKit rip of:
Legend of Zelda, The - Ocarina of Time & Master Quest (Europe) (En,Fr,De).nkit.iso
Older builds (e.g. r366) couldn't do that.

This means that I can continue my ancient save file for OoT on my nice big modern TV.

However, the Super Mario 64 rip remains an issue (corrupted memory card reported) on r836.

**Comment by Extrems** [comment]
Which region does those GCMs show up as?

**Comment by patters-syno** [comment]
The ripped ones show up as Japanese regardless of whether they're the PAL or NTSC versions. I guess because they didn't bother having a proper header or banner since they were encapsulated within another ISO. Could this be the issue?

**Comment by Extrems** [comment]
Yes. Set Force Text Encoding to ANSI and it'll fix your issue.

**Comment by patters-syno** [comment]
It does indeed fix it, thanks for the quick resolution. I had wondered what that setting was for.

So I have a workaround (but one I may forget about if I put this down for a few years). However I'm planning to convert these .gcm files to NKit to avoid the nag screen, so would flipping the region in the header fix it? Or would that break compatibility with existing saves?

**Comment by Extrems** [comment]
Yeah, you could change the BI2 region code.

**Comment by patters-syno** [comment]
How would I edit this BI2 region code? Can't find anything from web searches. Any of the normal GC ISO editing tools show no header/banner.
