### ISSUE TITLE
Trouble burning Swiss ISO to Mini DVD-R

### ISSUE THREAD

**Issue by h2befjon** [emukidid/swiss-gc#351]
I'm new to this and could use some help. I modded my US GC with a Xeno chip. Verified it works, I can play JP/US games. I downloaded the latest swiss used imgburn, settings are 2x write speed on a memorex DVD-R. When I pop it into the GC it say "the disk could not be read". Can someone please point me to where I could find a solution to my problem?

**Comment by Damn-Deal-Done** [comment]
Either the DVD is not very good, G04 dye seems to work the best with GameCube. Or you need to calibrate the disc drive laser to be able to read it. There are videos on YouTube showing how to do this, it is very straight forward.
