### ISSUE TITLE
Feature Request: Custom Console Type

### ISSUE THREAD

**Issue by NWPlayer123** [emukidid/swiss-gc#352]
Some games (e.g. Animal Crossing) disable OSReport after a certain point if it detects a retail console. Dolphin just always sets it to 0x10000006 so the check doesn't pass and it continues to print stuff. Not sure how granular it needs to be, AC just does OSGetConsoleType() & 0x10000000

http://hitmen.c02.at/files/yagcd/yagcd/chap4.html#sec4.2.1.1.2
0x8000002C

```
39:45:058 Core\HW\EXI\EXI_DeviceIPL.cpp:306 N[OSREPORT]: Console Type : Development HW3 (10000006)
39:45:058 Core\HW\EXI\EXI_DeviceIPL.cpp:306 N[OSREPORT]: Memory 24 MB
```

**Comment by Extrems** [comment]
Fixed in 750452e (r846).
