### ISSUE TITLE
swiss boot.iso: Disc shrunk using an unsupported tool

### ISSUE THREAD

**Issue by tjanas** [emukidid/swiss-gc#353]
If I select the boot.iso in Swiss from my GCLoader SD card, it produces the following warning:
`Disc shrunk using an unsupported tool. Please use NKit.`

Perhaps remove this warning for official swiss iso files?

If I continue to boot that (with Boot through IPL enabled in swiss), it re-loads Swiss correctly; a nice feature is that I can run that after performing IGR within game if I want to exit Swiss / return to IPL with the ability to return to Swiss via the `Game Play` option in the GameCube IPL (instead of it showing the last game ISO played).

**Comment by Extrems** [comment]
Fixed in b3c1119 (r893).
