### ISSUE TITLE
Boot with IPL audio when loading from GCLoader SD

### ISSUE THREAD

**Issue by tjanas** [emukidid/swiss-gc#354]
I have noticed that when loading a game from the GCLoader with “Boot with IPL” enabled, the GameCube animation sequence audio may be missing or quickly cuts out immediately. When loading a game from sd2sp2, this issue does not occur. When the game is loaded, audio is fine.

Swiss v0.5r845
GCLoader firmware 1.0.1
NTSC-U IPL 1.1

**Comment by emukidid** [comment]
Can you be more specific, what games? Include region too, is it every time?

**Comment by tjanas** [comment]
Seems to occur with every game I have tested, both NTSC-U and NTSC-J games. I can provide a video clip if no one else is able to replicate this issue.

**Comment by tjanas** [comment]
@emukidid here is a video clip of the issue: https://youtu.be/FYXYOQLGwlU

**Comment by Extrems** [comment]
Which settings are you using? Are you swapping cards to test from SD2SP2 and if so, what models are they?

**Comment by tjanas** [comment]
Not physically swapping cards, just changing the device from the default GCLoader to SD2SP2 via Swiss menu to view and launch disc images from my SD2SP2.

GCLoader SD card (formerly used as my SD2SP2 card):
Samsung 256GB 100MB/s (U3) MicroSDXC EVO Select Memory Card with Full-Size Adapter (MB-ME256GA/AM)

SD2SP2 SD card:
MicroCenter 32GB microSDHC Class 10 Flash Memory Card

**Comment by Extrems** [comment]
It sounds like your generic SD card might be particularly slow with single block reads.

**Comment by tjanas** [comment]
I also tried a different SD card for my GCLoader, same issue:
Kingston Digital SDXC Class 10 UHS-I 45R/10W Flash Memory Card (SD10VG2/128GB)

**Comment by Extrems** [comment]
The SD card in the GC Loader doesn't matter. The one in the SD2SP2 does.

**Comment by tjanas** [comment]
I can try removing my SD2SP2 completely and see if that makes a difference.

**Comment by Extrems** [comment]
Do not do that.

**Comment by tjanas** [comment]
What do you recommend?

**Comment by Extrems** [comment]
As I said, it's the SD card in the SD2SP2 that matter here.

**Comment by tjanas** [comment]
Understood. Should the following card be fast enough?
[SanDisk Extreme 32GB MicroSDHC UHS-3 Card - SDSQXAF-032G-GN6MA](https://amazon.com/dp/B06XWMQ81P)

**Comment by Extrems** [comment]
Buying a new card would be a waste. A solution could be using multiple block reads, as in the normal SD read code, or the GC Loader gaining write support.

**Comment by Extrems** [comment]
I suggest trying your Kingston SD card in a Memory Slot SD Card Adapter. You'll need to remove the SD2SP2 SD card while testing this.

**Comment by Extrems** [comment]
Fixed in 895e987 (r1020), as long as memory card emulation isn't enabled.
