### ISSUE TITLE
ISO which starts boot.dol directly from SD Card but does nothing else

### ISSUE THREAD

**Issue by deOctagon** [emukidid/swiss-gc#355]
I know this was sort of covered previously in #263 but would it be possible to produce a stripped down ISO which only function is to start boot.dol from SD2SP2 or the Slot 2 SD Card? 
Just a plain black screen would do, loading progress bar optional. It could reuse the load_auto_dol() function.

This way there wouldn't be a clash of version numbers being loaded on-screen, burnt discs set to one version number forever and it could also tie up with #332 if it is later implemented.

Many thanks for the great work so far.

**Comment by Extrems** [comment]
This already exists as Game Boy Interface's Memory Card Boot Disc.
