### ISSUE TITLE
Seamlessly booting latest version on SD card from outdated version on DVD.

### ISSUE THREAD

**Issue by Damn-Deal-Done** [emukidid/swiss-gc#356]
Hello.

Currently you can load a newer version of Swiss with an outdated version on DVD by putting Swiss on the SD card and naming it boot.dol

This first loads the old version from the DVD and then loads the newer version on the SD card.

Is there a way to make this seamless? Only boot the newer version on the SD card without first loading the older DVD version.

If not, could there be a separate program that only deals with booting from SD card? This can be burned to DVD and it will seamlessly boot straight into the latest version on an SD card.

I imagine the part of Swiss that deals with booting and accessing the SD card and checking for boot.dol is very rarely updated, so a stripped down program would make more sense as an app that is burned to DVD rather than the full Swiss.

Thanks

**Comment by Extrems** [comment]
This already exists as Game Boy Interface's Memory Card Boot Disc.

**Comment by Damn-Deal-Done** [comment]
Do you know where I can find this? Downloaded GBI and GBI extras. Is it boot.gcm in the extras folder? Cheers

**Comment by Extrems** [comment]
Yes.

**Comment by Damn-Deal-Done** [comment]
Cheers
