### ISSUE TITLE
Harry Potter POA does not boot from r785 onwards

### ISSUE THREAD

**Issue by doublef843** [emukidid/swiss-gc#359]
While testing my new GC Loader i have found that Harry Potter and the Prisoner of Azkaban does not boot from r785 onwards. My setup was initially the GC Loader with Swiss r845 and a secondary sd card on an sd gecko to save all settings. Every game i have tried boots fine but HP POA gives me either a black screen or a green screen freeze with random pixel garbage no matter what settings are set (force 240p, disable or enabled patches. Messing with other settings or keeping everything stock always results in a black or green screen freeze forcing a power cycle of the system). The files i am using are redump set isos, both the US and EU versions give the same crash with a black screen on US version and green screen on EU version. Decided to try other versions of swiss since i remember this game working fine previously and the latest versions that boots the game fine is r775 so i guess this might be a regression issue with the latest revisions. Using Samsung evo 32GB card on GC Loader and Toshiba 4 GB on sd gecko but also tried 32 gb kingston on both sd gecko and gc loader with same result. GC Loader FW version 1.0.1. If you have any possible fix or need further info, please ask. Best regards and awesome work!

**Comment by doublef843** [comment]
More info i forgot to mention. Using Samsung evo 32GB card on GC Loader and Toshiba 4 GB on sd gecko. GC Loader FW version 1.0.1

**Comment by Extrems** [comment]
This appear to be due to some remnant software profiling in the game. It's stuck in an infinite loop waiting for processor cycles to elapse. Our hypervisor reuse the performance counters to implement timers.

**Comment by doublef843** [comment]
Do you believe there is something that might be done in a future revision to reinstate functionality to this game?

**Comment by Extrems** [comment]
I'm currently researching the best way to address this.

**Comment by doublef843** [comment]
Thank you for quickly identifying the issue and for your hard work with swiss fixes. If there is any further info i can provide, let me know :)

**Comment by Extrems** [comment]
Fixed in bb9b9e4 (r857).
