### ISSUE TITLE
Store swiss settings as savedata on memory card

### ISSUE THREAD

**Issue by capz** [emukidid/swiss-gc#360]
I believe all of the apis are available in libogc for swiss to save its settings on the memory card instead of to an sdgecko, why hasn't this been done? Would be super convenient and saves having to keep an (sometimes 2nd) sd card permanently installed.

**Comment by Extrems** [comment]
It actually has for quite some time, to the detriment of some users as when accessing already unlocked memory cards got fixed, we found out there may be lingering data corruption bugs in libogc.

You still need a writable SD card for our hypervisor and patches to keep working in-game.
