### ISSUE TITLE
Since r854 Zelda TP won't start "Too many patches enabled, memory limit reached"

### ISSUE THREAD

**Issue by patters-syno** [emukidid/swiss-gc#361]
SD-Gecko, DOL-001, Qoob Pro 1.3c (patches disabled)
Legend of Zelda Twilight Princess (PAL) NKit from 32GB SanDisk 90MB/s SD card
Only enabled patches are 480p and Widescreen: 3D

Once this error is reported, it seems the memory isn't cleared down correctly and most subsequent games that are tried that session also then display this error (even if they work from cold boot), eventually resulting crash dump when one does try to load.

On the upside, the streaming audio in Ikaruga is much better - no more stutters.

**Comment by Extrems** [comment]
There is enough memory for Force Video Mode, I made sure of that, but not Force Widescreen.

**Comment by patters-syno** [comment]
This particular game doesn't use streaming audio so shouldn't it behave like before, or has there had to be a major re-org? What about the cheat engine in all of this? Does that use a separate allocation?

**Comment by Extrems** [comment]
The emulation is still part of the hypervisor regardless of which game you're playing.
The cheat engine steals some memory from the game, and as such is known to break some of them.

**Comment by patters-syno** [comment]
So will some titles lose the possibility of widescreen patching indefinitely, or do you expect later memory optimization following this initial release of the new audio streaming code?

**Comment by Extrems** [comment]
I'm expecting further optimizations, as the File Service Protocol desperately need them to support streaming audio.

**Comment by patters-syno** [comment]
Great thanks - I'll keep an eye out for updates.

**Comment by patters-syno** [comment]
Incidentally I hit the same memory limit when trying Super Monkey Ball (PAL) and attempting 480p and Widescreen patches. The music on this title was very broken up before and now it's smooth as silk so that new audio code is working wonders.

**Comment by Extrems** [comment]
Fixed in 87aaf7e (r867) for SD Card Adapters, but I don't expect it to last.

**Comment by herrkuhn** [comment]
Have the exact same issue in all versions after r867, also posted [on the forums](https://www.gc-forever.com/forums/viewtopic.php?f=16&t=4707). So, the only method to permanently fix this is using an ODE?

**Comment by Extrems** [comment]
Devices affected:
- IDE-EXI
- SD Card Adapter
- Wiikey Fusion

Devices at risk:
- Broadband Adapter (File Service Protocol)
- Disc Drive
- GC Loader
- USB Gecko

Yeah, not a permanent fix.
I'm looking for solutions, but they carry the risk of breaking game compatibility for everyone.

**Comment by Extrems** [comment]
Fixed in da0e03c (r909), but I don't consider it to be the final solution.

**Comment by Extrems** [comment]
Fixed in 55fcc82 (r1021).
