### ISSUE TITLE
Swiss Freezes When Attempting to Load from SMB / FTP

### ISSUE THREAD

**Issue by econoboxes** [emukidid/swiss-gc#362]
Attempting to select SMB / FTP from the Device Selection menu results in Swiss feezing. After the broadband adapter initializes, Swiss becomes unresponsive, with the seconds digits in the top right freezing.

I am able to connect to the same PC when using other homebrew utilities, such as GCOM24

**Comment by Extrems** [comment]
Partially fixed in 3f38f7e (r1092).

**Comment by Extrems** [comment]
Fixed in emukidid/libogc@fbe1cb4.
