### ISSUE TITLE
Render full width frame (720px) for Swiss menus in prog scan

### ISSUE THREAD

**Issue by patters-syno** [emukidid/swiss-gc#365]
Enhancement suggestion: If Swiss used a full frame resolution when progressive scan is enabled (720px wide or 704px wide) then it would fill the frame on a digital output to a 16:9 TV. My LG OLED for instance will only zoom the image to fill the screen width at 704px or greater. It looks somewhat odd to have vertical black bars on both sides of the image. This would also maximise the resolution for making fonts appear smoother.

**Comment by Extrems** [comment]
Fixed in 9acc88d (r859).
