### ISSUE TITLE
Enabling Gecko codes with IPL boot causes freezes

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#370]
I have a suggestion that might fix this.

Nintendont on Wii disables cheats until after the IPL leaves the screen and enables them when the game is booted.

Thoughts?

**Comment by Gitomata** [comment]
Hi, just wondering if this is the same issue I'm having, basically loading any game after I've selected "boot through IPL" results in a blank screen which doesn't occur if I don't select "boot through IPL". Is this the same issue?

**Comment by Extrems** [comment]
Fixed in 55fcc82 (r1021).
