### ISSUE TITLE
Harry Potter COS does not boot on r867

### ISSUE THREAD

**Issue by doublef843** [emukidid/swiss-gc#371]
On GCLoader running swiss latest revision (867) Harry Potter and the Chamber of secrets gets stuck on a black screen if using the US redump version iso and a green screen using the EU version iso. On previous versions the game botted fine as far as i remember. Tried with diferent forced resolutions and without forcing resolution and the issue remains. Seems a bit similar to the bug that prevented Prisoner of Azkaban from booting on previous revisions

**Comment by Extrems** [comment]
It's sorta similar? They seem to have hacked the base library to high hell.

**Comment by Extrems** [comment]
Fixed in 179e896 (r868).
