### ISSUE TITLE
Zelda Ocarina Double Pack: FMV freezing.

### ISSUE THREAD

**Issue by ExperimentT** [emukidid/swiss-gc#372]
Revision used: Swiss_870.dol
Device: SP2SD, SDGecko
SD Card's used: SanDisk Ultra 200 GB MicroSDXC UHS-I Memory Card (SP2SD)
                        SanDisk Extreme PRO 32 GB SDHC Memory Card Class 10, U3, V30 (SDGecko)
Console: GameCube DOL-001 (PAL)
IPL Revision: Revision 1.0 (PAL)
Swiss Settings: Default
ISO type: 1:1 ISO verified against redump database. Affects PAL and NTSC-U versions. NTSC-J version untested.

During the menu selection pressing any option produces small burst of static audio and cancelling out of any menu option generates an extremely loud burst of static. During gameplay there are small consistent bursts of stuttering and audio static. If one selects one of the FMV movies it'll start playing smoothly at first before slowly stuttering and desyncing before freezing. Pressing any button after the freeze will return you to the main menu.   

Curiously enough, The Zelda: Collector's edition version does not suffer from this issue.
Tested on both the SP2SD and SD Gecko and interchanging the micro SD Card between tests. Results were identical.

**Comment by ExperimentT** [comment]
Tested again with 876. Stuttering and audio static during gameplay no longer occur. Menu and FMV issues still occur.

**Comment by Papy-G** [comment]
r888 Still audio problems when getting back to the games menu, and freezing FMVs.
From a Kingston 8GB µSDHC Class4, PAL Cleanrip rip confirmed and shrunk with NKit.

First attempt gave me "too fragmented…" error
Disabled video patches, retried, ok.
Re-activated all the patches as for the first attempt, and it worked too…

Still, the main part is the games, the FMVs are available on other supports (Original game's discs, Promotionnal Video DVDs…).

**Comment by Extrems** [comment]
You don't need to retest issues I've triaged.

**Comment by Papy-G** [comment]
Sorry, on my side, I have for long considered FMVs reading normally from SD as something we don't have to expect.
Do you think it could be adressed one day?

**Comment by Extrems** [comment]
Partially fixed in b50c446 (r922).
