### ISSUE TITLE
Autoset forcing progressive scan when digital out device present

### ISSUE THREAD

**Issue by Papy-G** [emukidid/swiss-gc#374]
Forcing 576/480p mode has to be disabled when using an analog out display after it has been enabled, otherwise, it fallsback to 288/240p, which is very annoying fo those with multiple setups!

Is it possible to get the progressive scan forcing differentiated from the line quantity forcing, so that the progressive mode can be automatically enabled when digital device is present (or Component cable on the Wii), this way:

progressive scan forcing on digital detect: Disabled/Pal only/PAL and NTSC

To keep native line quantity (on PAL games) and native progressive mode (on NTSC games) as much as required by the user.

Who could not want progressive modes in games when it is available, anyways?

**Comment by Extrems** [comment]
You're saying conflicting things so I'm confused what you're asking here.

**Comment by Papy-G** [comment]
step one: I use my GC with HDMI plug, I set the globals to "force 480p" (I mainly have PAL games).

step two: The TV's not available, I have to use composite for my portable screen (or RF to share the TV), I have to set the global settings for video mode forcing to "no", otherwise I will be forced to 240p, which is ugly.

step three: The TV's available, I have to set video mode back to "force 480p"

With one detail, my son uses the GCs too, and I don't want him to mess around with settings.


Why 480p forcing has to fallback to 240p and not to 480i when no "ED" device is available?
can video forcing be just disabled when the output hardware can't achieve this?

example:
480p disabled to "no" when no device detected.

or a force video mode setting for when "ED" device is detected, and another for when no one is detected.

I know it's a long time demand, and I'm really confused to have to be that bothering, but this one thing actually prevents me to use 480p on PAL GC games, which is really a shame.

**Comment by Extrems** [comment]
Fixed in 9e7fc1c (r871).
