### ISSUE TITLE
Swiss v0.5r867 Breaks NFSUG2 (GUGE69)

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#378]
NTSC USA GameCube DOL-001 With IPL 1.1.

Run from 32GB SanDisk SD card in slot b @ 32MHz.
Works good on 0.5 r856.

**Comment by Extrems** [comment]
Fixed in 179e896 (r868).

**Comment by 60fpshacksrock** [comment]
I was going to request a close on this issue as I noticed it was fixed in the latest (as of this writing) version. Thanks.
