### ISSUE TITLE
Hide boot.iso from Display?

### ISSUE THREAD

**Issue by joshuaziel** [emukidid/swiss-gc#382]
Is it possible to create a setting to hide the swiss boot.iso from the root directory and just show games/homebrew?

**Comment by Extrems** [comment]
Set the hidden attribute on the file.

**Comment by RobertDaleSmith** [comment]
Just to help anyone with MacOS. You can use terminal with the following command after navigating to the directory containing the boot.ini.

```chflags hidden boot.iso```

[more info](https://www.howtogeek.com/211496/how-to-hide-files-and-view-hidden-files-on-mac-os-x/)
