### ISSUE TITLE
Stuck on “Loading” after IGR from multidisc games

### ISSUE THREAD

**Issue by tjanas** [emukidid/swiss-gc#389]
GCLoader with 256GB Samsung micro SD card.
SD2SP2 with 16GB Sandisk micro SD card.
SD2SP2 has Swiss compressed dol as boot.dol, igr.dol is the dol extracted from the GBI Memory Card Boot Disc.

On Resident Evil 4, Code Veronica, Freaky Flyers, Killer7, and all other multidisc games I have tried (launched from GCLoader), IGR returns to Swiss but gets stuck trying to load device contents. With some other games (Paper Mario, Metroid Prime, F-Zero GX) if/when it returns to Swiss it loads device contents without any issues.
![46FC802D-1651-4236-BACF-A1FA2A63D2AC](https://user-images.githubusercontent.com/20304619/90947534-3a717800-e3fc-11ea-9dd3-068cc157a367.jpeg)

**Comment by TH3GOD88** [comment]
Hello, how do you have your games set up?

**Comment by tjanas** [comment]
> Hello, how do you have your games set up?

Nkit-compressed iso stored on GCLoader SD card in a directory called GameCube.

**Comment by TH3GOD88** [comment]
Sorry, I meant how is your folders set up.

**Comment by tjanas** [comment]
gcldr://Gamecube/
gcldr://Gamecube/Japan/

USA region discs within gcldr://Gamecube/

**Comment by TH3GOD88** [comment]
Okay, so do you have Resident Evil 4 as /Gamecube/Resident Evil 4/game and then /Gamecube/Resident Evil 4/Disc 2?

**Comment by tjanas** [comment]
No. Both of the following in `/Gamecube/`:
```
Resident Evil 4 - Disc 1.iso
Resident Evil 4 - Disc 2.iso
```
There isn’t any problem with it switching disc; the issue is with doing an in-game-reset from within a multidisc game.

**Comment by TH3GOD88** [comment]
Oh, I see what you mean. My bad, I thought you were getting stuck on loading the game. Where do you have your igr.dol file?

**Comment by tjanas** [comment]
On the root of my sd2sp2. IGR generally works fine for single-disc games.

**Comment by TH3GOD88** [comment]
I read and my brain went poof. Anyway, have you tried to place another copy onto your one you have in the ODE?
