### ISSUE TITLE
Metroid Prime 2 C-stick x-axis is inverted

### ISSUE THREAD

**Issue by Luke9371** [emukidid/swiss-gc#390]
The map screen in Metroid Prime 2 has a controls display that shows the C-stick is being pressed left when it is pressed right and vice versa. The map also scrolls left and right in the opposite direction. Beam weapon selection is also affected. C-stick y-axis is unaffected, as are other games I've played on Swiss.

**Comment by Extrems** [comment]
Please verify you haven't accidentally set Invert Camera Stick to X.

**Comment by Luke9371** [comment]
> Please verify you haven't accidentally set Invert Camera Stick to X.

Controls options only gives option for y-axis inversion, which I have set to off.

**Comment by Extrems** [comment]
I'm referring to the option in Swiss.

**Comment by Luke9371** [comment]
Ahh ok, sorry to waste your time. Must have been enabled by accident by the GameCubes imprecise d-pad when I was messing with video settings.
