### ISSUE TITLE
Auto Forcing Games progressive mode region-wise

### ISSUE THREAD

**Issue by Papy-G** [emukidid/swiss-gc#391]
What about a general games setting's "auto" video mode, where the games would be launched with video mode forced if an HD device is present and according to the ISO area (480p for NTSC, and 576p for PAL). Quite like SWISS auto video mode, where it is forced according to the console area when available.

This video mode forcing would allow for PAL games that support it, to switch then to 480p, in the b-button menu, when available, avoiding weirdnesses that may happen when 480lines is forced on a 50Hz only game that doesn't support it at all. It would also allow NTSC games that don't natively support it to be run in 480p mode.

That would push ergonomy a step forward, as one still have to set 50 or 60 Hz according to whether the games support it or not when using both PAL and NTSC games. That would reduce the need for the per-game settings, as it is very unlikely that a 60Hz-only PAL game would crash, booting at 576p (I think they revert to 60Hz at launch anyways, and there can apply the per-game specific setting).

**Comment by Extrems** [comment]
Fixed in 50241a4 (r1376).
