### ISSUE TITLE
Write Access to Qoob Chip

### ISSUE THREAD

**Issue by renanbianchi** [emukidid/swiss-gc#393]
Since we already have Read Access, how about we'd be able to write to the Qoob Flash from Swiss instead of always connecting it to a PC using USB?

(In my personal case, i don't have the usb part and need to solder a usb cable every time i want to write to it).

**Comment by emukidid** [comment]
Write support has been added in [32ed236](https://github.com/emukidid/swiss-gc/commit/32ed2364db8c1647c56aa4c94a5f62291961caa6). It also lets you see all the other files on the flash as well.

**Comment by KiteAzureFlame** [comment]
Thank you very much, emukidid! It worked perfectly and I was able to flash it to my Qoob Pro memory (that also don't have the USB part).

**Comment by KiteAzureFlame** [comment]
> > Thank you very much, emukidid! It worked perfectly and I was able to flash it to my Qoob Pro memory (that also don't have the USB part).
> 
> Where can i find a tuto for made this ? I haven't the usb board too.

I don't think there's a tutorial, exactly. What I did was to use a Swiss Disc to boot the program on my GameCube, then I load this new version from emukidd that allowed me to flash the Swiss boot .dol file directly in my Qoob Pro Flash Memory.

The original post where I asked about this was this. There you can find more information:

https://www.gc-forever.com/forums/viewtopic.php?f=3&t=5343#p51730

**Comment by MiGaNuTs** [comment]
Ok, I understood why I couldn't do it. By default in swiss the 'file management' option is disabled and I couldn't find how to transfer swiss.dol to the qoob. after activating the option it was easier and it worked perfectly :) thank you for this feature.
