### ISSUE TITLE
Copying Disc Games to SD isn't working

### ISSUE THREAD

**Issue by renanbianchi** [emukidid/swiss-gc#394]
So I ripped a game using Swiss and the .gcm file isn't readable by Swiss at all. Then, i ripped the same game using CleanRIP (this time, it did work perfectly) and compared the two images.

The first one is the one from Swiss. The First offset line is selected
![GCM from Swiss](https://user-images.githubusercontent.com/57647129/91452281-c77d5c80-e854-11ea-9dd4-04c5f49a6b3b.png)

This one is the CleanRIP Image
![GM8E01](https://user-images.githubusercontent.com/57647129/91452395-e5e35800-e854-11ea-825e-89e2053f27ca.png)

The Same offsets are in different positions, so the data is being copied, it's just kinda scrambled.

**Comment by p0lar-bear** [comment]
Can confirm at least part of this. I have a XenoGC-modded system and am booting Swiss r906 from DVD-RW. I've attempted to rip Viewtiful Joe twice and both times I end up with a GCM file that has no icon and trying to launch it results in the error "Disc does not contain valid word at 0x1C."

**Comment by emukidid** [comment]
Yup, use CleanRip for the time being.

**Comment by coolaj86** [comment]
Is there an older version of Swiss that does work? (Prior to the SD2SP2 addition?)

**Comment by emukidid** [comment]
Yeah use cleanrip for now on GameCube

**Comment by Diegorella** [comment]
now that the revision in the ISO has been added to the swiss. please make a new dump and give us the feedback...

**Comment by A1bi** [comment]
I can confirm that this is fixed. Games ripped by Swiss are now bootable and SHA1 hashes of those images match with public databases.

**Comment by Extrems** [comment]
Fixed in 48451e8 (r924).
