### ISSUE TITLE
Unable to load or save swiss config to memory card

### ISSUE THREAD

**Issue by mariotaotao** [emukidid/swiss-gc#395]
hi, I notice that I can't load or save swiss config via memory card, and I can't find the memory card from the device list. Did you delete this feature in the latest released? Why? Thanks

**Comment by Extrems** [comment]
This feature wasn't ready for prime time and caused filesystem corruption.

**Comment by mariotaotao** [comment]
Ok, is there a way to save or load swiss config via gcloader's storage?

**Comment by emukidid** [comment]
@mariotaotao no, gcloader is read only for now. Get yourself a SD2SP2 or other SD based solution in the meantime.

**Comment by mariotaotao** [comment]
@emukidid got it, thank you for the reply
