### ISSUE TITLE
v0.5r906: Emulate Read Speed disc read error with boot through IPL

### ISSUE THREAD

**Issue by tjanas** [emukidid/swiss-gc#396]
I’m experiencing a new issue with r906 that I didn’t with r888: when starting up Paper Mario (nkit iso) with Emulate Read Speed enabled, I get a disc read error. No error when this option is disabled. Also, when the error occurs, pressing reset on the GameCube allows it to boot without an error.
![04AA263A-8EBE-467E-9F5C-4D6BD4DF57E7](https://user-images.githubusercontent.com/20304619/92427475-365e8d80-f152-11ea-8b7b-93eeb34c2297.jpeg)

https://youtu.be/tl_2pRzOryw

**Comment by tjanas** [comment]
Probably related to this, with Emulate Read Speed enabled, loading disc 1 of Tales of Symphonia seems to silently fail, acting as though I’m forcing it to the IPL menu, where it shows disc 2 is loaded.

**Comment by Extrems** [comment]
Fixed in c0df4ec (r911).
