### ISSUE TITLE
NKit compressed Animal Crossing non-functional.

### ISSUE THREAD

**Issue by GreenBeanMech** [emukidid/swiss-gc#398]
Enabled File Management in settings and when I attempt to load I still get the "Enable File Management" bug. I apologize if this is a  WIP feature or something obvious i'm missing 👍

**Comment by Extrems** [comment]
I'm guessing you're trying to load a GCZ compressed image. We don't support GCZ.

**Comment by GreenBeanMech** [comment]
Gotcha, it would be incredible if possible. The game in that form is only
16MB and is supported on Dolphin so I figured it would be at some point.

**Comment by Extrems** [comment]
Do you have any idea how much memory and CPU time this require?

**Comment by GreenBeanMech** [comment]
Probably too much that the poor GameCube can't handle. You've done an
incredible job Extrems. If I had it my way your UI would be used for every
6th gen consoles even the Xbox.
