### ISSUE TITLE
Swiss does not compile with devkitppc r38 / libogc 2.1.0

### ISSUE THREAD

**Issue by bitscher** [emukidid/swiss-gc#400]
Symbol `SYS_GetCoreTemperature` added to your fork of libogc has not been contributed upstream and prevents swiss from compiling against the upstream version of libogc.

Moreover devkitppc r38 is unable to build [emukidid/libogc](https://github.com/emukidid/libogc) because system calls have been reworked in the newlib patch and the `__syscalls` array is not defined anymore:

- https://github.com/devkitPro/buildscripts/commit/5e720e01c1db3cfa2366b0b22ef9a54e8f9f64e6
- https://github.com/devkitPro/libogc/commit/2ef0d45f2310d69d3e8dc7f2ea8a52e468b01737

Two non mutually exclusive fixes:

1. Rebase [emukidid/libogc](https://github.com/emukidid/libogc) on https://github.com/devkitPro/buildscripts/commit/6a74f8361637781e766bf66ff7cb62be4879f0aa
2. Contribute https://github.com/emukidid/libogc/commit/5623d2a6958b65a71ce8a244ec555e5b1ff59aa4 & https://github.com/emukidid/libogc/commit/38ea507c0e5cdddcbbbc630d47357f0798a5d759 to upstream

**Comment by Extrems** [comment]
Networking is broken with devkitPPC release 38.

**Comment by bitscher** [comment]
What version is recommended?

**Comment by Extrems** [comment]
devkitPPC release 36, release 37 has the same issues being based on GCC 10.

**Comment by Extrems** [comment]
Looks like that particular issue can be solved by building libOGC with -O1, but then it's built with -O1.

**Comment by Extrems** [comment]
Fixed in emukidid/libogc@e835315.
