### ISSUE TITLE
F-Zero GX Crash/Restarts Randomly

### ISSUE THREAD

**Issue by TorqueEmPup** [emukidid/swiss-gc#401]
Can't play more than a few races in F-Zero GX (USA Version) without the game freezing, then restarting.
Sometimes crashing the entire system to a black screen.

Can't find any rime or reason for it, can play one race, and have it crash on the next. Or Complete an Entire Cup then finish the first race on the next cup, and have it do a crash restart on the following race.

Using a SD Memory Card adapter plugged into Slot B, have tried two different SD cards.

.iso is hash verified against REDUMP. 
.iso, and .nikit.iso version of the game don't make any difference. If anything the nkit iso causes the crash to happen faster.

PAL version of the game doesn't have these issues at all.

**Comment by thamulot** [comment]
FYI - I played quite a bit of F-Zero GX NTSC version recently on release 963 with an sd-card in slot B and I've got absolutely no problem whatsoever. I don't say this to disregard your problem, but just to say that, on what seems to me a similar setup, I'm totally fine.

**Comment by TorqueEmPup** [comment]
Yeah I have no idea. I wish I had a different Gamecube to test to see if it might be an isolated issue to just my console or setup.

**Comment by Nicolas-Miranda** [comment]
I'm experiencing the same issue with a GCLoader Gamecube setup and the USA version of F-Zero GX have random crashes and sometimes goes to black screen and only audio plays. Sometimes laso has graphic glitches. Other games doesn't have tghis kind of issues.
