### ISSUE TITLE
Add GCLoader as "Configuration Device" support

### ISSUE THREAD

**Issue by Unfaehig** [emukidid/swiss-gc#402]
Hey folks,

i tried out a GCLoader today and i notice that its not possible to set it as a "Configuration Device" which is a bit sad. Not sure if its becuase of technical limitations related to an optical drive replacement, but would be greate if supports such feature as well!

**Comment by Extrems** [comment]
This isn't possible as there's no write command.

**Comment by Techsteps** [comment]
So, just to be clear. We will never be able to write a Swiss config to the SD in the GCLoader?

**Comment by emukidid** [comment]
Currently it's like trying to burn a DVD on a DVD reader, if gcloader make a firmware update to allow writes then we can add support to swiss.

**Comment by Techsteps** [comment]
Understood. Thank you for the clarification.

**Comment by gmipf** [comment]
@emukidid If he can implement write support to the GCLoader firmware, isn't it also possible to add write support to WKF/WASP by somehow hacking its firmware?

**Comment by Extrems** [comment]
In theory yes, but I doubt someone will spend the time developing new firmware for the WASP/Wiikey Fusion.

**Comment by Extrems** [comment]
Fixed in 6feebd3 (r1090) in conjunction with an upcoming firmware update.
