### ISSUE TITLE
GC Loader 480i mode

### ISSUE THREAD

**Issue by ferllen** [emukidid/swiss-gc#403]
Hi, I'm trying to setup Swiss menu in 480i mode (tool icon) because my TV doesn't support 480p, so to browse games I need 480i. but even after changing, swiss it still keeps the resolution like 480p. Swiss can start games starts fine on 480i, just the swiss menu doesn't change the resolution.
 That only happens to swiss using GCloader. Using Action replay booting from SD works fine. If I just renamed any game to boot.iso it also boots fine in 480i. It just happens to Swiss.

**Comment by Extrems** [comment]
You need a configuration device.

**Comment by ferllen** [comment]
> You need a configuration device.

I have Memory Card with with SD-Card, I saved the config to the Memory card, but it still boots only in 480p. It shows 480i in the config, but when I browse to the Info icon it shows 480p.

**Comment by ferllen** [comment]
here configuration starting as 480i (see it's configured as 480i)
https://imgur.com/4p7rRa1
Here's what the "info" icon shows it's 480p.
https://imgur.com/a/aFUBTUn
as you can seee my image is messed because it's 480p

**Comment by Extrems** [comment]
You're looking for Swiss Video Mode under Global Settings.
