### ISSUE TITLE
Config Failed to Save

### ISSUE THREAD

**Issue by Jaybaebay** [emukidid/swiss-gc#404]
No matter what I do I get a Config failed to Save message. I've set configuration device to SD card Slot 2 which is the device I'm using and the save bar goes about half way and then displays the error. Every other device just fails straight away. It worked at Xmas 2019 but now it doesn't I even tried reverting to the build I was using then and that doesn't work either.

Edit: Now it is telling me when I start a game that no writable media is present and that it can't load patches. My SD card works fine and isn't set to read only

**Comment by TH3GOD88** [comment]
I could only get a config to save if I had my SD Geko in Slot A. This is on r888 and r906

**Comment by Jaybaebay** [comment]
I can't even get Swiss to boot from slot A I'm using action replay to boot
Swiss from SD

**Comment by TH3GOD88** [comment]
Oh, I was booting from disc. Have you thought about buying the SD2SP2 package some are selling with the disc?

**Comment by Jaybaebay** [comment]
No I haven't because it was working fine before and I've gotta swap out the
disc to play anyway

**Comment by TH3GOD88** [comment]
Okay, just a thought. I know when ever I try to save a config anywhere, unless it was in Slot A, it would tell me that it failed to save. I have the SD2SP2 and now the GCLoader, still cannot save unless I have SD Geko in Slot A. So I know your pain. Hopefully they can answer why it is doing it.

**Comment by Jaybaebay** [comment]
Well we have different uses anyway I'm literally just using it to load pal
into progressive and use some of the Swiss enhancements like AF and
removing dithering but since last week I haven't been able to do anything
because it's saying it can't load patches without writeable media

**Comment by Jaybaebay** [comment]
Never mind I know the problem you removed the ability to use memory cards as configuration devices which is how mine was set up. I for some reason cannot use my SD as a configuration device so I'll have to just use r878 for now
