### ISSUE TITLE
Twilight Princess performance issues

### ISSUE THREAD

**Issue by kingjinxy** [emukidid/swiss-gc#405]
Game tested: Twilight Princess (PAL) Full ISO Redump
Revision: 912
Loader: GCLoader
Video: Composite on CRT, forced to 480i, 60Hz selected in-game

Whenever I move into a “large area” like Hyrule Field, the game has extreme slowdown for about half a second and then returns to normal. When in Hyrule Field, Eastern especially, the frame rate seems far lower than what I’ve seen in online walkthroughs for the GameCube version.

**Comment by Extrems** [comment]
Update to the latest release. This is likely fixed.

**Comment by kingjinxy** [comment]
> Update to the latest release. This is likely fixed.

Oh sorry, I meant to write rev 912.

**Comment by Extrems** [comment]
Is it the same when played as boot.iso?

**Comment by kingjinxy** [comment]
> 
> 
> Is it the same when played as boot.iso?

I can't test the PAL version as boot.iso because it throws an error (my GC is NTSC, so I think that that is the reason), but I tested the NTSC version and got the same result.

The extreme slowdown when entering a large area is not as bad with read speed emulation turned off. I have a video here of me exiting Kakariko Village into Hyrule Field and then warping to a different part of the field where the same lag occurs: https://youtu.be/TsVjbnC1U0s

**Comment by Extrems** [comment]
There's nothing we can do then.

**Comment by kingjinxy** [comment]
What do you mean? If you think that it's part of the game, I disagree. This video [https://youtu.be/-ypqc3aP2-8?t=612] (and see also about 13:15 in) seems to suggest that the game does not lag nearly as much when played from (presumably) a disc.

**Comment by Extrems** [comment]
https://www.reddit.com/r/Gamecube/comments/4j5phl/my_copy_of_twilight_princess_is_having_framerate/d34q2gv/
https://www.neogaf.com/threads/official-legend-of-zelda-twilight-princess-thread.128357/page-105#post-5128679

Sounds familiar?
