### ISSUE TITLE
[Mario Party 4] After first turn minigame, one player always has 999 coins.

### ISSUE THREAD

**Issue by SpadeCA** [emukidid/swiss-gc#408]
Happens after first turn minigame in Story Mode(Easy, All) on Toad's map. 
![MarioParty4](https://user-images.githubusercontent.com/11309486/93719947-c4674a80-fb3a-11ea-87ed-e97c70592d78.jpg)
Tested the exact same ISO on Dolphin, can't repo this in emulator but happens 100% of the time on Swiss with GCLoader. Also verified the ISO is a good dump.

**Comment by SpadeCA** [comment]
Just saw this was a duplicate of #149, closing.

**Comment by Extrems** [comment]
Aww, come on. This is still happening? I couldn't reproduce it.

**Comment by SpadeCA** [comment]
I have 100% Repo Rate with GCLoader 1.1.0 and Swiss v0.5r912.

**Comment by Extrems** [comment]
Nope, I still can't.

**Comment by SpadeCA** [comment]
Any settings different from default? I can't think of anything else.

**Comment by kingjinxy** [comment]
I've never played this game before, so I don't know if this is valid, but does the save file make a difference?

**Comment by Extrems** [comment]
From what I read on this issue in Nintendont, I suggest trying boot through IPL.

**Comment by SpadeCA** [comment]
Can confirm Boot through IPL fixes the issue.
