### ISSUE TITLE
Can only dump one of dvd_ram_low, dvd_ram_high, and dvd_rom

### ISSUE THREAD

**Issue by Pokechu22** [emukidid/swiss-gc#411]
After dumping one of `dvd_ram_low.bin`, `dvd_ram_high.bin`, and `dvd_rom.bin`, attempting to dump another (or possibly the same one a second time) will result in a file full of zeros.  It works properly if the system is rebooted between dumps, though &mdash; but that's annoying to do.  My guess is that since each one calls `dvd_enable_patches`, the patch is applied multiple times, which causes issues; the drive could be reset before the call to fix that maybe.

Tested on a DOL-001 GameCube (NTSC IPL 1.1) with SP2 present, booted using SD Media Launcher.  The drive firmware is 20020402.  Swiss Version 0.5, Commit 4715a64, Revision 912.

**Comment by Extrems** [comment]
Fixed in eb156a4 (r1083).
