### ISSUE TITLE
How are the 7z files being generated?

### ISSUE THREAD

**Issue by coolaj86** [emukidid/swiss-gc#418]
I've been on the lookout for some way to uncompress the 7z files with command line tools that work reliably cross-platform and there are, literally... none.

However, there is someone who is trying to provide a solution: https://github.com/selmf/unarr/issues/12

Unfortunately it appears that the 7z files that are being uploaded are not "standards" compliant files.

- What software are you using to generate them?
- On what OS / architecture?
- And what checkboxes (or CLI flags) are used?

With that info it may be possible to get support for swiss in open source 7z unarchivers.

cc/ https://github.com/emukidid/swiss-gc/issues/238

**Comment by Extrems** [comment]
- p7zip
- Arch Linux / x86-64

**Comment by Extrems** [comment]
https://pkgs.alpinelinux.org/packages?name=p7zip
https://packages.debian.org/search?keywords=p7zip
https://formulae.brew.sh/formula/p7zip
https://svnweb.freebsd.org/ports/head/archivers/p7zip/pkg-descr?revision=HEAD

Were you even looking?

**Comment by coolaj86** [comment]
> Were you even looking?

Yes, I'm looking for something that is **cross-platform** and easy to install and use in a scripted or automated fashion.

For example, [`arc`](https://webinstall.dev/arc) is cross-platform. Anyone can download and use it, on any platform. 0 complexity. Anyone can write an install script for it on any platform.

At the point that you have to run a hacked-together linux subsystem (MSYS2) or a 320mb+ package manager with loads of non-native libraries (brew), you're no longer in the realm of "cross platform".

p7zip does NOT have
- releases API
- Mac builds
- Windows CommandLine builds
- portable programming implementations

**7z is virtually UNSUPPORTED in ANY mainstream archive library or programming language**

I get that for you it's acceptable to have this kind of tooling, but I'm asking you to think outside of yourself:

Most people aren't the kind of people who can reverse engineer a GameCube bootloader, or even the people who use a DIY linux (when even an _easy_ linux is already _very_ DIY) - so from your perspective I can see how you might thing that p7zip easy to install and use, but in the world of 2020 where modern, maintained projects have release APIs and self-contained static cross-platform builds... it's not. It's complex and annoying and nearly impossible to build tooling around.

As grateful as I am that you are doing very difficult things that most people would find impossible, I don't understand why you wouldn't make it even more accessible and developer and user friendly by publishing it in a format that is easy to consume.

**Comment by Extrems** [comment]
`7z` is bundled with regular 7-Zip for Windows. This is a port of that application after all.
I've never used macOS, so I can't comment on the matter.

7-Zip is no problem to non-Mac users.
