### ISSUE TITLE
SD card sizes not compatible? Swiss + GC Loader

### ISSUE THREAD

**Issue by DubCheesy** [emukidid/swiss-gc#419]
I was having an issue getting Swiss to boot on my GC Loader from a 400GB microSD. GameCube kept returning the “unable to read disc” error. It would however boot fine from a 32GB microSD.

When I named an iso “boot” on the 400GB card, the game would load immediately.

After a lot of troubleshooting and ensuring I had the latest V1.1.0 GC Loader firmware, the final solve on getting Swiss to run from my 400GB microSD was to format the microSD as “exFAT” rather than “FAT32”.

Unsure if that’s an issue that others are having (or if it’s already solved). Just thought someone might be in the same spot as me and could use the info.

I believe I am running Swiss V0.5r912, so a couple revisions back.

**Comment by Extrems** [comment]
1.1.0 is not the latest, 1.1.2 is.
