### ISSUE TITLE
Game Saves Corrupting

### ISSUE THREAD

**Issue by jeffmaas4887** [emukidid/swiss-gc#422]
Ok So I still have a problem! I have the GC Loader PnP and My Game Saves are still getting corrupted. I did what others told me and I seperated all my diffrent region isos onto different sd cards for all of them and also have seperate memory cards for each region as well. And I have all the different Gamecube Memory card types. Is this an issue that will eventually be addressed because I am getting the feeling this is not just me having this problem? I have the current firmware and the current Swiss installed. Also will You eventually be having it set up where we save our game saves straight to a sd card instead of having to use Gamecube Memory cards. Like Dolphin has it where all saves are in one area and diffrent folders for each region??? :(

**Comment by Papy-G** [comment]
If you get the correct settings, you shouldn't have to worry about mixing Roman and Japanese based saves, unless you occasionnally play the games straight from boot with a modded GC (Which is unlikely as 1: You have installed a GCLoader in your (main) Cube 2: You want to save straight on SD cards with SWISS patches.)

You have to note that some games genuinely mess up saves on cards bigger than 251 blocks.

You seem to have a huge amount of save fails, that doesn't seem to be game related, did you even try to clean your MC slot pins/contacts?

Please be precise about which game corrupts the saves, and in which condition.

**Comment by jeffmaas4887** [comment]
!. what are the right settings for Swiss home menue settings? 2. I idint know I had to clean the pins on the memory cards been they are brand new and staright out of unopen packages and how do I do that? 3. How do i save my saves straight to a SD card instead of haveing to use gamecube memory cards. 4All the games I am trying to set up are of the same region on seperate sd csrds.5. The videos that Ihave found on Youtube are pretty basic and not very explanitory with step by step instructions on everything to do. 6. Sorry about my typing as of last night My Family has a serious Family emergency, Moms in Hospital and not looking good, and didnt sleep much. Thank You. :)

**Comment by Extrems** [comment]
The """""""correct settings""""""" they're alluding to can result in missing in-game text (and crash) or [mojibake](https://en.wikipedia.org/wiki/Mojibake), which is not ideal.

**Comment by jeffmaas4887** [comment]
So what are the correct settings. This is something no one seems to be able to tell me.

**Comment by Extrems** [comment]
The correct settings are the default settings. Their """""""correct settings""""""" is setting Force Text Encoding to ANSI.

**Comment by jeffmaas4887** [comment]
Thank You. I did what You said it it works. Better info then the 2nd Mis info been getting. Also you mentioned it is Possible to save game saves to straight to a SD card with out the need of a Gamecube Memory card. How do You do that and is there a limit on the size of the SD card You use for the Gamesaves?

**Comment by KirovAir** [comment]
Sometimes forcing a game title to a different video mode can change the internal region as well and fuck up a game save.
Example: The Wind Waker (PAL) forced to 480p will corrupt my PAL memorycard but works fine on my NTSC formatted card. (Not 100% sure about this example, but I've had instances like this)

**Comment by jeffmaas4887** [comment]
I havent been forcing anything and the other guy helped me fix the problem. Also it still doesnt tell me how to save straight to a regular SD card so I dont have to use a piece of Shit Garbage Gamecube memory card like the other was saying You can do!

**Comment by KirovAir** [comment]
I know you got it fixed. I felt like adding this info might help some other users experiencing the same issues. Also memory card emulation is not implemented yet as far as I know but some work has been made so maybe this will be made public in a future release.

**Comment by Extrems** [comment]
> Example: The Wind Waker (PAL) forced to 480p will corrupt my PAL memorycard but works fine on my NTSC formatted card. (Not 100% sure about this example, but I've had instances like this)

This could only happen if you have a NTSC-J system, set Force Text Encoding to No, and your "NTSC formatted card" is SJIS.

**Comment by KirovAir** [comment]
Ah that explains it. I do have a NTSC-J system.

**Comment by Papy-G** [comment]
@jeffmaas4887:
I couldn't be too specific, as I feared this was GCLoader related, and I don't know own one to help any further.

Cleaning the connectors on old consoles is routine maintenance, especially if these have been exposed somehow to dirt and haven't been used for a while.

There is no way, as of v5 of SWISS, to save game progression anywhere else than on regular Memcards. Nobody said that it is possible, I just stated that this is something you would want to do.

Sorry if I used wrong word, I should have said "appropriate settings for the use", I'm personnally happy with default setting (I don't use NTSC-J games).
I personnally use NTSC and Pal games on PAL consoles, dumps and saves are mixed among my memory cards regardless of "zone" with no noticeable problem so far (Only third-party ones, from 59 to 2043 blocks).

Take good care of yours.

**Comment by jeffmaas4887** [comment]
Just want to say Thank You to everyone for Your Help and also say Thank You for all the wonderful work You are doing Swiss. You People are truelly Amazing! :)

**Comment by llakssz** [comment]
> Their """""""correct settings""""""" is setting Force Text Encoding to ANSI.
@Extrems - maybe I am misinterpreting it, but by this do you mean 'Force Text Encoding' is not perfect and is not to be used all the time?
I'm asking because I had thought that using a JP formatted card and forcing all text encoding to SJIS would be the best scenario for playing different region games with one memory card. Since A-z09 is the same in ASCII and SJIS, both Japanese saves and English saves would display correctly in the GC save manager.

**Comment by Extrems** [comment]
It should only be set to the default of Auto.

**Comment by llakssz** [comment]
Thanks, interesting you say that. In my (very limited!) testing, things have been going well so far forcing all games to SJIS.
If there are any problems/specific games that would have problems, I'd like to know.
