### ISSUE TITLE
Save files corrupted when copied or moved

### ISSUE THREAD

**Issue by PolZol** [emukidid/swiss-gc#425]
I have only tried this with an SD2SP2 and the game Pikmin 2, but when copying or moving a save file from the memory card to the SD card, the copied/moved file on the SD card gets corrupted.

**Comment by JinxDojo** [comment]
How are you copying these files? From within the game itself?? What is in slot A? Slot B?

Are you using only physical memory cards or also emulated ones? As far as I know, there is currently no way to copy directly between the two using Swiss (see #431).

If you're only using physical cards, it's worth noting that the SDGecko does *not* act like an actual memory card. It can only be read by homebrew like Swiss and not by an unmodded Gamecube. I hope this helps.

**Comment by PolZol** [comment]
I have a memory card in slot A and a SD2SP2 with an SD card in the serial port. I tried to use the Swiss file manager to copy my saves from the memory card to the SD card, but they got corrupted in the process. Of course it is much more practical to use GCMM (I think that was the name of the backup program), but when I made the bug report I didn't know that program existed. Thanks for your help!

**Comment by Extrems** [comment]
Fixed in 474b219 (r1032).
