### ISSUE TITLE
Copying Memory Card

### ISSUE THREAD

**Issue by ninomae-inanis** [emukidid/swiss-gc#429]
With r963 adding SD memory card emulation I decided I'd like to make the switch. I initially assumed that the spoofed memory card would show up in the saves manager section of the GC but saw it wasn't in there so realized I needed to improvise. The solution I eventually came up with was to do a raw backup with GCMM on my Wii then copy the resulting raw file onto my SD card in the swiss_patches folder and rename it to MemoryCardA.USA.raw, however when I then load into a game it tells me the memory card in slot A is corrupted and needs to be formatted.

Is there some step I'm missing? Or am I doing things entirely wrong? Is there an easier method for copying the saves on a memory card to an SD card that I don't know about?

NTSC-U, GCLoader + SD2SP2

**Comment by Extrems** [comment]
It does show up if you use boot through IPL. The memory card image has to be from a Memory Card 2043.

**Comment by ninomae-inanis** [comment]
My savior! I've never touched that or pretty much any other option in the advanced settings cause I dunno what most of em do lmao, but that worked like a charm and I was able to copy all my saves over manually. Cheers!

**Comment by Extrems** [comment]
For files that you will be unable to manage, you can use Dolphin's Memory Card Manager.
