### ISSUE TITLE
Swiss won't load WiiRD codes for certain games (And any Gecko Codes [.gct] file)

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#436]
Super Mario Sunshine, Zelda: Wind Waker, and Zelda: Twilight Princess will not load WiiRD codes from a .txt file no matter what I do. What happens exactly in Swiss 0.5 r963 is I try to access the cheat menu by pressing Y on the aforementioned games, but it does nothing, and it doesn't even tell me if the cheat file is there or not. On Swiss 0.4 r371, however, the cheat menu shows but no codes are there when the codes do exist in the .txt file. I formatted everything correctly, including the codes, file placement, and file names. Also, Swiss will not recognize my cheats.qch file.

This is an example of how my cheats look:
Mario Sunshine: (https://github.com/emukidid/swiss-gc/files/5645049/GMSE01.txt)
Twilight Princess: (https://github.com/emukidid/swiss-gc/files/5645050/GZ2E01.txt)
Wind Waker: (https://github.com/emukidid/swiss-gc/files/5645051/GZLE01.txt)

Cheats .qch file: (https://github.com/emukidid/swiss-gc/files/5645060/cheats.zip)

Please fix this issue or let me know if I'm doing anything wrong here.

**UPDATE: Swiss 0.4 and 0.5 will not recognize any .gct (Gecko Codes) files either.**

**Comment by emukidid** [comment]
@GK6475 what is your device setup like? GCLoader? SD2SP2?

**Comment by GK6475** [comment]
SD2SP2 and SD media launcher

**Comment by GK6475** [comment]
> 
> 
> @GK6475 what is your device setup like? GCLoader? SD2SP2?

SD2SP2 (FAT32) and an SD media launcher (FAT), either one.

**Comment by emukidid** [comment]
Your cheat files are encoded in UCS-2 LE BOM, encode them in ANSI please. If you don't know what I'm talking about, open up the cheats files in notepad++ and then use the encoding menu to change to ANSI.

I'll add a warning for when a file is found with no valid entries to alleviate confusion.

.qch files haven't been supported for a long time either, so that's why those aren't working.

**Comment by GK6475** [comment]
That fixed my problem. Thank you!

**Comment by emukidid** [comment]
Warning added in 0984957383567080d453639c487cd3f74cc0baa0.
