### ISSUE TITLE
Pac-Man World 2 Freezes on Memory Card Initialization

### ISSUE THREAD

**Issue by Aarmaster11** [emukidid/swiss-gc#437]
On the latest release (r963) when loading Pac-Man World 2 from an SD2SP2, the game starts as normal up until it has to initialize the memory card. Upon trying to save or load, the game will hang indefinitely. This behavior does not persist when loading the game off of the original disc, even through Swiss to force 480p.

https://i.imgur.com/MsCsBK0.png

**Comment by Extrems** [comment]
This seem to have been fixed in the meantime. Not sure when nor how.

**Comment by Extrems** [comment]
Fixed in bc9a59c (r966).
