### ISSUE TITLE
Crash when accessing folder or selecting other device

### ISSUE THREAD

**Issue by gmipf** [emukidid/swiss-gc#438]
My setup: PAL Gamecube with WASP (64GB) and SP2SD (8GB) connected through official component cable. 

I have flashed the new r990 to my WASP today and after the restart I have noticed the resolution change. The swiss resolution setting has changed from Auto to 480i somehow. If I boot swiss with resolution at 480i or 480p, it will result in an instant crash if I try to access any folder on my 64GB card or press the eject button to access another device. Auto (which results in 576p with component cable on PAL) 576p and 576i setting works fine.

**Comment by Extrems** [comment]
Fixed in ac13816 (r994).
