### ISSUE TITLE
Wind Waker visual glitch - sun/lens flare appears through dungeon walls 

### ISSUE THREAD

**Issue by Gitomata** [emukidid/swiss-gc#441]
Legend of Zelda Wind Waker has a visual glitch where the sun/lens flare appears through walls in dungeons. I've PictoBoxed (=P sorry couldn't help make the reference) the glitch occurring in the first and second room of the Forest Haven (2nd dungeon):
![IMG_02](https://user-images.githubusercontent.com/72957852/103479196-30d33480-4e20-11eb-901d-ecde284d2296.jpg)
![IMG_01](https://user-images.githubusercontent.com/72957852/103479199-34ff5200-4e20-11eb-9362-21b7079ee74e.jpg)

**Details:**
Swiss version used where glitch occurs: r990
Game: The Legend of Zelda: Wind Waker NTSC version

**Possible cause**
I suspect the issue is connected to the fix implemented for a prior reported issue: #368 and it appears the solution implemented for the different workaround for EFB Z peek in r888 has fixed the issue in Star Fox but created one for Wind Waker. I say this as I later tried Wind Waker using r845 and the sun/lens flare issue did not appear.

The glitch is not game breaking and reverting to an earlier version of swiss does alleviate the issue.  

Thank you for your ongoing work on swiss =)

**Comment by Extrems** [comment]
Oh, for crying out loud...

**Comment by Extrems** [comment]
Fixed in 2764414 (r993).
