### ISSUE TITLE
Memory card not recognised when using r990

### ISSUE THREAD

**Issue by robosnacks** [emukidid/swiss-gc#442]
I'm having a problem with my memory card not being recognized using r990.
It's not showing up in Swiss. In game I get an error message, e.g. Twilight Princess, "The wrong device is inserted in Slot A. Please insert memory card"

I'm using this [unofficial, 'Link-e' branded, memory card.](https://www.amazon.co.uk/gp/product/B0157YZ6UC/)
I have 4 of these cards, all the same, all exhibit the same behavior. I've never noticed any problems using them previously.

If I revert back to r963 all works fine and as expected.

My setup: Booting Swiss from disc, DOL-001 EUR, XenoGC v1.0, booting games from SP2SD2 and BBA fsp client

**Comment by robosnacks** [comment]
In the meantime, I've got hold of a genuine DOL-008 memory card, this works fine with r990, so definitely just my dodgy memory cards causing the issue.

**Comment by Extrems** [comment]
The relevant change was tested with DOL-008, DOL-014, DOL-015, DOL-020, and DOL-022.
I have a good idea of what's happening, but I've ordered one for greater analysis.

**Comment by Extrems** [comment]
I'm having terrible luck with this kind of product. The one I got is working fine, but I notice the controller chip has a proper BGA package rather than being chip on board.

**Comment by Extrems** [comment]
Please give this a try before I lose my mind: [swiss_r1011.zip](https://github.com/emukidid/swiss-gc/files/5853415/swiss_r1011.zip)

**Comment by robosnacks** [comment]
Thanks! I've burned r1011 to disc and tested.

It's working more than it was before but unfortunately it doesn't seem to be reliable.

Here's what I found:

Using 3 cards, all the same, and TWP to test, Card1(my main card I am currently using), Card 2&3 (spares)

Card1 inserted, not recognized by Swiss or in game as before.
Switched to Card2 still in game, I get a  '....corrupted. Would you like to format...' etc. error message.
It formats OK and then works as expected and I am able to save the game.

However, I when I reboot and restart the game the card is not recognized again.
Switching to Card3 in game, this is recognized OK, without the '...corrupted...' error.
I can save OK.

On a 2nd restart Card3 is now not recognized again.
Then in game I switch back to Card1 and it now works OK and my current save game data is all there.
But on restart it's not recognized again...

I can reproduce this and it seems to serve as a workaround - if I start the game with a spare card inserted, it's not recognized, but if I then, in game, switch to my 'real' save card it works fine while I am playing.

**Comment by Extrems** [comment]
If this still doesn't work, it's over: [swiss_r1011.zip](https://github.com/emukidid/swiss-gc/files/5856411/swiss_r1011.zip)

**Comment by robosnacks** [comment]
No joy, I'm afraid. Not the end of the world!
Thanks for Swiss - it's awesome!
