### ISSUE TITLE
I am just going to ask because I need help?

### ISSUE THREAD

**Issue by jeffmaas4887** [emukidid/swiss-gc#444]
Look! I am 48 and not a complete genius and doing th best I can but having problems. What settings do I need to set it up where my Gamesaves save to a Micro SD card? Thank You. :(

**Comment by Extrems** [comment]
This is currently only available when booting a game from a DVD or GC Loader. It's Emulate Memory Card under Advanced Settings.

**Comment by jeffmaas4887** [comment]
I did that and not happening and do I do slot A or B and do I need a seperat card for the patches?

**Comment by Extrems** [comment]
You need an SD Card Adapter with an SD Card in it in conjunction with your DVD or GC Loader.

**Comment by jeffmaas4887** [comment]
I have that.

**Comment by jeffmaas4887** [comment]
I have the GC Loader PnP and the whole set up for the tray. Got 2 SD geckos. I have Sandisk SD cards and Nintendo Memory cards and all of that. But it would be nice if someone made a easy step by step of it all on Youtube. Not some Fly by night who thinks every one knows what there doing.

**Comment by Extrems** [comment]
All you need is one SD Gecko or SD2SP2 and enable the setting.

**Comment by jeffmaas4887** [comment]
And what slot do You use? Slot A or Slot B?

**Comment by Extrems** [comment]
You can use either Memory Slot A, Memory Slot B, or Serial Port 2. It doesn't matter.

**Comment by jeffmaas4887** [comment]
Keeps saying configure failed to save!

**Comment by Extrems** [comment]
Is Configuration Device under Global Settings set to a valid device?

**Comment by jeffmaas4887** [comment]
SD Card - SP2

**Comment by Extrems** [comment]
That doesn't answer my question. Do you have a SD2SP2 in Serial Port 2 and is there an SD Card in it?

**Comment by jeffmaas4887** [comment]
I have it in Slot A.

**Comment by Extrems** [comment]
Then set to SD Card - Slot A.

**Comment by jeffmaas4887** [comment]
Got it. Thank You. 👍
