### ISSUE TITLE
Reset to Swiss question.

### ISSUE THREAD

**Issue by jeffmaas4887** [emukidid/swiss-gc#446]
A reload stub enabling homebrew applications to return to Swiss has been added.
While this depend on a libOGC patch that may never make it upstream due to a rift with @devkitPro, the stub offer backwards compatibility with the older standard set by PSO/SDload. As such, many popular applications are supported today.

This feature require a copy of DOL/swiss_r990-compressed.dol on an SD card under one of the following file paths:

/autoexec.dol
/boot.dol
/boot2.dol
/igr.dol
/ipl.dol

For this to work do You have to do a Button Combination and what is it? Thank you! :)

**Comment by magu** [comment]
https://www.reddit.com/r/Gamecube/comments/b0i2xo/comment/eigs9pd

*B + R + Z + D-Pad Down*

Took two seconds googling. I'm also quite sure it's written somewhere in the docs or config menu, but am not by my computer/GC to check atm.

**Comment by jeffmaas4887** [comment]
Well Thank You and forgive me if I didnt think to Google it Ass!

**Comment by Extrems** [comment]
> 
> 
> https://www.reddit.com/r/Gamecube/comments/b0i2xo/comment/eigs9pd
> 
> _B + R + Z + D-Pad Down_
> 
> Took two seconds googling. I'm also quite sure it's written somewhere in the docs or config menu, but am not by my computer/GC to check atm.

That's for in-game reset. You need to look for an exit button in the application, same as on the Wii with the Homebrew Channel.
