### ISSUE TITLE
Cannot overwrite files (write fail)

### ISSUE THREAD

**Issue by rapperskull** [emukidid/swiss-gc#448]
The latest Swiss versions introduced a bug that was not present before. I don't know if it was introduced in r990 or r994, but it was definitely not present in r963. When I try to copy a file from the SD adapter in slot B to SD2SP2, and the file already exists, I get a file write error, intead of the prompt to overwrite the file. I don't know if this happens also when copying from other sources or to other destinations. As a workaround, it is possible to first delete the file, and then attempt the copy again.
Thank you for your support.

**Comment by Extrems** [comment]
Fixed in 1c366dc (r999).
