### ISSUE TITLE
Emulation Swiss save limit.

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#452]
I have every ISO of every Gamecube game and using a 256 Gb Sandisk Micro SD card for game saves. After getting game saves set-up for 131 games it said during several different games after 131 saves, that there was no more room on the Memory Card but still had tons of room on the SD Card.

**Comment by Extrems** [comment]
The memory card filesystem is limited to 127 files. We had no part in this technical decision, Nintendo did.

**Comment by GAMECUBE-N64** [comment]
Well Thank You on that. Ashame more Emulated cards cant be on the same sd card. But I decided I am going to Divide up the US/Japan ones I want on 2 SD cards, and Pal ones I really like a 3rd. Then the rest of the game cube isos been those ones are not hard for emulation I will be playing those on my Nvidia Shield Android TV 2015 500 GB Pro. Thank You again.

**Comment by Extrems** [comment]
It's already divided up by region.

**Comment by GAMECUBE-N64** [comment]
I know that and I wasn't talking about regions. I was talking about how many game saves I can have per card and how many I am gonna have for my Gamecube and the rest I will play on My Nvidia TV.
