### ISSUE TITLE
Regarding Memory Card Emulation

### ISSUE THREAD

**Issue by Zabuza825** [emukidid/swiss-gc#460]
Apologies if this is the wrong place to put this, I just am not sure where to put suggestions.

I'm no programming expert so I don't know how much work this would require, but I was just thinking that at the moment memory card emulation is restricted to either:

GCLoader + SD card adapter
DVD + SD card adapter

I understand that reading disks from the same device and writing to that device is not at the moment supported, and that is fine.

I was just wondering if it would be possible to have memory card emulation in a different way. Namely, an SD2SP2 and SDGecko.

As in, load games from the SD2SP2 and have the memory card be emulated on the SDGecko.

I'm not sure how difficult this would be to implement, and honestly if it would be too difficult it might be best to not bother, but it was just an idea I had. For all I know successfully implementing this could be just as difficult, if not more, than just having the saves be on the same device.

Again, I apologize if this is the wrong place to put this. I just wanted to voice my thoughts.

Everyone working on this has done some wonderful work and I look forward to future updates! You all are awesome!

**Comment by Extrems** [comment]
That'd be more difficult.

SD Card Adapter is supported in master, but using the old synchronous I/O at the moment.

**Comment by Zabuza825** [comment]
Ah okay, again it was just an idea.

Thank you for taking the time to reply to this!
