### ISSUE TITLE
24bit Color Option?

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#461]
The Gamecube normally outputs 16bit color most of the time and so I thought maybe it could be possible to use Swiss to force 24bit color on games for a higher quality image.

**Comment by Extrems** [comment]
16 bpp? That's only when MSAA is used, which is exceedingly rare.

I think you mean 6 bpc (18 bpp, if you ignore the alpha channel), which happen when the game needs a stencil buffer.
There's nothing we can do about that.

**Comment by GK6475** [comment]
Ok then. Just wanted to see if it was possible.
