### ISSUE TITLE
Config file failed to save with WiSD Memory Adapter in Slot B

### ISSUE THREAD

**Issue by statusquo1** [emukidid/swiss-gc#466]
Recently got my Gamecube successfully set up with SWISS and GC Loader installed. I have an official Gamecube memory card in Slot A which has been able to save games. I also have a WiSD Memory Adapter card with a 2GB Sandisk card inserted into Slot B.  I don't have anything installed on that SD card in the WiSD adapter. I formatted it for FAT16 (the only option I saw as it's less than 4gb).  I've also tried 2 other brands of SD cards (Lexar 8GB and Lexar 16GB) with no luck either.

I've tried to edit Device Compability settings in Swiss Global Settings.  But each time it gives me a "config failed to save" message. I've tried setting to both SD Card - Slot B and also to IDE-EXI - SLOT B. Neither options seem to still allow me to save SWISS settings.

Trying to figure out if I'm missing something quite obvious.

**Comment by Takumoru** [comment]
So you can read files no problem?
And are you able to write other content to the SD through the Gamecube?
For instance using memory card emulation or backing up saves using Swiss or GCMM?
If not, I'm thinking there's always the possibility of a faulty WiiSD (SD Gecko) adapter.

**Comment by emukidid** [comment]
Did you figure this out? If not, please re-open with more detail.
