### ISSUE TITLE
Starfox Adventures black screen/reset

### ISSUE THREAD

**Issue by rebrove** [emukidid/swiss-gc#475]
I just installed a GCLoader in my Gamecube and placed the most recent 1026 release on it. I am using a 256gb Sandisk in the GCLoader for games and GBI and a 4gb Sandisk in a memory card adapter to store Swiss settings. Everything works out fine except for Starfox Adventures. I've tested three different rips, including one I freshly created with Cleanrip on my Wii, and was getting nothing but a black screen after it was loaded, but that has progressed to Swiss restarting after attempting to load the DOL. Reverting back to 994 allows the game to work without issue. All other games I have tested work fine on 1026 release.

**Comment by Extrems** [comment]
Fixed in 867d626 (r1036). I'm so sorry for this.
