### ISSUE TITLE
Using memory emulation with the sd2sp2

### ISSUE THREAD

**Issue by InofficialPlaytester** [emukidid/swiss-gc#480]
I tried the new update, and enabled the memory card emulation, to use the sd2sp2 for saves. Its a 64gb card, and for testing I started RE1. It has been "Accessing" it for an hour now. I think it may be slowly going through the entire card, or it crashed. I don't know how this works, and I'm pretty new to swiss, but is it possible to limit the space reserved for saves? I also tried animal corssing, but it wanted to reformat my card, which already is FAT32 formated. Can I do anything about this in the settings or will it be addressed in future updates?

**Comment by Extrems** [comment]
This is low-level emulation of a memory card. The images are currently not preformatted, so it's normal for games to ask to format.
