### ISSUE TITLE
PAC-MAN World 3 Cannot Initialize Memory Card

### ISSUE THREAD

**Issue by Aarmaster11** [emukidid/swiss-gc#482]
Upon attempting to boot PAC-MAN World 3 from SD2SP2, the game loads just fine but cannot initialize the memory card and cannot save/load any games. I'm using the latest release (r1026).

[Video](https://www.youtube.com/watch?v=gHVcejPwgJI)

**Comment by Extrems** [comment]
Cannot reproduce.
