### ISSUE TITLE
X-Men Legends Fails at Mystique encounter

### ISSUE THREAD

**Issue by GabeShack** [emukidid/swiss-gc#483]
At beginning of xmen legends (gc-loader) when you get to where Mystique is pretending to be cyclops, the game freezes and says an error occurred and to power off and look at the manual for support.

Edit: Tried with Swiss 1047 same result. 

![IMG_0536](https://user-images.githubusercontent.com/53574780/109401203-42feba00-791b-11eb-91dc-f1a5af25a100.jpeg)
![IMG_0537](https://user-images.githubusercontent.com/53574780/109401204-45f9aa80-791b-11eb-9f99-e638a414fbdf.jpeg)
![IMG_0539](https://user-images.githubusercontent.com/53574780/109401206-4a25c800-791b-11eb-8d94-10c61b94dafc.jpeg)

I can try get a different rom file to test with.

**Comment by Extrems** [comment]
Fixed in a430b74 (r1048).

**Comment by GabeShack** [comment]
Hey @Extrems 
Would I be able to test using a430b74 r1048? Is there a beta release link I’m missing or would the commit to the master have included this in the current release?
