### ISSUE TITLE
Question about virtual Memory card.

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#486]
If virtual Memory card produces 2 simulated memory cards, how many game saves total would be possible on those 2?

**Comment by Extrems** [comment]
Their file systems have a hard limit of 127 files.

**Comment by GAMECUBE-N64** [comment]
So is this that 127 games per each memory card or the 2 of them together? Thank You. 😁

**Comment by Extrems** [comment]
A game may use many files. It is per memory card, and you have a set of two for Slot A & B per region.
