### ISSUE TITLE
Issue with reading sd2sp2 and saving config to sd2sp2 with GCLOADER.

### ISSUE THREAD

**Issue by WilliamDingler** [emukidid/swiss-gc#488]
There is a persistent issue with using the sd2sp2 as a config device for the GCLOADER. I have tried multiple micro sd cards of various sizes and speeds and brands. Each sd card was formatted to exFAT and fat32. I have also tried MBR partition schemes of the micro sd cards and GPT. In all situations, swiss fail to save the config file and read from sd2sp2. This sd2sp2 was purchased from castlemaniagames to ensure the proper board thickness was adhered to.

**Comment by emukidid** [comment]
Can you provide more information on the SD card brand/size. Can anything at all (emulators, other homebrew) read from them on the GameCube?

**Comment by WilliamDingler** [comment]
I haven't tried any other program to try reading them. The sd cards are all micro sd cards. The first is a very old 4gb class1 SanDisk sd card. This one is notable for being compatible with dreamshell on the Dreamcast, as such, I have used it for bios flashing.  The second is a 32gb class 4 Sandisk. The final one is an oddball brand Netac 32gb class 10 from amazon. All have been tested and verified with fakeflashtest v1.1.2.

**Comment by WilliamDingler** [comment]
Additional info. My gamecube is ipl v1.0, with pink bios.

**Comment by emukidid** [comment]
So what you're saying it doesn't read or write at all, can you browse the device at all? If not, it could be that the serial port itself is dirty/dusty.

**Comment by WilliamDingler** [comment]
I tried cleaning with alcohol, but that didn't work. I followed up with deoxit and that didn't work. Depending on the card it may try to access it and then fail to write config. I have also tried pushing the sd2sp2 to one side or the other when boot, but this shouldn't be required as the pcb should have been made to proper dimensions by castlemania games. Aside from reflowing the sp2 connector, I have tried everything. I have purchased a sd gecko, but it will take some time to arrive.

**Comment by WilliamDingler** [comment]
Update I just reflowed the capacitor and micro sd card slot on the sd2sp2, no change. It sounds like my gamecube is the only one having problems. I tried another sandisk card, 16gb class 4. No change.

**Comment by WilliamDingler** [comment]
I reflowed the sp2 connector and it didn't change. This either a problem with pink bios Gamecubes or just my Gamecube.

**Comment by WilliamDingler** [comment]
I reflowed the sp2 connector and it didn't change. This either a problem with pink bios Gamecubes or just my Gamecube.

**Comment by emukidid** [comment]
Cannot reproduce.
