### ISSUE TITLE
How do I set boot sound?

### ISSUE THREAD

**Issue by Knightsurfer** [emukidid/swiss-gc#490]
Sorry if I happen to be blind but I cannot find info anywhere on how you set the boot sound on your second latest update.
also is there multiple boot sounds you can set? I noticed my hold z boot is also muted.

**Comment by Extrems** [comment]
"Boot through IPL" under "Advanced Settings" now has "Sound 1" and "Sound 2" as options.

**Comment by Knightsurfer** [comment]
Neat ^ ^ I'm gonna hold off updating till you reenable memory card B but did you know sound 0 and sound 1 don't play correctly?
again you may of fixed that in a later version but just incase you didn't catch it. also will it ever be possible to set custom jingles dya think?

Setting the colour of the cube logo would be cool too but I imagine that's too hardcoded. :P

**Comment by Extrems** [comment]
Assuming you're using memory card emulation, you need to use v0.5r1047 or later for sounds to not get dropped, as asynchronous read was only introduced in this version forward.
You can use both Slot A & B if you use a SD2SP2.
