### ISSUE TITLE
The ability to rename files would be handy if possible.

### ISSUE THREAD

**Issue by Knightsurfer** [emukidid/swiss-gc#491]
I have an issue with one of my games with real memory cards without swiss, my Pokemon Colosseum disc corrupts the memory card when you get to the final phase of the game, issues like that make me think either renaming/switching out memory cards would be nice just incase the same happens without a disc, 

Also it would be neat if you can implement Dolphin's compression method for roms, though I imagine the reason why you haven't as of yet is probably due to the possibility of slowing down read speed.

also I may be wrong, but do games have a tiny bit of input lag through swiss? it feels like it but can't be sure,
talking about read stuff, is there a toggle for audio streaming? just the intro for smash bros melee is all out of whack,
dunno if it matters but I'm using the SPSD slot on the bottom to read iso's.

**Comment by Extrems** [comment]
> Also it would be neat if you can implement Dolphin's compression method for roms, though I imagine the reason why you haven't as of yet is probably due to the possibility of slowing down read speed.

We don't have enough memory to support GCZ nor RVZ.

> talking about read stuff, is there a toggle for audio streaming? just the intro for smash bros melee is all out of whack,
dunno if it matters but I'm using the SPSD slot on the bottom to read iso's.

Are you using memory card emulation? Asynchronous read was only just introduced in v0.5r1047. You're back to where we were before August otherwise.

**Comment by Knightsurfer** [comment]
> Are you using memory card emulation? Asynchronous read was only just introduced in v0.5r1047. You're back to where we  were before August otherwise.
>>
yeah I'm emulating memory cards, and yeah, gonna update my swiss now.
rather impressive what you guys have achieved I must say. ^ ^

**Comment by Extrems** [comment]
No version of Super Smash Bros. Melee use streaming audio.

**Comment by Diegorella** [comment]
about the title of this post
in fact, the SWISS file management feature is an old order.
Create directories
Compile directories
Exclude directories
Rename and edit files and directories.

**Comment by JinxDojo** [comment]
I agree that some more basic file management is needed--especially creating directories and renaming. Out of curiosity: is there an on-screen keyboard available or is that one of the main things holding this back? If so, perhaps a simple "append datetime to directory/file name" will suffice for renaming--I know it'd help my situation:

I also requested #547 which would enable users to copy their emulated memory card files in order to back them up.

**Comment by emukidid** [comment]
The ability to rename files/folders on FAT based devices has been added in bd05320aae86a51cfda25abd60728489737a046a.
