### ISSUE TITLE
GNED78 - Finding Nemo (Findet Nemo) does not work with swiss_r1026 and r1047

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#494]
**Finding Nemo** - size: 1459978240, CRC: 80C21A71, MD5: F7E01141CA1F1F30A20AB865BE952763, SHA1: 25EE447324591BD6210D813BA71F1F21303ED422
works great with **swiss_r994 (compressed .DOL version)**.

![vlcsnap-2021-03-08-21h22m26s559](https://user-images.githubusercontent.com/77854382/110377678-fc186f00-8054-11eb-9c7e-d0dd9b3a0545.png)
![vlcsnap-2021-03-08-21h22m39s375](https://user-images.githubusercontent.com/77854382/110377679-fcb10580-8054-11eb-8c88-4eaeda077414.png)
![vlcsnap-2021-03-08-21h22m53s701](https://user-images.githubusercontent.com/77854382/110377681-fd499c00-8054-11eb-9456-8de549d2af1a.png)
![vlcsnap-2021-03-08-21h23m01s056](https://user-images.githubusercontent.com/77854382/110377685-fe7ac900-8054-11eb-90a7-c062414ee104.png)
![vlcsnap-2021-03-08-21h23m04s481](https://user-images.githubusercontent.com/77854382/110377687-ff135f80-8054-11eb-92d1-d726f65211d4.png)
![vlcsnap-2021-03-08-21h23m12s696](https://user-images.githubusercontent.com/77854382/110377658-f6bb2480-8054-11eb-96af-dc5ab0814eab.png)
![vlcsnap-2021-03-08-21h23m18s356](https://user-images.githubusercontent.com/77854382/110377660-f753bb00-8054-11eb-9db7-70b3fcafe378.png)
![vlcsnap-2021-03-08-21h23m40s260](https://user-images.githubusercontent.com/77854382/110377661-f7ec5180-8054-11eb-9ce7-0252133728f8.png)
![vlcsnap-2021-03-08-21h23m51s136](https://user-images.githubusercontent.com/77854382/110377663-f884e800-8054-11eb-8e9e-390d55715e13.png)
![vlcsnap-2021-03-08-21h24m06s824](https://user-images.githubusercontent.com/77854382/110377667-f884e800-8054-11eb-83c9-2731072b520c.png)

The finding nemo main screen just works in **swiss_r994 (compressed .DOL version)**:
![vlcsnap-2021-03-08-21h24m30s213](https://user-images.githubusercontent.com/77854382/110377671-f9b61500-8054-11eb-8449-364f8266b47b.png)

Booting Finding Nemo with **swiss_r1026 (compressed .DOL version)** and **r1047 (compressed .DOL version)** results in just playing the intro videos, but the main menu does not appear and there is a black screen and/or the gamecube reboots.

I already tried to delete everything except the finding nemo.iso from the sdcards (Slot B, SD2SP2).
I did also remove the swiss settings file to get a "clean" environment for swiss_r1026 and r1047 but nothing helps.

**Comment by Extrems** [comment]
Fixed in 52cea9c (r1051).
