### ISSUE TITLE
Nintendo GameCube Service Disc Version 1.0-03 (USA) is not working

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#495]
Nintendo GameCube Service Disc Version 1.0-03 (USA).iso - 536dba21b557c8d8cd8292534cfaa260

![vlcsnap-2021-03-08-21h57m24s976](https://user-images.githubusercontent.com/77854382/110387836-7e5b6000-8062-11eb-963d-bab56c6a15bd.png)
![vlcsnap-2021-03-08-22h03m13s565](https://user-images.githubusercontent.com/77854382/110387858-874c3180-8062-11eb-92e7-38ee6dff010d.png)
![vlcsnap-2021-03-08-22h03m18s427](https://user-images.githubusercontent.com/77854382/110387866-89ae8b80-8062-11eb-9441-31006c2657a6.png)
![vlcsnap-2021-03-08-22h03m20s324](https://user-images.githubusercontent.com/77854382/110387871-8c10e580-8062-11eb-84d7-717faf5f1f55.png)
![vlcsnap-2021-03-08-22h03m32s864](https://user-images.githubusercontent.com/77854382/110387917-9b902e80-8062-11eb-8a66-1761bf13d3b0.png)

It seems to be the 408th .DOL file is the last one before swiss brings out a too fragmented error message.
![vlcsnap-2021-03-08-22h09m23s143](https://user-images.githubusercontent.com/77854382/110387953-a9de4a80-8062-11eb-907d-66bf2cc707d4.png)

After this, some kind of graphical glitches with the progressive bar appear.
![vlcsnap-2021-03-08-22h09m38s187](https://user-images.githubusercontent.com/77854382/110388062-d2fedb00-8062-11eb-8a61-9fe21a87cfd9.png)

![vlcsnap-2021-03-08-22h10m12s324](https://user-images.githubusercontent.com/77854382/110388078-d6926200-8062-11eb-98b3-a2fcbd77820e.png)

swiss r1047 is used.

**Comment by Extrems** [comment]
Yeah, I doubt it'll ever be possible to make this work.
