### ISSUE TITLE
Memory card emulation through network

### ISSUE THREAD

**Issue by SBRK** [emukidid/swiss-gc#496]
I don't know if that would even be possible, but having the ability to save or to import memory cards through the network would be really nice. I juggle between playing on Dolphin and on the real hardware, and having the ability to have a single save for both would be very nice.

**Comment by BorgNumberOne** [comment]
You can use a FSP server (www.720k.net --> FSP Server Software --> FSPd ; https://github.com/GoobyCorp/fspd) or a FTP server on your PC which is running Dolphin Emulator . Furthermore you can define the FSP/FTP upload directory to the place where your Dolphin Emulator stores its emulated memory card file.

So, you can copy the emulated memory card file from your swiss'ed GameCube to your Dolphin Emulator PC and vice versa.
You can also copy single .cgi savestates from real memory card to your Dolphin Emulator PC.
