### ISSUE TITLE
Patch for two disc games Tom Clancy's Splinter Cell

### ISSUE THREAD

**Issue by Diegorella** [emukidid/swiss-gc#497]
**the two-disc games in the Series:
Tom Clancy's Splinter Cell Double Agent and
Tom Clancy's Splinter Cell Chaos Theory
are not working for the second disc. it is impossible to finish them by the Swiss from the last revision.**

**Comment by Extrems** [comment]
Fixed in 220ab1e (r1355).

**Comment by retrofank** [comment]
I just had a look at this and booted disc 2 of Double agent using the latest 1400 build with a GCloader (full size redump iso).   Started a new game and it hung on a black screen when switching to disc 1 automatically.   I tried other disc 2 titles like MGS TS and that worked by auto switching to disc 1 after loading disc 2 and starting a new game.

**Comment by Extrems** [comment]
Make sure you have a working patch device.
