### ISSUE TITLE
F-Zero AX

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#507]
In 2013 it was discovered that F-Zero GX for the Gamecube also contains the full arcade F-Zero AX game.

This patch will make your F-Zero GX .iso boot directly into that hidden version without the use of codes.

Use https://www.romhacking.net/utilities/704/ or any other xdelta utility to patch your iso!

Based on the main.dol patch by Ralf from the now defunct GSCentral.

It is on this site. https://www.romhacking.net/hacks/5779/

**Comment by Extrems** [comment]
I'm not sure what you're asking of us.

**Comment by GAMECUBE-N64** [comment]
Wasn't asking anything. Just posted incase any one wanted F-zero Ax for
there Swiss modded Game cube.
