### ISSUE TITLE
The Italian Job.

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#510]
It has a glitchy screen. At the main menu after start. I have seen other Gamecube games where it is glitchy ,but manageable. This is really frustrating because You can't even see where You save Your settings.
Scroll to the right to options and You will see what I mean.

**Comment by Extrems** [comment]
I don't see what you mean.
![Screenshot](https://files.extremscorner.org/gamecube/screenshots/GIBE4F.PNG)
![Screenshot](https://files.extremscorner.org/gamecube/screenshots/GIBE4F-2.PNG)

**Comment by GAMECUBE-N64** [comment]
So let's see Your Swiss Settings for It. Because on my mine all I get is a flickering screen. Goes from normal picture to black screen and then flickers and does again, nonstop or sticks to black screen. I get this sometimes. On some other games. But not as frustrating as this one. So please tell us how Yours is perfect. Would really like to know. I been playing video games since pong and many systems. Supported myself for many years until I joined the Army after 9/11. Going to be 49 in June. Been married for 12 years and own our own house. And been a Father to my 2 nieces since they were kids because there real parents are garbage. I have no reason. To lie and I have no reason to 🐂Shit! And I have helped the creator of Mupen64FZ several times and that's why it's playing a lot more N64 games that it wasn't playing before.

**Comment by Extrems** [comment]
It works with the default settings.
