### ISSUE TITLE
in game reset reboot setting broken

### ISSUE THREAD

**Issue by MrFilz** [emukidid/swiss-gc#516]
With the new Swiss v0.5r1060 the in game reset option reboot gives me an error from the Gamecube. An error has occured, please turn of your gamecube. It is consistend with every try. Worked before, it was the only way to reset the system and go back to swiss without issues. Igr.dol gives me a black screen and nothing more with some games... I have a PAL Gamecube with GCLoader, and a SP2SD2 both equipped with new sandisk sd cards.

**Comment by Extrems** [comment]
Make sure your initial disc is named boot.iso with no hidden extension.

**Comment by MrFilz** [comment]
I erased the boot.iso file on my sd card, copied over the pal iso again, renamed it again to boot.iso, and now it works. Very strange...  sorry, i guess it was my fault somehow. Thanks for the gun patch, maybe you can do something for the pal release of Baldurs Gate, so that the conversation text is on screen, otherwise i will stick to the ntsc version. Thanks a lot for your great work, i love swiss in combination with the gcloader, the component cable and the ossc. it is simply amazing!

**Comment by Extrems** [comment]
Why aren't you simply using the provided boot.iso file?
Forcing 576p instead of 480p should fix your issue with Baldur's Gate: Dark Alliance.

**Comment by MrFilz** [comment]
I really dont know... I could i guess. I used always the provided pal.iso because i have a pal system. I should try that, thanks!
