### ISSUE TITLE
Cheats are no longer working

### ISSUE THREAD

**Issue by a-kohout** [emukidid/swiss-gc#521]
With Swiss rev 1085, widescreen patches/cheats do not work. With the patch loaded, the game doesn't recognize an existing save file (on physical card in slot A) and asks if it should create a new save file. Without the patch loaded, the game does recognize the save file.

So far I've noticed this issue with the following games:
GL8P4F Tomb Raider Legend PAL English
GM4P01 Mario Kart: Double Dash!! PAL
GP6P01 Mario Party 6 PAL
GZLP01 The Legend of Zelda: The Wind Waker PAL

With rev 1060, the following patches work fine and the games recognize the save file (with or without the widescreen patch loaded).

[GL8P4F.txt](https://github.com/emukidid/swiss-gc/files/6415110/GL8P4F.txt)
[GM4P01.txt](https://github.com/emukidid/swiss-gc/files/6415111/GM4P01.txt)
[GP6P01.txt](https://github.com/emukidid/swiss-gc/files/6415112/GP6P01.txt)
[GZLP01.txt](https://github.com/emukidid/swiss-gc/files/6415113/GZLP01.txt)

**Comment by nutstool** [comment]
I've also noticed this issue and found that none of my cheats work anymore on r1085 for any game. I was previously using r963 and they worked fine. I've re-tested by reverting to r963 and cheats are now working again.

**Comment by emukidid** [comment]
Fixed in 993e6fde93b883273d19b00399ae6caa719f166d
