### ISSUE TITLE
Resident evil code veroniva intro fmv skiping

### ISSUE THREAD

**Issue by wem2977** [emukidid/swiss-gc#522]
After starting the game and after the text scroll the fmv has audio issues, Tried many sd card and redump iso, nkit etc but same issues

**Comment by Glazeddberrie** [comment]
Same problem over here. I tried with emulating the reading speeds but even with that the fmv stutters a lot.

**Comment by SlowCatalyst** [comment]
What type of SD is being used?

**Comment by wem2977** [comment]
Hi

Tried many different ones, speeds , formats fat ,fat 32 NTFS , san disk
urtra standard etc..

However the pal version of the game does not have the intro fmv stuttering.

Hope that helps

**Comment by Glazeddberrie** [comment]
> What type of SD is being used?

Hi, im using this SanDisk SD https://www.amazon.com/SanDisk-Ultra-microSDXC-Memory-Adapter/dp/B073JWXGNT/ref=sr_1_7?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=sandisk+32gb&qid=1631720251&sr=8-7. However i already completed the NTSC-U game and the only fmv that stutters on my swiss revision (1085) is the opening one when you start a new game, i have to try another revision of swiss to see if it's fixed at least. I'll edit this comment if last revision fixed this.
