### ISSUE TITLE
Only 3 cheats working in the Wind Waker 

### ISSUE THREAD

**Issue by Gandoulf49** [emukidid/swiss-gc#528]
Hi all ! I'm Emmanuel, I'm French and I speak not a good English, sorry for that!
But in the Wind waker PAL version, on swiss 1086, only 3 cheats running. What is the problem? 

![IMG_20210509_212705](https://user-images.githubusercontent.com/84013658/117795565-990ea880-b24e-11eb-8563-2dde58759fab.jpg)

Thank you !

**Comment by Gandoulf49** [comment]
It is possible for the next update swiss, for working all the cheats on the Wind Waker ? Thank you. And sorry for my bad English.

**Comment by emukidid** [comment]
Can you upload your .txt file that contains your cheats for this game?

**Comment by Gandoulf49** [comment]
Yes no problem! 

![Screenshot_20210514_003427_com android htmlviewer](https://user-images.githubusercontent.com/84013658/118195869-55818d80-b44c-11eb-92ea-5e49e61e9a38.jpg)

![Screenshot_20210514_003458_com android htmlviewer](https://user-images.githubusercontent.com/84013658/118195877-59151480-b44c-11eb-8e65-c328a653bb3e.jpg)
![Screenshot_20210514_003503_com android htmlviewer](https://user-images.githubusercontent.com/84013658/118195886-5ca89b80-b44c-11eb-8858-b3d1ae5ecb00.jpg)
![Screenshot_20210514_003508_com android htmlviewer](https://user-images.githubusercontent.com/84013658/118195898-603c2280-b44c-11eb-95ea-d7362ccaf217.jpg)
![Screenshot_20210514_003511_com android htmlviewer](https://user-images.githubusercontent.com/84013658/118195907-63371300-b44c-11eb-96c1-f19d867201f7.jpg)

Etc....i'ts a very long list !

**Comment by Extrems** [comment]
I'm guessing it's stopping there because you failed to replace `xx` with proper values.

**Comment by Gandoulf49** [comment]
Only the first three are recognized. Not the ones after.

**Comment by Gandoulf49** [comment]
Ohhh thank you so much!

I replace like that?

" Link Takes Damage Multiplier [Ralf]
C21F49F0 00000003
8061000C 74648000
41820008 1C6300xx
60000000 00000000

xx = Damage Multiplier" 

>


"Link Takes Damage Multiplier [Ralf]
C21F49F0 00000003
8061000C 74648000
41820008 1C630003
60000000 00000000

03 = Damage Multiplier"

?

**Comment by Gandoulf49** [comment]
![IMG_20210514_110545](https://user-images.githubusercontent.com/84013658/118248245-6100a300-b4a4-11eb-85b1-7fc3bcf23398.jpg)

It's good ! Thank you for your help!
