### ISSUE TITLE
Time and Date in Swiss not working when booting via ViperGC Extreme

### ISSUE THREAD

**Issue by antmerino** [emukidid/swiss-gc#530]
In the last version, the Date and Time, Swiss resets to 2001 at 0:0:00, but in the system calendar it's in teh current days. It's as if the swiss didn't show the real time.

**Comment by antmerino** [comment]
I forgot it, I have a viper extreme with swiss put in plugin store

**Comment by emukidid** [comment]
>It's as if the swiss didn't show the real time.

What it really is, is "it's as if the ViperGC Extreme is a strange piece of hardware that gets in the way of Swiss reading the time".

**Comment by Extrems** [comment]
Duplicate of issue #141.

**Comment by antmerino** [comment]
Sorry , don't have any solution? Any advice? Thanks a lot for your work
