### ISSUE TITLE
PAL games on NTSC

### ISSUE THREAD

**Issue by pcaudill3323** [emukidid/swiss-gc#531]
Is there a patch you can make so the PAL games can play on a NTSC console ?

**Comment by Extrems** [comment]
Err, they already work.

**Comment by pcaudill3323** [comment]
they will work but in black and white, not color.

**Comment by Extrems** [comment]
You have 3 options:
1. Set AVE Compatibility to AVE N-DOL. This will output PAL video modes as NTSC 50.
2. Force 480i.
3. Use the Digital AV Out.

**Comment by pcaudill3323** [comment]
tryed, failed, i will try a xeon chip.
