### ISSUE TITLE
Feature to change polling rate of the controller?

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#537]
I noticed that GBI has a way to change the polling rate before launch to reduce latency, so would it be possible to implement this for any GC iso via the game settings? I'm thinking 125hz, 250hz, 500hz, 1000hz.

**Comment by Extrems** [comment]
But why? GBI does it because the buttons on a Game Boy are directly wired to the SoC and their state can be read whenever.

**Comment by GK6475** [comment]
I think it will reduce latency in GameCube games as well, unless the controller is already polled at 1000hz.

**Comment by Extrems** [comment]
What makes you think that?

**Comment by GK6475** [comment]
Well, I changed my keyboard and controller polling rate on my computer from 125hz to 1000hz and it reduced latency by a lot.

**Comment by Extrems** [comment]
Okay? And how does that translate to GameCube?

**Comment by GK6475** [comment]
I think that it might be possible to do the same thing on the console to have the same or similar effect as on my computer.

**Comment by Extrems** [comment]
Do you have actual evidence supporting that claim given how input polling on a GameCube work?

**Comment by GK6475** [comment]
No, I was only wondering if it was possible.

**Comment by Extrems** [comment]
It's certainly possible. Is it useful? I very much doubt so.
