### ISSUE TITLE
Quick access directory feature [Enhancement]

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#539]
I think it would be nice to be able to set a default directory when launching Swiss, so that it is easier to get to your games and/or apps. I have a folder that contains my GC ISOs and it would be nice to boot into it instead of just the root directory, where I usually have to scroll down to get to it, since I have a lot of homebrew applications on the SD card's root.

**Comment by Asteroburger** [comment]
Rename your folder: #GC ISOs and it will be on the top of your folders.

**Comment by GK6475** [comment]
Thank you! It might still be nice to have a quick access bar, though, for multiple folders, like on Windows.

**Comment by Extrems** [comment]
Fixed in b95b2db (r1315).
