### ISSUE TITLE
Shinehax Audio Issue

### ISSUE THREAD

**Issue by vaderag** [emukidid/swiss-gc#541]
High pitched audio when loading via Shinehax

**Comment by magu** [comment]
Ain't this also a likely dupe of #529 ?

**Comment by emukidid** [comment]
Duplicate of #529

**Comment by vaderag** [comment]
Posted this in #529 but if anyone lands here:

I've found a working solution to fix this seamlessly!

Instructions...
Get dolaunch from here: https://github.com/suloku/dolaunch/releases/tag/0.2-dolxz
Stick boot.gci of the standard version onto your memory card to get the DOL to be used with Shinehax
Put Swiss on your SD card (if using SD2SP2 as I am) and rename to autoexec.dol)

Load Shinehax as usual - no terrible beep!
