### ISSUE TITLE
PAL to NTSC

### ISSUE THREAD

**Issue by pcaudill3323** [emukidid/swiss-gc#543]
I wonder can you make a program to change a PAL to NTSC, Their is one but it only works on a few games?

**Comment by Extrems** [comment]
What are you looking for exactly?

**Comment by pcaudill3323** [comment]
I am looking for a program to convert pal games to ntsc, so I can play the pal exclusive games in color on my tube tv.

Sent from Mail for Windows 10

**Comment by Extrems** [comment]
Then force 480i.

**Comment by pcaudill3323** [comment]
tried that.

Sent from Mail for Windows 10

**Comment by Extrems** [comment]
If you're using a PAL GameCube on a NTSC TV, there's nothing that can fix the color encoding.

**Comment by pcaudill3323** [comment]
Using a NTSC Gamecube on a NTSC tv.

Sent from Mail for Windows 10

**Comment by Extrems** [comment]
https://files.extremscorner.org/gamecube/videos/force-480i.mp4

**Comment by pcaudill3323** [comment]
This is the list of game that don’t play in 480i but-ugly martians, cocoto funfair, cocoto kart racer, cocoto platform junper, f1 career challenge, franklin – a birthday, largo winch. Try these and see if yours is in 480i?

Sent from Mail for Windows 10

**Comment by Extrems** [comment]
Butt-Ugly Martians: Zoom or Doom! - Crashes
Cocoto Funfair - Working
Cocoto Kart Racer - Working
Cocoto Platform Jumper - Working
F1 Career Challenge - Working, but the bottom of the picture is clipped
Franklin: Un anniversaire surprise - Working
Largo Winch: Empire Under Threat - Very broken

**Comment by pcaudill3323** [comment]
For some reason these games will not be forced in to 480i, but other games will like conan PAL.

Sent from Mail for Windows 10

**Comment by pcaudill3323** [comment]
Question? When I update to a new swiss in my gc loader game cube do I have to update the sd2sp2 igr.dol file and I use the sd2sp2 to save games will their be an increase in memery blocks in the future?

Sent from Mail for Windows

**Comment by Extrems** [comment]
It's not necessary to use the igr.dol option. You could use the reboot option for a while now.

**Comment by pcaudill3323** [comment]
Cool, how about more memery blocks?

Sent from Mail for Windows

**Comment by Extrems** [comment]
The memory cards are as big as a memory card can be.

**Comment by pcaudill3323** [comment]
No, I am talking about the sd2sp2 and emulate memery card, can you make it bigger than 2040 blocks?

Sent from Mail for Windows

**Comment by Extrems** [comment]
They can't be any bigger. As this is low-level emulation, we're subject to existing limitations.

**Comment by pcaudill3323** [comment]
Ok, bummer.

Sent from Mail for Windows
