### ISSUE TITLE
File Management - Enable viewing/copying hidden files

### ISSUE THREAD

**Issue by JinxDojo** [emukidid/swiss-gc#547]
Currently the "swiss_patches" folder stores the emulated Memory Card files. This makes it impossible to create backups of the memory card using Swiss directly, because Swiss does not by default read hidden files. I would like to request the option to view/copy hidden files.

Some of the features suggested in #491 (rename/make directories) would also be very helpful toward this endeavor.

If anyone has alternative suggestions of how to copy emulated memory cards (using another application perhaps?), I'd be happy to hear those as well.

**Comment by emukidid** [comment]
Added in bd05320aae86a51cfda25abd60728489737a046a
