### ISSUE TITLE
Possible issues with Shadow The Hedgehog

### ISSUE THREAD

**Issue by GabeShack** [emukidid/swiss-gc#548]
Getting errors loading shadow the hedgehog with a gcloader stating possible fragmentation. I still need to try a different rom to verify it’s not a rom issue. Otherwise no other issues with any other rom on the SD card I’m using. 

I wanted to check if anyone else was seeing this issue.

**Comment by Extrems** [comment]
The error has nothing to do with the ROM contents. It's a FAT allocation issue.

**Comment by GabeShack** [comment]
Specific to the game or the gcloader? Or just a general issue with how Swiss addresses FAT?  Sorry for all the questions, I just like to try to understand.

**Comment by Extrems** [comment]
Your file was subject to too much fragmentation to be loaded into our fragment table. The limit is 40 fragments.

**Comment by GabeShack** [comment]
So it’s specific to my SD Card then and the fragmentation of each file therein?
