### ISSUE TITLE
Mario Kart Double Dash PAL Nkit check always fails

### ISSUE THREAD

**Issue by vaderag** [emukidid/swiss-gc#550]
I'm pretty certain this is not actually a swiss issue per se and more of an nkit issue as there seems to be no way to successfully pass verification in nkit with any PAL DD image, so I believe that the nkit database is actually incorrect for Mario Kart
If I ignore the warning in SWISS everything works just as expected with the nkit iso

So, with that in mind, I'm wondering if it's possible to add a way to disable NKIT checks, either on a per file basis (preferred) or even globally?

Thanks!

**Comment by Extrems** [comment]
The database is correct.

**Comment by vaderag** [comment]
> The database is correct.

It's definitely not. I've ripped it on my Wii, I've even downloaded from dubious sources to confirm, no matter what I do the check fails for Mario Kart Double Dash PAL when compressing to NKIT iso

**Comment by Extrems** [comment]
Here are the details for "Mario Kart - Double Dash!! (Europe) (En,Fr,De,Es,It).nkit.iso" as per [dats.site](https://dats.site/custom_system_datslist.php) (not the source used):

> Size: 607,504,384 bytes
> CRC-32: a211edb6
> MD5: be536eae5f13bf025814978c4e81c1ee
> SHA-1: 67d279cd0667598c5cce3e8cbb4cc8060734e390

This matches our database.

**Comment by vaderag** [comment]
> Here are the details for "Mario Kart - Double Dash!! (Europe) (En,Fr,De,Es,It).nkit.iso" as per [dats.site](https://dats.site/custom_system_datslist.php) (not the source used):
> 
> > Size: 607,504,384 bytes
> > CRC-32: a211edb6
> > MD5: be536eae5f13bf025814978c4e81c1ee
> > SHA-1: 67d279cd0667598c5cce3e8cbb4cc8060734e390
> 
> This matches our database.

Agreed. But it's wrong on the NKit database. It's impossible to match it

**Comment by Extrems** [comment]
So you agree and disagree at the same time?
https://github.com/emukidid/swiss-gc/blob/master/cube/swiss/source/nkit.c#L1067

**Comment by Extrems** [comment]
I've verified thrice over, and I could not produce a file that doesn't match the database.

**Comment by vaderag** [comment]
I'm agreeing that Swiss uses the given database correctly, but said database is incorrect for Mario Kart PAL. Everything else I've tested works fine but that is wrong

Given you seem to be making it work somehow for an example check 
https://archive.org/details/EuropeanGamecubeCollectionByGhostware

Whatever I do my checksum matches the once from the file there.

Back to the original ask, can we please either include the checksum above or allow us to disable the check. I'm not really sure the value it adds if the iso works...

**Comment by Extrems** [comment]
The database is generated using a local collection that is verified to match Redump as of July 2, 2021.

**Comment by Extrems** [comment]
The file linked matches Redump and as expected, produces the file present in two independent databases, including ours.

**Comment by vaderag** [comment]
> The database is generated using a local collection that is verified to match Redump as of July 2, 2021.

Back to the original ask, can we please either include the checksum above or allow us to disable the check. I'm not really sure the value it adds if the iso works...

**Comment by Extrems** [comment]
Which checksum? Everything is the same.

**Comment by vaderag** [comment]
> The file linked matches Redump and as expected, produces the file present in two independent databases, including ours.

It really doesn't. 
I've run it and many others through NKit a number of times is every conceivable way and in no way can you match it...

I'm open to explanations why it doesn't match, but if you're telling me that file matches, then I don't understand why it doesn't on mine. Neither does my original rip

**Comment by Extrems** [comment]
Which version of NKit are you using? Earlier versions may produce different results.

**Comment by vaderag** [comment]
> Which version of NKit are you using? Earlier versions may produce different results.

Nkit 1.4 from here: https://gbatemp.net/download/categories/iso-dol-management.171/ which is the latest I can find anywhere...

Using the file on archive.org (so we're comparing apples to apples), I've just run it through the processing app and used the Convert to ISO setting and here is the output:
![image](https://user-images.githubusercontent.com/17175988/124378698-bee28780-dcaa-11eb-9a7a-70e51516efc7.png)

`TimeStamp	Conversion	System	ReadResult	OutputResult	OutputCrc	OutputID4	RedumpMatch	RedumpName	InputSize	OutputSize	FullSize	InputFilename	OutputFilename	MD5	SHA1	Passes	SecondsElapsed	ErrorMessage
04/07/2021 09:32:04	ConvertToNKit	GameCube	VerifySuccess	VerifySuccess	A211EDB6	GM4P	MatchFail		1459978240	607504384	1459978240	D:\Downloads\Mario Kart - Double Dash!!.iso	D:\Downloads\Mario Kart - Double Dash!!.nkit.iso	BE536EAE5F13BF025814978C4E81C1EE	67D279CD0667598C5CCE3E8CBB4CC8060734E390	3 Passes: [ISO] >> [1:To NKit] >> [2:Calc Hashes] >> [3:NKit Verify]	73	
`

**Comment by Extrems** [comment]
I suggest to test your RAM using Memtest86, as it may be faulty.

**Comment by vaderag** [comment]
> I suggest to test your RAM using Memtest86, as it may be faulty.

![IMG_20210704_194522.jpg](https://user-images.githubusercontent.com/17175988/124396275-6b9b2400-dd00-11eb-8760-199683453e0a.jpg)

Only one pass but no issues. Tried on a different machine too. Same result with nkit

**Comment by Extrems** [comment]
Have you put the latest Redump datfile in Dats\Redump\GameCube as you're supposed to?

**Comment by vaderag** [comment]
> Have you put the latest Redump datfile in Dats\Redump\GameCube as you're supposed to?

Erm, no? Where does it tell me that I'm "supposed to" do that? No links to datfiles in the software or on the listing page that I can see?

Everything else verifies with what's included in the package...

**Comment by vaderag** [comment]
Okay, so adding the redump files I get a match. Great! So now I have a checksum to prove something I knew was working matches a database...
But that's not going to change the warning I get on Swiss is it, because the output file is still the same it's just matching the database on my computer now?
 
So... back to the original point... why have this check in Swiss at all?

![image](https://user-images.githubusercontent.com/17175988/124436959-74c2da00-dd6e-11eb-85e2-c7069b7c8b66.png)

**Comment by Extrems** [comment]
> Erm, no? Where does it tell me that I'm "supposed to" do that? No links to datfiles in the software or on the listing page that I can see?

https://wiki.gbatemp.net/wiki/NKit/UserGuide#Getting_Started

> But that's not going to change the warning I get on Swiss is it, because the output file is still the same it's just matching the database on my computer now?

If Swiss really is complaining about this file that you've just made, then there's a bug.
Which device are you loading from, and if applicable, which filesystem?

**Comment by vaderag** [comment]
Well, after testing, despite the output file size being identical, seems the redump file changes _something_ in the output and it's no longer detected as bad
I still think it's over zealous in it's blocking mind... if something is working it's working. But whatever, it's done now
