### ISSUE TITLE
Memory Card emulation (SD Slot B) is disabled when emulate read speed is used. (0.5 r1080)

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#552]
The game tested was Sonic Adventure DX (GXSE8P).

Memory card emulation only functions on this game if IPL boot is enabled and the read speed delay is disabled. I was trying to use cheats (without IPL boot) so I tried several options to see if I could find a workaround, but nothing.

**Comment by Extrems** [comment]
Duplicate of issue #552.
