### ISSUE TITLE
Option to disable nkit warning?

### ISSUE THREAD

**Issue by 60fpshacksrock** [emukidid/swiss-gc#555]
Most games that I trim with nkit (which are mostly Zelda N64 ROM injects) work fine.

But recently I had to double check to make sure one game was trimmed by nkit, and it was.
It is a mod of Paper Mario TTYD call Plus (it is on RHDN). The problem is that even though nkit trimmed the
disc image, Swiss still tells me to use nkit on it. I looked at it in HxD and I can see the nkit text and checksum hashes.

Maybe I am wrong, but I thought I read a while back that these warnings were removed.

**Comment by Extrems** [comment]
Mods must use a different disc revision or game ID than discs in Redump.

**Comment by 60fpshacksrock** [comment]
Thanks for the information. Still would be nice to disable it though.
