### ISSUE TITLE
[Enhancement] Force 608 horizontal pixels

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#559]
In games like Mario Kart: Double Dash and Pikmin 2, the games render at 608x448 internally and output 666x448 externally. I think that an option to force 608 horizontal pixels should be made available for games like these to increase the clarity of the video output.

**Comment by Extrems** [comment]
This already exist as Force Horizontal Scale 1:1. Note that you need to apply the same scaling elsewhere in the video chain.

**Comment by GK6475** [comment]
Thank you.
