### ISSUE TITLE
Backing out of recent menu drops you down to bar

### ISSUE THREAD

**Issue by captainbigbollox** [emukidid/swiss-gc#563]
Commit: 993e6fd rev: 1086

If you press start to summon the recent games list, but then press B to dismiss the recent list, your selection will go down to the bottom menu bar, meaning you have to press B again to get back up to the games list.

Could a change be made so that pressing B to back out of the recent list takes you back to the games list, rather than the bottom menu?

**Comment by emukidid** [comment]
This is fixed in bd05320aae86a51cfda25abd60728489737a046a, there just hasn't been a new release with that in it yet.
