### ISSUE TITLE
Disable dithering odd effect for Twilight Princess

### ISSUE THREAD

**Issue by captainbigbollox** [emukidid/swiss-gc#564]
NTSC US Gamecube (digital out)
GC loader
GCHD MK 2
Verified US nkit image

When playing Zelda Twilight Princess with alpha dithering disabled (either in 4:3 or 16:9) the game screen has an unusual effect.
It appears that the alpha dithering is much reduced over 3/4 of the screen, but the top/left quarter looks different. 
There is a visible difference. It's difficult to describe, but it almost looks like the colour depth is different. It is most noticeable in dark places.

I will attach a pic:
![20210801_150602](https://user-images.githubusercontent.com/88277954/127773803-15aa6509-eb6f-4a5a-82b3-4374e1ba6ce4.jpg)

It's not the screen. 
The same issue is visible when playing on my tube monitor without forced widescreen. 

Thank you!

**Comment by Extrems** [comment]
It's a glimpse of what the game would look like if dithering was disabled entirely. ;)

**Comment by captainbigbollox** [comment]
A glimpse into the future!? ;-)

**Comment by Extrems** [comment]
Nah, this is exactly what this feature was meant to avoid, but the heuristic can only see so much.

**Comment by Extrems** [comment]
Fixed in c186cb1 (r1134).
