### ISSUE TITLE
Controller invert patch for Pokemon Colosseum/XD?

### ISSUE THREAD

**Issue by suchipi** [emukidid/swiss-gc#565]
There is a bug in Pokemon Colosseum and Pokemon XD: Gale of Darkness where in some cases, pushing the left analog stick all the way down will move the character up instead of down. It appears to be related the distance the stick can be pushed; if you push the analog stick down only slightly, you walk down. It's only when it's fully pushed down that the problem occurs.

A user on reddit [reported that switching from a third-party controller to an official Gamecube controller fixed it for them](https://www.reddit.com/r/gamecollecting/comments/17bq7o/question_about_controls_in_pokemon_xd_gale_of/), but for me, the bug happens with one of my official Gamecube controllers, but not another.

To clarify, this isn't a bug in Swiss; this is a bug in the game itself. It happens with the retail disc.

[Some people experienced this in Dolphin](https://forums.dolphin-emu.org/Thread-gc-games-now-have-down-up) and changed the effective radius of their controllers to fix it.
Nintendont users [experienced this too,](https://github.com/FIX94/Nintendont/issues/282) and [a game patch was introduced to fix the bug](https://github.com/FIX94/Nintendont/commit/a960793ce4b61fbe90fc92b8acf9271d2689f99f#diff-f29ea38a475b9dbdd6525f601c2de63a634f5fb0a7e63372bb8d066f52ad2bb5R3371).

I'm not sure what Swiss's policy is on fixing bugs in games themselves, but would you be open to including the same patch Nintendont introduced to fix the issue? Other people might not have multiple Gamecube controllers to try with.

**Comment by Extrems** [comment]
I'm open to fixing certain game bugs. We're already fixing a few.

Is that official controller from recent production runs for Super Smash Bros.?

**Comment by suchipi** [comment]
Awesome! Happy to hear it.

No, it's an old Japanese spice orange controller. Both of the controllers I mentioned are.

**Comment by Extrems** [comment]
Fixed in r1132 (5e621d4) in a generic manner. This should fix any game with the same issue.

**Comment by suchipi** [comment]
Thanks so much!!!
