### ISSUE TITLE
[Enhancement] NTFS Support?

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#571]

**Comment by Extrems** [comment]
Is there any real use for this when we have exFAT?

**Comment by GK6475** [comment]
Isn't NTFS a bit faster?

**Comment by Extrems** [comment]
How? We use a static table at runtime. We don't traverse the filesystem at all.

**Comment by GK6475** [comment]
Oh, I didn't know that it used a static table. I guess NTFS wouldn't change much, then.
