### ISSUE TITLE
Sonic Gems: Sonic the Fighters, Sonic CD, and Sonic R freeze on black screen after selecting game

### ISSUE THREAD

**Issue by boj6987** [emukidid/swiss-gc#572]
As the title says. I'm not sure if it's a Swiss issue or a GC Loader issue, but those three games - Sonic the Fighters, Sonic CD, and Sonic R - after you pick them from the menu and it goes to load that game it freezes on a black screen. The EON is reporting a resolution of either 640x p or 640x0p. I can't remember which right at the moment. Not sure if that bit of information even helps. All the GameGear games and two Genesis games launch fine. As far as I can tell I'm on the latest version of Swiss and the most up to date firmware for the GC Loader.

**Comment by Extrems** [comment]
Do you have an SD card adapter for patches?

**Comment by boj6987** [comment]
I do not at the moment. Do I just need an adapter/sd card? Or do I need to go seek out a patch as well?

**Comment by Extrems** [comment]
You just need an SD card adapter with an SD card in it.

**Comment by boj6987** [comment]
I can probably find one, then. Out of curiosity (not that I'd understand): what is the issue that needs patched?

Also a loaded question: is the whole swiss not being able to write to the GC loader card a swiss thing? Or a GC Loader thing? Asking because I saw one of the update notes saying "basic gc loader support added" but it still doesn't do it.

**Comment by Extrems** [comment]
It's just something inherent to how Swiss functions and does.

You need the 2.0.0 firmware update to see any changes, although patch fragments on the device haven't been implemented yet.

**Comment by boj6987** [comment]
Gotcha. Don't know that I saw the 2.0.0 firmware on the GC Loader site, but I appreciate the help very much! :)
