### ISSUE TITLE
Some games say that they aren't playable but worked fine in the past

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#576]
The Mario Kart 64 iso for GameCube loaded fine in older versions of Swiss but now Swiss prevents me from even launching it, telling me that the game is "unplayable". It works fine, though. It would be nice to have an option to disable this message and the other one that says that the game is playable but needs to be recovered with Nkit.

**Comment by Extrems** [comment]
We do not support hijacking of game IDs present in Redump. Use a non-colliding game ID or disc revision.
