### ISSUE TITLE
Zapper

### ISSUE THREAD

**Issue by g5star** [emukidid/swiss-gc#577]
After completing the first level. The games goes back to a loading screen and then freezes. I tried loading from the SD card in the GCLoader , from the SD2SP2 SD card and from a Gecko SD card. All have the same results. I am running Swiss 0.5 r 878 with SD2SP2.

**Comment by Extrems** [comment]
r878 was a year ago. Can't you test with something newer?...

**Comment by g5star** [comment]
yes I missed wrote. I am using Swiss v0.5r1138. Sorry.

**Comment by Extrems** [comment]
It's a race condition with a zero-length read. Additionally, the game has a disc read error when clean booted through the GC Loader.

**Comment by g5star** [comment]
So, is there anything one can do to get it to fully work on the GC Loader or will I just have to play it on my Wii with the miniDVD?

**Comment by Extrems** [comment]
I already have a fix, just be patient.

**Comment by Extrems** [comment]
Fixed in f144537 (r1154).

**Comment by g5star** [comment]
Ok, since I'm such a noob. What I understand is that I need to wait for Swiss release of R1154. Is that correct? Or is there something that I am missing and I can get it to work now?

**Comment by g5star** [comment]
By the way. Thank you for helping me and everyone else.

**Comment by Extrems** [comment]
As this is open source software, you could compile the latest changes yourself, but I've gone ahead and cut a release now.

**Comment by g5star** [comment]
Your the best. Just got  the new swiss update.
