### ISSUE TITLE
Virtual memory doesn't support Super Smash Bros 20XX and cause a crash

### ISSUE THREAD

**Issue by Leandro1602** [emukidid/swiss-gc#581]
I was attempting to create a virtual memory through the latest release v0.5r1154 and use it to play a modified version of Super Smash Bros Melee called "20XX"  which uses the same ID of the original release "GALE01". Somehow, the save file always fails to create and corrupts the virtual memory somehow. This also happens with another modified version called "UnclePunch Training Pack" for the same game with ID "GTME01"

I don't know if this is intended behavior or a bug, but I thought of reporting it regardless.

![image](https://user-images.githubusercontent.com/62114107/133214002-6e788b25-aed8-467a-9883-d037ba3e950f.png)
![image](https://user-images.githubusercontent.com/62114107/133214151-99a354ab-cc74-4345-9341-67b205cd0c39.png)

I can provide a copy of the save file in case it's needed.

**Comment by Papy-G** [comment]
It's a long known issue: 20xx hacks just interfere with Swiss's patches.

**Comment by Extrems** [comment]
Cannot reproduce.
