### ISSUE TITLE
high resolution video mode(s?) (e.g. 960i) will be ignored in Default / Current Game Settings and different Games crashes now

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#582]
![GameCube-swiss-rev-1154-issues](https://user-images.githubusercontent.com/77854382/133344703-3b64485c-f1f3-4a0d-b90c-bf2322af460e.png)

After setting video mode to: "960i" or other higher resolutions in:
"Default Game Settings"
and after starting a Game ("Loading BS2") it seems to be that all games crash; no sound, no video - neither digital(gcvideo) nor analogue.

In earlier swiss releases I could enjoy 960i and 1152i and other resolutions (Pikmin 1 / 2, Final Fantasy etc...).
Furthermore: if I did change AVE compatibility settings in earlier swiss releases, I could get more/other high resolution modes for different games. And many of them worked well.

Hint:
(Noname- or Amazon-) CCTV or BNC 10''...19'' monitors/TVs with HDMI input or epiphan (or other) HDMI/DVI-Capture devices are able to display any exotic HDMI-resolutions wich are comming from GCVideo.

Furthermore, if I set the resolution in: "Current Game Settings" to: "960i", then the current swiss release will also ignore the settings and it also uses: "1152i" instead. Games do also crash.

**Comment by Extrems** [comment]
960i and 1152i are not compatible with boot through IPL. The IPL has a OSPanic when field rendering is enabled.
