### ISSUE TITLE
system info not corrected

### ISSUE THREAD

**Issue by toxic9** [emukidid/swiss-gc#583]
Hi,

I have a green Gamecube (Tales of Symphonia version).
This model is a DOL-001, but on swiss system information "i" it is detected as DOL-101.
I think there is a bug on the way swiss detects the system info...

**Comment by Extrems** [comment]
That's curious. It would imply a newer revision Gekko slipped into DOL-001's.

**Comment by Extrems** [comment]
Could you dump your `ipl.bin` and give me its CRC-32?

**Comment by toxic9** [comment]
Hi!

The CRC-32 is: AD1B7F16
It's a PAL bios v.1.2

**Comment by Extrems** [comment]
I'm afraid your system is completely indistinguishable from a DOL-101 from our perspective.

**Comment by emukidid** [comment]
Just to confirm, which ports does your GameCube have? Does it have Serial Port 2 and Digital AV Out?

**Comment by Extrems** [comment]
Other details such as the disc drive's firmware version and whether the unit was made in China would also be appreciated, even if they won't help your issue.

**Comment by Diegorella** [comment]
the same video game
at 0.5 (imagen 1)

 and in the 0.3 swiss version. (imagen 2)

My Dol 101 USA,
appears as a Dol 001




![This is and imagen](https://scontent.fudi1-1.fna.fbcdn.net/v/t1.6435-9/243327508_1035699043893307_8473832070177484628_n.jpg?_nc_cat=109&ccb=1-5&_nc_sid=8bfeb9&_nc_eui2=AeGVtd7BLTE1Kt2J9JQS_0x6hGwGA1PgmcKEbAYDU-CZwqi7XhPh76L3VJBsayHAGPHRfqV6owLh3MWznafsGM0F&_nc_ohc=5D2k9cnA6GkAX_4uIny&_nc_ht=scontent.fudi1-1.fna&oh=46da886f7185f94b25b3188944735cd4&oe=617B36C0)




![This is and imagen](https://scontent.fudi1-1.fna.fbcdn.net/v/t1.6435-9/243345502_1035699060559972_8961691559170967554_n.jpg?_nc_cat=102&ccb=1-5&_nc_sid=8bfeb9&_nc_eui2=AeEDa5TpKrnX_bT0r4tZB1izN0_giPELYsM3T-CI8Qtiw9cpIDuqvJAO6m3U11bw1rhRGMy4qnI5Eps8dOmGaujN&_nc_ohc=FRb8qZ8T3CwAX8yrjBa&_nc_ht=scontent.fudi1-1.fna&oh=5c0978ddd5bee82bfc5733977db3a8b5&oe=617E3136)

**Comment by toxic9** [comment]
I installed a viper on it. It's a standard revision A mobo. It has sp2 and digital output. nothing special about it.
I checked your code. You are checking system version based on bios hash.
I don't think this is 100% accuracy.

**Comment by Extrems** [comment]
You'd have to have a DD 4.0 Gekko instead of a DD 2.4e for it to be detected as a DOL-101, which is very much special.
This combination of components makes your system indistinguishable from a DOL-101.

**Comment by Diegorella** [comment]
For me:

DOL CPU 50-
STILL APPEARS AS
DOL 001

v0.6r1236
