### ISSUE TITLE
Rainbow Six 3 - Black Screen

### ISSUE THREAD

**Issue by earthprime** [emukidid/swiss-gc#584]
Rainbow Six 3 drops to a black screen (resolution drops to 0) upon loading the first stage.  This happens with both composite cables and HD cables (via HDMI adapter).  The issue is either Swiss or GCLoader.  Composite cables were used on a Commodore64 monitor (from 1983), so issue is verified to not be caused by modern displays.

**Comment by Extrems** [comment]
Cannot reproduce. Possibly a duplicate of issue #420.

**Comment by earthprime** [comment]
Updated with detailed steps to reproduce - posted in issue #420.

**Comment by Extrems** [comment]
This is not a supported hardware configuration. Use clean boot (L+A) if necessary.
