### ISSUE TITLE
Tube Slider not saving to SD2SP2

### ISSUE THREAD

**Issue by KevW7** [emukidid/swiss-gc#587]
Hi, I’ve been playing Tube Slider on my GameCube and for some reason I can’t create a save using a virtual memory card.  I get the error message “The file could not be created” I then get the message that the memory card is damaged and can’t be used (but I can delete the save OK). I was wondering if you had any ideas?

I’m using Swiss 0.5 commit 993e6fd Rev: 1086. I’m booting my games off of an SD card using GC loader but am using an SD2SP2 with a second SD card for my saves.

**Comment by Extrems** [comment]
I had 54 saves, so I don't think that's the issue.
The error suggests a write timeout occurred, which means the SD card is too slow.

**Comment by KevW7** [comment]
OK thanks, that's useful to know. My SP2SP2 just has an old 4GB card I had lying about. Maybe I should upgrade it then.
