### ISSUE TITLE
about japanese console running other region games with VMC enable

### ISSUE THREAD

**Issue by mariotaotao** [emukidid/swiss-gc#589]
Hi, thank you for making this amazing homebrew for gamecube.
    I'm using a Japanese console with gcloader installed and the latest swiss 
    when enable virtual memory card feature, It can read or write the save games (VMC file convert from real memory card via gcmm and dolphin tool)with no problem, but when I load the non Japanese games, the game shows the memory card is corrupt and need to be format, I remembered there was an option in the old version of  swiss  that can mod the save type to Japanese encode, but I can't find it anymore. And the latest version can read other region game saves on my real memory card with no issue. Any idea to work around? Thanks

**Comment by Extrems** [comment]
There's a different set of memory cards for each game region. You likely didn't have existing memory card images for those regions.

**Comment by mariotaotao** [comment]
got it, thanks
