### ISSUE TITLE
IGR button combo accessibility issue

### ISSUE THREAD

**Issue by dumbdumb** [emukidid/swiss-gc#593]
is there a way to change or simplify the IGR button combo? i have mobility issues so holding B + Z + R + D-pad Down its really hard/almost impossible to me.

maybe Z+ B + Down
or Z + L + B

**Comment by Extrems** [comment]
If you turn the controller by 180 degrees, you should be able to press the Z Button with your thumb.

**Comment by Extrems** [comment]
I think A + Z + Start is the most sensible choice for everyone then.

**Comment by Extrems** [comment]
Fixed in 553a9da (r1184).
