### ISSUE TITLE
Resdient Evil cheats crash gamecube to black screen

### ISSUE THREAD

**Issue by Liquidgykill** [emukidid/swiss-gc#598]
EDIT: update with stackdump

Im using the las version of Swiss so far (Swiss v0.5r1181)

Everytime I activate cheats I got a black screen inmediately I hit the option to boot, saying:

Exception (DSI) occurred!
lots of numbers and letters

STACK DUMP
800872d4 -- 800872b0 -- 800083fc -- 80048c84 --
80049ec4 -- 8004a108 -- 8004cbd4 -- 8004d384 --
80009710

CODE DUMP
800872d4: 990A0000 81410018 2C0A0000 4182000C
800872e4: 39000000 990A0000 2C1F0000 7D49192E
800872f4: 38600000 40820018 8001002C 83E10024

So far my other games dont give me this error but I dont know how to solve it.

It didnt happen in the previous Swiss version that I used (Swiss v0.5r963) I was able to use the same cheats and configuration without any issue.

**Comment by Extrems** [comment]
We need the stack dump at minimum to debug this.

**Comment by Extrems** [comment]
The stack dump doesn't make sense. Are you sure this is r1181?

**Comment by Bakuku** [comment]
I can confirm this issue on my Wiikey Fusion modded Gamecube.

Resident Evil remake crashed upon boot when enabling cheats (doorskip transition in my case).

**Comment by Liquidgykill** [comment]
still present in v0.5r1196 , the console crashes at the moment I try to boot RE with cheats.

**Comment by Bakuku** [comment]
> still present in v0.5r1196 , the console crashes at the moment I try to boot RE with cheats.

After talking with extrems yesterday, he told me its a memory issue. Too many cheats even when not enabled can cause the crash. So I removed the unused cheats from the Text file containing the cheats (In my case everything except the doorskip cheat) and the game now boots properly with doorskip enabled.

Maybe it’ll work for you as well.

**Comment by Liquidgykill** [comment]
I already tried with only 1 cheat and it still gives me the crash screen, in the previous revisions it didnt happened, I could always load the 3 cheats I use with no problem at all, now I cant activate even 1.

**Comment by Bakuku** [comment]
> I already tried with only 1 cheat and it still gives me the crash screen, in the previous revisions it didnt happened, I could always load the 3 cheats I use with no problem at all, now I cant activate even 1.

Just to be sure, you edited the txt file containing the cheats and removed all the text apart from 1 or 2 cheats?
I’m asking because for the off chance you might have misunderstood what I meant. Not enabling only 1 or 2 cheats but actually removing all the unused cheats text from the txt file.

**Comment by Liquidgykill** [comment]
Ok now I understand, but my question stays.
Why should I do that now when in v0.5r963 everything was ok and that was not necesary?

**Comment by Extrems** [comment]
It's a regression of sorts from 324f8f523a91c8acf54e6684a288aac13de06c2c.
This isn't my department, so I'm not too keen on fixing it.

**Comment by Liquidgykill** [comment]
I tried doing what was recommended above (to shave the cheats to only the ones I really use, since most are codes for all the slots in the item box) and the game launched without problems, its not the best solution but it works.
