### ISSUE TITLE
Game banners suddenly disappearing in Swiss

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#599]
When I launched Swiss today, many of the game banners just disappeared. However, it only seemed to happen on patched roms, for the most part. I am using the latest build of Swiss, r1184.

**Comment by Extrems** [comment]
You shouldn't be hijacking the disc ID of discs in Redump.

**Comment by Extrems** [comment]
A patched disc image keeping the existing disc ID is hijacking that disc ID.

**Comment by GK6475** [comment]
Ok. I fixed the problem by changing all the game IDs in the patched ISOs. I even managed to transfer save files, and they work.

**Comment by GK6475** [comment]
Ok. I'll keep that in mind.
________________________________

**Comment by GK6475** [comment]
Ok
________________________________
