### ISSUE TITLE
Memory Card in Port A Undetectable; Port B Works Fine

### ISSUE THREAD

**Issue by lyingriotman** [emukidid/swiss-gc#602]
Background: My GC is a late production DOL-101, using v0.5r1179 and GC-Loader PNP firmware version 2.0.0 (Beta). Issue still exists on version 1.1.0. No SD Gecko or SD2SP2. Swiss config unchanged aside from IGR settings.

Issue: Booting into games from Swiss results in memory cards inserted in port A being unreadable in a large number of titles (LoZ: TP, Metroid Prime, SSBM, Naruto: Clash of Ninja, Spiderman) with the main exception being LoZ: Collector's Edition, likely because each game has its own boot process. 

Using the IGR shortcut/hotkey doesn't reboot to the Swiss menu, but instead reboots the game as if through the GC-Loader itself, as the IGR hotkey no longer works. Upon IGR, the memory card in port A is detected and can be read/saved to normally.

Expected behavior: Booting into games through Swiss allows memory card port A to be read as usual, without IGR.

**Comment by lyingriotman** [comment]
Sorry, just looked and realized it's a duplicate. My bad

**Comment by Extrems** [comment]
You currently need a SD Gecko or SD2SP2 for IGR to work in The Legend of Zelda: Collector's Edition. You're warned about it every time you boot a game.
