### ISSUE TITLE
Tales of Symphonia Crashes After Disc Change

### ISSUE THREAD

**Issue by Nicolas-Miranda** [emukidid/swiss-gc#608]
I'm facing consistent crashes while playing Tales of Symphonia on a Gamecube with a GCLoader installed. The issue is reproducible after a disc change as the game crashes when loading a battle at any point in the game.

Gamecube Model: DOL-001 NTSC-J
SwissGC Version: 0.5 rev1138
GCLoader PnP Firmware version: 1.1.2
Sandisk Extreme Pro 256GB

I uploaded a video showing the problem loading the same save data which is for disc 2.

https://youtu.be/LOJ2NMBm0xQ

00:00:00 - 00:03:25 Normal behaviour when loading directly from disc 2.

00:03:00 - 00:04:57 Game crashes consistently when loading a battle after a disc change. Started the game using disc 1 to force the disc change when loading the save file.

This issue it also happens when loading a cleared save data from disc 2 (just after completing the game) in which it resets back to the SwissGC menu on the disc change.

Thanks so very much in advance!

**Comment by Extrems** [comment]
Turns out there's also this issue: JulianoW/Tales-of-Symphonia-NGC-Undub#2
I've taken a look, and the max FST size specified by disc 2 is too small for the FST of disc 1.

**Comment by Nicolas-Miranda** [comment]
> Turns out there's also this issue: [JulianoW/Tales-of-Symphonia-NGC-Undub#2](https://github.com/JulianoW/Tales-of-Symphonia-NGC-Undub/issues/2) I've taken a look, and the max FST size specified by disc 2 is too small for the FST of disc 1.

I was just reading that too. As you mentioned before, probably when loading Disc 2 from a clean ISO boot, Swiss was loading the patched ISO triggering the issue from the patch itself.
