### ISSUE TITLE
Pac-Man World 2 emulated memory card support issue

### ISSUE THREAD

**Issue by LittleHooligan74** [emukidid/swiss-gc#610]
this is a follow-up to of the previous question and the details for its issue:

1. I have GCloader
2. most games seem to support the feature
3. I'm running on the current version of swiss
4. pac-man world 2 doesn't seem to support as I have to play it all over again
5. I'm using a 4GB Toshiba micro sd as the memory card (via sd2sp2)
6. converted my own dumped iso into nkit.iso

#609

**Comment by Extrems** [comment]
Did you turn on disc read speed emulation for this game?

**Comment by LittleHooligan74** [comment]
no

**Comment by Extrems** [comment]
Couldn't reproduce using 10 different SD cards.
