### ISSUE TITLE
(0.6r1215) Unable to launch Pokemon Box Ruby & Sapphire

### ISSUE THREAD

**Issue by evanlott** [emukidid/swiss-gc#613]
Launching Pokemon Box Ruby & Sapphire via GC Loader version 1.1.2 and Swiss version 0.6r1215 throws an error reading "Too many patches enabled, memory limit reached". Trying a different iso gives a solid green screen. SD card is a 32GB SanDisk formatted as FAT 32. Not entirely sure if this is a GC Loader issue or a Swiss issue.

Edit: I found a workaround. Attempt to launch via the Swiss menu. After it errors out, go to the bottom right options menu. You can then launch it via the "Game Play" option in the gamecube settings.

**Comment by Extrems** [comment]
Please update your firmware.

**Comment by evanlott** [comment]
I’ll try that, thank you. Currently I’m running GC Loader 1.1.2, should I be running 2.0.0 beta?

**Comment by Extrems** [comment]
Since you don't have a patch device at this present time, yes, you should.

**Comment by evanlott** [comment]
Can confirm that the GC Loader 2.0.0 Beta Firmware resolves this issue. Thank you for your help!

**Comment by Extrems** [comment]
As a side note, you can press L+A instead of A for clean boot.
