### ISSUE TITLE
Swiss v0.6 - rev: 1215 -- Chibi Robo - no sound/music while GameCube startup logo animation

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#616]
Hi,

using the previous release of Swiss v0.5 - rev. 1196, there was a normal, good-looking boot of ChibiRobo (CRC-32: 88080c8f MD5: 3491a233b72d2e5ebc1fa34d37ce84cf) possible, when booting from GCLoader 2.0.0 ("swiss_patches" folder was stored to SD2SP2).
Including booting through IPL (animated boot logo with sound/ intro music) and including emulated memory card did work very well.

Everything worked awesome (test playing: about 15 hours - without any problems, loading and saving is really fast - thanks to swiss!!! :) ).

In Swiss v0.6 - rev: 1215: loading, patching and starting Chibi Robo is working...
![swiss-gamecube-05](https://user-images.githubusercontent.com/77854382/140795412-343ef3fc-e15e-4f21-8589-35bcf7e413cd.png)

...but there is no sound/music while GameCube boot logo animation anymore.
![swiss-gamecube-04](https://user-images.githubusercontent.com/77854382/140794509-1a0de316-b785-42b8-8325-acfde8b366e0.png)
(no GameCube intro tune here)

Could this be a sign for a new/general/in-deep bug in Swiss v0.6 - rev: 1215?

I could reproduce this new bug again and again in different ways
(Clean .iso) booting Swiss v0.5 - rev: 1196 and starting Chibi Robo - everything is ok.
(Clean .iso) booting Swiss v0.6 - rev: 1215 and starting Chibi Robo - no GameCube logo animation music.

(Clean .iso) Booting Swiss v0.6 - rev: 1215, then booting Swiss v0.5 - rev: 1196 (via swiss file browser) and starting Chibi Robo - everything is ok.
(Clean .iso) Booting Swiss v0.5 - rev: 1196, then booting Swiss v0.6 - rev: 1215 (via swiss file browser) and starting Chibi Robo - no GameCube logo animation music.

**Comment by Extrems** [comment]
I cannot reproduce this.

**Comment by BorgNumberOne** [comment]
Sorry.
Please excuse me, I forget to mention that the bug can only reproduced, when: "Force Video Mode" is set to 576p.

**Comment by Extrems** [comment]
Yeah, I've done so.

**Comment by BorgNumberOne** [comment]
It seems to be a small bug, but I'm very interested in the reason(s).

**Comment by Extrems** [comment]
Well, historically speaking this used to be an issue with memory card emulation, as it delayed the processing of DSP interrupts and then bugs in the IPL caused sounds to drop out.

**Comment by BorgNumberOne** [comment]
Your theory makes sense and it seems to be the reason for the problem, because with Swiss v06 - rev: 1215, everything (Swiss-ed game patches, emulated Memory Card),  will be stored to GCLoader 2.0.0's SD card now.

Well, I think it is very interesting that forced video mode (576P) and non forced video mode (576i in this case) makes such a difference.

**Comment by Extrems** [comment]
It shouldn't be happening on GC Loader as everything is asynchronous now, including writing. SD2SP2 still has synchronous writing, and this can sometime be observed as audio buzzing.

**Comment by BorgNumberOne** [comment]
Thank you very much for your great knowledge and explanations - yours is a great user support.

Well, with Swiss v0.6 rev: 1215 and GCLoader 2.0.0 it is really comfortable to have one fast (faster than SDGecko or SD2SP2) possibility of:
a) (emulated) Memory card read/write access and
b) fast GameCube game file data access
both at the same time and with just one SDcard.

However, if there should appear more timing related audio bugs (because everything is stored/read to/from GCLoader 2.0.0) with other games in the next days, and if there is no way to fix such a bug, then there maybe should be an future option in the Swiss settings where the swiss_patches folder can be defined (automatic(current/previous behavior), GCLoader, SD2SP2, SDGecko A, SDGecko B) .

**Comment by Extrems** [comment]
I'm wondering, can you hear it over the analog audio output? This might be a glitch in your digital chain.

> However, if there should appear more timing related audio bugs (because everything is stored/read to/from GCLoader 2.0.0) with other games in the next days, and if there is no way to fix such a bug, then there maybe should be a future option in the Swiss settings where the swiss_patches folder can be defined (automatic(current/previous behavior), GCLoader, SD2SP2, SDGecko A, SDGecko B) .

This is already possible since v0.6r1215 by changing your configuration device.

**Comment by BorgNumberOne** [comment]
"can you hear it over the analog audio output?" - what is this **a-n-a-l-o-g**? :rofl:

Well, it is a really difficult task.

I have connected my GameCube with
- a BitFunx HDMI - adapter ( a prebuilt, commercially available GameCube HDMI adapter with GCvideo firmware, besides the also available EON GCHD MK-II)
(http://www.bitfunx.com/wordpress/product/bitfunx-hdmi-line-doubler-adapter-gc2hdmi-for-nintendo-gamecube-ngc-digital-to-hdmi/)
**AND** a
- normal composite (not component) cable with audio line

at the same time.
(It is normally not possible, because of the width of the bitfunx adapter, but I was able to do it by plugging both adapters in a bit skewed and not completely into my GameCube)

However in this case (both adapters are connected to the GameCube and to my TV) and while booting swiss, it(swiss) seems to detect this state anyhow and disables the analog output - I just could see the GameCube logo for one second or two and nothing more.
My TV does not detect any signal anymore and disables the AV input.

Then I have to switch my Samsung's TV input from "AV" to "HDMI".
After this, booting any Game or homebrew does not reactivate the GameCube's analog output anymore so far.

If I disconnect the HDMI adapter from my GameCube, swiss detects this anyhow and keeps the analog AV output active while boot.
But in this case, swiss do not "see" any adapter or device on the GameCube's digital audio/video output port and does not allow to use progressive video modes anymore and displays a warning message  "**Component Cable not detected**".

After this, Chibi Robo (and the GameCube logo animation) will be started, but in interlaced mode and I can hear the starting music. --> reproducing the bug is not possible in this way.

**Comment by Extrems** [comment]
The analog audio output is definitely working 100% of the time. I use it since HDMI audio is a pain in the ass.

Try plugging it into the line-in on your PC.
