### ISSUE TITLE
Swiss v0.6 - rev: 1215 -- SpongeBob SquarePants - Creature from the Krusty Krab (E) - "An error has occured. ..."

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#617]
Hi.

there seems to be a new bug in Swiss v0.6 rev: 1215 while booting:
**SpongeBob SquarePants - Creature from the Krusty Krab (E)** - (crc-32: 5dcf1734,  md5: 10b725bed9a3be326a776db800682b47): "**An error has occured. ...**"

**Swiss v0.5 - rev: 1196:**
![SpongeBob-CFTKK--swiss-v05-1196-no-bug](https://user-images.githubusercontent.com/77854382/140796990-07ec6b07-decb-444d-aee5-bf91452c37af.png)

**Swiss v0.6 - rev: 1215:**
![SpongeBob-CFTKK--swiss-v06-1215-bug](https://user-images.githubusercontent.com/77854382/140797062-73de6d24-73a6-495a-a0fb-3a16e63dedb2.png)

**Comment by Extrems** [comment]
Fixed in cfe2cc1 (r1217).
