### ISSUE TITLE
Swiss v0.6 - some still missing help texts (e.g. in the swiss settings and "clean boot" shortcut & region hack info)

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#618]
In the Swiss settings, many menu items have got a short, appropriate but user-friendly and easy to understand help text.

But there are some menu entries/ menu points, where a future help text / explanation text of the respective menu item would be great.

Furthermore, it would be great, if Swiss could inform a little more about **clean boot** possibility, maybe in these ways
(just a suggestion ;) ):

a)bottom info - device selection
![swiss-device-selection--adding-info--supports-cleanboot-modified](https://user-images.githubusercontent.com/77854382/140825828-e357ba5d-45ac-4fbb-a275-016fdbc6fbf7.png)

b)Application/Game loading screen
![swiss-adding-cleanboot-shortcut-info--modified](https://user-images.githubusercontent.com/77854382/140824779-7e92d973-b067-4e98-a696-0e4a9985c488.png)

**Comment by Extrems** [comment]
Stating clean boot support on the device selection screen is redundant since all DI devices do, and none others can.
Other DI devices, beside an unmodified disc drive, have their own region hack.

I meant to include the button combo on the game information screen, but it was messier than I would've liked.

Lastly, WTF is that disc? Please submit to [Redump](http://wiki.redump.org/index.php?title=Nintendo_GameCube_/_Wii_Dumping_Guide).

**Comment by BorgNumberOne** [comment]
google: worldwide finding rare gamecube discs ;)

**Comment by BorgNumberOne** [comment]
Well, how is this basic region hack realized with GCLoader 2.0.0 - will some bytes / sectors of the .gcm/.iso file be changed temporally / in GCLoader's RAM or how does it work?

**Comment by Extrems** [comment]
It copies the disc header to a new file (boot.bin), replaces the region code in BI2 to be the one expected by BS2, then overlays that onto the original file.

There are compatibility issues relating to unexpected video modes, but fixing those would be quite a bit more complicated.

**Comment by BorgNumberOne** [comment]
Do you mean: unexpected video modes regarding the patched(suddenly inappropriate region)?

Well, with the help of GCLoader, Swiss and its "**clean boot**" feature, the Nintendo Service Disc is working very well - the really first time on my real physical EUR/PAL gamecube:

![NintendoGameCubeServiceDisc-v1_0-03--025](https://user-images.githubusercontent.com/77854382/140835279-28381556-0641-4c7c-b7fb-b909f7442509.png)
![NintendoGameCubeServiceDisc-v1_0-03--101](https://user-images.githubusercontent.com/77854382/140835314-e60c6c4e-043a-4d3e-9514-b0dedba0e3e9.png)
![NintendoGameCubeServiceDisc-v1_0-03--114](https://user-images.githubusercontent.com/77854382/140835575-3fd2c875-cce7-484c-9b92-df6ef8d9a4b5.png)
![NintendoGameCubeServiceDisc-v1_0-03--116](https://user-images.githubusercontent.com/77854382/140835578-461a252e-3cdf-41eb-867c-31d27b0b6d3e.png)
![NintendoGameCubeServiceDisc-v1_0-03--118](https://user-images.githubusercontent.com/77854382/140835583-78b904b4-b84c-4c7d-840e-1821bc20abd6.png)
![NintendoGameCubeServiceDisc-v1_0-03--121](https://user-images.githubusercontent.com/77854382/140835642-db9621aa-b6b6-4e86-b7d5-5d2f32fe67f9.png)
![NintendoGameCubeServiceDisc-v1_0-03--122](https://user-images.githubusercontent.com/77854382/140835640-c136b3b5-21dd-46b2-b082-ee8f8e4ab51b.png)
![NintendoGameCubeServiceDisc-v1_0-03--131](https://user-images.githubusercontent.com/77854382/140835779-16259387-3b83-41ad-92b0-6a0da165c130.png)
![NintendoGameCubeServiceDisc-v1_0-03--136](https://user-images.githubusercontent.com/77854382/140835776-574fbc2f-ac70-4a6c-a99d-c035d557d4df.png)


....but the "unexpected video mode" effect could be the reason that the cool 3D demo does not work on my real GameCube
![NintendoGameCubeServiceDisc-v1_0-03--204](https://user-images.githubusercontent.com/77854382/140835824-44504d05-126b-4ff3-b5cf-a884f6c76c27.png)
(after selecting: **Demo** nothing happens anymore, just rebooting my GameCube is still working.)



P.S.:
https://repo.mariocube.com/Datel%20and%20RVT-H%20Disc%20Images/RVT-H/DIAG_Ver3_1_1%20(060J01)%20(JPN)%20(GCN).gcm.rar 
Sorry, I currently do not exactly know, how I did find this site/page/file.
But i thin i did find the mariocube repo page and then I did manually check the sub folders.

There are surely more hidden (and already CleanRip-dumped) treasures (non-public GameCube discs et...) around the world...

It is time to bring the problem/effect: not loosing rare GameCube stuff/discs / increase the thought of preservation of rare digital media in general
...much more to the public anyhow.

**Comment by Extrems** [comment]
Many NTSC games don't like to be booted from a PAL video mode, and vice-versa.

**Comment by BorgNumberOne** [comment]
Would that be the only necessary modification to get the cool 3D car demo to run?
https://www.google.com/search?q=change+gamecube+region :rofl:

Does the 3D car demo successfully work on your gamecube?

**Comment by Extrems** [comment]
It works, but that's not a stereo 3D demo.

GCVideo-DVI also has no specific support for the column-interleaved stereo 3D mode (it's not flagged in the data stream), so you'd need to post-process it on a PC to get a usable picture.

**Comment by Papy-G** [comment]
Maybe finding an early 3D panel would help? (I remember seeing one back in the days on an in-store kiosk to advertise for coffee, it was just like the 3DS', no glasses needed, but wayyy bigger screen)
From the available technologies at this moment, you may expect a plasma panel with DVI connection, if not proprietary LVDS bus.

Otherwise, one can generate the occulting fringe mask for a given panel, this is not very complicated after all.

**Comment by Extrems** [comment]
Fixed in 429b6c4 (r1579).
