### ISSUE TITLE
Swiss v0.6r1215 -- Force clean boot for unsupported discs

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#619]
Hi,

Swiss' v0.6r1215 new feature: "Force clean boot for unsupported discs" ist a good idea, basically.

It would be better to realize this as a switchable setting / as an option in the SWISS settings.
Or, let the user decide (L+A) when the loading/patching Game screen appears.

Currently, I cannot do different .ISO experiments anymore with the latest Swiss Release, because Swiss decides if a Clean Boot will be done or not.

Furthermore: 
Logically, there cannot be a Clean Boot of an .ISO file which ist stored on SD2SP2 or SDGeckoA / B

But the current SWISS tries a Clean Boot of some of my experimental .iso files - which are stored on SD2SP2/SDGecko. Really soon Swiss recognize its failure and brings out an error message.

**Comment by Extrems** [comment]
There is no way these images will ever be supported on GameCube. Sorry.

**Comment by BorgNumberOne** [comment]
While doing (.iso modification related and other) experiments with further Non-Nintendo and non public (US/Non-Pal) .iso / .gcm files in the past weeks, it was really comfortable and really great to have:

- SWISS' patching features
**AND**
- the GCLoader file access speed

...at the same time.

For example it was also possible to start Non-EU/Non-PAL or Non-Nintendo .iso / .gcm image files on a PAL GameCube with the help of SWIS's previous feature **not** automatically force to clean boot such images files.
It is / it should already be well known, that there are disc image files(Nintendo Service Disc) which cannot be started in the SWISS-patching-way / which can only be started with GCLoader and with the clean boot way. So it is not the point getting these .iso / .gcm image files to run in the non-clean-boot-way.

In the past it was great that SWISS could boot action replay and other(...) disc images in the Non-clean-boot-way.
This was a great feature when doing experiments with these kind of .iso / .gcm files.
And because of the SWISS patching process my TVs could have a decent display output.

Now, all these images file will be automatically forced to boot directly (clean boot) without having the user friendly choice of disabling this automatic clean boot behaviour.

Furthermore, because of the missing patching process through SWISS, my TVs have troubles (e.g. with US releases of action replay disc images: unsupported video mode)

So please, please  bring back the feature that the user can decide, if he wants to clean boot an .iso / .gcm image file.(L+A)

Thank you very, very much.

**Comment by Extrems** [comment]
Datel discs are even more problematic for us.

**Comment by BorgNumberOne** [comment]
Surely.
I just would like to show you, how awesome and usefully the previous SWISS' feature was, letting the user decide if she/he wants to start **either**
- the SWISS-ed method
**or**
- the clean boot method.

So, please bring back the previous great possibility(L+A) (or another one, like suggested in the last post) of having the capability in SWISS to choose between clean boot or not.
