### ISSUE TITLE
Rush 2049 Legacy Edition mod

### ISSUE THREAD

**Issue by Sirethief2525** [emukidid/swiss-gc#622]
While the game is playable it doesn't allow any of the game specific settings to be set or does any patching to allow 480p which the original midway arcade treasures 3 does allow for, would there be any possible fix for this?

**Comment by Extrems** [comment]
Looks like they decided to be cute and set their game ID to 2049LE, while those starting with a digit are reserved for diagnostics.

**Comment by Sirethief2525** [comment]
So if I were to change the game id in a hex editor would that solve the issue?

**Comment by Extrems** [comment]
Fixed in 9f6588e (r1229).
