### ISSUE TITLE
Feature Request - hide boot.iso and igr.dol

### ISSUE THREAD

**Issue by mario-64** [emukidid/swiss-gc#623]
When used with GC Loader it would be great if we could hide boot.iso and igr.dol from the games list since they are basically system files. That way only actual games would be displayed. Similar to how Everdrives allow hiding their system folder.

**Comment by Extrems** [comment]
You can already do so by setting the FAT hidden attribute on them.

**Comment by mario-64** [comment]
Really? So within Windows just right click and check hidden on these two files? I assume you’d need to repeat this with every Swiss update?

**Comment by Extrems** [comment]
Windows will reset the attribute when you overwrite the old files, yeah.

**Comment by mario-64** [comment]
Ok great thank you
