### ISSUE TITLE
swiss-gc in dolphin emulator

### ISSUE THREAD

**Issue by BorgNumberOne** [emukidid/swiss-gc#627]
Some month ago, it was important for the dolphin-emu comunity and for the dolphin-emu developers to get to run Swiss in dolphin-emu.

https://de.dolphin-emu.org/blog/2020/07/05/dolphin-progress-report-may-and-june-2020/ --> "5.0-12151 - Basic Support for Thermal SPRs by delroth"

So, Swiss worked again for a while.

However,  Swiss v0.5r963 seems to be the latest version that a recent dolphin emulator can boot.
Swiss v0.5r990 and newer releases seem to boot but do nothing anymore after boot.

It would be great if the problem could be solved in Swiss or in dolphin-emu again.

**Comment by Extrems** [comment]
It's an issue on Dolphin's end with their EXI emulation.

**Comment by BorgNumberOne** [comment]
If it's an issue with Dolphin, why did Swiss v0.5r963 do work in Dolphin?
Which commit / bug fix / enhancement between Swiss v0.5r963 and Swiss v0.5r990 brings the effect of not working in Dolphin anymore?

**Comment by Extrems** [comment]
[extremscorner/libogc2@7fe9cb8...ea9dc0a](https://github.com/extremscorner/libogc2/compare/7fe9cb86a969d9bdc8f62d5ddd2e15f1d748b6be...ea9dc0a503efc28457ecb1fbe6a0bfaecaebbce9)

**Comment by Extrems** [comment]
No, it's highly dependent on everything that happened since then.
