### ISSUE TITLE
Game Mods/Hacks Flagged as Bad Dumps on Selection

### ISSUE THREAD

**Issue by gourdcaptain** [emukidid/swiss-gc#630]
When selecting several game mods in Swiss such as the [F-Zero AX Direct Boot Patch](https://www.romhacking.net/hacks/5779/) or the [Tales of Symphonia Undub v2.0 Beta](https://github.com/JulianoW/Tales-of-Symphonia-NGC-Undub/releases), Swiss does the thing where it waits for several seconds on an unskippable "File is a bad dump, but may be playable. Please attempt recovery using NKit." message. These patches were applied to valid Redump-matching copies of the games (ripped myself with CleanRip, matched against the Redump dat files correctly), and so it would be nice if it were possible for a user to flag files as known to be modded? 

Understand if that's not feasible, this just falls under "mild annoyance/would like to distinguish from any actual bad dumps that may have turned up in my collection."

**Comment by Extrems** [comment]
Please change at least the game revision.
