### ISSUE TITLE
[Feature Request] Custom checksums for nkit images

### ISSUE THREAD

**Issue by MichiS97** [emukidid/swiss-gc#633]
Hi,

so I don't know if something like this is useful for a lot of people but I'd really love to see a way of either having the option to provide custom CRCs for nkit images or just to be able to disable CRC verification on a per-game basis.
Some of my games have custom DOLs that I have made myself and the "verification failed" pop-up gets annoying when it happens every time you boot the game.

The only workarounds that are possible right now are either simply not using nkit for games with a modified executable or compiling Swiss with a changed CRC for that particular game in nkit.c...unless I'm missing something?

**Comment by Extrems** [comment]
Change the disc revision.

**Comment by MichiS97** [comment]
That makes sense. Cheers.
