### ISSUE TITLE
Disabling alpha dithering doesn't work on Swiss v0.6r1243

### ISSUE THREAD

**Issue by Gitomata** [emukidid/swiss-gc#641]
Hi Extrems and emukidid

First amazing work on the homebrew Swiss. 

I'm on GCLoader (with swiss set as Boot.iso) using SDloader to save settings. On the latest version of Swiss it appears that disabling alpha dithering doesn't work? I have it set to 'Yes' specifically for Prince of Persia Sands of Time but it doesn't appear to work compared to the prior version of Swiss I was using which was v0.5r1086. I've taken pictures but my phone doesn't really show it that well but it's obvious to see. Disabling alpha dithering has a cleaner blockier look whereas when it's not disabled, there's a filter like a screen door over things like smoke and light and some textures. 

Let me know if you need more details or if you want me to try other games. 

P.S the digital trigger level option is a cool extra feature in Swiss that works really well in this game :) hopefully that didn't break the disable alpha dithering.

Thanks for your commitment and work.

**Comment by Extrems** [comment]
This is a regression from a change made in c186cb1 to avoid issue #564.

**Comment by Extrems** [comment]
This won't be fixable, but it still has a major effect on the dithering in this game.

**Comment by Gitomata** [comment]
Thanks for confirming.

**Comment by Gitomata** [comment]
Hi @Extrems any chance the pre c186cb1 way you implement disarming Alpha dithering could be added as an extra option? From my playtime using Swiss, your old implementation leads to such a clean image most of the time. Maybe a 'yes', 'no' and 'experimental version'?

Totally understand if your don't want to do this. I appreciate the effort you and @emukidid  put into Swiss, and your work here has let me continue playing on the GameCube. Thanks
