### ISSUE TITLE
[Issue]: Compile issue

### ISSUE THREAD

**Issue by bladeoner** [emukidid/swiss-gc#644]
### Describe the bug

Hi I'm looking into adding a Github Workflow for Nightly Builds and I'm trying to compile the source on a Ubuntu 20.04 machine but it fails.

You can see my test run here: https://github.com/bladeoner/swiss-gc/actions/runs/1854100790

Is the source compatible with the latest Devkitpro tools?
And is it possible to compile it on Linux or is it only working on Windows?

Thanks in advance.

### Steps to reproduce

- Download the source from Github to a Ubuntu 20.04 machine.
- Install the latest Devkitpro tools to compile GC projects including devkitPPC
- Compile Swiss

### Expected behavior

That the compile finishes without any error.

### Relevant log output

```shell
Run make -j2
Building on
make[1]: Entering directory '/__w/swiss-gc/swiss-gc/cube/patches'
make[1]: Leaving directory '/__w/swiss-gc/swiss-gc/cube/patches'
make[1]: Entering directory '/__w/swiss-gc/swiss-gc/cube/swiss'
clean ...
make[1]: Leaving directory '/__w/swiss-gc/swiss-gc/cube/swiss'
make[1]: Entering directory '/__w/swiss-gc/swiss-gc/pc/usbgecko'
make[1]: Leaving directory '/__w/swiss-gc/swiss-gc/pc/usbgecko'
make[1]: Entering directory '/__w/swiss-gc/swiss-gc/cube/patches'
Building C Patches ...
Building Reboot ...
Building Stub ...
Building SD Patch ...
Building SD Patch + CARD ...
Building SD Patch + DTK ...
Building IDE-EXI-v1 Patch ...
Building IDE-EXI-v1 Patch + CARD ...
Building IDE-EXI-v1 Patch + DTK ...
Building IDE-EXI-v2 Patch ...
Building IDE-EXI-v2 Patch + CARD ...
Building IDE-EXI-v2 Patch + DTK ...
Building DVD Patch ...
Building DVD Patch + CARD ...
Building USBGecko Patch ...
Building WKF Patch ...
Building WKF Patch + CARD ...
Building WKF Patch + DTK ...
Building FSP Patch ...
Building GCLoader-v1 Patch ...
Building GCLoader-v1 Patch + CARD ...
Building GCLoader-v2 Patch ...
Building GCLoader-v2 Patch + CARD ...
make[1]: Leaving directory '/__w/swiss-gc/swiss-gc/cube/patches'
make[1]: Entering directory '/__w/swiss-gc/swiss-gc/cube/swiss'
Current Directory /__w/swiss-gc/swiss-gc/cube/swiss
GIT Revision 1f891bb
systemimg.scf
gcdvdsmall.scf
hdd.scf
qoob.scf
gcloaderimg.scf
m2loaderimg.scf
fileimg.scf
elfimg.scf
sdsmall.scf
dirimg.scf
checked_32.scf
btnhilight.tpl
btnexit.tpl
btndevice.tpl
btnrefresh.tpl
boxinner.tpl
files.c
patcher.c
video.c
elf.c
mp3.c
exi.c
swiss.c
/__w/swiss-gc/swiss-gc/cube/swiss/source/swiss.c: In function 'load_app':
/__w/swiss-gc/swiss-gc/cube/swiss/source/swiss.c:848:9: warning: 'memset' offset [0, 255] is out of the bounds [0, 0] [-Warray-bounds]
  848 |         memset((void*)0x80000000,0,0x100);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/swiss-gc/swiss-gc/cube/swiss/source/swiss.c:849:9: warning: 'memset' offset [0, 255] is out of the bounds [0, 0] [-Warray-bounds]
  849 |         memset((void*)0x80003000,0,0x100);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/__w/swiss-gc/swiss-gc/cube/swiss/source/swiss.c:867:9: warning: 'memcpy' offset [0, 31] is out of the bounds [0, 0] [-Warray-bounds]
  867 |         memcpy(gameID,(char*)&GCMDisk,0x20);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c
In file included from /__w/swiss-gc/swiss-gc/cube/swiss/source/main.c:35:
/__w/swiss-gc/swiss-gc/cube/swiss/source/devices/fat/ata.h:116: warning: "__lhbrx" redefined
  116 | #define __lhbrx(base,index)                     \
      | 
In file included from /__w/swiss-gc/swiss-gc/cube/swiss/source/main.c:11:
/opt/devkitpro/libogc2/include/ogc/machine/processor.h:76: note: this is the location of the previous definition
   76 | #define __lhbrx(base,index)                     \
      | 
In file included from /__w/swiss-gc/swiss-gc/cube/swiss/source/main.c:35:
/__w/swiss-gc/swiss-gc/cube/swiss/source/devices/fat/ata.h:121: warning: "__lwbrx" redefined
  121 | #define __lwbrx(base,index)                     \
      | 
In file included from /__w/swiss-gc/swiss-gc/cube/swiss/source/main.c:11:
/opt/devkitpro/libogc2/include/ogc/machine/processor.h:81: note: this is the location of the previous definition
   81 | #define __lwbrx(base,index)                     \
      | 
util.c
bba.c
/__w/swiss-gc/swiss-gc/cube/swiss/source/bba.c: In function 'init_network':
/__w/swiss-gc/swiss-gc/cube/swiss/source/bba.c:20:23: error: too few arguments to function 'if_config'
   20 |                 res = if_config(bba_ip, NULL, NULL, true);
      |                       ^~~~~~~~~
In file included from /__w/swiss-gc/swiss-gc/cube/swiss/source/bba.c:4:
/opt/devkitpro/libogc2/include/network.h:252:5: note: declared here
  252 | s32 if_config( char *local_ip, char *netmask, char *gateway,bool use_dhcp, int max_retries);
      |     ^~~~~~~~~
make[2]: *** [/__w/swiss-gc/swiss-gc/cube/swiss/Makefile:39: bba.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:164: build] Error 2
rm boxouter.tpl mp3img.tpl hdd.tpl pal.tpl memcardimg.tpl boxinner.tpl m2loaderimg.tpl elfimg.tpl fileimg.tpl qoob.tpl gcdvdsmall.tpl unchecked_32.tpl btnrefresh.tpl ntscu.tpl dolimg.tpl gcloaderimg.tpl loading_16.tpl btndevice.tpl btnsettings.tpl usbgeckoimg.tpl btnexit.tpl sdsmall.tpl checked_32.tpl backdrop.tpl systemimg.tpl sambaimg.tpl dolcliimg.tpl ntscj.tpl wodeimg.tpl btnhilight.tpl btninfo.tpl dirimg.tpl wiikeyimg.tpl
make: *** [Makefile:52: compile] Error 2
make[1]: Leaving directory '/__w/swiss-gc/swiss-gc/cube/swiss'
Error: Process completed with exit code 2.
```

**Comment by Extrems** [comment]
Releases are currently being built using devkitPPC release 40 with libogc2 (master) on Arch Linux.

**Comment by bladeoner** [comment]
@Extrems thanks for the quick response.

**Comment by Extrems** [comment]
They work on Windows and Linux x86-64 with a glibc environment.

**Comment by bladeoner** [comment]
Thanks, when I find some time I will give it another try.

**Comment by Extrems** [comment]
xorrisofs is usable as an alternative, and is used on Windows as it's packaged by MSYS2.

**Comment by bladeoner** [comment]
I think I can work around mkisofs, thanks for the suggestion.

Do you have an idea about the error in the attached logfile of my previous comment?

**Comment by Extrems** [comment]
It might be a glitch because you're using multiple jobs.

**Comment by bladeoner** [comment]
I also tried it on my own machine then I'm getting the same error, also when I compile using: make windows

The USB Gecko Server for Windows is the only file that won't compile.

**Comment by Extrems** [comment]
Does this mean with or without `-j2`?

**Comment by bladeoner** [comment]
It occurs with and without, this is the output just with: make

The swissserver is compiled but the swissserver.exe not.


gcc -Wall -Wextra -Os -g -pipe -c gecko.c main.c
main.c: In function ‘cache_path’:
main.c:139:17: warning: format ‘%i’ expects argument of type ‘int’, but argument 3 has type ‘__off_t’ {aka ‘long int’} [-Wformat=]
  139 |    printf ("%s %i [%s]\n", ent->d_name, fstat.st_size, S_ISDIR(fstat.st_mode) ? "DIR":"FILE");
      |                ~^                       ~~~~~~~~~~~~~
      |                 |                            |
      |                 int                          __off_t {aka long int}
      |                %li
main.c: In function ‘main’:
main.c:168:15: warning: unused parameter ‘argc’ [-Wunused-parameter]
  168 | int main (int argc, char **argv) {
      |           ~~~~^~~~
main.c:168:28: warning: unused parameter ‘argv’ [-Wunused-parameter]
  168 | int main (int argc, char **argv) {
      |                     ~~~~~~~^~~~
main.c: In function ‘send_file_data’:
main.c:161:3: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
  161 |   fread(buffer, 1, req->size, served_file_fp);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -L ../-lFTD2XX gecko.o main.o  -o swissserver -L ../-lFTD2XX
strip -g swissserver
i686-w64-mingw32-gcc -Wall -Wextra -Os -g -pipe -c gecko.c main.c
make: i686-w64-mingw32-gcc: Command not found
make: *** [Makefile:33: windows] Error 127

**Comment by bladeoner** [comment]
What makes it difficult is that the Devkitpro docker image that is available only runs on Linux and in Github that is Ubuntu.
