### ISSUE TITLE
[Feature request]: Non-Anamorphic Widescreen Rendering

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#646]
### Describe the feature

For this feature, I was thinking that something similar to the Wii could be implemented, with a resolution close to 852x480, instead of anamorphic 640x480 or 720x480. I imagine that the games would be rendered beyond their horizontal boundaries, similar to the current widescreen hack.

**Comment by Extrems** [comment]
That's not how the Wii works, and this is impossible to implement.
