### ISSUE TITLE
[Issue]: Exhausted Reserved Memory with Force Anisotropic Filter and Force Widescreen

### ISSUE THREAD

**Issue by s3anami** [emukidid/swiss-gc#651]
### Describe the bug

Exhausted Reserved Memory 
An SD Card Adapter is necessary in order for patches to reserve additional memory.

### Steps to reproduce

Using GCLoader to boot latest Swiss 1250
Using SD2SP2 with 8 GB SD card (tried 2 GB as well) for configuration device settings (attempting to use GCLoader writeback gives no SD card error)
Attempting to load game using FSP from RetroNAS
It starts patching the necessary DOL files to boot the game
Then right before loading gives this error
Games load just loading from GCLoader

### Expected behavior

Game to start

**Comment by Extrems** [comment]
Are you using boot through IPL with some weird game settings?

**Comment by s3anami** [comment]
I dont have it enabled. 
Here are my settings in full
https://imgur.com/a/r3sMc5S

What happens
https://imgur.com/a/yBvg49Q

**Comment by Extrems** [comment]
Force Widescreen 2D+3D is a weird game setting. You're insane for having that by default.

**Comment by s3anami** [comment]
i turned it off and anisotropic off.  Now it attempts to boot a game and always crashes. Says an error has occured turn the power off

**Comment by Extrems** [comment]
Are you on a separate subnet? The server must be in the same broadcast domain.

**Comment by s3anami** [comment]
its all on 192.168.1.x  
there are some unmanaged switches on other side is all that's different from a normal just plug into router set up.
the retronas piece is running on a hyper-v vm

The files work on a windows box right next to the gamecube using dolphin as well
They are nkit shrunk, but retronas documentation says that is support so i assumed same here

**Comment by s3anami** [comment]
one of the switches in the mix was not functioning properly, sorry for wasting your time

**Comment by Extrems** [comment]
Partially fixed in 8cbdaaf (r1366).

**Comment by Extrems** [comment]
Fixed in 1d90e3d (r1583).
