### ISSUE TITLE
[Issue]: Graphical Issue in Killer 7 - Double Enemies

### ISSUE THREAD

**Issue by 1lluminado** [emukidid/swiss-gc#655]
### Describe the bug

In Killer 7, when you encounter an enemy, you can see one rendered next to the other.  

I'm guessing that this is supposed to be a layered texture effect or shadow, but you can distinctly see 2 different models, only one of which you are able to shoot.   

In this video, you can clearly see a good close-up of the issue as the two models are overlaid in the cutscene.
https://i.imgur.com/olHhhlX.mp4

Someone reported a similar issue in the same game on the Wii with Nintendont with a video width option, not sure if that's relevant to this:
https://github.com/FIX94/Nintendont/issues/209

### Steps to reproduce

Start the Game in either 480p or 480i Modes with Default Swiss Settings and any enemy you encounter (at least in the first level) will be doubled.

If you "Disable Video Patches: All / Game" then it will be normal. 

### Expected behavior

I'm assuming the "distorted" graphical layer should be overlaid on the enemy model. (screenshot shows expected single enemy)

### Add screenshots

Issue:
![Killer7Issue](https://user-images.githubusercontent.com/32724794/157732102-7d3acfa4-6324-4b6d-bbde-a49ea6f51537.png)

Expected: (Disable Video Patches: Game / All)
![Killer7Expected](https://user-images.githubusercontent.com/32724794/157732098-64d176c6-9a10-4bb6-8aff-ad76671e6482.png)

**Comment by Extrems** [comment]
Fixed in e41e00f (r1281).

**Comment by frossardd** [comment]
hey can you explain how and where to put the content on my sd card to fix killer7`s problem? please, i do not know anything of programming
