### ISSUE TITLE
[Issue]: Ingame reset on Qoob Pro

### ISSUE THREAD

**Issue by RamsesUTL** [emukidid/swiss-gc#656]
### Describe your question

I have an PAL Gamecube with Qoob Pro and use iplboot as BIOS on it to run Swiss from SD2SP2.
Everything works fine except for the ingame reset. It doesn't matter if I choose "reset" or "igr.dol" the Gamecube does the reset and boots into the original Nintendo menu (with the hovering cube). I've tried swiss and iplboot as igr.dol on the card in the SD2SP2 and even on the Qoob Pro, but it changes nothing.
Is this problem known? Any hints on what I might miss here? Thanks in advance ...

**Comment by Extrems** [comment]
The former is a known issue. As for the latter, make sure the SD Card isn't formatted as exFAT, as the reload stub currently does not support it.

**Comment by Extrems** [comment]
Fixed in b2f5c27 (r1292).

**Comment by RamsesUTL** [comment]
My card was exFAT formated. I did not thought of that because everything else worked just fine. Thanks for the response and re-enabling Qoob with your fix . I'm looking forward to the next build.

**Comment by Extrems** [comment]
It's available through GitHub Actions: https://github.com/emukidid/swiss-gc/actions/runs/2009894979
