### ISSUE TITLE
[Issue]: Failed to setup the file (too fragmented?)

### ISSUE THREAD

**Issue by lodgerz** [emukidid/swiss-gc#663]
![IMG_20220407_135551](https://user-images.githubusercontent.com/9266267/162193326-ab8357f8-193b-4183-a957-81d3ea3a6152.jpg)
### Describe the bug

Hello, 
i can't load iso of Zelda Wind Waker. 

### Steps to reproduce

When i select it on swiss menu it says:
"Device doesn't support disc images. Set EXI speed to 16MHz".
Than i go to settings and set "SD/IDE speed" to 16MHz"
Now it can load the iso but it says:
"Failed to setup the file (too fragmented?)".

### Expected behavior

Can i solved?
I launch swiss with SD Media Launcher. I use Lexar SDHC 8gb card. Swiss 0.6.

**Comment by Extrems** [comment]
Is there enough space less on the device?
Is the file in less or equal than 40 FAT fragments?
Can the file be verified successfully? (Press the R Button on the info screen)
