### ISSUE TITLE
[Issue]: Exhausted reserved memory on Audio stream games through FSP

### ISSUE THREAD

**Issue by rayfoster14** [emukidid/swiss-gc#665]
### Describe the bug

When trying to boot an iso from my FSP server, the Exhausted reserved memory. An sd adapter is necessary.etc error appears if the game has audio streaming. 

I have a sd gecko and serial port sd adapter instead when trying this too.

### Steps to reproduce

Boot audio streaming iso through FSP

### Expected behavior

Thr game to boot, I have an earlier iteration of swiss and it works just fine (although the audio stream feature is automatically disabled)

**Comment by Extrems** [comment]
The server must have a writable root directory or `/swiss` directory. This is done by creating empty `.FSP_OK_RENAME`, `.FSP_OK_MKDIR`, `.FSP_OK_ADD` and `.FSP_OK_DEL` files in the relevant directory.

**Comment by rayfoster14** [comment]
Thanks! That worked. Getting FSP audio streaming up and running is a big deal for me so I really appreciate all of the hard work you guys put in to make this tool what it is!
