### ISSUE TITLE
[Question]: Just out of curiosity???

### ISSUE THREAD

**Issue by GAMECUBE-N64** [emukidid/swiss-gc#667]
### Describe your question

Is there any emulators that work on Nintendo Gamecube with Swiss?

For N64, NES, SNES, Sega Genesis, Gameboy Advanced, and others???

**Comment by Extrems** [comment]
Nintendo 64:
- [Cube64](https://github.com/emukidid/Wii64/releases)
- [Not64](https://github.com/extremscorner/not64/releases)

Nintendo Entertainment System:
- [FCE Ultra GX](https://github.com/dborth/fceugx/releases)
- [RetroArch](https://retroarch.com/?page=platforms)

Super Nintendo Entertainment System:
- [Snes9x GX](https://github.com/dborth/snes9xgx/releases)
- [RetroArch](https://retroarch.com/?page=platforms)

Sega Genesis:
- [Genesis Plus GX](https://github.com/ekeeke/Genesis-Plus-GX/tree/master/builds)
- [RetroArch](https://retroarch.com/?page=platforms)

Game Boy Advance:
- [Enhanced mGBA](https://www.gc-forever.com/wiki/index.php?title=Enhanced_mGBA)
- [RetroArch](https://retroarch.com/?page=platforms)
- [Visual Boy Advance GX](https://github.com/dborth/vbagx/releases)
