### ISSUE TITLE
[Issue]: Phantasy Star Online - Episode 1 & 2 Crashes when playing Online on the latest Swiss firmware,1318, using GC Loader, works fine with 1236

### ISSUE THREAD

**Issue by GrimMeNaCe** [emukidid/swiss-gc#673]
### Describe the bug

Whenever going online with Phantasy Star Online - Episode 1 & 2 on the latest Swiss firmware, version 1318 on GC Loader, the game glitches in terms of weapons vanishing and etc., lags, freezes and crashes back to the Swiss menu after a few minutes or a few seconds. Offline works fine. I had to downgrade back to the older version of Swiss that I was using previously, 1236 and online works perfectly fine with no issues at all.

### Steps to reproduce

Use Phantasy Star Online Episode 1 & 2 on a GC Loader on Swiss firmware 1318 to go online on the Schtack servers, join a game, go into the forest or whatever other level and after a bit the game begins to show problems in terms of lag, glitches and then an eventual reboot of the GameCube. Sometimes you don't even need to join a game, just stand in the lobby and the game starts messing up before rebooting. Sometimes it reboots right when you get online.

### Expected behavior

Normally I would except to go online without problems and etc., I've been using firmware 1236 for months to play PSO online without a single issue. Once I upgraded to the latest 1318 version, whenever I go online, the game begins to show signs of glitching during gameplay, freeze, lag and a crash, making the system reboot back to the menu.

**Comment by Extrems** [comment]
Looks like we've hit the memory limit for this game.

**Comment by Extrems** [comment]
Fixed in 2c0b98a (r1326). Probably. It's not the most wise of fixes.

**Comment by Extrems** [comment]
Fixed in 7a9aa56 (r1330).
