### ISSUE TITLE
[Issue]: GBI Intermittently Not Launching

### ISSUE THREAD

**Issue by aarmastah** [emukidid/swiss-gc#674]
### Describe the bug

Trying to run the Game Boy Interface via Swiss (specifically I am running the speedrunning version via SD2SP2) will intermittently lock up the console, requiring a reboot to continue. I have confirmed my connections are solid and the SD card is not corrupt.

### Steps to reproduce

Launch GBI-SR via Swiss.

### Expected behavior

GBI launches.

### Add screenshots

https://www.youtube.com/watch?v=b0lMEuonMwM

**Comment by Extrems** [comment]
Fixed in 13225af (r1432).
