### ISSUE TITLE
[Issue]: Exception occurs when attempting to load cheats on a physical disk

### ISSUE THREAD

**Issue by jhd8h** [emukidid/swiss-gc#678]
### Describe the bug

When attempting to press the cheats button on a game that is being read from the disk drive, an "Exception (ISI)" will occur. This does not occur on ISOs from the sd card. 

Going through different releases, this started occurring with release r1290.

My specific configuration of gamecube is as follows:
DOl-001 model
XenoGC modchip installed
Burned minidvd with Swiss r963
SD2SP2 with latest boot.dol on root of sd card
"Sandisk Ultra Plus" 32gb formatted fat32

### Steps to reproduce

- Boot Swiss with a version of r1290 or newer
- Insert a game disk
- Select the dvd drive from the device selection menu
- Select the game executable at the top of the list
- Press (Y) to attempt to view cheats
- Exception occurs here

### Expected behavior

Expected behavior is that either the normal cheats menu appears or the prompt saying no cheats were found, as it does on versions lower than r1290. 

### Relevant log output

```shell
A picture of the exception is attached below.
```

### Add screenshots

![image](https://user-images.githubusercontent.com/71046946/169926169-459a52b9-6b54-4a07-b6e3-9c2f1a10ce2b.png)

**Comment by Extrems** [comment]
For clarification, this stack dump is from r1318.

**Comment by jhd8h** [comment]
I believe so, yes. I will get another picture just to be safe.

**Comment by Extrems** [comment]
Fixed in 4f15d67 (r1332).
