### ISSUE TITLE
[Issue]: IGR doesn't seem to work when running games from FSP

### ISSUE THREAD

**Issue by flashpc** [emukidid/swiss-gc#681]
### Describe the bug

In game reset seems to work fine when using gc loader, but when using the broadband adapter to play games from the network the games run fine but when you try to reset it just freezes the game

### Steps to reproduce

I have tried putting igr.dol in the network drive folder, tried changing the reset from igr.dol to reboot and back again, and I thought there maybe some sort of conflict running the network initialisation and so that has been disabled but still freezes

### Expected behavior

Reboot console back to swiss please

**Comment by Extrems** [comment]
Fixed in 54868ed (r1321).
