### ISSUE TITLE
[Feature request]: Change default device shown after booting

### ISSUE THREAD

**Issue by ChristinMilloy** [emukidid/swiss-gc#684]
### Describe the feature

Presently when booting e.g. from SD Slot B, Swiss launches into folder view of root on SD Slot B.

It would be great if we can configure instead to default showing arbitrary device e.g. FSP or SD2SP2 device folders instead, and can fallback to boot device if unsuccessful.

**Comment by Extrems** [comment]
Fixed in b95b2db (r1315). Press Z on the ".." directory entry with file management enabled.
