### ISSUE TITLE
no memery card found[Issue]: 

### ISSUE THREAD

**Issue by pcaudill3323** [emukidid/swiss-gc#685]
### Describe the bug

when i updated to v0.6r1318 swiss all my saves are not their it says no memery card found when i try to play a game, i did update the gcloader with the beta new os? I hope that is not the problem. when i go into the saves the memery cardes saves are their.

### Steps to reproduce

when ever i try to play a game and save or play a saved game.

### Expected behavior

save a game or play a saved game.

**Comment by Extrems** [comment]
This might be issue #442.

**Comment by pcaudill3323** [comment]
I hope that with the next version this will be fixed, because I would like not to have to get a older version, I like the new version better.

Sent from Mail for Windows

**Comment by Extrems** [comment]
Duplicate of issue #442.

**Comment by pcaudill3323** [comment]
Tried swiss r1011 still no memery card found.

Sent from Mail for Windows
