### ISSUE TITLE
1333 Green screen on all games.[Issue]: 

### ISSUE THREAD

**Issue by tinergbr** [emukidid/swiss-gc#687]
### Describe the bug

Having updated to 1333. After I launch any game greeted with a green screen.

### Steps to reproduce

Launch 1333. Select multiple games. Press A button to launch and met with green screen. Nothing else happens until console restarted.

### Expected behavior

Games to play!

**Comment by Extrems** [comment]
Please try v0.6r1335.

**Comment by tinergbr** [comment]
Just tried. Same green screen

Sent from the all-new AOL app for Android 
 
  On Sun, 12 Jun 2022 at 14:11, ***@***.***> wrote:   


Please try v0.6r1335.

**Comment by tinergbr** [comment]
Gone back to 1318. Working fine

**Comment by Extrems** [comment]
What's your SD card's brand, model, capacity, and year of purchase?

**Comment by Diegorella** [comment]
It could be the SD not properly seated...
but
try deleting the patches folder inside the swiss folder.
also delete the settings.
just DO NOT click save.
try clearing the carche with L+A in Swiss.

Is the battery and date correct for you?

**Comment by 2mac** [comment]
I can confirm this issue in 1333 and 1335. 1318 works fine. I have no patches directory. I don't understand this L+A instruction. I tried that when loading and it said that the device doesn't support clean boot.

I'm loading the games from a Samsung SDHC card, 32GB, purchased 2021, connected via SD2SP2 interface.

**Comment by tinergbr** [comment]
1333 and 1335 boot up normally. I still receive the list of games from my SanDisk 128gb extreme bought 3 weeks ago. After I select a game and press A button greeted with green screen. Can't reset using button combo it anything. Console has to be turned back on and off.

**Comment by Extrems** [comment]
What happens if you back out to the device selection screen then select the device again?

**Comment by 2mac** [comment]
> What happens if you back out to the device selection screen then select the device again?

Same behavior. Tried selecting a difference device first as well.

**Comment by tinergbr** [comment]
![IMG_20220612_160338](https://user-images.githubusercontent.com/107351618/173239470-15415190-606c-4632-b4a2-31a80b7ad0c4.jpg Same here!

**Comment by Diegorella** [comment]
> Posso confirmar este problema em 1333 e 1335. 1318 funciona bem. Não tenho diretório de patches. Eu não entendo esta instrução L+A. Eu tentei isso ao carregar e disse que o dispositivo não suporta inicialização limpa.
> 
> Estou carregando os jogos de um cartão Samsung SDHC, 32GB, adquirido em 2021, conectado via interface SD2SP2.



there is a "swiss" folder that is hidden inside your SD.
You have to activate the option to view hidden files in the swiss menu.
delete patches inside Swiss folder

**Comment by 2mac** [comment]
> there is a "swiss" folder that is hidden inside your SD. You have to activate the option to view hidden files in the swiss menu. delete patches inside Swiss folder

Okay, I was able to find and delete the patches directory. Same behavior.

**Comment by Diegorella** [comment]
weird... for me the only thing that is happening is that in metroid prime in the last 2 revisions the game crashes when i jump in the water with Samus.

**Comment by tinergbr** [comment]
Deleted Patches. Still the same green screen.

**Comment by Extrems** [comment]
> weird... for me the only thing that is happening is that in metroid prime in the last 2 revisions the game crashes when i jump in the water with Samus.

Why didn't you bring that up before? It's the same root problem.

**Comment by Extrems** [comment]
Fixed in f93ca0f (r1336).
