### ISSUE TITLE
[Issue]: R: Racing Evolution garbled text

### ISSUE THREAD

**Issue by AnthonyRyuki** [emukidid/swiss-gc#689]
### Describe the bug

After a movie ends playing, the text in the description at the bottom of the screen is garbled. In every other situation, the text looks fine.

### Steps to reproduce

Enter "Racing Life" mode, and after the movie ends, the pre-menu race for the next race will appear, but the issue will also take place.

SD2SP2 was used.

### Expected behavior

The text in the description bar should be readable.

### Add screenshots

![IMG_1397](https://user-images.githubusercontent.com/62845774/173894476-692444bc-fd4b-4135-8a79-c309061b8b60.JPG)

**Comment by Extrems** [comment]
I can't reproduce this. Please press the R Button on the game info screen to verify your disc image.

**Comment by AnthonyRyuki** [comment]
It says "Passed integrity verification".

**Comment by Extrems** [comment]
Can you provide more specific instructions? Preferably save data as well.

**Comment by Diegorella** [comment]
which iso region?
do you use memory card emulation?
use boot with IPL?
deleted the "patches" folder inside the swiss folder. (must enable see hidden files)
Have you tried using another previous revision so swiss?
another SD card
or B Gekko slot?

**Comment by AnthonyRyuki** [comment]
I'm using the American version on a PAL GC.
I tried enabling and disabling all video patches, Memory Card emulation and boot with IPL, as well as deleting the "patches" folder and nothing worked.
Here's my save data, though I doubt it will make a difference.
[MemoryCardA.USA.zip](https://github.com/emukidid/swiss-gc/files/8929606/MemoryCardA.USA.zip)

By the way, the issue does not always take place if you skip the movie.

**Comment by Extrems** [comment]
It looks like a game bug where they forgot to specify 32-byte alignment for a memory allocation and it just happen to work out most of the time.

**Comment by Extrems** [comment]
I'm still unable to reproduce this issue, or find a potential problem, so I'm afraid this is unfixable.

**Comment by AnthonyRyuki** [comment]
Well, turns out that the PAL version does not have said issue. It looks like it's caused by a regional mismatch between console and game.

**Comment by Extrems** [comment]
It isn't, and I did test the NTSC version on a PAL console.
