### ISSUE TITLE
game intro latency

### ISSUE THREAD

**Issue by lucart84** [emukidid/swiss-gc#690]
hello, 
when I launch a game like for example mario kart double dash the intro bug and the launch of the races there is some lag.
I have the latest version of swiss and an sd2sp2 as well as a gcloader lite.
Thanks for your help.

**Comment by Extrems** [comment]
This could only happen if you set EXI Speed to 16MHz. Did you do that?

**Comment by Extrems** [comment]
Can't reproduce.

**Comment by lucart84** [comment]
whether I am in 16 or 32 the game slows down the same.
