### ISSUE TITLE
[Issue]: Smash Bros Melee 20xx Save Reboot Problem

### ISSUE THREAD

**Issue by GrimMeNaCe** [emukidid/swiss-gc#695]
### Describe the bug

I'm using an official GC Loader with Swiss and I have the save for Smash Bros. Melee called 20xx Tournament Edition on my official memory card with memory card emulation turned off. To load the save you have to click on VS. and then name entry to make the 20xx save load on Smash Bros. Melee but when I do that on the new Swiss version 1336 it reboots the Gamecube back to the menu. The issue wasn't present on 1236, it would load perfectly fine. The website for the save is http://www.20xx.me/download.html

### Steps to reproduce

Put the 20xx Tournament save for Smash Bros. Melee somehow on an official memory card, turn off memory card emulation in Swiss and then load Smash Bros. Melee through Swiss version 1336. Click on VS. and then name entry. The Gamecube will reboot back to the menu. The same steps done through version 1236 cause no problems and the save will load perfectly fine.

### Expected behavior

Gamecube will reboot back to the menu on version 1336 when clicking on name entry in VS. instead of loading the save like normal the way it does on version 1236.

**Comment by Extrems** [comment]
Can you specify the device used?

**Comment by GrimMeNaCe** [comment]
Using Swiss on an offical GC Loader

**Comment by Extrems** [comment]
This only (partially) worked in v0.6r1236 by luck. You need to use clean boot with this. Press L+A on the game info screen.
