### ISSUE TITLE
[Issue]: Gameboy Interface Giving a Black Screen

### ISSUE THREAD

**Issue by GrimMeNaCe** [emukidid/swiss-gc#696]
### Describe the bug

I'm using an offical GC Loader with the Gameboy Player a long with the Gameboy Interface to load the Gameboy Player. On version 1236 of Swiss I would usually click on the regular GBI dol file to load the interface but on 1336 it just gives me a black screen. The only way for me to load it is by clicking on the GBISR dol file but that dol file is for speed running. Theres another dol file called GBIHF and that doesn't work either though I'm not sure what that one is used for. Basically the normal dol file for the Gameboy interface called just GBI gives me a black screen on Swiss 1336 and works fine on 1236.

### Steps to reproduce

Launch the GBI dol file on version 1336 of Swiss on a GC Loader and it gives a black screen, works fine on 1236.

### Expected behavior

Black screen when clicking on GBI dol file for the Gameboy interface on Swiss 1336, works fine on 1236.

**Comment by Extrems** [comment]
This is not a Swiss issue.
