### ISSUE TITLE
[Question]:  Disable dvd boot

### ISSUE THREAD

**Issue by maniaco007** [emukidid/swiss-gc#697]
### Describe your question

Good morning everyone.
How can I disable dvd boot attempt on Swiss startup?
I don't use the player, I just wanted to directly access the games on the sd without wasting time trying to boot the dvd.

**Comment by Diegorella** [comment]
you must disable IPL boot.
in tab 2 of the Swiss settings.
above memory card emulation.
check no.
so that the game does not access the IPL.

or press B to skip DVD tracking if you work without a drive...

**Comment by maniaco007** [comment]
Thanks for the feedback.
I'm at work now, I'm going to test at lunch time.

**Comment by Extrems** [comment]
There's nothing wrong with boot through IPL. I have no idea what Diegorella is on about.

**Comment by Diegorella** [comment]
that's exactly what i was talking about.
I don't think this is manageable for now...

**Comment by Extrems** [comment]
Improved in 8e4f1ef (r1343).

**Comment by maniaco007** [comment]
I updated using version r1343, but I didn't get the much-desired deactivation of the disk boot attempt...

Do I need to perform any additional configuration?

**Comment by Extrems** [comment]
If there's no disc, it'll be faster than with a disc present. Quickest will be with the lid open.

You can also remove the disc drive altogether.

**Comment by Zonark** [comment]
Was this ever implemented? Where we can set in the settings that no drive is attached so it skips that press b nag? Maybe in a nightly build?

**Comment by Extrems** [comment]
It is automatically skipped in the latest release.

**Comment by Ichicoro** [comment]
Sorry, commenting this because it seems there's still no way to FORCE disabling dvd booting even with the DVD drive present... :(
