### ISSUE TITLE
[Issue]: Cannot copy GCI file to memory card

### ISSUE THREAD

**Issue by wfowler1** [emukidid/swiss-gc#698]
### Describe the bug

It's great being able to backup game saves by copying them to your SD card through the file management system. However, the system doesn't seem to work in reverse. When trying to copy a GCI file for Pokémon XDback onto the memory card I get an error:
`Failed to Write! (-11)
carda:/PokemonXD.gci`
It'd be great to have a way to move GCI files onto Memory cards, either emulated or real. I don't see a way to do it in Swiss at the moment, but maybe I'm missing something.

### Steps to reproduce

1. Copy GCI save file from memory card somewhere else 
2. Attempt to copy the GCI file back onto the memory card.
3. Observe error. It will fail even if you delete the save file from the memory card first.

### Expected behavior

I expect to be able to restore the save backup onto the memory card.

**Comment by Extrems** [comment]
Fixed in c33607d (r1493).
