### ISSUE TITLE
[Feature request]: Emulating memory card in only one slot at a time

### ISSUE THREAD

**Issue by wfowler1** [emukidid/swiss-gc#700]
### Describe the feature

Currently there seems to only be one option for emulated memory cards, "on" and "off". This option works on both memory card slots at once. It would be better to turn it on or off for the slots individually, so you could use a real memory card in slot A while using an emulated one in slot B.

**Comment by Extrems** [comment]
A physical Memory Card in Memory Slot B is already passed through if present.

**Comment by Extrems** [comment]
Could you explain the use case for a physical Memory Card in Memory Slot A?

**Comment by wfowler1** [comment]
Sorry, but why is this not planned? Seems like a perfectly valid feature request to me.

**Comment by Extrems** [comment]
You haven't explained why it is.

**Comment by rapperskull** [comment]
I don't know if it's the reasoning behind the OP, but some games just default to the memory card in slot A if present, without asking which slot to use, so there's no way to force a save to be in the physical memory card, if memory card emulation is enabled.

**Comment by Extrems** [comment]
I understand that, but what's the point of memory card emulation then?

**Comment by rapperskull** [comment]
IDK, maybe avoid having to turn MCE off for every game one wants to store on the physical memory card? Or just flexibility, don't having to worry about where the physical memory card is.
