### ISSUE TITLE
[Issue]: Unable to copy dsp_rom.bin and dsp_coef.bin

### ISSUE THREAD

**Issue by wfowler1** [emukidid/swiss-gc#701]
### Describe the bug

For some reason these files cannot be copied from the system files.

### Steps to reproduce

1. Use the device selection to navigate to the system memory.
2. Attempt to copy dsp_rom.bin or dsp_coef.bin to another device.
3. Observe error:
`Failed to Read! (4096 0)`
`sys:/dsp_coef.bin`

`Failed to Read! (8192 0)`
`sys:/dsp_rom.bin`

### Expected behavior

I would expect it to be able to copy these files.

**Comment by Extrems** [comment]
Duplicate of issue #443.
