### ISSUE TITLE
[Question]: Blueretro modding.

### ISSUE THREAD

**Issue by Luizcsf** [emukidid/swiss-gc#706]
### Describe your question

Good evening.
I have the 1336 version of swiss and i can't do the in-game reset with blue retro mod (ps4 controller on gamecube).
Will there be any compatibility with this mod in the future?

Is there any way to reset swiss with the reset button?

Thanx for the attention.

**Comment by Extrems** [comment]
If you're able to control the game, then the mod isn't the problem.

**Comment by Luizcsf** [comment]
Actually, i want to apologize because i found the correct command and now the mod Works beautifully.
