### ISSUE TITLE
[Issue]: Bitfunx component cables don't work with swiss.

### ISSUE THREAD

**Issue by CMR779** [emukidid/swiss-gc#708]
### Describe the bug

My Bitfunx component cables don't seem to work with swiss.  They work fine with normal disk games, but with swiss I don't see anything but a bit of noise scrolling up the screen.  I'm using an NTSC Gamecube DOL-001.  I've got a picoboot installed and I'm launching swiss from an SD Gecko type adapter.  I can also burn it to disc and try launching it that way if it will help.

### Steps to reproduce

use Bitfunx component cables plugged into the digital video port

### Expected behavior

image displayed on the screen

**Comment by Extrems** [comment]
You need to set Swiss Video Mode to 480i. Your display is incompatible with 480p.

**Comment by CMR779** [comment]
Thanks.
