### ISSUE TITLE
[Question]: Can you increase the disc initialization time?

### ISSUE THREAD

**Issue by Deathstryker** [emukidid/swiss-gc#709]
### Describe your question

Hello, I recently added Swiss (latest version at the time of this post) to my GameCube via an SD card through the serial port. When Swiss attempts to initialize a disc before it loads the menu, it never finds my OEM GameCube disc. However, when I start my GameCube without Swiss, the disc loads up.

My question is: Is there a way to increase this initialization time? I'm wondering if Swiss just isn't giving the disc enough time to load. 

Thanks

**Comment by Diegorella** [comment]
you arrive in Swiss d, how? xeno chip; original media explorer...??
you must mention which OEM you refer to;
check if the mentioned disk is on the Swiss compatibility list;
what state of work...
check for dump of the same in the NGC library

**Comment by Deathstryker** [comment]
I'm using Pico Boot to arrive at Swiss. I'm using original Nintendo Discs. Not burnt discs. Swiss starts up as soon as I turn it on and it tries to initialize the official disc at startup but doesn't load the game.

**Comment by Extrems** [comment]
The DVD device is rarely the default device. Press B, then A on the eject button, then navigate to it.

**Comment by Deathstryker** [comment]
Extrems, thanks for responding. What do you mean it's rarely the default device? I never set it up differently. Is there a way to not make it the default?

**Comment by Extrems** [comment]
You need to not have any SD cards or memory cards in the system for it to be selected as default.

**Comment by Deathstryker** [comment]
Cool, thanks for answering.

**Comment by Extrems** [comment]
You'll probably want to follow issue #704. Closing now.
