### ISSUE TITLE
[Issue]: Emulated Memory Card not saving to SD card

### ISSUE THREAD

**Issue by MrRussellgro** [emukidid/swiss-gc#710]
### Describe the bug

I happen to have the Emulated Memory Card enabled on page 3 in Swiss, but it doesn't do anything but save to my actual memory card instead on my card in the SD2SP2 drive.

How can I get this working again so I don't save it to my actual memory card again?

### Steps to reproduce

So I tried out a little bit of Doshin the Giant. As I got to saving the game after the boot, it said my memory card was corrupted and it had to format.
I left the game to play something else and now it saves straight to my memory card instead.

### Expected behavior

Just as I enabled the emulation for a memory card in my SD card in the SD2SP2 device. Now it just goes into my actual memory card instead.

**Comment by Extrems** [comment]
Does that something else happen to be a streaming audio game? Turning on disc read speed emulation will also disable it.

**Comment by MrRussellgro** [comment]
> Does that something else happen to be a streaming audio game? Turning on disc read speed emulation will also disable it.

I could check it out. I will see if that was a problem. Then I might let you know. Thanks!

**Comment by MrRussellgro** [comment]
@Extrems So I have the Read speed turned off, but it still goes into my memory card. Do you mind if I send you some pics to show you what happened?

**Comment by Extrems** [comment]
The important thing is whether or not the game is a streaming audio game.

**Comment by MrRussellgro** [comment]
So what page do I find that in?

**Comment by Extrems** [comment]
It's written here.
![Streaming](https://user-images.githubusercontent.com/554978/179814330-b45af6f3-d93c-45ff-bcba-4d48ac3f0e17.png)

**Comment by MrRussellgro** [comment]
Okay, I see thank now. Thanks for showing me where it is!
