### ISSUE TITLE
[Issue]: Sonic Adventure 2: Battle Black Screen

### ISSUE THREAD

**Issue by hts739** [emukidid/swiss-gc#717]
### Describe the bug

When booting the game, there is only a black screen. Curiously, when holding B for progressive scan support, the in-game progressive scan option does show up, but choosing either yes or no confirms your choice and just goes to a black screen.

### Steps to reproduce

Using GCLoader 2.0.0 with Swiss r1196 (also tried GCLoader 1.1.2 with latest swiss 1336)
Using SD2SP2 for configuration.
Load game with default settings.
Black screen (Progressive scan option appears when holding b, then black screen after selection.)

The game loads perfectly booting it directly through gcloader as the boot.iso, bypassing swiss. Game also works using swiss 1184

### Expected behavior

Game to start

**Comment by Extrems** [comment]
Tested NTSC-J, NTSC-U and PAL versions. Cannot reproduce.
