### ISSUE TITLE
[Feature request]: Changing Icons.

### ISSUE THREAD

**Issue by maniaco007** [emukidid/swiss-gc#718]
### Describe the feature

Hello everyone.

Would it be possible to customize the icon for .dol files?

This way we could add icons with custom logos in emulators, apps, etc...

### Add screenshots

![dol](https://user-images.githubusercontent.com/82119174/183406335-2fa12d02-895a-4b30-bac3-e53aed98e534.jpg)

**Comment by Extrems** [comment]
Currently the intended method is issue #536.

**Comment by maniaco007** [comment]
> Currently the intended method is issue #536.

I apologize for the little knowledge.
I couldn't understand what I need to do to be able to assign an icon to the .dol

**Comment by Extrems** [comment]
You can use ppm2bnr from cubeboot-tools to create the opening.bnr you need to put in the directory. It will be assigned to the directory itself.

**Comment by maniaco007** [comment]
Thanks for the replies.

I thought it would be something a little simpler.

Unfortunately I couldn't.

Do you have any reference of someone who has done and shared how?

**Comment by ZweiBR** [comment]
would it be possible to share the test swiss 1353?
