### ISSUE TITLE
[Issue]: Cheat file only reads DOS line endings

### ISSUE THREAD

**Issue by duh102** [emukidid/swiss-gc#721]
### Describe the bug

After an upgrade from an older version (I think release ~11xx) to 1336 I noticed that my cheat files were coming up as not having any cheats in them (the "empty or unreadable" message).
This cheat file worked previously, and in several other games I noticed that some or all of the cheats were still working. Looks like at some point in the past Swiss accepted either cr/lf or just lf as line endings, now it only accepts cr/lf. 

### Steps to reproduce

Create and upload a new cheat file using Unix line endings (lf only)
Attempt to activate cheats on a game

### Expected behavior

Cheats should appear and be selectable

**Comment by Extrems** [comment]
Fixed in d77be8c (r1425).
