### ISSUE TITLE
[Issue]: Can't save on Zelda Collection, virtual memory is not working

### ISSUE THREAD

**Issue by animekai** [emukidid/swiss-gc#723]
### Describe the bug

In the Zelda Collection games I can't save because it ask me a memory card is not found, the virtual memory works on other games from other regions but this Zelda collections can't recognize the virtual memory card.

I can skip the try to save screen and play normally but without saving 

### Steps to reproduce

Load Zelda Collection iso and select a game like Zelda ocarina, and try to save it cant

### Expected behavior

That virtual memory card could save normally the progress in games

**Comment by Extrems** [comment]
Duplicate of issue #493.
