### ISSUE TITLE
[Issue]: Video Mode 480i /480sf Changues Emulated Memory card PAL to NTSC  and some games PAL dont recognize the NTSC Emulated Memory

### ISSUE THREAD

**Issue by Gand46** [emukidid/swiss-gc#724]
### Describe the bug

If the video is forced to 480i/480sf for the PAL games (this is made for some games are on other languages and the GCB and the TV is NTSC) the memory card file selected is USA, but the game is originally PAL what ends in the game not being capable of use the virtual memory card

### Steps to reproduce

PAL GAME =>Swiss Game settings - Video Forced 480i/480sf - Swiss selects Memory Card NTSC based on video output not game file => PAL Game can't Write saves on NTSC Memory Card

### Expected behavior

Swiss selects Emulated Memory Card based on game file not on video mode

**Comment by Extrems** [comment]
Cannot reproduce.
