### ISSUE TITLE
F-Zero GX Resetting

### ISSUE THREAD

**Issue by KongsNutz** [emukidid/swiss-gc#727]
F-Zero GX will randomly reset the game back to the Sega Logo.
It doesn't seem to happen anywhere in particular.

Swiss Version - 1362
ISOType - Verified nkit.iso
Region - NTSC on PAL GC
Boot method - PicoBoot + SDGecko 
Video Forced - None
Memcard Emulation - Yes

**Comment by Extrems** [comment]
Duplicate of issue #401.
