### ISSUE TITLE
[Issue]: The physical "Reset" button causes Super Smash Bros. Melee to run at 16 Mhz.

### ISSUE THREAD

**Issue by Tichinde925** [emukidid/swiss-gc#731]
### Describe the bug

I help run SSBM tournaments via GameCube. Currently, we are using version 1.03 TE (Tournament Edition): https://b0xx.com/pages/103

1.03 Tournament Edition, manual and download (GCI and/or ISO Builder): https://drive.google.com/drive/folders/1_gA17RZ_aonT62TSNRGcYCzuMOZINwL3

After configuring the VS mode options; removing the memory card from Slot A and pressing reset will lock those VS mode options so that players cannot change them during the tournament. 

As stated in the manual: https://i.imgur.com/XnPKtjU.png

The Main Issue: Pressing Reset causes the game to drop from 32 Mhz to 16 Mhz. This occurs on both the vanilla SSBM version 1.02 ISO and the 1.03 TE ISO, on a 32 GB microSD SanDisk Ultra UHS-I Class 10 connected via SD2SP2.  

This results in a delay/lag when players choose their characters on the VS Mode screen.

Also, "Boot through IPL" had to be set to "Yes" for 1.03 TE ISO to boot, otherwise it would result in a green screen freeze.

### Steps to reproduce

Pressing Reset causes the game to drop from 32 Mhz to 16 Mhz.

Also, "Boot through IPL" had to be set to "Yes" for 1.03 TE ISO to boot, otherwise it would result in a green screen freeze.

### Expected behavior

The game to retain 32 Mhz 

### Add screenshots

![TELock](https://user-images.githubusercontent.com/113464101/189972192-8568255f-80c8-4fd0-92b1-b633bf383417.png)

**Comment by Extrems** [comment]
This mod is doing things we can't account for. You're lucky it worked at all.
