### ISSUE TITLE
[Issue]: WWE Day of Reckoning inconsistent boot in forced 480p

### ISSUE THREAD

**Issue by YTQ00** [emukidid/swiss-gc#734]
### Describe the bug

Having an issue with booting Day of Reckoning (Japanese disc version) consistently in forced 480p. Sometimes it will work and sometimes it won't. When it works there seems to be no issues. When it doesn't, it freezes on a green screen with a garbled line across the top and I have to turn the console off. The green screen with a garbled line also shows up when it works, but it's at the bottom of the screen and it's much larger. 

### Steps to reproduce

Just force the game to 480p and try to boot into it.

### Expected behavior

Freeze up on a green screen with garbled line across the top when it doesn't work.

**Comment by Extrems** [comment]
Interesting. This game sets up memory protection on the end of the main thread's stack.

**Comment by YTQ00** [comment]
Thanks for the reply, extrems. Love your work. Been trying it some more tonight and it seems to not want to boot at all in 480p anymore. Really strange. It ran fine and looked so good when it did work. Is there anything I could try to see if I can get it up and running?

**Comment by Extrems** [comment]
Fixed in 5d8d97d (r1375).

You can enable boot through IPL as a workaround. Where Swiss' framebuffer sits happen to overlap with the game's stack, and so VI memory reads tripped up the memory protection.

**Comment by YTQ00** [comment]
It's working great now. Thank you so much!
