### ISSUE TITLE
.

### ISSUE THREAD

**Issue by GCRVL** [emukidid/swiss-gc#736]

**Comment by Extrems** [comment]
We need a dump.

**Comment by GCRVL** [comment]
Don't have a dump.

CPU is DOT-CPU-01.

No "Press Start" in the menu.

**Comment by Extrems** [comment]
Do you not have an SD card adapter? All you need to do is enable file management, then copy `dvd_rom.bin` and `ipl.bin` from the system device.

**Comment by Extrems** [comment]
Fixed in 9a56361 (r1380). I'd still like a dump so that it can be properly supported though.
