### ISSUE TITLE
[Issue]: on the current R1365 there's a green screen that shows within' a milisecond before booting to game

### ISSUE THREAD

**Issue by ScytheandGenesisGames** [emukidid/swiss-gc#739]
### Describe the bug

I have the latest R1362 of Swiss and when I launch my games there's sometimes a green screen then it loads the game, not to sure what could be the cause of that during boot for the game.

It might be something do with the patches I'm not sure about that could be the cause.

I also deleted the patch folder and it still does this brief green screen before it goes to the warning screen.

### Steps to reproduce

Launch a copy of Paper Mario Mario Thousand Year Door and wait for it to boot and load the game.

The green screen will be a brief second then shows the warning screen.

### Expected behavior

I expected it will boot normally like a there was a disc inside without this kind of issue.

**Comment by Extrems** [comment]
Fixed in 5d8d97d (r1375).
