### ISSUE TITLE
[Issue]: Dragon Ball Z: Budokai 1 and 2 Stuck in "duel" Menu

### ISSUE THREAD

**Issue by TimeToGetCereal** [emukidid/swiss-gc#743]
### Describe the bug

After selecting player 1 vs COM and picking characters... the map will load but the game will freeze. Also found the game(s) had a "bumpy" screen effect when locked at 480p.

Was found to be an issue on GCloader 2.0.0 BETA
Recently updated to GCloader 2.0.0 and same result

Updated to latest release of Swiss GC (Ver:0.6r1362).

Attempted different SD cards

Used both compressed .iso and non-compressed .iso.

Trying to identify and raise awareness to an issue so that it can hopefully be better for others someday! :)

Love the project overall. Great to see the progress that is made on it consistently!

### Steps to reproduce

Load Dragon Ball Z: Budokai with GC Loader and Ver:1362.

In main menu, select "duel"

Select characters...

Will freeze on map selection (as shown in screenshot below).

For Budokai 2:

Same process of loading game with GC Loader and ISO.

In main menu, select "duel"

Will freeze before selecting characters.

### Expected behavior

Budokai: Map screen to display upon selecting characters.

Budokai 2: Characters to be selectable.

### Add screenshots

![Budokai1Freeze](https://user-images.githubusercontent.com/115675365/195478338-cfd320a2-c5e6-4c80-b16e-c4bb2136c5aa.jpeg)
![Budokai2Freeze](https://user-images.githubusercontent.com/115675365/195478347-db17cce9-ad27-4cc8-b163-d900ca1ef3c1.jpeg)

**Comment by Extrems** [comment]
> Also found the game(s) had a "bumpy" screen effect when locked at 480p.

These are ones of the very few games that are impossible to display in 480p, as they're field rendered.

**Comment by Extrems** [comment]
I cannot reproduce this issue in either game.

**Comment by TimeToGetCereal** [comment]
Good to know regarding the 480p field render.

Hmm okay. I can try some more troubleshooting steps when i’m available again.

I could reformat my drive(s) and make fresh ISO’s again (including my sd2sp2 but that’s a stretch).

I can perhaps try to insert the sd card directly into GC Loader as opposed to going through a 6 inch extender for my 3D printed disk tray… doubt that is it but worthy of trying.

Any other options or advice that’s relevant?

How can i access log info to be more helpful for tickets?

Thanks!

**Comment by Extrems** [comment]
> How can i access log info to be more helpful for tickets?

USB Gecko debug output can sometimes be useful, but this is likely some kind of medium error or a hardware defect.
