### ISSUE TITLE
[Question]: Loud click and initialise dvd after picoboot installation

### ISSUE THREAD

**Issue by DorDur215** [emukidid/swiss-gc#744]
### Describe your question

Ok so today I installed picoboot into my gamecube.

Everything is working great but I've noticed everytime I turn on my gamecube it does a loud click and says "initialise dvd" for a while then the video cuts out for a second and then im in the swiss menu.

I do not have a disc inserted at all.

This does not happen when I leave the disc drive door open.

This never happend with other swiss booting methods (action replay disc, xeno modchip) as far as I remember.

Is this normal behaviour? Can I somehow make it stop doing that?

Also I still have my xeno modchip installed on the disc drive in addition to picoboot. Could that be the issue?

**Comment by Extrems** [comment]
A loud click is unusual. The video cutting out is normal if your video mode setting differs from the default.

**Comment by DorDur215** [comment]
Ok so I found out when I phisically move the laser to the inner end of the rail and then start the gamecube it doesn't click.

When I reboot the gamecube after that without moving the laser again it clicks again.

So for the click to not happen I have to move the laser to the inner part of the rail before every boot. I will obviously not do that since it's propably not healthy for the disc drive.

And both the click and the "initialise dvd" don't happen when I leave the lid open.

I mean in the grand scheme of things it's not really that big of a deal but it's kinda bothering me :/

**Comment by Extrems** [comment]
Unfortunately for as long as the GC Loader exists, there's no alternative.

**Comment by emukidid** [comment]
For the record, picoboot or not, the original menu would do this exact same thing too. Something has to initialise the disc drive and unfortunately hard hitting the laser to a fixed position is what the drive does when you ask it to reset.
