### ISSUE TITLE
In game reset not working when SD Card is formatted in exFAT

### ISSUE THREAD

**Issue by Voyager-III** [emukidid/swiss-gc#745]
### Describe the bug

I am using Picoboot and I formatted my SD card to exFat and when you try IGR when playing a game the console resets to the Gameube logo and then into the system menu, you have to turn the console off then back on to boot back to Swiss, this happens when using both SD2SP2 and GC2SD when the SD Card is formatted as FAT32 it is OK no problems

### Steps to reproduce

Format the card to exFAT and try IGR when playing a game

### Expected behavior

IGR to work when SD card is formatted as exFAT

**Comment by AliciaBurrito** [comment]
Has there been any update on this? I've been experiencing the same issue.

**Comment by Extrems** [comment]
Fixed in 3e351a7 (r1700).
