### ISSUE TITLE
[Issue]: Tony Hawk's Pro Skater 4 doesn't boot

### ISSUE THREAD

**Issue by Im-Ben** [emukidid/swiss-gc#749]
### Describe the bug

When booting THP4 using Swiss v0.6r1387 the game will freeze after the initial animations.

### Steps to reproduce

Tried every available graphics setting and had someone else test to confirm that it's not just me. It's the only one of my 80 games that I can't get to work.

### Expected behavior

Game works as expected in version v0.6r1290

**Comment by Papy-G** [comment]
1362 is the later to work fine in regard to THPS4.

**Comment by Extrems** [comment]
I'd like to give a shoutout to ArtX for making such wonderful and bugfree hardware.

**Comment by Extrems** [comment]
This issue is related to eFB RGBA pokes, which is similar to the previous issue with eFB Z peeks.

**Comment by Extrems** [comment]
Fixed in 7882785 (r1400). Probably. I doubt this is the last I'll hear of this.
