### ISSUE TITLE
[Issue]: Audio problems in RE2 / RE3

### ISSUE THREAD

**Issue by squeeeb** [emukidid/swiss-gc#752]
### Describe the bug

I didn't see a report for this, apologies if I missed it.

I'm getting bad audio in Resident Evil 2 and 3.  It could be described as crackling.  It seems to be only the music tracks during gameplay.  The intro cinematics are fine.

I've played a few dozen games and these are the only two I've noticed this issue on.  Note that no custom options are set at game launch except forcing 480p.

### Steps to reproduce

Launching the RE2/RE3 ISOs via SD card or FSP - both result in the same behavior.  Everything is fine in the main menu and cinematics, but the issues are noticeable immediately once gameplay starts.  Here is a video I recorded of it occurring:

https://youtu.be/IU4J8YWIkA8

### Expected behavior

Normal audio output.

**Comment by Diegorella** [comment]
try deleting the patch folder.

works for me in some cases.
have you tested on a previous swiss?
see if it's the version.
disable the IGR, and the IPL also helps.
Test on 480i RCA to see if it's progressive video streaming.

**Comment by Extrems** [comment]
Fixed in 4d958fd (r1395).
