### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Akurie** [emukidid/swiss-gc#753]
### Describe your question

Good Day, I am running with a pi pico with .2v picoboot.uf2 latest Swiss loaded to a 126 Micro SD (FAT32) plugged into a GC2SD in slot A. I followed the instruction to the fullest extent and I keep Getting the CG IPL not Swiss. I am sure I might be missing something. Looking for guidance.

**Comment by Extrems** [comment]
Please go to the PicoBoot project for PicoBoot questions.
