### ISSUE TITLE
[Issue]: Loading game via BBA and FSP gives error "Failed to setup the file (too fragmented?)"

### ISSUE THREAD

**Issue by sdufus** [emukidid/swiss-gc#754]
### Describe the bug

I currently load Swiss from a SD->GC memory card adapter. Console has GCVideo installed and an SD2SP adapter.

I was previously using Swiss v0.6 rev 1236. Games loaded fine via FSP or SD2SP.

A while back I upgraded to v0.6 rev 1318 and FSP loading stopped working. I can load FSP location and still display the games properly. However, when I attempt to load a game, a few "Patching File" progress bars show up before the following message appears:

_Failed to setup the file (too fragmented?)_

I then waited and thought it was a bug and tried subsequent releases of Swiss after that, like rev 1318 and rev 1387, but FSP loading still errors out.

I've tried different SD cards of different brands and sizes, formatting them in FAT, FAT32 and exFAT with different block sizes with no change in behavior.

In addition I've tried changing the Swiss configuration location from memory card (SD to GC mem card adapter) to SD2SP. The issue still persists.

Is there something I've overlooked?

In the meantime I've gone back to using rev 1236, but would like to be able to use a new version with upcoming devices that'll support Game ID functionality.

More than happy to provide any screenshots, video or anything else if it'll help with troubleshooting.

### Steps to reproduce

Load a game using FSP with any version of Swiss from rev 1318 onward.

### Expected behavior

Game should load without error.

**Comment by Extrems** [comment]
Cannot reproduce. Make sure you're using FSP 2.8.1 Beta 29, that `/swiss` is properly writable on the server, and that sufficient disk space is available on the server.
