### ISSUE TITLE
[Issue]: Exception (DSI) occured

### ISSUE THREAD

**Issue by Abalduin-adm** [emukidid/swiss-gc#755]
### Describe the bug

While starting i get this error message, not sure how to handle it

### Steps to reproduce

downloaded the swiss-gc -> [Macho Nacho Productions](https://www.youtube.com/c/MachoNachoProductions) , 

### Expected behavior

to boot into the main menu of swiss-gc

### Add screenshots

![BOOT1](https://user-images.githubusercontent.com/110982992/202025670-42970085-9809-4c96-99fb-f0ae413c5b7b.jpeg)
![BOOT2](https://user-images.githubusercontent.com/110982992/202025672-baccad45-2a10-4148-8894-162b1a2d9231.jpeg)

**Comment by Extrems** [comment]
This crash is inside iplboot. See redolution/iplboot#26.
