### ISSUE TITLE
Looking for the perfect Pixel (448p, black bar…)

### ISSUE THREAD

**Issue by ChipsLabs** [emukidid/swiss-gc#756]
### Describe your question

Got a NTSC-J DOL 001 NGC with picoboot freshly installed. I use a GCPlug with the latest GCvideo 3.1 firmware and an old 640 x 480p phillips monitor (having pixel perfect image with it).

My question : when I play 640 x 480 games (Luigi’s Mansion) the game looks perfect. I can use scanlines from GCvideo.

But when I play F-Zero GX forced 480p with swiss, the in and out resolution is 448p.
The game show in full screen, and looks good. But scanlines from gcvideo are not pixel perfect.

So what’s happening when GC video show me 448p in full screen ? Should’t I have black bars up and down to get pixel perfect image and perfect scanlines.
Or is the forced game is indeed in 480p, and this is a bug from gcvideo ?

Thanks for your help

### Add screenshots

![C38910C0-DD1E-4FED-B8BA-6E54913A5410](https://user-images.githubusercontent.com/104869127/202867283-53f29b75-b2b5-4adc-8704-ad78aa45043a.jpeg)
![3577417E-8898-44C2-8A90-085FBA0C20AB](https://user-images.githubusercontent.com/104869127/202867285-486c25db-4ba4-4bcb-91bc-541ab9105aba.jpeg)
![25C967C0-CECA-482D-B5C4-565A7C701CBF](https://user-images.githubusercontent.com/104869127/202867287-fbeed757-025f-4b9d-bb88-7a32cb7992ad.jpeg)
![3BD29255-9951-44AB-9952-7B0C3D0F9C14](https://user-images.githubusercontent.com/104869127/202867290-790a1ee0-4e65-4d7b-8a1f-43b5ba305a9c.jpeg)
![673FE460-5738-4E47-BE80-BF5FE0B3D5E5](https://user-images.githubusercontent.com/104869127/202867293-d2e78afb-5903-4c55-986c-e0e456798e01.jpeg)
![9B4AC832-0017-4BAD-BD89-EC55CA8B09BD](https://user-images.githubusercontent.com/104869127/202867295-dd635871-596c-4305-ab0e-b57dfce018ee.jpeg)

**Comment by Extrems** [comment]
This is the expected behavior from turning off Fix Resolution, which you shouldn't be doing.
