### ISSUE TITLE
[Issue]: 'same' game unable to share memory card?

### ISSUE THREAD

**Issue by Eduardolicious** [emukidid/swiss-gc#758]
### Describe the bug

using gcloader with its memory card functionality. what i'm trying to do is, i have a copy of f-zero gx on there, as well as a copy of the 'turns f-zero gx into ax' hack (this one, if anyone cares https://www.romhacking.net/hacks/6857/ ), and i expected them to share the same virtual memory card, but it doesnt seem to be working, unless i'm missing something. ax has a save, and THINKS its saving to a gx save, but gx doesnt get anything unlocked. I assume the way the gamecube/arcade memory card sharing originally worked was that both versions just saved as the same game or id or whatever, but im not able to get that sorta functionality behaving

if its writing saves based on filename or something and it just wont work as is/by design, is there some way i can specify a virtual memory card for these two games to save?

thx. hopefully what im trying to explain makes some sort of sense haha

### Steps to reproduce

- copy fzerogx and fzeroax to gcloader and enable writing
- create profile in gx, works fine
- run ax, play game, unlock parts, game displays that it's saving the items to your gx save
- start gx again, no unlocked parts

### Expected behavior

expected an iso and a hack of the same iso to write to the same memory card/save

**Comment by Extrems** [comment]
This is an issue with the mod and also occurs with real memory cards.
