### ISSUE TITLE
[Issue]: Mid-boot video appears to load in 480p when using component cable

### ISSUE THREAD

**Issue by timesscar** [emukidid/swiss-gc#760]
### Describe the bug

When loading Swiss, the preboot text displays in 480i, but when Swiss loads, it appears to be in 480p for 1-2 seconds.  Afterward, the forced 480i setting takes effect and it switches resolutions.

Configuration:
DOL-001 console
Picoboot to sd2sp2 with latest version of swiss
Trinitron 480i-only component video connected via Bitfunx component cable

### Steps to reproduce

Connect cable to TV
Power on gamecube.  Observe video behavior.

### Expected behavior

The Swiss menu should immediately load into 480i instead of starting in 480p.

### Add screenshots

https://user-images.githubusercontent.com/10659660/206527685-503a0507-d0f5-496a-bdb3-dcef45ad4d9f.MOV

**Comment by timesscar** [comment]
Video didn't seem to upload right, but here are the relevant frames
![image](https://user-images.githubusercontent.com/10659660/206528199-3d2fa717-ce1c-4ac6-bd2d-e348a33c374e.png)
![image](https://user-images.githubusercontent.com/10659660/206528265-487f3711-264f-4884-b187-bd7a3abdb683.png)
![image](https://user-images.githubusercontent.com/10659660/206528357-e1f6152b-6ef7-4a03-a809-6bed166b3174.png)

**Comment by timesscar** [comment]
Well, that was a quick close.  Is there some technical reason why it is not considered?

**Comment by Extrems** [comment]
Ugh, fine. I'll see what I can do, but this isn't dangerous.

**Comment by Extrems** [comment]
Fixed in 8a69e1b (r1399).
