### ISSUE TITLE
[Question]: RE4 under forced 480P, the image appears horizontal stripes

### ISSUE THREAD

**Issue by BeijingFan407** [emukidid/swiss-gc#766]
### Describe your question

Sorry, please allow me to use the translation software to ask this question

I noticed that when swiss is set to force 480P, some regular bars appear on the RE4 or RE1 images

If the 480P mode is not forced, this problem is not solved by using the B button on the gamepad, but the image sharpness is slightly decreased

Is there a solution?
(I use GCVIDEO for my video output, which goes to the plasma TV via an HDMI cable)
(Max resolution for plasma TV is 852x480)

### Add screenshots

![1](https://user-images.githubusercontent.com/52919966/212477027-0317f96b-8124-448c-8333-f80c4c6eb10a.JPG)
![2](https://user-images.githubusercontent.com/52919966/212477037-82b2b756-63cd-4e32-8293-62a2f1b2e03c.JPG)

**Comment by Papy-G** [comment]
It has to do with alpha dithering I believe, try to turn on or off the option in SWISS. ;)

**Comment by BeijingFan407** [comment]
> It has to do with alpha dithering I believe, try to turn on or off the option in SWISS. ;)

Thank you very much for your reply

I tried to set “disable alpha dithering” to “Yes”

This problem is solved.

But in the forced 480P mode, while the picture is sharp, the colors seem to feel weird.

Holding the B button on the gamepad to open 480P looks more natural

Anyway, thank you very much
