### ISSUE TITLE
[Question]: 【RE4】Setting "disable alpha dithering" to "YES" causes problems with Greyscale levels

### ISSUE THREAD

**Issue by BeijingFan407** [emukidid/swiss-gc#767]
### Describe your question

Sorry, please allow me to ask the following question again using the translation software.

To get rid of the horizontal stripes on the image, I tried setting "disable alpha dithering" to "YES"
The horizontal fringe problem is solved.

But there are new problems

After disable alpha dithering is set to YES
The gray level of the image seems to decrease, resulting in strange looking colors.

Is there a solution to this problem?

thank you

(I used a GCVIDEO and HDMI cable to connect my plasma TV.)

### Add screenshots

【Setting "disable alpha dithering" to "YES"】
![3](https://user-images.githubusercontent.com/52919966/212550776-976e8d8c-7954-4800-af3d-d0ed7a6dad42.JPG)

【Normal】
![4](https://user-images.githubusercontent.com/52919966/212550834-74c6f6c7-cc50-449f-a8ee-1136af763d70.JPG)

**Comment by Extrems** [comment]
Yes, this is what dithering does. It reduces banding. You have to pick your tradeoff.
