### ISSUE TITLE
[Issue]: BBA for Online Play is disabled when loading ISO via FSP (without warning the user so)

### ISSUE THREAD

**Issue by ChristinMilloy** [emukidid/swiss-gc#768]
### Describe the bug

BBA not detected by Game when Game is loaded via FSP over BBA

### Steps to reproduce

After loading game via FSP, trying to use game's online features (e.g. PSO) reports "no BBA (detected) in Serial 1," when in fact BBA is installed in Serial 1 (but I guess already being used for FSP).

### Expected behavior

I realize that making online functionality work simultaneous with FSP Loading is probably not achievable (thus, I can understand how such a bug report would be "closed as won't fix"), however it would be nice to give the user a warning about this issue when loading a game with BBA functionality over FSP.

For example, when attempting to load one of the PSO games (or other popular game with BBA functions) over FSP, Swiss could give a warning "Please note: BBA Online play is not available when loading via FSP [Continue] - [Cancel]" or a similar message.

Ultimately, I resolved the issue by loading PSO ISOs via SD2SP2. But.....

I admit my own foolishness here -- As of this moment, it seems like common sense to me that BBA would not work in-game after FSP load... However, during the day time I did not realize this, and it confused me for about three hours trying to troubleshoot it. So a warning of this nature would be very helpful for foolish users such as myself. Thanks :)

**Comment by Extrems** [comment]
Fixed in 2cb3867 (r1518).
