### ISSUE TITLE
marged 4/3 in hdmi

### ISSUE THREAD

**Issue by gego51** [emukidid/swiss-gc#769]
### Describe your question

Can we configure Swiss for playing games to marged 4/3  on 16/9 in HDMI?

**Comment by Extrems** [comment]
No, and it's not possible.

**Comment by gego51** [comment]
Ok. Thanks for your answer.

You can't add blacks marges in "3d+2d" on the option "force widescreen" called "marged"?

I know the gamecube can't render 16/9 screen, but stretching horizontal scale of game's render to 0.75 and hading black marges could not impossible.

**Comment by Extrems** [comment]
It is impossible because the hardware does not support ratios smaller than one.

**Comment by gego51** [comment]
I don't thinks to reduce the render of hardware, but add an overlay (for marges) to the game with "widescreen force" mode to get a simili 4/3 merged show on widescreen TV.

**Comment by Extrems** [comment]
That's even less possible.

**Comment by gego51** [comment]
Ok. Thanks you for your's answers.

**Comment by Papy-G** [comment]
Why would one like to force widescreen, then crop to 4/3?

There are zoom options on TVs called "pan & scan", or even more obviously "4/3", combined with overscan to crop around a little, may give you the result you expect. Some smarter TVs might even have zooming option with 4/3 ratio, crop top and bottom, to reduce side black bars, and icing on the cake, pseudo-spherical display distortion to simulate CRT rendering!

I sometimes wish HDMI had the abilities the SCART had, such as turning on or off the TV, automatically selecting input, signal nature, display ratio...

**Comment by Extrems** [comment]
It does. It's called HDMI CEC.
