### ISSUE TITLE
[Issue]: Marvel Nemesis: Rise of the Imperfects; presents aesthetic failures

### ISSUE THREAD

**Issue by FascistMan** [emukidid/swiss-gc#771]
### Describe the bug

The game starts normal and is playable most of the time, but it has a horrible green bar at the bottom of the screen, which causes the game's display area to shrink considerably.

Psdt: I'm using the SD2SP2 adapter with the game in its NTSC version.

### Steps to reproduce

Just start the game by default on the micro SD (I don't remember what was the configuration which when activated the intro of the Gamecube appears after patching the game, but the thing is that the black bar does not appear in this section and it will only appear when the name of the title already appears on the screen.)

### Expected behavior

I would like to see if you could please try to solve this error with some video patch or some other configuration, because the game is already playable but that huge "black bar" ruins the gaming experience.

**Comment by Extrems** [comment]
I'm struggling to see what you mean that's so game breaking.
![GVLE69-1](https://user-images.githubusercontent.com/554978/213777267-e5aceb2b-c645-4f6f-bd1b-3d0660fd6902.png)
![GVLE69-2](https://user-images.githubusercontent.com/554978/213777287-c5595e91-d7f3-4ea2-b19a-0598106848d6.png)

**Comment by Extrems** [comment]
I think you forced 480p. This doesn't occur with the automatic 480p.

**Comment by FascistMan** [comment]
@Extrems  Look at this, this is what I mean.

![IMG_20230120_161658](https://user-images.githubusercontent.com/105764113/213807377-de8682ea-e5ab-4ba5-8fe0-39bf6313bfc9.jpg)

![IMG_20230120_161619](https://user-images.githubusercontent.com/105764113/213807409-e575f0c0-0bfa-4845-8d50-7ddb0115ac42.jpg)

480p video mode is default, I also used 480i on my crt and iodo stays the same.

**Comment by Extrems** [comment]
The default is auto, and has different behavior from the 480p or 480i options.
