### ISSUE TITLE
Slow, compatibility issues

### ISSUE THREAD

**Issue by djchildren** [emukidid/swiss-gc#773]
### Describe the bug

New version Swiss v0.6r1400 shows a loading message when scrolling thru every file, it doesnt read subfolders and .nkit does not compatible for run games

### Steps to reproduce

Running on Gamecube with Raspberry Pico with Picoboot (actually Cubeboot) and GeckoSD

### Expected behavior

Previous version Swiss v0.6r1387 runs without any problem last mentioned

**Comment by Extrems** [comment]
Cannot reproduce.
