### ISSUE TITLE
[Question]: USB Gecko Debug Output

### ISSUE THREAD

**Issue by SquiddyGoat** [emukidid/swiss-gc#775]
### Describe your question

How is the "USB Gecko Debug Output" option supposed to be set up? I have a USBGecko plugged into Slot B with it's cable connected to my PC. I can load games through it just fine, but I'm not sure how to get the OSReport prints from it.

Attached is a screenshot of what swissserver.exe prints when this option is enabled.

EDIT: I'm running my games through BBA usually, but this also happens when running games from SD2SP2.

### Add screenshots

![img](https://user-images.githubusercontent.com/77563767/215158020-fdb4a9a8-263a-4db1-9183-59ec2d306a11.png)

**Comment by Extrems** [comment]
You need to use PuTTY in serial mode, or other terminal emulator. `swissserver` is for file serving.

**Comment by SquiddyGoat** [comment]
> You need to use PuTTY in serial mode, or other terminal emulator. `swissserver` is for file serving.

I had to enable VCP in the driver settings, and the USBGecko port appeared as COM3.

I can read the debug output through PuTTY now, thank you.
