### ISSUE TITLE
Allow Game ID passing to memcard pro without revision number in ID

### ISSUE THREAD

**Issue by kousaka** [emukidid/swiss-gc#785]
### Describe the feature

I don't know how many people would actually care to have different memory cards for different revisions of the same game. Don't even know how many actual games have multiple revisions.

But the default behavior I think should match what most people would use. Perhaps the revision can be left out as an option in swiss.

Makes migrating save files into memcard gc pro easier

**Comment by Extrems** [comment]
This is not our responsibility.
