### ISSUE TITLE
Can you customize the Swiss Loader menu?

### ISSUE THREAD

**Issue by Marko2155** [emukidid/swiss-gc#786]
### Describe your question

So my friend and I wanted to mod my DOL-001 GameCube with PicoBoot and run Swiss on it. He wanted to make the menu look different than the normal Swiss menu and for that, I'm asking if there is any way to change what the menu looks like? If it already exists, then send me a link or something in a comment. I made the "screenshot" in MSPaint.

### Add screenshots

![Swiss Normal to Swiss Custom](https://i.imgur.com/brqkP1D.jpg)

**Comment by Extrems** [comment]
I'm not sure I understand the difference.

**Comment by Papy-G** [comment]
One can rename files adding numbers at the beginning so the games appear in a choosen order.

**Comment by Marko2155** [comment]
I meant change the theme of Swiss

**Comment by Extrems** [comment]
You can change the backdrop.
https://www.gc-forever.com/forums/viewtopic.php?f=25&t=5178

**Comment by Marko2155** [comment]
Alright, thanks.
