### ISSUE TITLE
[Question]: Migrate from MC to SD w/o SP2?

### ISSUE THREAD

**Issue by coolpick** [emukidid/swiss-gc#787]
### Describe your question

Hi guys,

I'm trying to figure out if this is possible.  My Gamecube doesn't have a serial port 2.  I'm trying to migrate to an emulated memory card because my current card is nearing empty.  I managed to format an emulated memory card, but I'm having no luck moving data to it since either port A or B is already filled with the SD Gecko.  

Is it possible to move my memory card saves to an emulated memory card without SP2?  If so, how can I go about this?

Thanks 😃

**Comment by Extrems** [comment]
Use GCMM to make a raw backup, then use that as your new image.

**Comment by coolpick** [comment]
> Use GCMM to make a raw backup, then use that as your new image.

DOH!  Why the didn't I think of that?  I swear it's always the simple things.  Thanks!
