### ISSUE TITLE
[Issue]: Latest update breaks video sync with gbihf-ossc.dol+cli on the retrotink 5x

### ISSUE THREAD

**Issue by iguanatamer** [emukidid/swiss-gc#788]
### Describe the bug

It causes the screen to roll and for the video to not switch to 360p on the retrotink 5x. I am using official component cables. I rolled back to swiss_r1387 and it syncs again and works just fine.

### Steps to reproduce

Boot up the latest build of swiss and launch gbihf-ossc.dol+cli with official component cables and a retrotink 5x.

### Expected behavior

For video on gbi to sync.

**Comment by Extrems** [comment]
Duplicate of issue #779.

**Comment by iguanatamer** [comment]
Tried that and now swiss freezes on trying to start gbi. The dol and cli file work fine when I roll back swiss.
