### ISSUE TITLE
[Feature request]: boot animation support

### ISSUE THREAD

**Issue by f3bandit** [emukidid/swiss-gc#789]
### Describe the feature

Add boot animation support like [flippyboot - IPL](https://github.com/OffBroadway/flippyboot-ipl)
please and thank you

### Add screenshots

![image](https://user-images.githubusercontent.com/4943324/225176286-bcfd05b7-d96f-4e01-957c-482b289accc0.png)

**Comment by Extrems** [comment]
This is already covered by the boot through IPL option.
