### ISSUE TITLE
[Feature request]: Broadcast GameID over JoyBus Controller Line

### ISSUE THREAD

**Issue by SamDamDing** [emukidid/swiss-gc#790]
### Describe the feature

Can this be added? I know it can be done over EXI but it'd be much easier to use a flex cable adapter on the controller port than soldering. The purpose of this feature is to relay the GameID for configuration of aesthetic peripherals depending on the game being played, like rgb lighting.

**Comment by Extrems** [comment]
We already support PixelFX's N64 GameID standard for use with BlueRetro.

**Comment by SamDamDing** [comment]
Thanks! I can't find any documentation on that for Swiss or on [this wiki](https://www.sites.google.com/site/consoleprotocols/home/nintendo-joy-bus-documentation/joybus-command-list?authuser=0) . Is the command still `0x1D`?
