### ISSUE TITLE
[Feature request]: Swap Analogsticks Input

### ISSUE THREAD

**Issue by KayJay-EU** [emukidid/swiss-gc#791]
### Describe the feature

Swapping the Left & Right Analogstick Input for Shooters that didn't support swapping Movement Stick with Aim Stick.

**Comment by Extrems** [comment]
I'm not sure if this is a good idea as it would also affect menu navigation.

**Comment by KayJay-EU** [comment]
> I'm not sure if this is a good idea as it would also affect menu navigation.
For some maybe,
I always use the D-Pad for navigating menus.

**Comment by Extrems** [comment]
Fixed in 431013a (r1438).
