### ISSUE TITLE
[Issue] Swiss 1420 Does Not Properly Disable Alpha Dithering

### ISSUE THREAD

**Issue by GK6475** [emukidid/swiss-gc#792]
After updating to Swiss 1420, the disable alpha dithering feature no longer seems to work. I was able to tell using Zelda: Wind Waker since it normally has a lot of dithering at nighttime. In previous Swiss revisions, the feature disabled most of that dithering. Now it doesn’t appear to work at all.

**Comment by GK6475** [comment]
Never mind, apparently this game just has a lot of dithering on its own.

**Comment by Extrems** [comment]
This feature is not intended to disable all dithering, but only dithering during alpha blending operations, as the error accumulate and become ever larger the more things are blended on top of one another.
