### ISSUE TITLE
Metroid Prime 2: Echoes (NTSC-U) Conditionals Don't Work

### ISSUE THREAD

**Issue by ReclaimerShawn** [emukidid/swiss-gc#793]
### Describe the bug

Basically, it seems as if some, if not all the codes with button conditionals on Metroid Prime 2 refuse to work. I have seen Code Types 28 and 20 fail in-game so far. I have also confirmed that the button address is the same as the reported address for codes while Swiss is running via USB Gecko, so this shouldn't be happening unless something's wrong on the end of the codehandler. Codes without conditionals seem to work.

Strangely enough, button conditionals work on Pokemon Colosseum, which makes me think this issue may be specific to Metroid Prime 2. This issue is present so far in r1387 and r1420. This bug might exist on versions even further back, as well.

### Steps to reproduce

Use any code with Code Types 28 and/or 20 and you'll see them fail. For example, place this code in a cheat file and attempt to use it in-game:
Enable Phazon Shot (Press L+R)
28704C24 00000060
041CC824 3B600004
041CC9BC 3BE00004
041DA590 3A600004
E2000001 80008000

However, this code without the button modifier works:
Enable Phazon Shot
041CC824 3B600004
041CC9BC 3BE00004
041DA590 3A600004

If you cannot reproduce this issue, it must be on my end. I've tried with a regular controller and a wavebird controller and gotten the same results, if that matters.

### Expected behavior

Pressing L+R on the Enable Phazon Shot code above should enable the code, and from there, the code should function like the code without the button conditional does. The code would normally cause your beam to shoot circular blue blasts, but this doesn't happen with the version of the code that has the button conditional.

**Comment by Diegorella** [comment]
you must disable IPL boot. and the igr.
and see if it works...

**Comment by ReclaimerShawn** [comment]
> you must disable IPL boot. and the igr.
> and see if it works...

Neither were or are enabled.

**Comment by ReclaimerShawn** [comment]
Issue is still present in r1443.

**Comment by ReclaimerShawn** [comment]
@emukidid I think I figured out a way to fix the button conditionals on Metroid Prime 2. I've only tried this on NeoGamma so far, but it works perfectly. I made a Gecko Code that I believe you could integrate into the game patcher. Here's the code:
(M) Button Conditionals:
04001500 A0630004
04001504 3D808000
04001508 906C1510
0400150C 4830A12C
0430B634 4BCF5ECC

This makes it so address 80001500 has a copy of the same value at the button address 80704C24. For some reason the code handler cannot read the address at 80704C24 with Codetype 28, so any code with a button modifier would fail. However, address 80001500 is perfectly readable with Codetype 20. Though, in order to completely integrate this, you'd need to also add a check to look at the G2ME01.txt file before the game launches and then have Swiss change any line that says 28704C24 to 20001500

**Comment by ReclaimerShawn** [comment]
@emukidid @Extrems Button activators are able to work after applying the following Master Code:
(M)
C6354E70 800018A8 //Hook 80354E70 to 800018A8
C636F000 800018A8 //Hook 8036F000 to 800018A8
2130294C 4E800020 //If 8130294C == 4E800020 (blr instruction) then
C730294C 800018A8 //Hook 8130294C to 800018A8
0441FD80 00000000 // 8041FD80 = 0
E0000000 80008000 //End

Roughly, here's what this code does:
80354E70 = 0x494A9238 (Set instruction to b 0x817FE0A8)
8036F000 = 0x4948F0A8 (Set instruction to b 0x817FE0A8)

If 8130294C == 0x4E800020 then
   8130294C = 0x484FB75C  (Set instruction to b 0x817FE0A8. Didn't see this get set in real time, so not 100% certain, but considering this is where the other hooks branched to, probably it.)
   8041FD80 = 0x00000000
End

I never saw 8130294C equal the blr instruction and I never saw 8041FD80 equal anything other than 0 in my short amount of time testing the code. If you want to fix the codehandler issue, put at least the first two lines into the DOL patcher to patch the game DOL before the game starts. If necessary, add the rest if crashes or restarts occur, I recommend including this not just to fix the codehandler, but also to allow the USB Gecko to hook, as the USB Gecko can only hook when this code is enabled.

**Comment by Extrems** [comment]
Let's see...
`80354E70` is VIGetTvFormat.
`8036F000` is ICFlashInvalidate.
`8130294C` is DCInvalidateRange in apploader.

This seems random.

**Comment by ReclaimerShawn** [comment]
I got the Master Code from here. It was originally a code made by CodeJunkies in the ARMax era, but goemon_guy converted every line except the last one to WiiRD. 
The forum posts are herehttps://wiird.gamehacking.org/forum/index.php/topic,5823.225.html.

Later on in the thread, it appears the same patches used for Pokemon Colosseum in Swiss also originated from goemon_guy and this thread. I personally do not know how the Master Code works other than what the codetypes mean, but it does fix the problem. 

If you want to test to see I'm right, true using any code with the button address without the (M) code and it'll fail. You could also try to enable WiiRD debugging and use a USB Gecko. It will also fail without the M code. 

The code isn't a full fix for the entire codehandler (for instance, you're apparently not able to take a full mem80/81 dump), but it does fix the problem reported in this issue. The other master code goemon_guy was trying to write presumably would fix any problems in the codehandler, but it crashes the game at the title screen. So, this would serve as a partial bug fix.
