### ISSUE TITLE
[Issue]: Exception (Program) occurred

### ISSUE THREAD

**Issue by blakezilla** [emukidid/swiss-gc#802]
### Describe the bug

Getting an error code when booting into swiss

### Steps to reproduce

Changed boot.iso, updated to new version

### Expected behavior

Expected to boot into swiss.

### Add screenshots

![IMG20230417183126](https://user-images.githubusercontent.com/79169813/232430610-5e713c6b-7672-4e39-80db-316f9e4e2e2c.jpg)

**Comment by emukidid** [comment]
I'm assuming GCLoader? Is it genuine? When you say you changed boot.iso, do you mean with the latest release? Lastly, "updated" mentioned in your description, does that mean just Swiss or did you update your GCLoader firmware too?

**Comment by Extrems** [comment]
That's indeed v0.6r1443 going by r2/r13. The executable appear to be corrupt, please make sure your GC Loader has firmware 2.0.0.BETA or later.

**Comment by blakezilla** [comment]
Hi there,
Sorry went to sleep, 
GC Loader was genuine, firmware up to date. My setup I have two sd cards, the first one did the above screen, the second one didn't boot anything. Tried recopying it over again. The first one did the same screen as above, the second one booted properly. Redownloaded a second time and recopyed and it booted.

Not sure what happened but it looks like it works now hopefully
