### ISSUE TITLE
[Question]: Certain code files not working

### ISSUE THREAD

**Issue by axlester** [emukidid/swiss-gc#805]
### Describe your question

I have a question about why some WiiRD code files work while other don't. I have them formatted the same way and they all encoded with ANSI and my SD file structure is right (for the revision I am using, gotta double check which one) and as I said some work files work and some don't unfortunately they are the games I wish to play with cheat codes (coz I have finished them before and I wanna have a bit more fun this time round).

**Comment by Extrems** [comment]
Make sure you're using v0.6r1443 or later as there were known problems with parsing the files.
