### ISSUE TITLE
[Question]: Can't load generic ISO9660 disc through BBA.

### ISSUE THREAD

**Issue by SquiddyGoat** [emukidid/swiss-gc#807]
### Describe your question

I'm trying to load a "gc-linux compatible ISO9660" .iso image via BBA using the latest Swiss. For some reason, even though I can boot .ISO and .GCM files this way, this particular .iso refuses to boot, saying "Device does not support clean boot".

Is this a bug?

### Add screenshots

![image](https://github.com/emukidid/swiss-gc/assets/77563767/79e4d010-2fb2-4d79-8b21-c798284b36e1)

**Comment by Extrems** [comment]
It's not a bug. Only devices attached to the disc interface can use clean boot.

**Comment by SquiddyGoat** [comment]
> It's not a bug. Only devices attached to the disc interface can use clean boot.

Whoops then... I'm not sure what clean boot is, but I guess I can't use this kind of .iso file to try reading files from DVD.

I'm using the BBA because I'm trying to load files into ram for a homebrew program. If I store my assets on an SD card for reading, would that basically be the same thing as loading them from a disc?

**Comment by Extrems** [comment]
Swiss' hypervisor is only compatible with Dolphin SDK software. Homebrew and unlicensed software must be booted as-is.

Your program should support any relevant storage device on its own.

**Comment by SquiddyGoat** [comment]
> Swiss' hypervisor is only compatible with Dolphin SDK software. Homebrew and unlicensed software must be booted as-is.
> 
> Your program should support any relevant storage device on its own.

Sorry for the late reply,

Thanks for the info, I'll try to figu
