### ISSUE TITLE
[Question]: Config Failed to Save

### ISSUE THREAD

**Issue by gbw41** [emukidid/swiss-gc#811]
### Describe your question

Hey I have an issue with trying to save my settings to stay at 480i it wont save it. what  do I need to do to put it under gc loader because I do not have a memory card with an sd slot for slot a or b?

**Comment by Extrems** [comment]
Update your firmware to [2.0.0.BETA](https://github.com/danielkraak/GC-Loader/blob/master/Firmware%20Updates/GCLoader_Updater_2.0.0.BETA.dol) then set the configuration device to GC Loader.

**Comment by gbw41** [comment]
> Update your firmware to [2.0.0.BETA](https://github.com/danielkraak/GC-Loader/blob/master/Firmware%20Updates/GCLoader_Updater_2.0.0.BETA.dol) then set the configuration device to GC Loader.

How do I do that I’m a novice at best at this

**Comment by Extrems** [comment]
You simply put this executable file in the root directory of your SD card, then it should boot automatically if you have Swiss v0.6r1458 or later.
