### ISSUE TITLE
Problem opening Metal Gear Solid TS and WWE DoR 1&2

### ISSUE THREAD

**Issue by Bas962008** [emukidid/swiss-gc#815]
Hey guys!
I'm having issues at the moment getting metal gear and wwe games to work on my Picoboot'd GameCube. It's current version is r1476. When I load the game(MGS) the typical boot intro starts then goes to a green screen and 2-3 seconds later it goes pitch black. 

With Day of reckoning there is only just a green screen appearing and nothing else.

I'm using a Sony Bravia 46" with composite cables. My settings are currently on display through pictures. I have tried to drop most settings into auto and no's as I got pikmin 1 to finally play ![Uploading 247306980...]![image](https://github.com/emukidid/swiss-gc/assets/137232611/4d822638-4123-4f02-a3e6-46e41d973dcf)
![Uploading 247307058...]![image](https://github.com/emukidid/swiss-gc/assets/137232611/40fe92f8-8ff0-4bc0-a3e2-00e155147c8b)
![Uploading 247307157...]![Uploading 247307158...]![Uploading 247307159...]
![Uploading 247307198...]![image](https://github.com/emukidid/swiss-gc/assets/137232611/65436fa8-45f2-4c24-9883-a6415d797275)

**Comment by Bas962008** [comment]
![image](https://github.com/emukidid/swiss-gc/assets/137232611/9a58c151-911d-4b94-857e-c525b40670c8)

**Comment by Bas962008** [comment]
![image](https://github.com/emukidid/swiss-gc/assets/137232611/ed524a42-d07b-4f32-ac70-7be6966717fc)

**Comment by Extrems** [comment]
Cannot reproduce.
