### ISSUE TITLE
[Issue]: Dr. Muto usa version freezes in intro movie

### ISSUE THREAD

**Issue by Reideldm** [emukidid/swiss-gc#816]
### Describe the bug

 freezes in intro movie unplayable 

### Steps to reproduce

New game and freezes in intro movie

### Expected behavior

movie completely reproduced

**Comment by Extrems** [comment]
Sorry, you must use a better device such as the Broadband Adapter, Disc Drive, GC Loader, IDE-EXI or M.2 Loader.
