### ISSUE TITLE
[Issue]: LoZ Wind Waker (GZLE0100) will not start.

### ISSUE THREAD

**Issue by tjaldridge68** [emukidid/swiss-gc#819]
### Describe the bug

Starting on v0.6r1495 for GCLoader, Legend of Zelda: The Wind Waker (USA) no longer loads and stays on a black screen. Downgrading back to v0.6r1476 allows the game to load. Loading game of SD2SP2 as well as FSP results in a black screen when loading the game. Game ISO was already in nkit.iso format prior to updating Swiss. Other games tested load without issue.

### Steps to reproduce

Place the v0.6r1495 boot.dol onto SD card and insert into GCLoader. Boot the Gamecube and load the LoZ: Wind Waker (USA) nkit.iso from either SD2SP2 or Network adapter using FSP with default settings. Screen will go black and remain that way until system is powered off.

### Expected behavior

After loading the game image, the system should show the Gamecube logo then load the game.

**Comment by Extrems** [comment]
I can't reproduce this.
