### ISSUE TITLE
[Issue]: this disc cannot be read

### ISSUE THREAD

**Issue by zkade15** [emukidid/swiss-gc#821]
### Describe the bug

Hello Together

i have a problem with my gamecube.

I have on my SD2SP2 adapter the SD card with the autoexec.dol file 

and on the other SD card the games in .iso and the boot.iso file on it which I put on a SD card adapter.

My Gamecube recognized and booted the players at the very beginning. The second time I turned it on, I got the message I have to update Swiss. The third time I turned it on, the Gamecube tried to update the GC-Loader.

Since then my Gamecube does not boot, but gives directly the following message:

this disc cannot be read

Please read the instruction manual for more information.

Can anyone help me?

### Steps to reproduce

 -

### Expected behavior

-

### Relevant log output

```shell
-
```

### Add screenshots

[https://ibb.co/jJWKPjn
https://ibb.co/wCr3QKt
https://ibb.co/XfQjN2n
https://ibb.co/b2N6LXM](url)

**Comment by zkade15** [comment]
i am a new user and don't quite understand how to report a problem if something is missing please let me know

**Comment by zkade15** [comment]
https://ibb.co/b2N6LXM - Screenshot 1

https://ibb.co/XfQjN2n - Screenshot 2

https://ibb.co/wCr3QKt - Screenshot 3

https://ibb.co/jJWKPjn - Screenshot 4

**Comment by zkade15** [comment]
i am a new user and don't quite understand how to report a problem if something is missing please let me know

**Comment by Extrems** [comment]
You have a fake GC Loader Lite. Please seek a refund.
