### ISSUE TITLE
Newest release (Swiss v0.6r1527) will not boot on my GC Loader HW2[Issue]: 

### ISSUE THREAD

**Issue by Hattmeiny** [emukidid/swiss-gc#828]
### Describe the bug

Newest release ([Swiss v0.6r1527) will not boot on my gamecube.  If I use 1515 on GC Loader HW2, it wokrs no problem.

### Steps to reproduce

Using the latest swiss .iso will not let it boot.  Using the one found in the GC Loader folder or using the iso (renamed to boot.iso)

### Expected behavior

Expected the system to boot?

**Comment by Extrems** [comment]
I don't have a HW2 and I'm not able to reproduce this on HW1.
