### ISSUE TITLE
[Issue]: multi disc not supported anymore

### ISSUE THREAD

**Issue by Waterhazzerd** [emukidid/swiss-gc#830]
### Describe the bug

With the new update i cant play any game that needs to change discs.  When the game gets to when it needs to change discs i always get an error message.

### Steps to reproduce

When the game gets to when it needs to change discs i always get an error message. I'm also using a gc loader  

### Expected behavior

When the game gets to when it needs to change discs i always get an error message. The gamecube will tell you to turn the console off and check the user manual.

**Comment by Extrems** [comment]
I can't reproduce this. Are you on HW1 or HW2? Which firmware version?

**Comment by Waterhazzerd** [comment]
I think its hw2

**Comment by Extrems** [comment]
Unfortunately I'm not able to help with HW2 firmware bugs.
