### ISSUE TITLE
[Feature request]: Ignore BS2 boot, if check for known BS2 image failed

### ISSUE THREAD

**Issue by Sylph4** [emukidid/swiss-gc#833]
### Describe the feature

Would be good, to ignore setting of bios boot and just run a game, if check for known BS2 image failed (was added recently). Useful for running swiss on Wii for example using SD Gecko.

**Comment by Extrems** [comment]
You can provide a working image as `/swiss/patches/ipl.bin`.

**Comment by Sylph4** [comment]
Thank you! Works ok :) 

Closing
