### ISSUE TITLE
[Issue]: Swiss v0.6r1545

### ISSUE THREAD

**Issue by ZweiBR** [emukidid/swiss-gc#840]
### Describe the bug

I'm using a 128Gb LEXAR card and the folder above no longer shows apps and games
To make it work I have to select the card in the device selection option like a refresh and it will appear again

### Steps to reproduce

Swiss v0.6r1495

works well

```

### Add screenshots

https://a.imagem.app/oYJA2J.jpeg
https://a.imagem.app/oYqpfV.jpeg
https://a.imagem.app/oYJb5G.jpeg

**Comment by Extrems** [comment]
This is too little information to work with. Which revision are you coming from?

**Comment by Extrems** [comment]
Fixed in extremscorner/libogc2@73a829c.

**Comment by ZweiBR** [comment]
I apologize for the delay in responding.
The problem I reported has now been resolved in this latest version. [Swiss v0.6r1548]

**Comment by ZweiBR** [comment]
I apologize for the delay in responding.
The problem I reported has now been resolved in this latest version. [Swiss v0.6r1548]
Thank you very much for correcting
