### ISSUE TITLE
[Issue]: PAL game doesn't display language selection with Gamecube NTSC-J

### ISSUE THREAD

**Issue by Nicoluslog** [emukidid/swiss-gc#841]
### Describe the bug

I wanted to play to The legend of Spyro : A new Beginning but the game launched in English version by default. When I try the game with Dolphin, the language selection appears. The Gamecube is with Swiss v0.6 with an Raspberry Pi Pico and a SD2SP2 to stock the games and saves.

I would lke to play the game in French. Could you help me please ?

### Steps to reproduce

I just put the ISO (european version) game file in the SD card et launch it in Swiss.

### Expected behavior

I thought I could play in French like all the other games in the SD card.

**Comment by Papy-G** [comment]
did you try to boot trough IPL with Spyro to set the language in french in IPL first?

**Comment by Nicoluslog** [comment]
> did you try to boot trough IPL with Spyro to set the language in french in IPL first?

Yes, It tried with IPL activated and desactivated but the problem stay. I also tried with another iso file of this game.

**Comment by Extrems** [comment]
> did you try to boot trough IPL with Spyro to set the language in french in IPL first?

Why would you need to do that? System Language is under Global Settings.

**Comment by Nicoluslog** [comment]
> > did you try to boot trough IPL with Spyro to set the language in french in IPL first?
> 
> Why would you need to do that? System Language is under Global Settings.

In the Global Settings, I set the language on French. In all the games I can set the language when I launch them except with this Spyro game.

**Comment by Nicoluslog** [comment]
I found the solution. As I use a Bitfunx GC Video, I set the resolution to 480p but the game The Legend of Spyro only used English because the game thinks it is reading by a NTSC Gamecube. I set the resolution in "Auto" and the game worked very well and propose me all the possible languages.

Thank you for your help.

**Comment by Extrems** [comment]
Auto will force progressive video anyway. You'd only want 480p explicitly if it's 50Hz-only game.
