### ISSUE TITLE
Microsoft Defender Antivirus found threats in Swiss v0.6r1548

### ISSUE THREAD

**Issue by myeuropeanPAL** [emukidid/swiss-gc#842]
### Describe the bug

Cannot download it with latest Edge,
can download it with Firefox, but then it gets removed when trying to extract it.

### Steps to reproduce

Downloading or extracting Swiss v0.6r1548 on Windows.

### Expected behavior

No virus threat warnings

**Comment by lininjim2** [comment]
Try another browser, I've scanned with eset (todays definitions) no detection.

**Comment by myeuropeanPAL** [comment]
> Try another browser, I've scanned with eset (todays definitions) no detection. (downloaded with Opera)

I don't think that the browser is relevant, it is Microsoft Defender which founds threats and removes the files..
however it seems that Microsoft Defender only has a problem with the .7z file
I could download and unzip the .tar.xs file without any warnings

**Comment by Extrems** [comment]
Microsoft Defender seem to think all 7-Zip files are Trojan:Script/Wacatac.B!ml right now.
