### ISSUE TITLE
New ODE CUBEODE support?[Question]: 

### ISSUE THREAD

**Issue by azareth012** [emukidid/swiss-gc#844]
### Describe your question

In a few days a new ODE called CUBEODE will go on sale that claims to have compatibility with Swiss, but I can't find any reviews of the product and the website is simple www.cubeode.com, the latest Swiss update does not mention it anywhere, you know If this new ODE could have problems with Swiss? Is it a clone of GCLoader? Will it have Swiss support in the future?

The GCLoader Lite clone with swiss shows an update notice for GCLoader, but it cannot be updated since it is not an authentic GCLoader, will CUBEODE have the same problem? https://es.aliexpress.com/item/1005006180407836.html

Thank you.

### Add screenshots

![CUBEODE](https://github.com/emukidid/swiss-gc/assets/94273118/acc641f5-c9bd-4674-925c-46c9c9fb9c36)

**Comment by Extrems** [comment]
We don't know any more than you do.

**Comment by huangjielg** [comment]
CUBEODE is not GCLoader, so you can not upgrade it by using GCLoader's pack.
But you CAN upgrade swiss . Just replace boot.iso with newer one
