### ISSUE TITLE
[Issue]: any fmv or have audio streaming no music

### ISSUE THREAD

**Issue by 0bie0ne** [emukidid/swiss-gc#846]
### Describe the bug

(GC loader hw2) any games that gave audio streaming background music doesn't work but sfx works, I change to sd2sp2 and it work. formatted sd card as well no dice

### Steps to reproduce

example Alien Hominid no background music but sfx works.

### Expected behavior

I change to sd2sp2 and works,

**Comment by TwilightSlick** [comment]
I have a GC Loader HW2 (just got it yesterday), and I cannot reproduce this. Check your ISO, it might be bad.
