### ISSUE TITLE
[Issue]: Gamecube with ES CPU is identified as Wii

### ISSUE THREAD

**Issue by foxlet** [emukidid/swiss-gc#849]
### Describe the bug

When using a GameCube with an engineering-sample CPU, Swiss erroneously identifies the GameCube as a Nintendo Wii.

### Steps to reproduce

1. Swap the stock CPU with an ES CPU using a rework station
2. Load Swiss

### Expected behavior

GameCube is identified as GameCube.

### Add screenshots

![gc-es](https://github.com/emukidid/swiss-gc/assets/1627533/22dbd9ab-5b70-43a7-80d2-9cbcd750a21b)

**Comment by oscie57** [comment]
top 10 nintendo wii's of 2054

**Comment by Extrems** [comment]
Fixed in 41e0420 (r1561).
