### ISSUE TITLE
Need For Speed Underground 1 Crashes just after the game menu starts[Issue]: 

### ISSUE THREAD

**Issue by CvbePyramid** [emukidid/swiss-gc#850]
### Describe the bug

Its been happening since early builds of Swiss, i'm using it via real hardware, nkit nfs underground file(also tried iso files) same error occurs with r1196, 963, 990 and the latest 6r1562

### Steps to reproduce

Load the nkit/iso file through swiss, game loads until the menu screen, game starts the memory card reading and CRASHS the CONSOLE normally after the first screen of game menu or even after the memory card reading, i need to turn off the power source and reboot the console to start again swiss.

### Expected behavior

Game working normally just like NFS UNDERGROUND 2 

### Add screenshots

![Imagem do WhatsApp de 2024-01-21 à(s) 23 06 02_74928b64](https://github.com/emukidid/swiss-gc/assets/157330965/18b64af3-f731-46a3-8ddb-3e34a5dcbce6)
![Imagem do WhatsApp de 2024-01-21 à(s) 23 06 31_77953f5e](https://github.com/emukidid/swiss-gc/assets/157330965/c7170c52-174e-4333-ac38-5b40080bd4b4)
![Imagem do WhatsApp de 2024-01-21 à(s) 23 07 06_55bd1e05](https://github.com/emukidid/swiss-gc/assets/157330965/5dc862a5-0d62-485e-9101-2bc2a871f36c)

**Comment by CvbePyramid** [comment]
![Imagem do WhatsApp de 2024-01-22 à(s) 00 23 36_074f59d0](https://github.com/emukidid/swiss-gc/assets/157330965/880dd6a9-3250-4843-ac3d-37708515b8aa)

**Comment by Extrems** [comment]
Cannot reproduce using multiple regional variants, multiple device types, and both EXI bus speeds.
