### ISSUE TITLE
[Issue]: 1024MB card not working on swiss versions newer than r1318

### ISSUE THREAD

**Issue by Rempai** [emukidid/swiss-gc#852]
### Describe the bug

When I use any version above 1318 when opening a game and not using memcard emulation it will tell me my memory card is corrupt and needs to be formatted. While on 1318 and below the memcard does work and I'm able to save to it. I'm fine with memcard emulation however for game collections such as the zelda anniversary collection it would be nice to be able to use my memory card.

### Steps to reproduce

Get an 1024mb memory card
Download any version newer than 1318
disable memory card save emulation
open any game
press start to try go into the game

### Expected behavior

Open the game
get a pop-up to create sava data on the memory card
Play the game and save

**Comment by Papy-G** [comment]
What do you call 1024MB memcard?
Did you mix saves from US and Jap games on it?

I personally use a 2043 blocks Memcard, while not an official one, and had no problem using it.
Note that I never used virtual memory card function.

**Comment by Rempai** [comment]
[https://amzn.eu/d/0gLj9uN](https://amzn.eu/d/0gLj9uN)

I use one like this one I linked above. I only play US or EUR games on my gamecube since I haven't really found any JAP games I'm personally interested in at the moment yet.

**Comment by Extrems** [comment]
I can't seem to reproduce this using the blue 512MB memory card.

**Comment by Extrems** [comment]
I've now acquired the orange 1024MB memory card with Mcbazel-branded packaging and still cannot reproduce this.
