### ISSUE TITLE
[Issue]: Bugs after replacing Swiss version for GC Loader

### ISSUE THREAD

**Issue by benwiley4000** [emukidid/swiss-gc#854]
### Describe the bug

I'm using Swiss with GC Loader. Previously I was using the October 2023 release. Generally everything worked with that release, except for an inability to get past the initial game selection menu in Zelda Ocarina of Time/Master Quest. I upgraded to January 2024 and this problem was resolved, however there are some new issues, which persist even if I change to a different Swiss version (including Dec 2023 and the October 2023 release I used originally):

- A warning (perhaps important) that no writeable device is available, telling me to use SD card adapter, when I boot up a game (this problem went away after I upgraded my GC Loader firmware it seems)

- The initial bootup Gamecube animation is cut short very quickly and Swiss boots immediately

- DCP files are no longer hidden (I gave Game Boy Interface.DOL and Game Boy Interface.DCP in my root directory and now I can see both of them, not sure if this is intentional - before I could only choose the DOL).

### Steps to reproduce

Hard to say exactly, but for me it was triggered by changing the boot.iso file in the root directory of my GC Loader SD card. I also ended up deleting my prior swiss directory while I was debugging.

### Expected behavior

I should be able to change boot.iso without issue

**Comment by Extrems** [comment]
None of these are bugs, nor new things.

**Comment by benwiley4000** [comment]
I guess I wonder why it would have changed when I switched versions. Is the
GameCube bootup animation not supposed to finish before Swiss starts?

Ben

Le mar. 13 févr. 2024, 11 h 52 p.m., Extrems ***@***.***> a
écrit :

**Comment by Extrems** [comment]
That's an intentional feature called fastboot and was added 4 years ago.

**Comment by benwiley4000** [comment]
Thanks for the info. I can't figure out why the behavior was different
previously, so perhaps there's a bug there, but it's good to know it's now
working as intended.

Ben

Le mar. 13 févr. 2024, 11 h 59 p.m., Extrems ***@***.***> a
écrit :

**Comment by Extrems** [comment]
You probably followed some guide that told you to use one of the generic boot images under the ISO directory.

**Comment by benwiley4000** [comment]
Indeed I think you're right, because I recall renaming something to
boot.iso, whereas this time I just copied something that already had this
name. What's the difference in the images?

Le mer. 14 févr. 2024, 12 h 09 a.m., Extrems ***@***.***> a
écrit :

**Comment by benwiley4000** [comment]
Can fastboot be disabled?

Ben

**Comment by Extrems** [comment]
It can be by using one of the generic boot images, but you can also enable boot through IPL. You'll then see the boot animation before each game instead of Swiss.
