### ISSUE TITLE
[Question]: some games dont have a banner, how to add?

### ISSUE THREAD

**Issue by a4vx** [emukidid/swiss-gc#857]
### Describe your question

some of my games dont have a banner, how do i add one? I want it to be visible it in the swiss menu, as well as show in memory card menu. (for specifics its super mario 64 converted to a .gcm file using exp-n64v2.gcm)

**Comment by Extrems** [comment]
You should add a opening.bnr to the GCM file.

**Comment by a4vx** [comment]
Solved, took me a few hours to figure out

First, I converted the png to a bmp with dimensions of 96x32 with a bit depth of 24

Then I used GCFT to copy a .bnr file from a different rom that already has an image (to replace with the new image for the rom without an image)

Third, I used BMP2BNR to turn replace the contents of the original .bnr file with the image from the .bmp

Finally, I used GCFT to put the new .bnr file into the files of the rom without the image

Notes:
Not sure if this is just my computer, or my version of windows, but for some reason in command prompt I had to put the directory of the BMP2BNR.exe file, rather than just the BMP2BNR.exe file

also, BMP2BNR does not make a new bnr file, it just replaces the image from the old bnr file, so make sure you get a bnr file to change.
