### ISSUE TITLE
[Issue]: Mario Party 7 Drops Frames in Spin Doctor Minigame (Using r1614 of v0.6)

### ISSUE THREAD

**Issue by cambm94** [emukidid/swiss-gc#858]
### Describe the bug

As the title mentions, when playing Mario Party 7 and the Spin Doctor, Duel minigame is played the game drops frames to a very noticeable low level. I did verify that an unmodified system with the same Disc does not have any issues running the minigame. I was originally using v1336 I believe, but upgraded to v1614 with no change.

If there is something I am missing here, please call me out

### Steps to reproduce

1. Boot up Swiss with an SD2SP2 with the Mario Party 7 Disc in the system
2. Boot Mario Party 7 using the Disc from Swiss
3. If you already have a save file, use that as it likely already had the "Mini-Game Cruise" Unlocked, Select Mini-Game Cruise
4. Navigate the menus and choose the option that allows you to play any minigame you've unlocked. Setup your player and the CPUs as necessary.
5. Select the Spin Doctor minigame, and play it. When playing the game an immediate drop in frames occurs until you get closer to completing the minigame where the system "catches up"

### Expected behavior

Expected behavior is no slow down and a consistent frame rate

**Comment by TwilightSlick** [comment]
I'm not seeing any slowdown, either when loading the game via a SD2SP2 or a GC Loader. I am using r1614 with the NTSC-U 1.01 ISO on a NTSC-U GC. I don't have the original disc on hand.

**Comment by Extrems** [comment]
I think you've turned on Force Anisotropic Filter. We can't help it if the GPU can't keep up.
