### ISSUE TITLE
[Feature request]: Ability to supress audio streaming warning while using GCloader system

### ISSUE THREAD

**Issue by molton** [emukidid/swiss-gc#861]
### Describe the feature

The warning is displayed before any game that has audio streaming comes up. I wish I could disable that function.  Not a big deal but I figured it could be a quick change too if you don't mind.  Thanks

**Comment by molton** [comment]
I should mention I'm using that new CubeODE disc drive replacement and it works with the audiostreaming with the emulation off from my tests with super monkey ball 2 and Naruto 3, both seemed to stream the audio fine.

**Comment by Extrems** [comment]
Fixed in 34a0ce9 (r1625).

**Comment by molton** [comment]
sweet, I'm glad the gamecube has yall working on this software because it's the best.  Thanks a lot
