### ISSUE TITLE
[Issue]: Mario Kart Double Dash (USA) error when loading over FSP

### ISSUE THREAD

**Issue by coolbho3k** [emukidid/swiss-gc#863]
### Describe the bug

When loading Mario Kart Double Dash (USA) over FSP, it crashes right after the progressive scan selection screen with "An error has occurred" error.

_Sometimes_, the game is able to load to the intro movie. This is really rare for me.

My config:
1. Loading from my Synology DS923+ using the `frenskefrens/fsp-server` Docker image with default configuration. The NAS and GameCube are connected to the same 1 Gbps switch.
2. This happens with both an nkit ISO and clean ISO. Both ISOs load from GCLoader fine 100% of the time.
3. **Other games seem to play from FSP fine**, the only one I found that crashes so far is Mario Kart Double Dash.
4. I tried an MTU of 1500 and 9000 (jumbo frames are enabled on the NAS and switch)
5. I'm using the official Nintendo BBA.
6. Swiss v0.6r1622 booting from GCLoader

### Steps to reproduce

1. Try to load Mario Kart Double Dash (USA) over FSP. I used the `frenskefrens/fsp-server` Docker image.
3. The game crashes right after the progressive scan selection screen with the below error.

### Expected behavior

The game is able to load properly

### Relevant log output

```shell
N/A
```

### Add screenshots

<img width="1295" alt="Screenshot 2024-04-05 at 4 44 03 PM" src="https://github.com/emukidid/swiss-gc/assets/303270/0cc4fa43-d927-4381-8891-ef86b90e4a93">

**Comment by Extrems** [comment]
Docker is not supported.
