### ISSUE TITLE
[Feature request]: Add ENC28J60 module support on Serial Port 1

### ISSUE THREAD

**Issue by Fouindor** [emukidid/swiss-gc#866]
### Describe the feature

Add ENC28J60 support on Serial Port 1.
(Serial Port 2 is taken and I'd like to use my Serial Port 1 breakout board I use to mess with stuff :) )

I'm not familiar enough with Swiss code to know if my request is feasible. If not, I'll withdraw my request.

Many thanks to the team for their hard work over the years, much appreciated.

### Add screenshots

N/A

**Comment by Papy-G** [comment]
I have already asked for that, so that unmodded Dol-101 could get access to that too.
The answer is no: SP1 support is not planned as long as it is an "experimental" feature, and for the sake of code simplicity.

**Comment by Fouindor** [comment]
Ah, what a shame, thanks for the answer. Still, would be a good feature to add for people like us :)

I get what you're saying: I have a modded DOL-101 but I'm not too keen to mess with what I already did.

Before someone tells me to get a broadband adapter: while I can afford it, I have really conflicting feelings on blowing a sizeable chunk of my wage on it and I don't want to encourage the price gouging going on this accessory.

**Comment by Extrems** [comment]
Serial Port 1 is partially supported, but doesn't appear to be working. The front memory slots do work.

**Comment by Fouindor** [comment]
<


§6W66666666666666666666666666666666666666666666666666666666666666666666666666666666666/0Thanks for your answer. 54W

**Comment by Fouindor** [comment]
I don't know if you expected updates, but I wanted to take advantage of being in town for once and take the latest version (r1695) for a spin. The ENC28J60 module seems to be unrecognised.
I've checked the connections between my SP1 breakout board and the module, everything seems to be connected and I've kept the cable length between the module and the breakout board to a minimum. 

Don't hesitate if you need testers.

**Comment by Extrems** [comment]
It's known to be working within the Swiss menu now. It's still not supported within the hypervisor.

**Comment by Fouindor** [comment]
Okay, thanks ! :)

**Comment by Extrems** [comment]
Fixed in 128f792 (r1787).
