### ISSUE TITLE
[Question]: Configuration saves on gc loader SD and not on sd2sp2 SD.

### ISSUE THREAD

**Issue by Polypheides** [emukidid/swiss-gc#868]
### Describe your question

Hi when I enable virtual memory card the .raw creates on my gc loader SD and not on my sd2sp2 SD any tips?
The same for patches
The sd2sp2 is set as configuration device

My sd2sp2 SD card is fat32 sdhc 4gb from Toshiba

I'm on gc loader hw2 1.1.0.beta
swiss commit 5b8fb69c revision 1622 version 0.6 

### Add screenshots

![20240502_190815](https://github.com/emukidid/swiss-gc/assets/20396169/9fea4044-f6e2-429b-811e-6c2a415c0015)
![20240502_190746](https://github.com/emukidid/swiss-gc/assets/20396169/ed5a069b-8f2c-4040-b7a1-8825657987b0)
![20240502_190908](https://github.com/emukidid/swiss-gc/assets/20396169/0973be4d-27c6-4070-9605-5f20e09ae5d5)

**Comment by Extrems** [comment]
This might happen if you're booting a streaming audio game, but this is the inverse of what should happen with this firmware version.

**Comment by Polypheides** [comment]
it might be this from the patch note Forcibly use GC Loader as patch device if enabled features demand it. 

i tested the Swiss v0.6r1614 release and that one works fine using the sd2sp2 as virtual save location.

i believe it forcing the VMC on the GC loader SD it prevents me from saving games i even tried moving the VMC to the sd2sp2 SD but swiss still recreated it on GC SD

**Comment by Extrems** [comment]
Have you enabled anything else?

**Comment by Polypheides** [comment]
Only show hidden files, file managment and boot through IPL

**Comment by Polypheides** [comment]
https://youtu.be/0idITJ0jxQc video showing what im doing. i believe im doing everything correctly.

**Comment by Extrems** [comment]
This is a streaming audio game. e8911d3 accidentally inverted the workaround for this firmware version.

**Comment by Polypheides** [comment]
will it be fixed in next swiss update? 

i will downgrade my version v0.6r1614 since that works. 
thank you.

**Comment by Papy-G** [comment]
Checking your RTC battery may help avoiding random behaviour and loosing settings too. (some settings are stored in the SRAM)

**Comment by Extrems** [comment]
Fixed in dc3b947 (r1651).
