### ISSUE TITLE
[Question]: compiling stops at gcm.c

### ISSUE THREAD

**Issue by Polypheides** [emukidid/swiss-gc#869]
### Describe your question

with error:
elf.c
exi.c
files.c
gameid.c
gcm.c
swiss-gc/cube/swiss/source/gcm.c:9:10: fatal error: psoarchive/PRS.h: No such file or directory
    9 | #include <psoarchive/PRS.h>

what am i missing?

**Comment by Extrems** [comment]
You're missing the `ppc-libpsoarchive` package.
