### ISSUE TITLE
[Question]: PAL video mode

### ISSUE THREAD

**Issue by AlfredoDore** [emukidid/swiss-gc#870]
### Describe your question

I use Swiss on Wii and I have a question
my Wii is American, when I put 576i video mode on it gets a graphical error (broken image) and when I put it on 576p or 540p 60hz the screen goes black/blue, I saw videos where NGC users when they put 576i video on also got an error graphic (black and white screen and distorted image) wouldn't it be possible to add patch for PAL?
O.B.S: I use an HDMI converter on my Wii, so it's in progressive, besides, I really liked Swiss, certain PAL games are in progressive and 60Hz on it, Nintendont still lacks support

**Comment by Extrems** [comment]
This is outside of our control. The AVE-RVL must be configured properly before switching to compatibility mode.
