### ISSUE TITLE
[Issue]: SD Gecko Disabled After IGR / Return from Loader

### ISSUE THREAD

**Issue by AskaLangly** [emukidid/swiss-gc#878]
### Describe the bug

Swiss is unable to load settings from SD Gecko due to it being 'unknown' for some reason (as reported in Device Info) when rebooting the system via in-game reset, or by loading `boot.iso` when coming back from IPL when Return to Loader was used.

Notes: You can still use all other devices, like GCLoader. Assuming if settings are saved to GCLoader, settings will load from it.

Setup: DOL-001 with GC Loader HW2 (1.1.0 beta), SD Gecko in Slot-B, ETH2GC, GB Player.

Swiss revision: 1667. Started to happen in 1664.

### Steps to reproduce

After loading Swiss,

1. Set in-game reset to Reboot, then start a game and use IGR button combo, or
2. Use the Return to Loader option, starting the Swiss ISO.

### Expected behavior

Load settings from SD Gecko when starting Swiss via ISO or DOL.

**Comment by Extrems** [comment]
Not this shit again...
I'm so tired of SanDisk SD cards.

**Comment by AskaLangly** [comment]
I have a PNY 64GB uSD and a 16GB Sony SD. Should I try those?

**Comment by Extrems** [comment]
Fixed in extremscorner/libogc2@c0a95d8.
