### ISSUE TITLE
SD2SP2 visible but then vanishes

### ISSUE THREAD

**Issue by Bent3ndo** [emukidid/swiss-gc#883]
When I load Swiss using the Sunshine memory card method, the SD card option is visible. However when selected it flickers instantly back to the media options only without SD now an option.

I'm using a 256GB SanDisk Ultra MicroSD card, with my ISO rips on the root of the card.

What could be causing this to happen? Thanks.

**Comment by Extrems** [comment]
Which revision are you using?

**Comment by Bent3ndo** [comment]
The memory card is 0.5 but the latest version is on the SD card which I believe should be detected but isn't.

**Comment by Extrems** [comment]
You have to update the version on the memory card.

**Comment by Bent3ndo** [comment]
> You have to update the version on the memory card.

I thought Swiss detected later versions on the SD and loaded those even if the Memory Card is older sorry?

**Comment by Extrems** [comment]
It can't do that if it can't read from the SD card. Catch-22.
