### ISSUE TITLE
[Issue]: "Failed integrity check" message when trying to start a game

### ISSUE THREAD

**Issue by koewr** [emukidid/swiss-gc#887]
### Describe the bug

I just installed Swiss via Picoboot and when I try to launch a game from SD or Disc I get the message "Failed integrity check" Im on Swiss r1668

### Steps to reproduce

Try to launch any game 

### Expected behavior

Launch the game 

### Relevant log output

```shell
"Failed integrity check"
```

### Add screenshots

![IMG_1066](https://github.com/user-attachments/assets/5feea8da-4ead-47a3-bb25-3f288ae81a2d)

**Comment by koewr** [comment]
I had this Issue yesterday, today I added some games but didn't really change anything, and now it just works, weird.

**Comment by Extrems** [comment]
You might have a fake SD card.

**Comment by koewr** [comment]
I'm using the SD2SP2 Adapter and some old SD Card, while the SD Card is not of very high quality I don't think it caused the issue.

**Comment by Extrems** [comment]
This error can only crop up because the checksum in the patched file didn't match the checksum before we wrote it to the SD card.
