### ISSUE TITLE
[Issue]: When playing the opening video of the game, the video gets stuck and slow, why is that?

### ISSUE THREAD

**Issue by 2006MASTER** [emukidid/swiss-gc#889]
### Describe the bug

When I watch the opening videos such as Tales of Symphonia, Blitch, Biohazard Code Veronica, etc., the part gets severely sticky, why is that? There was no problem with the Wii loader, but I used the latest version of swiss_r1668, but it's a pity that the opening video playback is not perfect. If there is any way, please let me know?

### Steps to reproduce

When I watch the opening videos such as Tales of Symphonia, Blitch, Biohazard Code Veronica, etc., the part gets severely sticky, why is that? There was no problem with the Wii loader, but I used the latest version of swiss_r1668, but it's a pity that the opening video playback is not perfect. If there is any way, please let me know?

### Expected behavior

When I watch the opening videos such as Tales of Symphonia, Blitch, Biohazard Code Veronica, etc., the part gets severely sticky, why is that? There was no problem with the Wii loader, but I used the latest version of swiss_r1668, but it's a pity that the opening video playback is not perfect. If there is any way, please let me know?

### Relevant log output

```shell
When I watch the opening videos such as Tales of Symphonia, Blitch, Biohazard Code Veronica, etc., the part gets severely sticky, why is that? There was no problem with the Wii loader, but I used the latest version of swiss_r1668, but it's a pity that the opening video playback is not perfect. If there is any way, please let me know?
```

**Comment by Extrems** [comment]
This is a limitation inherent to passive SD card adapters. You need to use a better supported device.

**Comment by 2006MASTER** [comment]
GameCube SD2SP2 SD Card Adapter, Raspberry Pi Pico Board, Pico Boot IPL Replacement Mode Chip I've soldered the latest new one, is this not working? What exactly is a good ODD?

**Comment by Extrems** [comment]
The following supported devices are better than the SD2SP2:

- SD2SP2 **2.0**
- Broadband Adapter
- IDE-EXI v2
- M.2 Loader
- WASP / Wiikey Fusion
- WODE
- FlippyDrive
- GC Loader / GCODE
