### ISSUE TITLE
Direct Solder SD Card adapter failure to load games

### ISSUE THREAD

**Issue by rguerra0499** [emukidid/swiss-gc#890]
### Describe the bug

Using picoboot, swiss will load up from sd card adapter, but will not access games on sd card adapter. Citing " physical drive cannot load " Swiss v0.6r1622 work fine but not newer versions. Sd card adapter is solder directly to the memory card slot 2. this issue is only presented on newer versions of swiss. Note that swiss is renamed to IPL.dol before been placed on sd card adapter, though it does load up the newer swiss, but swiss will just refuse to access the sd card adapter.

### Steps to reproduce

direct solder sd card adapter to the gamecubes memory slot 2
direct drop of newer swiss version been renamed to IPL.dol
boot using picoboot selecting newer version of swiss ( will load up swiss)
selecting sd card slot 2 on swiss menu will fail (physical drive cannot work)

### Expected behavior

accessing games from sd card slot 2

**Comment by Extrems** [comment]
Which SD card are you using?

**Comment by rguerra0499** [comment]
It's a micro SD card SanDisk imagemate 128gb formated to fat32

![IMG_20240727_171054](https://github.com/user-attachments/assets/b9d2507f-1df4-4a8e-af6b-e610b679b0e6)

This is how I have it setup
![IMG_20240727_171130](https://github.com/user-attachments/assets/b8030d02-a6ff-4706-a9ef-26a26e71e8b6)

Here's an image with swiss rev 1614 working fine 
![IMG_20240727_171423](https://github.com/user-attachments/assets/cb5a171a-fb05-41e4-bf09-eab5880e4c98)

**Comment by Extrems** [comment]
I've been hearing many reports of 128 GB SanDisk cards no longer working, but the one I've got has no issues. This sucks.

**Comment by AlfredoDore** [comment]
> I've been hearing many reports of 128 GB SanDisk cards no longer working, but the one I've got has no issues. This sucks.
the error I mentioned seems to be that, but I'm surprised that certain games work and others don't, since I was playing Splinter Cell Chaos Theory perfectly in version v0.6r1668 and now I can't anymore, my card is Sandisk and I load it through a WiiSD, for now I'll stay on version v0.6r1668

**Comment by AlfredoDore** [comment]
I tested it with another SD card and it is indeed the Sandisk, these last two versions prevent certain games from starting, something must have been put on it, but I will continue with the previous version since it is working correctly (and all my games are on it)

**Comment by Extrems** [comment]
Can you try the latest CI build and see if anything changes?
https://github.com/emukidid/swiss-gc/actions/runs/10650241524/artifacts/1878642728

**Comment by Massouille78** [comment]
No, same problem with this version ![image](https://github.com/user-attachments/assets/fe82d4ef-eb6b-4dfa-ab1a-70ab2384f93e)![image](https://github.com/user-attachments/assets/f1233dff-7705-494b-aa90-12e4e9294fcc)

**Comment by Extrems** [comment]
Can you try both r1664 and r1667 to try to narrow it down?

**Comment by Massouille78** [comment]
Hello,

Here are the results of the complete tests this morning :

-1723 : Not working
-1712 : Not working
-1695 : Not working
-1668 : Not working
-1667 : Working
-1664 : Working
-1622 : Working
-1614 : Working
-1400 : Working
![IMG_4395](https://github.com/user-attachments/assets/2f47b192-9b50-4ad0-aa96-644186ac23d0)
![IMG_4396](https://github.com/user-attachments/assets/908b53af-5043-4458-9cf6-564e932b480d)
![IMG_4393](https://github.com/user-attachments/assets/6456deaf-44aa-4610-8608-d11d465b70d0)
![IMG_4394](https://github.com/user-attachments/assets/aadccbe0-b25d-4561-ab1d-f82539886783)

**Comment by Extrems** [comment]
Try these and show me the results.
[tests.zip](https://github.com/user-attachments/files/16910239/tests.zip)

**Comment by Extrems** [comment]
Sorry, I mistakenly sent tests for Memory Slot B earlier. Please try these.
[tests.zip](https://github.com/user-attachments/files/16910927/tests.zip)

**Comment by Extrems** [comment]
Can somebody please run these tests? I'm flying blind here and have nothing actionable still.

**Comment by rguerra0499** [comment]
![IMG20240907190324](https://github.com/user-attachments/assets/8439a25c-fab8-4beb-bfdb-0621c4029c74)

Test file dump, witch ever file was used the dump was the same. this is using direct boot of a.dol file

**Comment by Extrems** [comment]
Sorry, these tests were for Serial Port 2. You need the Memory Slot B tests.
[tests.zip](https://github.com/user-attachments/files/16920220/tests.zip)

**Comment by rguerra0499** [comment]
![IMG_20240907_195231](https://github.com/user-attachments/assets/495e0aff-275c-4db7-bcdf-3ba6e90aed07)
![IMG_20240907_195318](https://github.com/user-attachments/assets/067c360a-aa87-47d5-b1c6-8b42caff1b35)

Can't really read the first line but this is the dump for both a.dol and b.dol respectably 

I hope it helps somehow

**Comment by rguerra0499** [comment]
Just an update of up to where swiss seems to work fine.

![IMG20240907200501](https://github.com/user-attachments/assets/4b859659-1e6d-44ec-9def-e1c036ec53ae)
( Works )

![IMG20240907200602](https://github.com/user-attachments/assets/66695a52-ddb6-4f9e-8e0c-64baa2b2911d)
( Doesn't work, detects something since it auto selects SD card slot B )

![IMG20240907200705](https://github.com/user-attachments/assets/3b7e2e3c-09f4-48f3-abf1-0009287371c4)
( Doesn't work, same as above )

![IMG20240907200804](https://github.com/user-attachments/assets/511bff9d-8178-4860-8858-bd0e8de466e8)
( Same issue, doesn't load )

![IMG20240907200910](https://github.com/user-attachments/assets/2d78e3f8-f9c7-4975-8dde-35abe9feb4b1)
( Doesn't work either, got this one from last post )

**Comment by Extrems** [comment]
If r1667 is where it's breaking for you, then you should really check your wiring. The SD2SP2 2.0 change is also applicable to Memory Slot B.

As for the others, you can try this build: https://github.com/emukidid/swiss-gc/actions/runs/10728515673/artifacts/1905293122

**Comment by Massouille78** [comment]
Hello, 

I have sd2sp for serial port and a  old gc2sd for memory card slot.

I don't understand What test I must do? A.dol, b.dol? And what result I must have?

Thanks in advance,

**Comment by Extrems** [comment]
Just run them and post a picture of the screen.

**Comment by Tiki77** [comment]
Any progress? I can only use r1664, higher versions give the same error

**Comment by Extrems** [comment]
Nobody is running the tests so there's nothing I can do.

**Comment by Tiki77** [comment]
> Nobody is running the tests so there's nothing I can do.
i try it…

**Comment by Tiki77** [comment]
> Nobody is running the tests so there's nothing I can do.

my ngc use serial port2. must also be tested Memory Slot B？

**Comment by Tiki77** [comment]
![a](https://github.com/user-attachments/assets/13f75db1-d081-4ea8-8e6d-e01d1b7d1643)
![b](https://github.com/user-attachments/assets/428bf1bc-4f62-4205-afe0-fcdb8a394f07)


> Sorry, I mistakenly sent tests for Memory Slot B earlier. Please try these. [tests.zip](https://github.com/user-attachments/files/16910927/tests.zip)

I use this for test Serial Port 2. a.dol and b.dol show the same content.
i use new tf card(512G) only put in r1730,but show me “Error occurred in the low level disk i/o layer”,why？

**Comment by Extrems** [comment]
You can try this build. However, I suspect your SD card's microcontroller is crashing, and the SD card is most certainly a shoddy counterfeit.
[swiss_r1730.zip](https://github.com/user-attachments/files/17088157/swiss_r1730.zip)

**Comment by Tiki77** [comment]
> You can try this build. However, I suspect your SD card's microcontroller is crashing, and the SD card is most certainly a shoddy counterfeit. [swiss_r1730.zip](https://github.com/user-attachments/files/17088157/swiss_r1730.zip)

no,sd card is okay.After testing, I put the card with the new system into sd2sp2 1.2a and it can be loaded normally. I suspect that there is something wrong with my sd2sp2 2.0.
![bb](https://github.com/user-attachments/assets/a64a4ad7-87f7-4d80-80f2-a28473e17354)
![sd2sp1 2a](https://github.com/user-attachments/assets/abc8907a-7808-4c5b-bd7e-646f2842b74f)

**Comment by Tiki77** [comment]
this is my sd2sp2 2.0 pic.
![dd](https://github.com/user-attachments/assets/5fe02768-3275-4544-89fc-0edceff4765f)

**Comment by Extrems** [comment]
Whoever designed that PCB was drunk.

**Comment by Tiki77** [comment]
> 设计该 PCB 的人一定喝醉了。

haha...So I'm going to remake one myself...Thanks for your reply

**Comment by Massouille78** [comment]
sorry for the time spent, I'm on a business trip. so for the tests:

A.dol : ![image](https://github.com/user-attachments/assets/e01c46ef-844b-4a5c-89ef-8a59303ebfdf)

![image](https://github.com/user-attachments/assets/0de47039-1bc5-4d04-9768-3a77a8433984)

B.dol 

![image](https://github.com/user-attachments/assets/806169e7-ea76-4b26-8f8f-1a723a123d1d)

And last version 1730
![image](https://github.com/user-attachments/assets/4e8038ff-37ca-4f83-b661-8e93d0bad1d9)

Test with sd2sp2.

the latest working version is 16677

![image](https://github.com/user-attachments/assets/7f239612-73ff-472c-85f4-aba52b89bf1e)

**Comment by Extrems** [comment]
I think you ran the tests for Memory Slot B as that's the ID for a GameCube Memory Card.
The ones for Serial Port 2 are up here: https://github.com/emukidid/swiss-gc/issues/890#issuecomment-2334457883

**Comment by Massouille78** [comment]
No; look 

Uploading 2024-09-23 21-11-27.mov…

**Comment by Extrems** [comment]
Well, this could be problematic if true. Give this build a try.
[swiss_r1730.zip](https://github.com/user-attachments/files/17104012/swiss_r1730.zip)

**Comment by Tiki77** [comment]
> sorry for the time spent, I'm on a business trip. so for the tests:
> 
> A.dol : ![image](https://private-user-images.githubusercontent.com/64223347/370014087-e01c46ef-844b-4a5c-89ef-8a59303ebfdf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzUyMTUsIm5iZiI6MTcyNzEzNDkxNSwicGF0aCI6Ii82NDIyMzM0Ny8zNzAwMTQwODctZTAxYzQ2ZWYtODQ0Yi00YTVjLTg5ZWYtOGE1OTMwM2ViZmRmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QyMzQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjk4ZjU4N2YxYzhiMTc3YjIyOTY5ZDE0MWY3MzJhNTk4ZmI0Yjc5ZjY1OTQ2OWIwMWE3OTFiZWFmMjM0NGNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fwwIDpoL1pIzBMVZPlo00KJPrMJgkTd-Z-OoE8_8qjs)
> 
> ![image](https://private-user-images.githubusercontent.com/64223347/370014175-0de47039-1bc5-4d04-9768-3a77a8433984.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzUyMTUsIm5iZiI6MTcyNzEzNDkxNSwicGF0aCI6Ii82NDIyMzM0Ny8zNzAwMTQxNzUtMGRlNDcwMzktMWJjNS00ZDA0LTk3NjgtM2E3N2E4NDMzOTg0LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QyMzQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODIzODk3YThjNzcxMjZkN2YzOWM5ZDc1OGNjMWM1MDEzMjdjZDc1NDIxNmI5NWJlYjMxNzUzNGRkNWI1NTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KVypklQ_boDoeLGBoPM15ZyAG54mxkWgsu2eue80t4c)
> 
> B.dol
> 
> ![image](https://private-user-images.githubusercontent.com/64223347/370014295-806169e7-ea76-4b26-8f8f-1a723a123d1d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzUyMTUsIm5iZiI6MTcyNzEzNDkxNSwicGF0aCI6Ii82NDIyMzM0Ny8zNzAwMTQyOTUtODA2MTY5ZTctZWE3Ni00YjI2LThmOGYtMWE3MjNhMTIzZDFkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QyMzQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NDMwYzhhYjg0MTU0N2YzMmI4N2YzNDQzZDcxYWFiZWExZTY4OTAxMWJhYzYyODhlMmYwMTRkMjJjZDgxNTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.73hBXSljvkqMjjlm2-VRjgKxcE9-ccEANHbE8Bs3kI8)
> 
> And last version 1730 don't work ![image](https://private-user-images.githubusercontent.com/64223347/370014432-4e8038ff-37ca-4f83-b661-8e93d0bad1d9.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzUyMTUsIm5iZiI6MTcyNzEzNDkxNSwicGF0aCI6Ii82NDIyMzM0Ny8zNzAwMTQ0MzItNGU4MDM4ZmYtMzdjYS00ZjgzLWI2NjEtOGU5M2QwYmFkMWQ5LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QyMzQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTc0MDNlYTQ1ZDZmNTBlMzU2ZTBmZGQ0ZjRkYWVjN2M3NmY3NDU2ZmE2MmRmN2RkNTg1NjQzODdmZWQ2MDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VeIaOukk7RLe-tkgjK800sUBxIjY1L8CKgbp4DsOBGc)
> 
> Test with sd2sp2.
> 
> the latest working version is 16677
> 
> ![image](https://private-user-images.githubusercontent.com/64223347/370015491-7f239612-73ff-472c-85f4-aba52b89bf1e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzUyMTUsIm5iZiI6MTcyNzEzNDkxNSwicGF0aCI6Ii82NDIyMzM0Ny8zNzAwMTU0OTEtN2YyMzk2MTItNzNmZi00NzJjLTg1ZjQtYWJhNTJiODliZjFlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QyMzQxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTZjZTA1YTVhYmVkZTljY2EwZDAxODY3ZmE0MjljYWNiODhiMjlhYzQ2Yzc1NGIwODZkNjljZTAzODhkNTU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OUJMCVJtInOxRGP6BwI4-mQGjLjmVwDR_H_91HPZZnY)



> No, it is good file, look
> 
>  2024-09-23.21-11-27.mov

I think there may be a problem with your tf card. It may just not be recognized by the new Swiss version, because I found that there is no problem with the recognition on the computer, but not in Swiss. I switch a new tf card and use the same program,it can be found in Swiss. Recognized (r1730)

**Comment by Tiki77** [comment]
update:I replaced the new TF card (Samsung white card 128G), and can use the latest r1730 on the same SD2SP2. It seems that there is a problem with my previous SanDisk TF (64g) card.

**Comment by Tiki77** [comment]
why r1730 In-GameReset remove igr.dol..?In version r1730, a+z+start can't go back to Swiss, only reboot

**Comment by Extrems** [comment]
It was replaced with a more reliable and compatible mechanism.

**Comment by Tiki77** [comment]
> It was replaced with a more reliable and compatible mechanism.

Is it impossible to return to Swiss in the game? Or am I doing it wrong?

**Comment by Tiki77** [comment]
okay..i use  r1668..

**Comment by Extrems** [comment]
This is going way off-topic but you need `/swiss/patches/apploader.img` on the SD card. You can find it in the IGR folder.

**Comment by Tiki77** [comment]
> This is going way off-topic but you need `/swiss/patches/apploader.img` on the SD card. You can find it in the IGR folder.

thank you.i wiil try this.

**Comment by Massouille78** [comment]
> Well, this could be problematic if true. Give this build a try.
> 
> [swiss_r1730.zip](https://github.com/user-attachments/files/17104012/swiss_r1730.zip)
> 
> 

Same issue with this version : ![image](https://github.com/user-attachments/assets/a42b8d9f-b27d-4213-ab04-d7516cb7a043)
![Uploading 370376747...]

![image](https://github.com/user-attachments/assets/5e40bb99-4f3d-4fc7-bd2c-590f247209e7)

![image](https://github.com/user-attachments/assets/8c8f5e8f-14f3-4634-a215-efd4720b2212)

**Comment by Extrems** [comment]
Are you sure you ran the correct tests? Do you have a GameCube Memory Card in Slot B?

**Comment by Massouille78** [comment]
> Slot

Yes iam sure than test it is ok... I spend a lot of time to advance the subject. See photo, I have memory card in slot A and B. If you want, this evening, we can make a video, a conference call, a video conference, or whatever you want, I am available 

![image](https://github.com/user-attachments/assets/0d740980-76fe-4551-bd31-801c94a599e8)

**Comment by Extrems** [comment]
Remove any objects from Memory Slot B then run the tests. If the screen is blank, then you aren't running the correct tests.

**Comment by Extrems** [comment]
This is proof you aren't running the correct tests. Please use the ones for Serial Port 2.

**Comment by Massouille78** [comment]
> This is proof you aren't running the correct tests. Please use the ones for Serial Port 2.

I use this test https://github.com/user-attachments/files/16920220/tests.zip I remove all memory card. I don't understand What more can I do?

**Comment by Extrems** [comment]
That link is from https://github.com/emukidid/swiss-gc/issues/890#issuecomment-2336492609, which is for Memory Slot B. The correct files are in https://github.com/emukidid/swiss-gc/issues/890#issuecomment-2334457883.

**Comment by Massouille78** [comment]
> Sorry, I mistakenly sent tests for Memory Slot B earlier. Please try these.
> 
> [tests.zip](https://github.com/user-attachments/files/16910927/tests.zip)
> 
> 

Hello, so correct files, without memory card slot A and B, with my sp2sd 256Go ultra micro sd : A.dol 
![image](https://github.com/user-attachments/assets/67c8282c-0606-4adf-b11d-51a149b0f5d5)

And b.dol 

![image](https://github.com/user-attachments/assets/8ef2957b-cf15-4155-806b-23342d6c8a98)

I have reformat my sd card to Fat32 in 64kb : same problem, test tests and same results. Swiss ok until 1667.

**Comment by Extrems** [comment]
This is the same result Tiki77 had, so the same I said here is applicable: https://github.com/emukidid/swiss-gc/issues/890#issuecomment-2365443327

I'm afraid I cannot fix this.

**Comment by Massouille78** [comment]
For more tests, I have 2 others sd card Samsung ultra 128 GO, the both work with Swiss 1730... aie, I don't understand why my 256 go work until v1667

**Comment by Extrems** [comment]
@Massouille78 @Tiki77 I have a new test for your counterfeit SanDisk cards.
[newtestsp2.zip](https://github.com/user-attachments/files/17155543/newtestsp2.zip)

**Comment by Massouille78** [comment]
> @Massouille78 @Tiki77 I have a new test for your counterfeit SanDisk cards.
> 
> [newtestsp2.zip](https://github.com/user-attachments/files/17155543/newtestsp2.zip)
> 
> 

Hello, last test with c.dol, without memory card ![image](https://github.com/user-attachments/assets/7fb559ff-d07b-4f4a-8236-2c40b248e25a)

![image](https://github.com/user-attachments/assets/461dd1b8-1451-4b67-b542-a05f519e7b05)

**Comment by Extrems** [comment]
Alright, let's give one last thing a try.
[newnewtestsp2.zip](https://github.com/user-attachments/files/17180028/newnewtestsp2.zip)

**Comment by Massouille78** [comment]
> Alright, let's give one last thing a try.
> 
> [newnewtestsp2.zip](https://github.com/user-attachments/files/17180028/newnewtestsp2.zip)
> 
> 

Last test without memory card : ![image](https://github.com/user-attachments/assets/53122ee0-99d4-4c86-9930-307943519709)

![image](https://github.com/user-attachments/assets/6a249c83-5d3d-40c0-9a65-4ea5746010a3)

**Comment by Extrems** [comment]
Some new ideas came to mind. Hopefully we'll finally see something different.
[newtestssp2.zip](https://github.com/user-attachments/files/17199277/newtestssp2.zip)

**Comment by Extrems** [comment]
g/h is intriguing but I don't know what to make of it when i/j couldn't go any further.

**Comment by Extrems** [comment]
One last try before I close this.
[newnewnewtestsp2.zip](https://github.com/user-attachments/files/17235457/newnewnewtestsp2.zip)

**Comment by Extrems** [comment]
[finaltestsp2.zip](https://github.com/user-attachments/files/17252609/finaltestsp2.zip)

**Comment by Massouille78** [comment]
> [finaltestsp2.zip](https://github.com/user-attachments/files/17252609/finaltestsp2.zip)
> 
> 

Hey ! Last result. Something is different !!! ![image](https://github.com/user-attachments/assets/f92a9f9d-569f-42c9-b089-eb38671cbf1a)

![image](https://github.com/user-attachments/assets/875e3a6f-8f57-46bc-a989-102335a6fa71)

**Comment by Extrems** [comment]
Okay, great! Unfortunately you'll have to burn a new disc to make it work again. gekkoboot will also have to be updated for those using that.

**Comment by Massouille78** [comment]
I didn't understand your answer

**Comment by Extrems** [comment]
You will have to burn the next release onto a new disc. It won't work as `boot.dol` from your current version.
