### ISSUE TITLE
[Issue]: crashes when starting game with bios (IPL)

### ISSUE THREAD

**Issue by AlfredoDore** [emukidid/swiss-gc#893]
### Describe the bug

when starting the game, the NGC bios starts normally, but then crashes and says there was an error

### Steps to reproduce

in the new version you must activate the IPL boot

### Expected behavior

the gamecube logo and then the game starts

**Comment by Extrems** [comment]
Cannot reproduce.

**Comment by AlfredoDore** [comment]
> Cannot reproduce.

I forgot to mention that it doesn't happen with all games, it happens to me with Animal Crossing (PAL), Splinter Cell Chaos Theory (USA), Hacht I don't know what (I forgot the name), but by disabling the IPL the game works
I should also mention that I downloaded IPL from third party

**Comment by Extrems** [comment]
Please use the one built into your console.
