### ISSUE TITLE
[Issue]: FSP Consistently Crashing on v0.6r1695

### ISSUE THREAD

**Issue by j117-esc** [emukidid/swiss-gc#894]
### Describe the bug

Playing games through FSP on **v0.6r1695** has constant crashes (been having this issue for a few releases now).
Many games have been showing the 'An error has occurred' message. The timing differs on games, some crash after a few minutes and others I can play for a good 20 or so minutes.

I've tried several different SD cards (formatted) with the same outcome.
Reverting back to **v0.6r1622** and I no longer have the crashes that I do in the newer releases.

### Steps to reproduce

Load game through FSP on v0.6r1695.

Example games: Tonka & Splinter Cell.

### Expected behavior

Game does not crash.

**Comment by Extrems** [comment]
While FSP is the most tested device out of any others, I'm following the recommended practice of putting the GameCube and FSP server on their own network segment, and so a race condition slipped through the cracks. oops.

**Comment by Extrems** [comment]
Fixed in fa692ca (r1697).

**Comment by j117-esc** [comment]
Thanks! Games are running good now 🤘
