### ISSUE TITLE
[Feature request]: swiss versions after 1400 dont work on wii 

### ISSUE THREAD

**Issue by kamikazilucas** [emukidid/swiss-gc#897]
### Describe the feature

provide update to make it work on wii

**Comment by Extrems** [comment]
Can you be more specific? It looks to be working to me.
https://files.extremscorner.org/wii/videos/swiss_r1695.mp4

**Comment by kamikazilucas** [comment]
> Can you be more specific? It looks to be working to me. https://files.extremscorner.org/wii/videos/swiss_r1695.mp4

if you use the dol file with homebrew launcher it dosent

**Comment by Extrems** [comment]
We aren't responsible for bugs in Wii applications.
