### ISSUE TITLE
[Issue]: config not saving keeps saying failed to save

### ISSUE THREAD

**Issue by kamikazilucas** [emukidid/swiss-gc#899]
### Describe the bug

i can not save any of the config or the save the game settings and i cant make the swiss ini file appear on the memory card

### Steps to reproduce

turn on swiss and try to save anything 

### Expected behavior

saving to memory card or sd card

**Comment by Extrems** [comment]
You must use a passive SD card adapter designed for Nintendo GameCube. The front SD slot on a Wii cannot be used. GameCube memory cards are not currently supported.

**Comment by kamikazilucas** [comment]
they were supported in 0.5, why are they not supported now?

**Comment by Extrems** [comment]
There were issues that corrupted them. They also aren't sufficient to support basic functionality.

**Comment by kamikazilucas** [comment]
> There were issues that corrupted them. They also aren't sufficient to support basic functionality.

well it worked fine for me, all i needed was just disc settings to be saved and now i cant even get that, unless i use 0.5
