### ISSUE TITLE
[Issue]: swiss not booting

### ISSUE THREAD

**Issue by Roadmouse85** [emukidid/swiss-gc#902]
### Describe the bug

Hi. Just bought a cubeode 1.2 install it copy swiss to sd card tried sandisk and samsung evo card and it wont boot. I turn power on enter gamecube logo and then display an error occur please shutt your system. Can someone please help?

### Steps to reproduce

.

### Expected behavior

How to get it to work...

### Relevant log output

```shell
.
```

### Add screenshots

![Screenshot_20240820_105130_Google](https://github.com/user-attachments/assets/1eb36ba8-06ce-4464-be6c-548f3f4fa397)

**Comment by Extrems** [comment]
Duplicate of issue #900.
