### ISSUE TITLE
[Issue]: Crash Splinter Cell Chaos Theory and BUG IPL

### ISSUE THREAD

**Issue by AlfredoDore** [emukidid/swiss-gc#905]
### Describe the bug

When starting the game with IPL the bios simply does not start and as for Splinter Cell, the game when it is in the menu is fine, but when you start the game it stays on a black screen forever, this does not happen in version v0.6r1668

### Steps to reproduce

update to the last two versions of Swiss and simply start any game

### Expected behavior

the game and the IPL will run normally

### Relevant log output

```shell
# Recent list. Created by Swiss
Recent_0=sdb:/swiss/games/Tom Clancy's Splinter Cell - Chaos Theory [GCJE41]/game.iso
Recent_1=sdb:/swiss/games/The Legend of Zelda - Twilight Princess [GZ2P01]/game.iso
Recent_2=sdb:/swiss/games/Skies of Arcadia Legends [GEAP8P]/game.iso
Recent_3=sdb:/swiss/games/Enter The Matrix [GMXP70]/game.iso
Recent_4=sdb:/Home/IPLdumper.dol
Recent_5=sdb:/swiss/games/Luigi's Mansion [GLMP01]/game.iso
Recent_6=sdb:/swiss/games/Phantasy Star Online Episode I & II [GPOJ8P]/game.iso
Recent_7=sdb:/IPLdumper.dol
```

### Add screenshots

![erro](https://github.com/user-attachments/assets/6ea13ce0-c74e-4fde-a593-299075975f1d)

**Comment by Extrems** [comment]
Cannot reproduce with any IPL.
