### ISSUE TITLE
[Question]: Swiss v0.6r1730

### ISSUE THREAD

**Issue by AlfredoDore** [emukidid/swiss-gc#914]
### Describe your question

the new version fixed many things from versions v0.6r1695 and v0.6r1712. however version v0.6r1668 remains the most stable, version v0.6r1730 I still have problems with IPL in most games, but removing them now most games started working again, however, I have a question, wouldn't it be better to return the PAL-M codes to version 0.6r1668?

**Comment by Extrems** [comment]
PAL-M is not used on the Wii. This is only relevant to the DOL-002(BRA) sold in Brazil.

**Comment by AlfredoDore** [comment]
> PAL-M is not used on the Wii. This is only relevant to the DOL-002(BRA) sold in Brazil.
Oh, mine is American, so it was some instruction that you added that fixed most of the problems present in the last two versions.
