### ISSUE TITLE
[Feature request]: The problem with some game videos being disconnected and not coming out properly

### ISSUE THREAD

**Issue by 2006MASTER** [emukidid/swiss-gc#916]
### Describe the feature

Can't I change the disconnected and unwanted video playback features like Tails of Symphonia or Biohazard Code Veronica to play normally with a new patch? Sorry but it doesn't matter if I change the new BOOT..

### Add screenshots

Can't I change the disconnected and unwanted video playback features like Tails of Symphonia or Biohazard Code Veronica to play normally with a new patch? Sorry but it doesn't matter if I change the new BOOT..

**Comment by Extrems** [comment]
Sorry, you need a better device, like the SD2SP2 2.0 or SD Gecko 2.0.
