### ISSUE TITLE
[Issue]: After the change to in game reset, it doesn't work. 

### ISSUE THREAD

**Issue by Jdbye** [emukidid/swiss-gc#918]
### Describe the bug

Booting to igr.dol worked. But this isn't an option anymore.
I use PicoBoot flashed to a Pi Pico, which boots igr.dol, which contains Cubeboot, which boots swiss.dol
The new Apploader option just freezes the GC. And the reboot option boots into stock. 

### Steps to reproduce

See above

### Expected behavior

The old igr.dol option would boot back into Cubeboot, which booted back into Swiss, so everything worked.

**Comment by Extrems** [comment]
You must have `/swiss/patches/apploader.img` on the patch device used for your game. It can be found in the IGR folder.

**Comment by Extrems** [comment]
It's been renamed to Apploader since people couldn't notice the IGR one.

**Comment by austin-l-taylor** [comment]
@Extrems I moved the apploader.img file from the the AppLoader folder to the root of my SD card and set the "In Game Reset" to App Loader but I get the same issue. It does a normal boot and not into Swiss. I'm currently using the PIco Boot with an SD Gecko.

**Comment by Extrems** [comment]
It doesn't go in the root directory, it goes in the `/swiss/patches` directory.
