### ISSUE TITLE
[Issue]: On Gamecube, no longer saves configurations for each game.

### ISSUE THREAD

**Issue by Amagumon** [emukidid/swiss-gc#923]
### Describe the bug

No longer saves configurations for each game ( resolution... etc. )
I had version 1668, this bug appears with the latest version released, but maybe on previous versions, I haven't tested the others.

### Steps to reproduce

I change the options of a game, I save, I have the text telling me that it is saved, I move on to another game, I come back to the one I modified, I go back into the options, my changes are no longer taken into account.

### Expected behavior

The changes should be saved.

**Comment by Extrems** [comment]
Cannot reproduce. Check your SD card hasn't turned into read-only mode or something.

**Comment by Amagumon** [comment]
Weird, I don't have any read only mode, and saving in game (on SD) works fine.
