### ISSUE TITLE
[Question]: Swiss v0.6r1742

### ISSUE THREAD

**Issue by AlfredoDore** [emukidid/swiss-gc#924]
### Describe your question

The version that came out now finally solved the problem I was having, what did you necessarily do?
and another thing, I play Swiss on the Wii, but for some reason it doesn't recognize 576p, which would be vital for some European games, so I'm wondering if this is due to Swiss itself or the charger I use, which maybe I can use another charger that can use Swiss

**Comment by Extrems** [comment]
To use 576p, the AVE-RVL must be configured into a PAL video mode prior to launching BC. We cannot reconfigure it.

**Comment by AlfredoDore** [comment]
> To use 576p, the AVE-RVL must be configured into a PAL video mode prior to launching BC. We cannot reconfigure it.

and how do you do that?

**Comment by Extrems** [comment]
`VIDEO_Configure(&TVEurgb60Hz480Prog);` or `VIDEO_Configure(&TVPal528Prog);` will do the trick.

**Comment by AlfredoDore** [comment]
> `VIDEO_Configure(&TVEurgb60Hz480Prog);` or `VIDEO_Configure(&TVPal528Prog);` will do the trick.

I will do it, but where exactly do I put this command?

**Comment by Extrems** [comment]
Anywhere before `ES_LaunchTitle` or `WII_LaunchTitle` depending on implementation. You'll need to call `VIDEO_Init` if you aren't already.
