### ISSUE TITLE
[Question]: Why the igr dont works?

### ISSUE THREAD

**Issue by Diabolo-kun** [emukidid/swiss-gc#926]
### Describe your question

Well, my opcions to do a "in game reset" are the normal reset, out of swiss, and "apploader", and in info says "requires /swiss/patches/apploader.img" i search a tutorial and i dont know what i supoust to do, can someone help me?

### Add screenshots

![aaa](https://github.com/user-attachments/assets/16ab6c7a-a359-4d9f-b4db-99a34d5f0ef2)

**Comment by Anakiev2** [comment]
It's in the archive.
