### ISSUE TITLE
[Issue]: F-Zero GX Unleashed ignores game-specific patches for F-Zero GX

### ISSUE THREAD

**Issue by MysticAx0lotl** [emukidid/swiss-gc#931]
### Describe the bug

I already brought this up on Discord, but I'm submitting a formal issue for posterity. GX Unleashed can be built with a different titleid (UFZ_01) than vanilla F-Zero (GFZ_01), which causes Swiss to ignore any game-specific patches for F-Zero GX. This causes a crash on boot

### Steps to reproduce

- Build F-Zero GX Unleashed and change the titleID (ex. changing GFZE01 to UFZE01)
- Run it through Swiss
- The game will crash immediately upon load

### Expected behavior

The game loads and plays

**Comment by Extrems** [comment]
Fixed in 2ba9ff9 (r1779). A different solution will be needed long-term.
