### ISSUE TITLE
[Issue]: bug reboot

### ISSUE THREAD

**Issue by IvanAmatiDotCom** [emukidid/swiss-gc#932]
### Describe the bug

reboot bypass swiss direct to gc home

### Steps to reproduce

I'm using a raspberry pi pico with sd2sp2 tf.
everything works perfectly except the reboot,
I tried all the combinations but it reboot at the cube logo bypassing swiss, am I doing something wrong?
I'm using the latest release.

I tried a release from 2 years ago (v0.3) and in the options there is the possibility to choose igr.dol and this works

### Expected behavior

reboot to swiss

**Comment by Extrems** [comment]
This is expected behavior as PicoBoot is a one-shot deal. Reboot is only compatible with the CUBEODE, FlippyDrive, GC Loader, KunaiGC, Qoob Pro/SX, and the disc drive with a supporting disc.

You must use the apploader option, which is the replacement for the igr.dol option.
